### ISSUE TITLE
Audit top 5 integration overviews

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#1019]
## Description

Let's audit the documentation for our top 5 integrations. The descriptions can be improved so users have a better understanding of what benefit they offer, how Elastic can help with the user's use case, and persuade them to install the integration.

Since these integrations are owned by multiple teams, let's work with the docs writers of those teams to help establish best practices.

Our top integrations are:
1. System
2. Endpoint security
3. APM
4. Windows
5. OS Query manager
6. AWS
7. Linux
8. Nginx

### Examples

1. The system integration says:

> The System integrations allows you to monitor your servers. Because the System integration always applies to the local server, the hosts config option is not needed.

  This integration monitors more than just servers, it can monitor any host including laptops, etc. Also, I'm not sure why first time users need to know about the hosts config option.

2. The endpoint integration says:

> This integration sets up templates and index patterns required for Endpoint Security.

  Shouldn't it say something about protecting your systems from security threats and malware? Most users shouldn't need to know lower-level details like index templates or patterns.

3. System, Endpoint, and Windows (maybe others?) refer to packages instead of integrations. See https://github.com/elastic/integrations/issues/2468.

## Collaboration

* The docs team will define with product team the structure and location, and the product team will provide the initial content

**Contacts:**

* @akshay-saraswat and @jamiehynds for system, linux, windows
* @caitlinbetz for endpoint security
* @melissaburpo for OS query

## Suggested Target Release

TBD

**Comment by dedemorton** [comment]
Note that there is a related issue here. A lot of the feedback is based on a much earlier design, but is still relevant: https://github.com/elastic/integrations/issues/260

@bmorelli25 FYI that this came up at a Fleet/Agent meeting today.

**Comment by bmorelli25** [comment]
Thanks, DeDe. I'll also link in the newly created issue, https://github.com/elastic/observability-docs/issues/962. It repeats many of your concerns from last year and adds in a few new ones.

**Comment by bmorelli25** [comment]
@mostlyjason Did you use telemetry data to determine the top five integrations? If so, can you share a link to your query/visualization? I'm struggling to find the right fields in the telemetry cluster.

**Comment by colleenmcginnis** [comment]
I'm working on this now! My plan is to open six separate PRs: 

- [x] Update System integration docs (https://github.com/elastic/integrations/pull/3306)
- [ ] Update Windows integration docs
- [ ] Update AWS integration docs
- [ ] Update Linux integration docs
- [ ] Update Nginx integration docs
- [ ] Update guidelines for documenting integrations

**Comment by bmorelli25** [comment]
After the markdown changes are merged into the integrations repository, we'll need to promote the new versions to the production endpoint of the EPR, rerun the doc generation script, and manually trigger a new docsmobile build.

**Comment by colleenmcginnis** [comment]
This is done for the top observability integrations! 🎉  I'm going to close here, but here are some related next steps:
* @elastic/obs-docs is working on updates to the docs for all integrations for individual AWS/Amazon services in https://github.com/elastic/integrations/issues/3572.
* @elastic/security-docs @jamiehynds  if you're interested in doing this for "Endpoint security" and other popular security integrations, you can find the new documentation guidelines in the [integrations repo's docs](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md).
* I opened three issues to track follow-up work related to documentation guidelines:
  * https://github.com/elastic/elastic-package/issues/880
  * https://github.com/elastic/integrations/issues/3625
  * https://github.com/elastic/integrations/issues/3628
