### ISSUE TITLE
Beats/Agent comparison page for first time user audience

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#1032]
## Description

When a user is getting started with Elastic we plan to tell users to install Elastic Agent or Beats when they are adding an integration for the first time. Users need to understand the differences between these so they know which to choose based on their needs. 

We have an existing comparison page here https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html#supported-inputs-beats-and-agent. However, it is written for existing Beats users and assumes the reader is familiar with low-level Beats concepts. We have another for Elastic Cloud here, however its specific to cloud https://www.elastic.co/guide/en/cloud/current/ec-cloud-ingest-data.html#ec-ingest-methods, and does not focus on choice between Beats and Elastic Agent.

This new page should:
1. Provide links to learn more about Elastic Agent and Beats
2. Don't assume they know what inputs/outputs are
3. Recommend Elastic Agent and Fleet for most users
4. Provide a short summary of advanced use cases where users may prefer Elastic Agent standalone mode or Beats
5. Provide links to the other concepts users may not know

## Collaboration

* [ ] The docs team will lead producing the content
* [x] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Contact Person:**

*(We need to have a contact person in the product/development team to provide information about how the item to be documented works.)*
@mostlyjason @nimarezainia 

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*
TBD, but its an important part of our onboarding funnel

## Stakeholders

*(Please list any stakeholders for this issue.)*
@mukeshelastic

**Comment by mukeshelastic** [comment]
@mostlyjason Thanks for writing this up and discussing it in our docs sync. 

Here is how I was thinking about the [capabilities](https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html) page (even though the page doesn't explicitly outline that objective at the top, something we should change) The beats and agents capabilities page is aimed at beats users to assess the functionality differences between agent, beats and make a self-service decision whether to move forward with agent or not. So the assumption here is that it assumes you are beats users. 

Your point about -> a page in our docs to let first time users know about different ways to ingest data without drowning them with concepts they don't need to know. -> is very very valid! We do need to have simpler data ingestion page that describes the different ways to ingest data in elastic in simpler manner.  We will be tackling that outside of capabilities page for now.

**Comment by mostlyjason** [comment]
Thanks @mukeshelastic a simpler page seems like a good suggestion. I updated the title and description to reflect that.

**Comment by mostlyjason** [comment]
@nimarezainia any input on who should be the PM owner for this page? Beats/Agent are the agent team's area, but we'd like a link for the unified integrations view in 7.16 and I'm not sure on your capacity.

**Comment by mukeshelastic** [comment]
I think this will be covered by onboarding guide improvements elsewhere so no longer need to keep this issue open
