### ISSUE TITLE
[Request] we got feedback that the 'Fleet UI Settings' page could link to and NOTE the requirement to have a running Fleet Server already before going further

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#1035]
[Request] we got feedback that the 'Fleet UI Settings' page could link to and NOTE the requirement to have a running Fleet Server already before going further

If someone is accessing the Docs via search, they may not have started at the beginning and may benefit from the additional context and save time.

Even worse, it can look like other known problems and present as a false positive, like this for instance:
https://discuss.elastic.co/t/unable-to-install-fleet-server/282613

**Comment by dedemorton** [comment]
Sorry this got lost in our backlog. Added it to our project board. We'll get it done.
