### ISSUE TITLE
Clarify APM 7.0 update steps

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#1036]
## Description

There is some ambiguity in the **[Upgrade to APM Server version 7.0](https://www.elastic.co/guide/en/apm/server/current/upgrading-to-70.html)** guide. Run through the guide and add clarifications/fixes where necessary.

Additional information is in the issue linked below (internal only).

**Comment by insukcho** [comment]
As the [comment](https://github.com/elastic/sdh-apm/issues/346#issuecomment-932073823) from @sqren, 
if we want to upgrade from 6.x to 7.13 or higher, we first have to upgrade to 7.12 before upgrading to 7.13. We need to put this restriction in a public reference, too.

**Comment by insukcho** [comment]
Hi, team. What is the progress of this issue? any update?

**Comment by bmorelli25** [comment]
Hi Chris. Unfortunately, there hasn't been any progress on this issue. With the size of our team, it's unlikely that we'll prioritize this.

**Comment by bmorelli25** [comment]
cc @ollyhowell for visibility and input

**Comment by bmorelli25** [comment]
7.0 is EOL so I'm going to close this as won't fix.
