### ISSUE TITLE
Update the Observability Guide to use Elastic Agent 

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#1071]
## Summary

The [Observability guide](https://www.elastic.co/guide/en/observability/master/add-observability-data.html) currently documents ingestion with Beats shippers and a standalone APM Server architecture. We should update the ingest content to use Elastic Agent integrations instead.

## Related

* Related to https://github.com/elastic/observability-docs/issues/784, which will rework the Fleet User Guide and move the Quick start guides to the Observability Guide.

**Comment by dedemorton** [comment]
As part of this effort, we need to make sure the stack getting started gets updated, too. Otherwise, I think it will be confusing to users.

**Comment by dedemorton** [comment]
The quick start guides are moved over to the obs guide in https://github.com/elastic/observability-docs/pull/1149.

After that PR is merged, we need to do some related cleanup in the obs docs:

* Remove repetition in the Spin up the Elastic Stack page and the Prerequisites section in the first two Elastic Agent quick starts. At some point in the future we might be able to refine the preq section, add it to the Splunk topic, and remove the Spin up the Elastic Stack page.
* Clean up the links that point to the beats-related ingest topics.
* Decide how to handle images that are embedded in shared widgets (right now, they are duplicated under `observability` and `ingest-management`.

**Comment by dedemorton** [comment]
Closing because the obs docs now have content about ingesting with Elastic Agent. 

We still have more work to do, but we should create issues about specific changes rather than keeping this old one open.
