### ISSUE TITLE
Renaming of index patterns to data views

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#1096]
## Description

Related issue: https://github.com/elastic/kibana/issues/100844

Looks like we now have shared attributes for **Data view** in the docs repo.

cc @elastic/obs-docs 

## Collaboration

* [x] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

## Suggested Target Release

7.16

**Comment by bmorelli25** [comment]
The Kibana index pattern documentation URL is also changing as a part of this renaming. All documentation links will need to be updated: `index-patterns.html` (old) → `data-views.html` (new). See https://github.com/elastic/kibana/pull/110421.

**Comment by colleenmcginnis** [comment]
#1671 updates docs related to parts of the UI that have already been updated to use "data views". 

Not all parts of the Observability UI have switched from "index patterns" to "data views" yet. We should continue to track:

- [ ] https://github.com/elastic/kibana/issues/125498 for updates to Observability's **Metrics** > **Settings** > **Indices** > **Metric indices**
- [ ] https://github.com/elastic/kibana/issues/128192 for updates to Observability's **Uptime** > **Settings** > **Indices** > **Uptime indices**

**Comment by bmorelli25** [comment]
The linked development issue was moved to the bottom of the backlog https://github.com/elastic/kibana/issues/125498#issuecomment-1609284915.

I'm keeping this in blocked and moving to the bottom of our backlog as well.

**Comment by dedemorton** [comment]
https://github.com/elastic/kibana/issues/125498 was closed as "not planned." Should we just close this issue, too?
