### ISSUE TITLE
[Request] Need to review / tweak docs on how to upgrade integrations (for when auto-upgrade won't work)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#1103]
## Description
based on the work done in Kibana Fleet and as doc'ed here:
https://github.com/elastic/observability-docs/pull/1029/files#diff-412dafddd8ce282acddb187794445e0c6ff79a360c7ccca9da1c2c4b09bb78d5R341

we are doc'ing mostly just the auto-upgrade feature.  But it is known that in some advanced cases (even from just 1 version back) the Integration upgrade won't work, so I think we should leave a really clear and easily found and navigable trail for someone who needs to do this process manually.

The task here is to review that PR, starting with that line and adjust it so it is more inclusive of the intended likelihood that the manual upgrade will be needed and review if we need to add anything back (not done yet)

**Comment by bmorelli25** [comment]
Hey, @EricDavisX 👋. Do you know if internal docs exist or where I can turn to learn more about this manual update process?

**Comment by EricDavisX** [comment]
I'm out of the loop on what progress Fleet team has made.  can I ask that we pull in @kpollich or @jen-huang (or both) to confirm if we still have any intention on users manually upgrading integrations, and if so, if we want to invest in doc'ing more there or let it ride as is.  I'm not sure if many SDH have come in or requests/problems on it.

**Comment by bmorelli25** [comment]
Friendly bump, @kpollich / @jen-huang.

**Comment by jen-huang** [comment]
I'm actually not sure if any action is needed here, looks like we have docs accounting for manual upgrade of policies here:
https://github.com/elastic/observability-docs/issues/900
https://www.elastic.co/guide/en/fleet/current/upgrade-integration.html#upgrade-integration-policies-manually

**Comment by dedemorton** [comment]
Closing because the docs cover this now. If additional changes are required, please open a new issue. Thanks!
