### ISSUE TITLE
[Request] Rename the Fleet User Guide to Fleet and Elastic Agent Guide

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1104]
## Description

Current doc title does not convey the fact that the book includes content about Fleet and Elastic Agent. We discussed various options, including _Fleet and Elastic Agent Operator's Guide_, _Data Ingestion Guide_, and just simply _Fleet and Elastic Agent_.

I propose that we use _Fleet and Elastic Agent Guide_. It follows the pattern established by the Kibana Guide and broadens the scope of the guide to include Elastic Agent. It does not address user goals or specific user roles, but I think that's OK since the book paradigm will go away with the new system anyhow.

Here's what we need to do to rename the book:

- [x] Change the title in the conf.yaml.
- [x] Change the title in the index.asciidoc file.
- [x] Search for hard coded references across the documentation and replace them in the master, 7.x, and 7.16 (didn't check all the repos, but the major ones that were likely to refer to the book by name).
  - [x] apm
  - [x] beats
  - [x] cloud
  - [x] elasticsearch
  - [x] kibana
  - [x] observability-docs
- [x] Update the Kibana UI to use the new name in doc links. (Hopefully they are all in the docs link service: https://github.com/lcawl/kibana/blob/master/src/core/public/doc_links/doc_links_service.ts)
- [x] Communicate the change to authors across the org.
- [x] NO ~Set up a global redirect (if we decide to change the URL).~

Open issues:
- [x] NO Do we want to backport link changes to other versions? 
- [x] NO Do we want to change the URL to match the book? The URL is currently: https://www.elastic.co/guide/en/fleet/<version>/fleet-server.html
- [x] YES. Is is OK if older versions of Kibana say "Fleet User Guide" but point to the "Fleet and Elastic Agent Guide"? The name change is global and affects all versions of the book. If a naming discrepancy is not OK, we will need to create a legacy book, which is not ideal for in-service releases, IMO. Other option is to backport the change in Kibana to all maintained releases and not worry about existing users who choose not to upgrade.

## Collaboration

* [x] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

## Suggested Target Release

7.16 (the sooner the better)

## Stakeholders

Other writers across the org need to know that the book name is changing in case they mention the book by name.

**Comment by dedemorton** [comment]
@mostlyjason @nimarezainia We'd like your input on the renaming of this guide.

**Comment by mostlyjason** [comment]
👍

**Comment by ollyhowell** [comment]
LGTM!

**Comment by dedemorton** [comment]
Closing because the book is now renamed.
