### ISSUE TITLE
[Synthetics] Improve discussion of imports in `synthetics.config.ts`

### ISSUE THREAD

**Issue by andrewvc** [elastic/observability-docs#1105]
Per [this forum post](https://discuss.elastic.co/t/synthetics-test-configuration/284150) our docs covering `synthetics.config.ts` are incomplete, and only cover putting it in a node module. We should document the multiple ways this file can be used.

**Comment by colleenmcginnis** [comment]
@andrewvc is this still relevant?

In the [forum post](https://discuss.elastic.co/t/synthetics-test-configuration/284150) you mentioned that you don't have to import `SyntheticsConfig`. You pointed to the /synthetics-demo repo as an example where we _don't_ import `SyntheticsConfig` in the config file, but it looks like in https://github.com/elastic/synthetics-demo/commit/98947134c0b53134c606577cf76b820c5ede6f03 you updated that file, and now it _does_ import `SyntheticsConfig`. Is this just the `SyntheticsConfig` import is built into the `init` command or is it required now?

If this is still relevant, can you expand on what you mean by "the multiple ways this file can be used"?
