### ISSUE TITLE
[Request] Simplify synthetics steps shown in the Quick Start for agent/fleet

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1111]
## Description

We should simplify the [synthetics instructions in the quick start guide](https://www.elastic.co/guide/en/fleet/current/fleet-quick-start.html#add-synthetics-integration) by showing a simple HTTP monitor that users are unlikely to mess up. Otherwise, users might get the settings wrong and be forced to edit the integration policy.

Also, providing a simple example helps us avoid having to point to the Heartbeat docs, which are going to be super confusing because they show Heartbeat config examples that are not valid if you are running Elastic Agent. It's a lot to expect users to map the Heartbeat config settings to what they see in the UI.

## Collaboration

* [x] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Comment by colleenmcginnis** [comment]
I _think_ this was sufficiently addressed #1725 (see [Set up monitors](https://www.elastic.co/guide/en/observability/current/uptime-set-up.html)). I'm going to close here, but feel free to reopen if I missed something!
