### ISSUE TITLE
Elastic Agent integration naming

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#1112]
An "Elastic integration" is a broad term that can indicate any kind of integration including Beats, enterprise search and more.  We should use the naming "Elastic Agent integration" to help distinguish them from other kinds of integrations when content is talking specifically about Elastic Agent. 

Pages to update:
https://www.elastic.co/guide/en/fleet/current/integrations.html#update-integration
https://docs.elastic.co/en/integrations
https://www.elastic.co/guide/en/fleet/current/fleet-overview.html#configuring-integrations

Possibly others need to be updated as well.

CC @akshay-saraswat

**Comment by dedemorton** [comment]
@mostlyjason Are you OK with using "Elastic Agent integration" as the first instance on a page/section? Otherwise the docs will be super repetitive and harder to read.

**Comment by mostlyjason** [comment]
@dedemorton yeah I think that's fine. Broadening the definition of "integration" is a confusing concept for people internally, and I imagine the different types of integrations can be confusing for users. The point of this is mainly to make the type of integration clear to readers. That doesn't mean we need to be overly verbose where the context is clear.

**Comment by dedemorton** [comment]
Fixed in #1259 

There might be stray references that we need to fix in other places, but this is at least a start. (I noticed some minor inaccuracies in https://www.elastic.co/guide/en/fleet/master/fleet-overview.html, but will fix those in a follow-on PR).
