### ISSUE TITLE
[Request] Journalbeat to be removed in 7.16

### ISSUE THREAD

**Issue by andresrc** [elastic/observability-docs#1173]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*

Journal beat is going to be removed in 7.16. The functionality has been subsumed into the `journald` input in filebeat (see [docs](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-journald.html)). Directly removing the docs might be confusing for current users so the proposal (open for discussion) would be to change the current content of the [book](https://www.elastic.co/guide/en/beats/journalbeat/current/index.html) for an explanation that the functionality is currently in filebeat and a link there.

## Collaboration

* [x] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Contact Person:**

*(We need to have a contact person in the product/development team to provide information about how the item to be documented works - this can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

@nimarezainia @kvch 

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*

7.16

## Stakeholders

*(Please list any stakeholders for this issue.)*

@elastic/elastic-agent-data-plane

**Comment by dedemorton** [comment]
Closed in https://github.com/elastic/beats/pull/29137.
