### ISSUE TITLE
[docs] Ingest Manager & Agent (and Integrations / Beats / Endpoint) data flow citation is needed in docs

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#118]
Hi, internal and external questions are arising about what Ingest Manger and Agent are doing in terms of where data is coming from and how it gets to where it goes for setup, etc.  Users familiar with Beats may have an incorrect inherited assumption, and so we can document it all together, in one place, and in a way to clarify and inform new-to-Beats users, too.

Content is below, tho  you can frame it all as desired in the Docs, I don't think it needs to be in the FAQ or listed as Q&A necessarily:   

Does the Elastic Agent download or does Kibana download the Integration packages needed from the internet?

answer:  Kibana connects to the Elastic package registry at epr.elastic.co and downloads the Packages and stores their assets in Elasticsearch.  This done for the user now in Ingest Manager as opposed to configuring and executing it manually as in stand-alone Elastic Beats usage.

Does Elastic Agent download anything at all from the Internet?

answer: No, with one special exception.  Since Metricbeat and Filebeat are bundled with the Elastic Agent they are on the host when Agent is installed.  The special case is the Elastic Endpoint, which is downloaded by the Agent based OS and architecture from the Elastic download site, when Elastic Agent Policy is set to include it.  Bundling Elastic Endpoint together with Elastic Agent is a known feature request scoped for a future release (link to issue?)

Do the Beats that Agent configures on the host send assets into Elasticsearch like stand-alone beats do?

answer: No, this is handled by Ingest Manager now.  For the example of the stand-alone Elastic Beat Nginx module, the Integrations packages on epr.elastic.co contain what used to be in the Filebeat or Metricbeat module.  That is, the Elasticsearch and Kibana assets. As the assets are now managed by Ingest Manager, there is no need for the Elastic Agent configured Beats to run their setup step and send assets to Elasticsearch and/or Kibana.

**Comment by EricDavisX** [comment]
@skh Thanks for help confirming info.  Does the above look right?

@immon hope this helps, please help us clarify any more questions that relate to this or if any language isn't as clear.

@dedemorton keep in touch, if I can help put it in or get more info or review

**Comment by EricDavisX** [comment]
updated epr.co to epr.elastic.co - thanks Pawel.

**Comment by dedemorton** [comment]
Noting here that we are plan to provide a more complete introduction that describes the architecture, how data flows through the system, the indexing strategy, and so on. See https://github.com/elastic/integrations-dev/issues/64.

I think it might be good to add some FAQ topics in the mean time.
