### ISSUE TITLE
[Request] Observability RAC features documentation in 7.16

### ISSUE THREAD

**Issue by vinaychandrasekhar** [elastic/observability-docs#1190]
## Description
Observability RAC features - the new Alerts View, the new Cases View, and alert annotations in APM - will be made available to all users as "Experimental" features in 7.16. Please see reference and communication links below. These new features will need accompanying documentation describing the functionality. Requesting updates to the following documentation, and would welcome guidance from the doc team on any additional docs that might need to be updated. 

Docs and doc updates being requested:
- Release Notes: Need to mention feature, plus include instructions on how to disable the feature if the user needs to
- User Guide / Reference Guide update
   - Info message stating that the feature is Experimental and that the data structures are subject to change (could reuse the language that is shown when hovering over the "Experimental" badge shown in the UI)
- Documentation to our Support staff to be able to disable the feature if needed when working through Support cases

Reference and communication links:
Feature flags being enabled - https://github.com/elastic/kibana/issues/105237 , https://github.com/elastic/kibana/pull/115785
Communication - https://groups.google.com/a/elastic.co/g/rac/c/tETDFwDkqEM
Design ticket - https://github.com/elastic/observability-design/issues/111

## Collaboration

* [x] The docs team will lead producing the content

**Contact Person:**
PM - @vinaychandrasekhar 
Engineering - @mgiota 

## Suggested Target Release

7.16

## Stakeholders
@cyrille-leclerc 
@jasonrhodes

**Comment by paulb-elastic** [comment]
@EamonnTP just catching up on this, with the merges done, can this be closed, is there anything outstanding?  Thanks.

**Comment by EamonnTP** [comment]
Hi @paulb-elastic Yes, this can now be closed. I'll close it now. Related PR: https://github.com/elastic/observability-docs/pull/1211
