### ISSUE TITLE
HTTP JSON Input supported in Elastic Agent but it is not exposed by any integration

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/observability-docs#1207]
The documentation page <https://www.elastic.co/guide/en/fleet/master/beats-agent-comparison.html#supported-inputs-beats-and-agent> shows HTTP JSON input is supported in Elastic Agent.

There are several Integrations using `httpjson` under the hood, but we do not have any exposing `httpjson` input or which allow collecting data from a custom `httpjson` source.

We have also an issue which seems related in integrations: https://github.com/elastic/integrations/issues/709

**Comment by dedemorton** [comment]
@lucabelluccini Just to confirm: it sounds like we just need to remove the check mark next to httpjson input for standalone and managed Elastic Agent?

@mostlyjason @nimarezainia FYI

**Comment by mostlyjason** [comment]
@nimarezainia it sounds like the confusion is the meaning of the checkmark on that page. I think you intended it to say that the input was supported internally for integrations, but the reader interpreted that as being available for customers to use directly?

**Comment by lucabelluccini** [comment]
**An example**

I want to migrate a Filebeat where I'm using `httpjson` to an Agent.
Checking that table I would be tricked by the fact there's an integration/solution for me to use the `httpjson` and decommission my Filebeat with an Agent.

**Comment by nimarezainia** [comment]
@mostlyjason @dedemorton yes I see @lucabelluccini 's point here. As mentioned it's being used under the hood by integrations such as: apache, AWS, GCP, netscout and Okta but it's not available as a standalone input.  sorry for the confusion.

Could we uncheck those from the fleet managed agent. I believe Standalone would inherit from beats.

**Comment by dedemorton** [comment]
Opened https://github.com/elastic/observability-docs/pull/1238. Please review the PR when you get a chance. Thanks!
