### ISSUE TITLE
[Synthetics] Phase out using Uptime checks terminology

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#1232]
## Description

As part of phasing out using the **Uptime checks** terminology, we need to change the title of the following asciidoc file:

`monitor-uptime-asciidoc` -> `monitor-lightweight.asciidoc`

This update will required a redirect and updatied links in various other docs.

**Comment by colleenmcginnis** [comment]
We need to keep references to "uptime" while the Uptime app is still the primary way to view monitors in Kibana. When the Synthetics service launches, we'll do a full sweep for "uptime" terminology.
