### ISSUE TITLE
[Request] Removing "-f" as a recommendation on the Elastic Agent install command

### ISSUE THREAD

**Issue by nimarezainia** [elastic/observability-docs#1234]
## Removing the "-f" option in our recommendation of how Elastic Agent is deployed

*(Describe what needs to be documented. Link to relevant issues.)*

Throughout the docs we recommend that the Elastic Agent be installed/enrolled using the "-f" flag. This is valid but will also cause issues if the user continously calls with that flag on. While we are working on addressing the robustness around usage of "-f" we think it would be best not to recommend it in our quick start guides and examples.

A few places I see this being used:
https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html
https://www.elastic.co/guide/en/fleet/current/fleet-quick-start.html

Also this snippet should be fixed to remove the comment about -f:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/13442829/140548443-2bc7e7a4-fb3b-4cf9-ad6f-a8ddf61c7a3a.png">

Will open another issue to better describe usage of "-f".

## Collaboration
*(Indicate the expected collaboration model by marking the appropriate task and deleting the others.)* 
* [ ] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person: @nimarezainia **

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*
Anytime but soonish :-)

## Stakeholders

*(Please list any stakeholders for this issue.)*
@ruflin @michalpristas

**Comment by dedemorton** [comment]
Closing because we fixed this awhile ago. I guess we forgot to close it.
