### ISSUE TITLE
[Exploratory view permission] Exploratory view needs index pattern permissions to bootstrap

### ISSUE THREAD

**Issue by shahzad31** [elastic/observability-docs#1250]
## Description

In exploratory view, just like Lens, we need to create index patterns(data view) to create visualizations, an admin user at least needs to create relevenat data type series, once so that it can create those index patterns. Once that is done, at that point for exploraing purpose we don't need those permissions. But if user needs to save those viz or need to add to case, we need further permissions.

We need to document all these permission requirements by exploratory view.

Right now we show an error if user doesnt have permissions to create index pattern

![image](https://user-images.githubusercontent.com/3505601/140943810-88f5ab17-3796-4cb2-950c-8649c9ce65ee.png)

## Collaboration
*(Indicate the expected collaboration model by marking the appropriate task and deleting the others.)* 
* [ ] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:**

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by colleenmcginnis** [comment]
>We need to document all these permission requirements by exploratory view.

@shahzad31 is this still relevant? If it is can you list the permissions requirements here?

**Comment by shahzad31** [comment]
This is not relevant, so closing it
