### ISSUE TITLE
[Request] [Fleet] Remove `.` prefix from custom component template docs

### ISSUE THREAD

**Issue by hop-dev** [elastic/observability-docs#1261]
## Description

@axw noticed [here](https://github.com/elastic/apm-server/pull/6553#issuecomment-966608256) that we do not need to add a `.` prefix to the custom component template in the Customize data retention for integrations docs [here](https://www.elastic.co/guide/en/fleet/master/data-streams.html#data-streams-ilm-two) 

The component template name should be `<type>-<dataset>-<namespace>@custom`.

## Collaboration
* [x] Other : @bmorelli25 wrote the docs originally, I am happy to have a go at making the changes if needs be, I dont know if there are guidelines on generating screenshots for docs? 

**Contact Person:** @hop-dev 

## Suggested Target Release

7.16.0

**Comment by bmorelli25** [comment]
No worries, @hop-dev, I can make this fix. I'll move this to the obs-docs board.

**Comment by hop-dev** [comment]
Closing as this documentation is being removed as part of [119013](https://github.com/elastic/kibana/issues/119013)
