### ISSUE TITLE
Make ingest docs more prominent on the doc landing page

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#128]
Currently the docs about Elastic Agent and Fleet (fka Ingest Manager) are buried under the [Ingest Management Guide](https://www.elastic.co/guide/en/ingest-management/current/index.html) in the Beats documentation. The docs need to be more prominent. There's not an ideal location on the existing doc landing page, which is siloed by product. This problem will be solved by the site redesign that's in progress, but it might take awhile. In the mean time, should we consider moving the content to a more visible location in https://www.elastic.co/guide/index.html?

We need to think about the security and endpoint use cases, too. Let's discuss the possibilities in this issue.

Assigning this to all writers who are impacted, plus the ingest management PM. Feel free to add participants.

**Comment by dedemorton** [comment]
@mostlyjason @ph Given that we have renamed Ingest Manager to Fleet, does it make sense to rename the book from "Ingest Management Guide" to "Fleet User Guide"?On the landing page, we could make Fleet a top-level entry on the doc landing page and provide the guide underneath. Eventually we would also have a Fleet API Reference under the same top-level category.

WDYT?

why? Until we have the new doc system, we need to have a "book" structure that holds the content. In the new system, the book paradigm will go away, which will open more possibilities for organizing content purely around user goals.

**Comment by ph** [comment]
I think it's a great idea. +1 on that and it open the door. Could a "endpoint" or Security could be a book below Fleet user guide?

**Comment by andresrc** [comment]
As discussed in the thread we are going with:
* Section Name: "Fleet: Install and manage Elastic Agents"
* Book name: "Fleet User Guide"

Let's put it initially just before the beats section.
