### ISSUE TITLE
[Request] Removing some hyperlinks from Elastic Agent comparabilities page

### ISSUE THREAD

**Issue by nimarezainia** [elastic/observability-docs#1290]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*

In this section of the docs: https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html#supported-configurations
we have hyperlinks to filebeat where the configuration option has been described in detail. this is confusing some users as it's referring them to filebeat and the configuration is not exactly the same for the Elastic Agent.

The request here is to remove the hyperlink from the table in order to avoid further confusion.

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content
- The product team will provide the initial content and the docs team will edit / review
- The docs team will define with product team the structure and location, and the product team will provide the initial content
- Other (please describe)

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:**
@nimarezainia 

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by dedemorton** [comment]
Fixed in https://github.com/elastic/observability-docs/pull/1841.

Sorry we didn't get to this ahead of you. (It got a bit lost in the move to a new project board.)
