### ISSUE TITLE
[Request] Update 7.16 Release Notes regarding Journalbeat replacement

### ISSUE THREAD

**Issue by nimarezainia** [elastic/observability-docs#1291]
## Description

Need the following to be included in the release-notes for 7.16:

*Journalbeat, a lightweight shipper dedicated to collecting logs written by Journald system service, is being deprecated in this release. This functionality is instead provided as an input for Filebeat. Users should migrate to using Filebeat and it’s journald input as described in the [Elastic documentation](https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-input-journald.html).

The users can also enable collection of Journald logs via the Elastic Agent by enabling the "Custom Journald Logs" integration. 
*

[NOTE: it would be great to point the user to the integrations docs for "Custom Journald Logs" - however  I don't have that URL]

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content
- The product team will provide the initial content and the docs team will edit / review
- The docs team will define with product team the structure and location, and the product team will provide the initial content
- Other (please describe)

**Contact Person:**
@nimarezainia 

## Suggested Target Release

*7.16*

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by dedemorton** [comment]
@nimarezainia @kvch I just noticed that the Journald input *and* the Custom Journald logs integration are both still marked as experimental. Is that a mistake, or are we really recommending that users migrate to something that is experimental?

**Comment by kvch** [comment]
Both of them are still experimental. The input is stable, the only reason we kept it experimental is that I am introducing breaking changes to the configuration in https://github.com/elastic/beats/pull/29294
