### ISSUE TITLE
[Request] Add Fleet Server Integration Policy Upgrades Known Issue

### ISSUE THREAD

**Issue by kpollich** [elastic/observability-docs#1294]
## Description

Add "known issue" under https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html for errors after upgrading Fleet Server integration policies in Cloud in 7.16.

Root cause issue: https://github.com/elastic/kibana/issues/119523

## Collaboration

- The product team (@kpollich) will provide the initial content and the docs team will edit / review

**Contact Person:** @kpollich 

## Suggested Target Release

7.16.x

## Stakeholders

@elastic/fleet

**Comment by kpollich** [comment]
Description WIP

**Comment by kpollich** [comment]
_Draft of docs content_

## After upgrading integration policies for Fleet Server, "Elastic Agent on Cloud" agents remain stuck in "Updating" or go "Offline"

In Elastic Cloud, after [updating](https://www.elastic.co/guide/en/fleet/current/integrations.html#update-integration) Fleet Server and its integration policies, your "Elastic Agent on Cloud" agents may experience issues updating. To resolve this, take the following steps. 

1. Delete the Fleet Server integration policy under the "Elastic Agent on Cloud" policy

You can find the ID of the Fleet Server integration policy by navigating to `Fleet -> Agent Policies -> Elastic Agent on Cloud -> Fleet Server`. This should take you to a URL like this:

`<kibana_ur>/fleet/policies/policy-elastic-agent-on-cloud/edit-integration/<integration_policy_id>`

Using the integration policy ID value in the URL, open up `Management > Dev Tools > Console` in Kibana and execute the following query to remove the Fleet Server integration policy:

```
DELETE .kibana/_doc/ingest-package-policies:<integration_policy_id>
```

2. Recreate the Fleet Server integration policy

Execute the following `cURL` request, providing your Kibana superuser credentials to forcefully recreate the Fleet Server integration policy on the "Elastic Agent on Cloud" agent policy:

```shell
$ curl -u <username>:<password> --request POST \
  --url <kibana_url>/api/fleet/package_policies \
  --header 'content-type: application/json' \
  --header 'kbn-xsrf: xyz' \
  --data '{"name": "Fleet Server","description": "","namespace": "default","policy_id": "policy-elastic-agent-on-cloud","enabled": true,"output_id": "","inputs": [{"type": "fleet-server","policy_template": "fleet_server","enabled": true,"streams": [],"vars": {"host": {"value": ["0.0.0.0"],"type": "text"},"port": {"value": [8220],"type": "integer"},"max_connections": {"type": "integer"},"custom": {"value": "server.runtime:\n  gc_percent: 20","type": "yaml"}}}],"package": {"name": "fleet_server","title": "Fleet Server","version": "1.0.1"},"force": true}'
```

3. Remove any agents stuck in the "Updating" status

Follow the steps in https://github.com/elastic/observability-docs/pull/1292 to remove any agents stuck in the "Updating" status

---

cc @nchaulet - do these steps looks correct to you? Is there a better way to recreate the Fleet Server package policy we use in cloud?

**Comment by nchaulet** [comment]
@kpollich I think we can add another step between 1 and 2 

Clean the existing `.fleet-policies` doc
```
POST .fleet-policies/_delete_by_query?q=policy-elastic-agent-on-cloud
```

**Comment by kpollich** [comment]
> @kpollich I think we can add another step between 1 and 2
> 
> Clean the existing `.fleet-policies` doc
> 
> ```
> POST .fleet-policies/_delete_by_query?q=policy-elastic-agent-on-cloud
> ```

Good catch - added above.

**Comment by kpollich** [comment]
@elastic/obs-docs could we get a set of eyes on this from the docs team? Would love to land this known issue soon as we've seen quite a few support cases experiencing this issue in the last few weeks.

**Comment by dedemorton** [comment]
Yes, we can bump the priority here.
