### ISSUE TITLE
Old terms for referring Agent state is used in Elastic docs under Fleet overview guide page.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/observability-docs#1298]
Link : https://www.elastic.co/guide/en/fleet/7.16/fleet-overview.html

Under the marked area on above mentioned guide page Agent state with current reference needs to be updated.

Screenshot:
![image](https://user-images.githubusercontent.com/72375798/144039595-bccabee5-f604-4d2e-915a-92f45ed8a091.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @dedemorton 

CC: @EricDavisX

**Comment by dedemorton** [comment]
Fixed in https://github.com/elastic/observability-docs/pull/1345/commits/de03f5f9bbafdf7c69c4f3b21ccdbfc162e23ba1

**Comment by dikshachauhan-qasource** [comment]
Hi @dedemorton 

We have validated the merged changes at 7.16 Elastic guide and abel able to fetch the updated changes.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/145971740-de72af92-d125-4445-95d4-a1e15b973790.png)

Hence, we are closing this out.

Thanks'
QAS
