### ISSUE TITLE
Move Uptime monitoring guide into observability-docs

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#13]
The [Uptime monitoring guide](https://www.elastic.co/guide/en/uptime/current/index.html) currently lives in the [Kibana repo](https://github.com/elastic/kibana/tree/master/docs/uptime-guide). We should move this content to the observability-docs repo to live with the other Observability content.

* All branches, from `master`-`7.2` need to be moved.
* Unfortunately, there will not be a way to maintain the history of the content.
* Once moved, the `master` content should be deleted from the Kibana repo.

cc @elastic/uptime for any concerns or feedback

**Comment by andrewvc** [comment]
Love this idea
