### ISSUE TITLE
Update Beats docs to include ES CA fingerprint

### ISSUE THREAD

**Issue by jlind23** [elastic/observability-docs#1307]
With security on by default she should mention the new fingerprint option for ssl verification mode. We should also tell users where to find this information when they start ES for the first time (the ES logs) or later (using their browser, curl or the openssl command).

**Comment by dedemorton** [comment]
Who will lead creating this content? The dev team or docs team?

If docs team, we'll need more guidance about this feature, how it impacts the documentation, and the name of the SME who will provide input and review the docs PR.

**Comment by jlind23** [comment]
Dev team, @belimawr will take care of it.
