### ISSUE TITLE
Update Elastic Agent and Fleet docs to include ES CA fingerprints

### ISSUE THREAD

**Issue by jlind23** [elastic/observability-docs#1308]
For Standalone agent and managed agent.

**Owner**
@michel-laterman

**Comment by dedemorton** [comment]
@jlind23 Can you provide more detail about the content changes/additions that are required here? Also what is the name of the SME who will provide input and review our doc changes?

**Comment by dedemorton** [comment]
Sorry just noticed that Michel is assigned this issue, but it's not clear who you expect to lead the documentation effort. The template for creating issues makes this clear, so it would be good to stick with that template so we get all the pieces we need to triage these issues. Thanks!

**Comment by dedemorton** [comment]
Removing the needs-input label because Michel has opened a PR with details.

**Comment by jlind23** [comment]
@dedemorton sorry for not sticking to that template. Indeed @michel-laterman will take care of it and we expect your to review if that's ok on your end.

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman 
While validating docs for 8.0 we haven't observed any documentation for `Fingerprints` changes with respect to standalone agents or installation of fleet server on a self-managed environment.
Tested area:
- https://www.elastic.co/guide/en/fleet/8.0/install-standalone-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/8.0/add-a-fleet-server.html

As far as we have checked we get few updates on fingerprint under:
[Encrypt traffic in a self-managed cluster](https://www.elastic.co/guide/en/fleet/master/secure-connections.html)

Could you please confirm if these es ca fingerprints changes are updated in guides for standalone agents, beats and fleet-server?
It will be helpful if you can share few guide links where this has been implemented. 

cc: @jlind23 

Thanks

**Comment by michel-laterman** [comment]
Oops, looks like I forgot to add it under the stand alone guide

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman 
Thanks for confirming.
Could you please check guide for self-managed Fleet Server:
- https://www.elastic.co/guide/en/fleet/8.0/add-a-fleet-server.html#add-a-fleet-server

We haven't observed any updates related to fingerprints for self-managed Fleet Server installation.
Further commands are also not updated under this guide:
![18](https://user-images.githubusercontent.com/77374876/149926917-a1223651-d4d9-4d00-b116-20c1b829fa26.JPG)

**Current expected command:**
```
sudo ./elastic-agent install  \
  --fleet-server-es=https://x.x.x.x:9200 \
  --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDI1MDYwMDY3MDY6d294c3hhQnRUMldmcnBwYzZzb3Nqdw \
  --fleet-server-policy=499b5aa7-d214-5b5d-838b-3cd76469844e \
  --fleet-server-es-ca-trusted-fingerprint=b15c3353614dc2525114409b7593050a934911bece4633f7a81ddcbdd2bcf4a6 \
  --fleet-server-insecure-http
```
Please let us know if we are missing anything here.
Thanks

**Comment by michel-laterman** [comment]
@amolnater-qasource, the PR still needs to be reviewed: https://github.com/elastic/observability-docs/pull/1463
