### ISSUE TITLE
[Request]: Minor changes related to Filebeat installation on 8.0.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#1309]
**Related Ticket:**
https://github.com/elastic/beats/issues/29175

**Description:**
As per few changes related to filebeat on 8.0, we have gone through the docs for the same at link https://www.elastic.co/guide/en/beats/filebeat/8.0/filebeat-installation-configuration.html.
While testing we observed some changes like:
**Scenario 01:**
- User has to manually enable filesets for modules from 8.0 onwards.[Which wasn't required earlier after running `./filebeat modules enable system` ]

Though information is provided under 8.0 docs for the same, however info line can be highlighted for this like: `Filesets are disabled by default.` as this change wasn't there on 7.16 or below.
![17](https://user-images.githubusercontent.com/77374876/144560196-b5bfa0ee-d2d9-422a-bf26-aecd0f3bcb1f.JPG)

**Scenario 02:**
On manually enabling the above filesets for system we observed an extra index pattern _(apm--transaction...)_ under Discover tab.
Detailed information is shared at: https://github.com/elastic/beats/issues/29175#issuecomment-982536819

However no information regarding any other index pattern is there other than `filebeat-*`.

**Screenshot:**
![18](https://user-images.githubusercontent.com/77374876/144560320-5623006d-189e-48eb-af8e-1e2dce63a4da.JPG)

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to: @elastic/elastic-agent-control-plane

cc: @EricDavisX

**Comment by jlind23** [comment]
@kvch would you give a stab at it? As far as i remember your worked on it right?

**Comment by kvch** [comment]
PR: https://github.com/elastic/beats/pull/29887
