### ISSUE TITLE
[Observability RAC] document xpack.ruleRegistry.write.disabledRegistrationContexts flag 

### ISSUE THREAD

**Issue by mgiota** [elastic/observability-docs#1310]
## Description

In this [issue](https://github.com/elastic/kibana/issues/119217) we introduced a new `xpack.ruleRegistry.write.disabledRegistrationContexts` flag, which user can use to disable writing to alerts-as-data indices in a more granular way. 

## Collaboration

- The docs team will define with product team the structure and location, and the product team will provide the initial content

`xpack.ruleRegistry.write.disabledRegistrationContexts`::
Specifies the observability alert indices that are disabled to be written. Data type is array. Allowed values are: [ 'observability.logs','observability.metrics','observability.apm','observability.uptime' ]

**Contact Person:**
@mgiota 

## Suggested Target Release

8.0.0

**Comment by colleenmcginnis** [comment]
@mgiota should information on this new flag replace the content at the beginning of [View Alerts](https://www.elastic.co/guide/en/observability/current/view-observability-alerts.html)? 

<img width="787" alt="image" src="https://user-images.githubusercontent.com/10479155/161339677-04a781ee-b888-401c-b5fe-f38b1cf8a470.png">

**Comment by colleenmcginnis** [comment]
@vinaychandrasekhar can you help with the question above?

**Comment by vinaychandrasekhar** [comment]
@mgiota would be the right person to answer the query. @mgiota thoughts please when you get a chance?
