### ISSUE TITLE
Update Fleet Settings for 8.0

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#1314]
## Description

In 8.0 we updated Fleet Settings by moving it to a separate tab in the Fleet UI. We also enhanced the output management controls. Users click the Edit action to configure an output now. Also, on Elastic Cloud, we added a new internal output used for routing. We should document the purpose of this new output, which is internal routing to reduce external network charges with the Elastic Cloud agent policy, and to provide visibility for troubleshooting on ECE. Its locked because users should not edit it directly. Users should use the default output for their agents.

![image](https://user-images.githubusercontent.com/6370704/144864178-7dfaec1d-be0c-4c1e-b7a8-ac61231363f3.png)

Here is the original issue, but we only implemented the Fleet settings part of it. We are deferring support for mulitple outputs to a later release.
https://github.com/elastic/obs-dc-team/issues/595

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- [X] The docs team will lead producing the content

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:**
@nchaulet 

## Suggested Target Release
8.0

*(Let us know if this feature is needed for a specific release.)*

## Stakeholders
@mostlyjason

*(Please list any stakeholders for this issue.)*

**Comment by dedemorton** [comment]
### Doc impact

I went through the Elastic Agent/Fleet docs + the quick start today and identified topics that need to be updated. Some have substantive changes that need to be addressed for 8.0. The other topics have stale screens, but shouldn't cause too much pain for users, so we can do them after 8.0, if necessary. A subset of those screens probably need to be updated for other reasons, so it makes sense to wait until later.

### Elastic Agent/Fleet docs

Substantive changes:

https://www.elastic.co/guide/en/fleet/current/secure-connections.html 
- Update the tasks and Fleet Settings screen capture under “Encrypt traffic between Elastic Agents, Fleet Server, and Elasticsearch”

https://www.elastic.co/guide/en/fleet/current/fleet-agent-proxy-support.html 

- Update the steps and screen capture under “Set the proxy for communicating with Elasticsearch”

https://www.elastic.co/guide/en/fleet/8.0/fleet-settings.html 

- Update the steps and add missing settings.

### Stale screenshots (not urgent):

https://www.elastic.co/guide/en/fleet/current/fleet-overview.html
- Add Nginx integration screen capture. No longer has Fleet Settings link.
- Fleet screen capture. Now has a Settings tab.

https://www.elastic.co/guide/en/observability/7.16/ingest-logs-metrics-uptime.html
- Fleet screen captures. Now have a Settings tab
- Add Elastic Synthetics integration screen. No longer has Fleet Settings link.
- Default policy screen. No longer has Fleet Settings link.
- Add Nginx integration screen. No longer has Fleet Settings link.
- Second Default policy screen. No longer has Fleet Settings link.

https://www.elastic.co/guide/en/observability/8.0/ingest-traces.html 
- Add agent screen. No longer has Fleet Settings.
- Fleet screen. No longer has Fleet Settings.

https://www.elastic.co/guide/en/fleet/current/upgrade-integration.html
- Upgrade Nginx integration screen. No longer has Fleet Settings link.
- Upgrade AWS integration screen.  No longer has Fleet Settings link.
- aws-1 integration policy screen. No longer has Fleet Settings link.

https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html 
- Add agent page. No longer has Fleet Settings link.

https://www.elastic.co/guide/en/fleet/8.0/fleet-server-scalability.html 
- Elastic Cloud agent policy screen. No longer has Fleet Settings link.

https://www.elastic.co/guide/en/fleet/8.0/fleet-server-monitoring.html
- Fleet Server policy screen. No longer has Fleet Settings link.

https://www.elastic.co/guide/en/fleet/8.0/upgrade-elastic-agent.html 
- Fleet screens (2). No longer have Fleet Settings link.
- Add agent screen. No longer has Fleet Settings link.

https://www.elastic.co/guide/en/fleet/8.0/view-elastic-agent-status.html 
- Fleet screens (2). Now have a Settings tab.

https://www.elastic.co/guide/en/fleet/8.0/agent-policy.html 
- Create agent policy screen. No longer has Fleet Settings link.
- Fleet screens (2).  No longer have a Fleet Settings link.

https://www.elastic.co/guide/en/fleet/8.0/fleet-enrollment-tokens.html 
- Fleet screens (2). No longer have Fleet Settings link.

https://www.elastic.co/guide/en/fleet/8.0/data-streams.html 
- Fleet screen. No longer has Fleet Settings link.

**Comment by amolnater-qasource** [comment]
Hi Team
While testing docs for 8.0, we have observed these changes to Fleet Settings not yet available.

We will be retesting the same when available.
Thanks

**Comment by amolnater-qasource** [comment]
Hi @dedemorton 
We have observed at page: 
https://www.elastic.co/guide/en/fleet/8.0/manage-agents-in-fleet.html
- Component- Settings also needs to be added as Fleet Settings are available as a tab now.

We will be updating this comment if we found any other requirement not mentioned above.
Thanks

**Comment by dedemorton** [comment]
Sounds good. I'm working on the doc updates right now and should have them up for review in a day or two.

**Comment by dedemorton** [comment]
@amolnater-qasource A PR of the changes for this issue is up at https://github.com/elastic/observability-docs/issues/1314. (As noted, this includes content changes, and not screenshots, which are covered in a separate (less urgent) PR. Thanks!

**Comment by amolnater-qasource** [comment]
Thanks for confirming @dedemorton 
We will keep track of these PRs and will validate docs after merges.
