### ISSUE TITLE
[Request] Link to the GCP Dataflow integration docs from the Integrations page in Kibana and on elastic.co

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/observability-docs#1315]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*
Hi Folks, I think the GCP Dataflow entry in the integrations page on elastic.co, and within Kibana would be better if it pointed to the [GCP Dataflow docs
](https://www.elastic.co/guide/en/observability/7.15/gcp-dataflow.html) instead of listing the fields populated by the integration, as the list of fields does not give the reader a way to implement the integration.

I would write a PR, but I don't know how the integrations page in the docs or in Kibana are generated.  If the suggested change is OK with you and you want to teach me how to fish, I am happy to do it.

**Comment by DanRoscigno** [comment]
@linyaru can you suggest who I can talk to to find out which of the above docs are the "best practices" for each of the CSPs?  Would it be Adam Quan for AWS?  I don't have any idea who to speak to for GCP.

**Comment by dedemorton** [comment]
I'm closing this issue because it's old. The current version of the integration docs do not mention data flows, so it doesn't seem quite right to add a link there. We are working on general improvements to the docs about various data ingestion methods and will address any problems with content discovery there.

**Comment by DanRoscigno** [comment]
I thought for a second you said you were "closing it because Dan is old"

;)

**Comment by dedemorton** [comment]
@DanRoscigno Well...that would be the pot calling the kettle black. 😆
