### ISSUE TITLE
Update content to match training videos

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#1323]
Training videos will be updated to reflect the use of Elastic Agent and Integrations. The content on the following pages will require an update to match the videos:

- [Logs](https://www.elastic.co/guide/en/observability/current/monitor-logs.html)
- [Metrics](https://www.elastic.co/guide/en/observability/current/analyze-metrics.html)

**Comment by bmorelli25** [comment]
Vids have been updated!
