### ISSUE TITLE
How-to guide for a PCF integration

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#135]
### Summary

Within the Observability guide, we should add a how-to guide relating to the PCF integration. The content should reflect the different use-cases (personas) listed in this [google doc](https://docs.google.com/document/d/1U_U_eamllOkrEvNwvR151MCGKRoNPQdg1FCl51ND-O8/edit), which will be used as a source for the published content in the Observability guide.

**Comment by mukeshelastic** [comment]
fyi @jsoriano @andresrc

**Comment by bmorelli25** [comment]
@mukeshelastic what's the status of this issue?
