### ISSUE TITLE
[Request] Links on "Fleet and Elastic Agent overview" page with wrong syntax

### ISSUE THREAD

**Issue by AndersonQ** [elastic/observability-docs#1401]
## Description

Some links on "Fleet and Elastic Agent overview" aren't using the correct syntax, instead of [link](http://exzampler.comn) a few are in the form _[link] ([http://example.com](http://example.com))_.

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- Other (the docs team needs to approve the change)

**Contact Person:** @AndersonQ 

## Suggested Target Release

None (?) - it's just a formaring issue.

## Stakeholders

@jlind23

**Comment by dedemorton** [comment]
Closed by #1402
