### ISSUE TITLE
Update documentation that shows how to disable alerts as data

### ISSUE THREAD

**Issue by vinaychandrasekhar** [elastic/observability-docs#1416]
## Description

8.0 has a new and different flag to enable / disable the alerts as data feature. Current (7.16) documentation needs to be updated to reflect this change.  

https://github.com/elastic/kibana/issues/119217

## Collaboration
- The product team will provide the initial content and the docs team will edit / review

**Contact Person:**
@mgiota 

## Suggested Target Release
v8.0

## Stakeholders
@jasonrhodes @vinaychandrasekhar

**Comment by colleenmcginnis** [comment]
Is this a duplicate of https://github.com/elastic/observability-docs/issues/1310?

**Comment by colleenmcginnis** [comment]
Closing in favor of #1310. Please re-open if this is not a duplicate.

**Comment by mgiota** [comment]
@colleenmcginnis Yep it looks like a duplicate.
