### ISSUE TITLE
o11y - Update documentation to reflect changes to the Alerts view

### ISSUE THREAD

**Issue by vinaychandrasekhar** [elastic/observability-docs#1417]
## Description

Alerts page now shows counts of enabled, disabled rules. And user modifications to the alerts table in the Alerts view will be persisted when navigating away and back. Both of these need a mention accordingly in the documentation. 

https://github.com/elastic/kibana/issues/116476

https://github.com/elastic/kibana/issues/117698

## Collaboration
- The product team will provide the initial content and the docs team will edit / review

**Contact Person:**
@claudiopro for rule counts
@Zacqary for alert settings persistence

## Suggested Target Release
v8.0

## Stakeholders
@jasonrhodes @vinaychandrasekhar

**Comment by vinaychandrasekhar** [comment]
Please note that elastic/kibana#116476 is now tracked for 8.1 availability. Check with @mgiota or me on any queries on this ticket.

**Comment by colleenmcginnis** [comment]
Do these need to be specifically mentioned in the documentation or just reflected in relevant screenshots?

**Comment by vinaychandrasekhar** [comment]
@colleenmcginnis reflected in relevant screenshots.

**Comment by colleenmcginnis** [comment]
Relevant screenshots were updated in https://github.com/elastic/observability-docs/pull/1723. If you notice any other screenshots that need to be changed, feel free to reopen!
