### ISSUE TITLE
Integration doc updates

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#1432]
Update tomorrow:

- [ ] [Osquery](https://docs.elastic.co/en/integrations/osquery_manager) should be GA
- [ ] GitHub integration should be published

**Comment by melissaburpo** [comment]
Thanks for opening this issue @bmorelli25. I believe both Osquery integrations need to be updated, based on their manifest files + release version in 7.16:
* Osquery Manager ( [doc](https://docs.elastic.co/en/integrations/osquery_manager) | [manifest - `release: ga`](https://github.com/elastic/integrations/blob/master/packages/osquery_manager/manifest.yml) )
* Osquery Log Collection ( [doc](https://docs.elastic.co/en/integrations/osquery) | [manifest - `release: ga`](https://github.com/elastic/integrations/blob/master/packages/osquery/manifest.yml) )
