### ISSUE TITLE
Update Set up on Cloud content

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#144]
It looks like we can no longer include the generic [ess-getting-started](https://www.elastic.co/guide/en/observability/current/install-observability.html#set-up-on-cloud) file from the docs repo. There is now an additional step of selecting Elastic Observability, which is not included in the file.  

Should we write the steps involved or do we need to create a specific 'set up on Cloud' topic for Observability, that we then include from the Observability repo?

<img width="1349" alt="obs-set-cloud" src="https://user-images.githubusercontent.com/31283375/94155635-1380e880-fe77-11ea-865c-a60011b54000.png">

cc @bmorelli25 @dedemorton

**Comment by bmorelli25** [comment]
I had to create some new content for this in https://github.com/elastic/apm-server/pull/4222 (see https://github.com/elastic/apm-server/blob/1280e37e07e6239f533e0713dc3c1fbd44ff72e7/docs/tab-widgets/spin-up-stack.asciidoc). Hope you don't mind me hijacking this one 😅 

I've opened https://github.com/elastic/docs/pull/1969 with my thoughts. Tagged Nik as well as I'm curious to hear his thoughts. Worst case scenario, I end up removing the OBS content and only fixing the general ESS content.

**Comment by EamonnTP** [comment]
Thanks @bmorelli25 for picking this up.
