### ISSUE TITLE
Integration Doc Updates

### ISSUE THREAD

**Issue by jamiehynds** [elastic/observability-docs#1448]
The Security team have recently published new integrations, which we need corresponding docs for. 

- Akamai - https://github.com/elastic/integrations/tree/master/packages/akamai
- Atlassian Bitbucket - https://github.com/elastic/integrations/tree/master/packages/atlassian_bitbucket
- Atlassian Confluence - https://github.com/elastic/integrations/tree/master/packages/atlassian_confluence
- Atlassian Jira - https://github.com/elastic/integrations/tree/master/packages/atlassian_jira
- AWS Network Firewall - https://github.com/elastic/integrations/blob/master/packages/aws/docs/networkfirewall.md
- Modsecurity - https://github.com/elastic/integrations/tree/master/packages/modsecurity
- Microsoft SQL Server - https://github.com/elastic/integrations/tree/master/packages/microsoft_sqlserver
- QNAP NAS - https://github.com/elastic/integrations/tree/master/packages/qnap_nas
- Snyk - https://github.com/elastic/integrations/tree/master/packages/snyk
- Symantec Endpoint Protect - https://github.com/elastic/integrations/tree/master/packages/symantec_endpoint
- Tenable.sc - https://github.com/elastic/integrations/tree/master/packages/tenable_sc
- VMware vSphere - https://github.com/elastic/integrations/tree/master/packages/vsphere

On a related note, it looks like the list of integrations on the left-nav of the docs page does not display all the available integrations and is not in alphabetical order. Is it possible to get this address?

**Comment by bmorelli25** [comment]
Thanks for the list, Jamie! I do see three of these already published, but it looks the rest aren't. I'll try to get them added quickly.

Cisco (all of them): https://docs.elastic.co/en/integrations/cisco
Network Packet Capture: https://docs.elastic.co/en/integrations/network_traffic
Symantec Endpoint: https://docs.elastic.co/en/integrations/symantec

**Comment by jamiehynds** [comment]
Thanks @bmorelli25 - I've removed Cisco and Network Packet Capture. 

@andrewkroh can you confirm if the current Symantec docs are based on the RSA integration or your new integration? https://docs.elastic.co/en/integrations/symantec

**Comment by andrewkroh** [comment]
https://docs.elastic.co/en/integrations/symantec is for the deprecated RSA2ELK integration. The new integration name is `symantec_endpoint`. 

It's promoted to production and you can see what it looks like in Kibana here: https://github.com/elastic/package-storage/pull/3257

**Comment by bmorelli25** [comment]
PR opened. I'll follow-up when the changes are live.

**Comment by bmorelli25** [comment]
Docs are live! https://docs.elastic.co/en/integrations

**Comment by jamiehynds** [comment]
Looks great - thanks as always, @bmorelli25!
