### ISSUE TITLE
[Integrations] Update or remove the list of GA-level integrations in the Fleet/Agent guide

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1453]
## Description

This topic has not been updated since 7.14: https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html

We really need to remove the list of GA-level integrations from this topic because integrations are released and promoted to GA on their own schedule. The docs will get stale quickly. We should point to https://docs.elastic.co/en/integrations as the source of truth. However the topic that lists GA integrations was removed because the script for creating it was not working.

For now, I think we should:

1. Remove the list of integrations from [Choosing between Elastic Agent and Beats](https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html#choosing-between-agent-and-beats).
2. Tell users to go to https://docs.elastic.co/en/integrations to verify that the integrations they want to use are GA.

When the list of GA-level integrations is available in the docs, we can point to that instead of telling users to check individual integrations.

## Collaboration

- The docs team will lead producing the content

**Contact Person:**

@bmorelli25 

## Suggested Target Release

7.15+

## Stakeholders

n/a

**Comment by bmorelli25** [comment]
👍 Makes sense to me.
