### ISSUE TITLE
[Bug]: Incomplete installation command available under Agent Upgrade guide.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#1469]
**Description:**
Link: https://www.elastic.co/guide/en/fleet/8.0/upgrade-elastic-agent.html#upgrade-7.12-lower
(Under Self-Managed section)
Incomplete installation command available under Agent Upgrade:
- `--fleet-server-policy` flag is missing.

**Screenshot:**
![20](https://user-images.githubusercontent.com/77374876/150098108-8fd06a9b-d77a-4f6f-8966-6efca8492f83.JPG)

- Even the command in attached snapshot doesn't match with available command.

**Expected Result:**
Available command should be complete and shouldn't give ambiguous information.

**Current 8.0 command:**
```
sudo ./elastic-agent install  \
  --fleet-server-es=https://x.x.x.x:9200 \
  --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDI1MDYwMDY3MDY6d294c3hhQnRUMldmcnBwYzZzb3Nqdw \
  --fleet-server-policy=499b5aa7-d214-5b5d-838b-3cd76469844e \
  --fleet-server-es-ca-trusted-fingerprint=b15c3353614dc2525114409b7593050a934911bece4633f7a81ddcbdd2bcf4a6 \
  --fleet-server-insecure-http
```

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @dedemorton

**Comment by dedemorton** [comment]
Closing for a couple of reasons:

* This problem is minor because the UI shows the correct command.
* This command was removed in 8.2 and later (so already fixed).
