### ISSUE TITLE
[Request] Update Fleet screenshots

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1471]
## Description

8.0 introduced UI changes that affected many screens in the documentation (for example, moving Fleet Settings to a separate tab in the Fleet UI affects about every screen capture that shows Fleet.)

Updating those screens will require extra setup steps and possibly coordination with other writers, so I am breaking this work out from the original issue: https://github.com/elastic/observability-docs/issues/1314.

### List of stale screenshots in Fleet-related docs

First we should ask if these screenshots are essential, or if we should remove them to make it easier to maintain this content over time.

https://www.elastic.co/guide/en/fleet/8.2/fleet-overview.html
- [x] Add Nginx integration screen capture. No longer has Fleet Settings link.
- [x] Fleet screen capture. Now has a Settings tab. 

https://www.elastic.co/guide/en/observability/8.2/ingest-logs-metrics-uptime.html
- [x] Fleet screen captures. Now have a Settings tab. Fixed or n/a in 8.2
- [x] Add Elastic Synthetics integration screen. No longer has Fleet Settings link. Fixed or n/a in 8.2
- [x] Default policy screen. No longer has Fleet Settings link. Fixed or n/a in 8.2
- [x] Add Nginx integration screen. No longer has Fleet Settings link. Fixed or n/a in 8.2
- [x] Second Default policy screen. No longer has Fleet Settings link. Fixed or n/a in 8.2

https://www.elastic.co/guide/en/observability/8.0/ingest-traces.html 
- [x] Add agent screen. No longer has Fleet Settings. Fixed or n/a in 8.2
- [x] Fleet screen. No longer has Fleet Settings. Fixed or n/a in 8.2

https://www.elastic.co/guide/en/fleet/8.0/upgrade-integration.html
- [x] Upgrade Nginx integration screen. No longer has Fleet Settings link.
- [x] Upgrade AWS integration screen.  No longer has Fleet Settings link.
- [x] aws-1 integration policy screen. No longer has Fleet Settings link.

https://www.elastic.co/guide/en/fleet/8.0/install-fleet-managed-elastic-agent.html 
- [x] Add agent page. No longer has Fleet Settings link. Fixed or n/a in 8.2 

https://www.elastic.co/guide/en/fleet/8.0/fleet-server-scalability.html 
- [x] Elastic Cloud agent policy screen. No longer has Fleet Settings link. 

https://www.elastic.co/guide/en/fleet/8.0/fleet-server-monitoring.html
- [x] ~Fleet Server policy screen. No longer has Fleet Settings link.~ Will do as part of https://github.com/elastic/observability-docs/issues/1843#issuecomment-1122910583 when we'll have a self-managed Fleet Server set up.

https://www.elastic.co/guide/en/fleet/8.0/upgrade-elastic-agent.html 
- [x] Fleet screens (2). No longer have Fleet Settings link.
- [x] Add agent screen. No longer has Fleet Settings link. Fixed or n/a in 8.2

https://www.elastic.co/guide/en/fleet/8.0/view-elastic-agent-status.html 
- [x] Fleet screens (2). Now have a Settings tab.

https://www.elastic.co/guide/en/fleet/8.0/agent-policy.html 
- [x] Create agent policy screen. No longer has Fleet Settings link.
- [x] Fleet screens (2).  No longer have a Fleet Settings link.

https://www.elastic.co/guide/en/fleet/8.0/fleet-enrollment-tokens.html 
- [x] Fleet screens (2). No longer have Fleet Settings link.

https://www.elastic.co/guide/en/fleet/8.0/data-streams.html 
- [x] Fleet screen. No longer has Fleet Settings link. 

## Collaboration

- The docs team will lead producing the content

**Contact Person:**

n/a

## Suggested Target Release

8.2

## Stakeholders

n/a

**Comment by dedemorton** [comment]
We won't be updating the screens for 8.0 since 8.2 has already been released. IMO the changes are minor enough that I don't think they will be too confusing.

I do think we should update (or in some cases remove) these screens in 8.2.

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated the docs on above shared links and had below observations:

**Tested Docs:**
1. https://www.elastic.co/guide/en/fleet/8.2/fleet-overview.html
2. https://www.elastic.co/guide/en/observability/8.2/ingest-logs-metrics-uptime.html
3. https://www.elastic.co/guide/en/observability/8.2/ingest-traces.html
4. https://www.elastic.co/guide/en/fleet/8.2/upgrade-integration.html
5. https://www.elastic.co/guide/en/fleet/8.2install-fleet-managed-elastic-agent.html
6. https://www.elastic.co/guide/en/fleet/8.2/fleet-server-scalability.html
7. https://www.elastic.co/guide/en/fleet/8.2/upgrade-elastic-agent.html
8. https://www.elastic.co/guide/en/fleet/8.2/view-elastic-agent-status.html
9. https://www.elastic.co/guide/en/fleet/8.2/agent-policy.html
10. https://www.elastic.co/guide/en/fleet/8.2/fleet-enrollment-tokens.html
11. https://www.elastic.co/guide/en/fleet/8.2/data-streams.html

**Observations:**
- Latest Screenshots with Settings tab are available.
- Add integration page no longer has Fleet Settings link.

**Reported issues:**
For Self managed sections of guides:
https://www.elastic.co/guide/en/observability/8.2/ingest-logs-metrics-uptime.html
https://www.elastic.co/guide/en/observability/8.2/ingest-traces.html

We have logged two issues at links:
- https://github.com/elastic/observability-docs/issues/1875
- https://github.com/elastic/observability-docs/issues/1877

For updating a screenshot on guide: https://www.elastic.co/guide/en/fleet/8.2/view-elastic-agent-status.html
We have logged an issue at link:
- https://github.com/elastic/observability-docs/issues/1876

Hence marking this as **QA:Validated**.
Please let us know if anything else is required from our end.

cc: @dedemorton 
Thanks
