### ISSUE TITLE
New concise, consistent alert reason messages

### ISSUE THREAD

**Issue by vinaychandrasekhar** [elastic/observability-docs#1478]
## Description
improvements to and standardization of alert reason messages across Observability. The messages are now limited in length while conveying the same bits of important information. Documentation update needs might be minor. Please ensure any screenshots that show the older messages are replaced with newer screenshots. 

"Master" GH ticket is [here](https://github.com/elastic/kibana/issues/117697).  

## Collaboration
- The product team will provide the initial content and the docs team will edit / review

**Contact Person:**
@fkanout 

## Suggested Target Release
8.1

## Stakeholders
@vinaychandrasekhar 
@emma-raffenne 
@jasonrhodes

**Comment by colleenmcginnis** [comment]
@vinaychandrasekhar I couldn't find any references to specific alert messages in the [Alerting](https://www.elastic.co/guide/en/observability/current/create-alerts.html) docs except for the screenshot that is already being updated in https://github.com/elastic/observability-docs/pull/1723. 

Are there other references I'm missing that you'd expect to be updated?

**Comment by vinaychandrasekhar** [comment]
None that I can recollect @colleenmcginnis
