### ISSUE TITLE
Alert flyout pagination and navigation

### ISSUE THREAD

**Issue by vinaychandrasekhar** [elastic/observability-docs#1479]
## Description

When viewing alert details in the flyout, there will now be pagination controls that help navigate between the alerts shown in the table. As users navigate between alerts, the alerts table in the background should highlight the current alert being viewed via the pagination controls in the flyout. 

Related GH issue is [here](https://github.com/elastic/kibana/issues/96568). 

## Collaboration
- The product team will provide the initial content and the docs team will edit / review

**Contact Person:**
@mgiota 

## Suggested Target Release
8.1 (please note - stretch goal for 8.1)

## Stakeholders
@vinaychandrasekhar 
@emma-raffenne 
@jasonrhodes

**Comment by colleenmcginnis** [comment]
[Looks like](https://github.com/elastic/kibana/issues/96568#event-6155921151) this is moving to 8.3+.

**Comment by vinaychandrasekhar** [comment]
Yes, that moved out to a future release

**Comment by ollyhowell** [comment]
Assigning @mdbirnstiehl as Alerts but you might have to check status with Vinay and team

**Comment by emma-raffenne** [comment]
@bmorelli25 
That was implemented some time ago (can't find the issue or PR right now) but you can see it on 8.7
