### ISSUE TITLE
Supplement Fleet docs with bulk action information

### ISSUE THREAD

**Issue by jen-huang** [elastic/observability-docs#149]
https://github.com/elastic/kibana/pull/77690 introduced bulk actions UI in Fleet for taking actions on multiple agents at a time: reassign, unenroll, and (soon to come) upgrade agents.

I don't see docs where we document Fleet UI in granular detail, but just to give a few ideas, we could call out that bulk actions (the ability to easily manage a large amount of agents) is available in:
1. [Fleet overview](https://www.elastic.co/guide/en/ingest-management/7.x/ingest-management-overview.html#central-management)
2. [Unenroll agents](https://www.elastic.co/guide/en/ingest-management/7.x/unenroll-elastic-agent.html)

Note: Bulk actions is only available with Gold+ license

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/1485
