### ISSUE TITLE
[Request] AWS Lambda support in the APM UI

### ISSUE THREAD

**Issue by gbamparop** [elastic/observability-docs#1490]
## Description
Some APM agents now support AWS lambda instrumentations. In this context some of the data is not available while some additional, serverless-specific information is available that is very valuable for APM use cases. 

Additions for [service overview ](https://www.elastic.co/guide/en/kibana/current/service-overview.html) (charts, metadata icons and details) and [transactions](https://www.elastic.co/guide/en/kibana/current/transactions.html). 

Issue: https://github.com/elastic/kibana/pull/122775

## Collaboration
- The docs team will lead producing the content

**Contact Person:**
@gbamparop 

## Suggested Target Release
8.1.0

## Stakeholders
APM UI team
@AlexanderWert

**Comment by bmorelli25** [comment]
@gbamparop or @AlexanderWert do you know of any dev environments with lambda data? Or would it be easier to wait for https://github.com/elastic/kibana/issues/134888?

**Comment by AlexanderWert** [comment]
@bmorelli25 

I have a private environment with some lambda data.

Also, we have[ this blog post](https://www.elastic.co/blog/observability-apm-aws-lambda-serverless-functions) (that potentially might be helpful).
