### ISSUE TITLE
[Request] Improve the Elastic Agent quick start guides

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1497]
## Description

The "quick start" guides for Elastic Agent contain a lot of caveats that make it hard to run through the steps quickly (especially for cloud users). Also the workflow that's described is outdated. Instead of recommending that users start in Fleet, we should drive them towards the onboarding experience that begins in the Integrations app.

To streamline the content, we should:

- Remove any steps related to self-managed deployments and link to related docs instead. This will benefit cloud users who don't have to set up Fleet Server or worry about Stack-related configuration requirements.
- Make sure that any caveats are true and needed for users to get started. Some of the "extra" stuff was added before we improved the UI and may no longer be needed.
- Remove duplicated content, like the installation command, especially if it shows info that's already shown in the UI.
- Change the order of sections to match the recommended onboarding experience.

We may need to update some links from the product or web pages that rely on content in the quick start.

Affected guides:

https://www.elastic.co/guide/en/observability/current/ingest-logs-metrics-uptime.html
https://www.elastic.co/guide/en/observability/current/ingest-traces.html

## Collaboration

- The docs team will lead producing the content

**Contact Person:**

## Suggested Target Release

8.1 (or earlier if possible)

**Comment by dedemorton** [comment]
@DanRoscigno I think you've done some ingest-related writing for cloud. Let me know if you have any other suggestions for improving the quick starts (specifically the ones that use Elastic Agent). I think they've gotten very bloated and wordy. :-/

**Comment by dedemorton** [comment]
Moving the state here to in-progress because it makes sense to make these changes while I'm making related updates in https://github.com/elastic/observability-docs/issues/1792.

**Comment by DanRoscigno** [comment]
@dedemorton this one is updated for the new Agent workflow in Kibana:
https://github.com/elastic/tech-content/pull/124

I really like the new workflow, it is so much nicer to stay in Kibana while doing this.

**Comment by dedemorton** [comment]
@DanRoscigno Yup, saw that! I hope we can converge on one source of truth at some point so we aren't updating similar content in multiple places, but we aren't ready for that yet unfortunately.

**Comment by dedemorton** [comment]
Most of this is done in https://github.com/elastic/observability-docs/pull/1824

What's not done, I'm gonna defer because the new onboarding docs provide a good quick path for cloud users, so maybe it's OK to keep the self-managed info here (at least until we have a clearer strategy on how we want to cover self-managed).
