### ISSUE TITLE
[Request] Document beta support for OpenTelemetry Logs

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/observability-docs#1500]
## Description

We are doing in 8.0 the quiet launch of the `beta` support of OpenTelemetry Logs.
For the record, we already support OpenTelemetry Traces and Metrics.

We thought of adding a section "Logs Support (beta)" in https://www.elastic.co/guide/en/apm/guide/current/open-telemetry.html

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content
- The product team will provide the initial content and the docs team will edit / review
- The docs team will define with product team the structure and location, and the product team will provide the initial content
- Other (please describe)

TBD

**Contact Person:** @cyrille-leclerc 

## Suggested Target Release

Target is 8.0.

Otel Logs beta support is a quiet launch so we have more flexibility to publish the updated documentation.

## Stakeholders

* @cyrille-leclerc 
* @simitt 
* @axw

**Comment by simitt** [comment]
@cyrille-leclerc is working on a blog post for this for the `8.1` launch. @bmorelli25 the idea is to have the docs ready until then and also backport them to the `8.0` docs. Does that sound feasible?

**Comment by bmorelli25** [comment]
@cyrille-leclerc ping me when the blog post is ready and I'll turn it into documentation.

**Comment by cyrille-leclerc** [comment]
Hello @bmorelli25 , no ETA yet.

**Comment by simitt** [comment]
@cyrille-leclerc should this be planned for the `8.2` release time frame or be moved to `8.3` docs?

**Comment by simitt** [comment]
@cyrille-leclerc do you have any update on this?

**Comment by cyrille-leclerc** [comment]
As the [OpenTelemetry Logs data model](https://opentelemetry.io/docs/reference/specification/logs/data-model/) and the [OpenTelemetry Logs protocol](https://opentelemetry.io/docs/reference/specification/protocol/otlp/) are marked as "stable", I proposed to mark our support of OTLP logs as GA.
Does it make sense @simitt , @alex-fedotyev , @axw ?

**Comment by axw** [comment]
That's fine by me.

**Comment by alex-fedotyev** [comment]
SGTM.
Is this mainly change in docs? Is there anything in the product?

**Comment by bmorelli25** [comment]
Thanks. I'll remove the beta label from the docs.
