### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Wow123419** [elastic/observability-docs#1534]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content
- The product team will provide the initial content and the docs team will edit / review
- The docs team will define with product team the structure and location, and the product team will provide the initial content
- Other (please describe)

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:**

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by dedemorton** [comment]
Closed because this appears to have been created by mistake.
