### ISSUE TITLE
Add Memory/CPU usage & Min hardware spec requirements for Agent Documentation

### ISSUE THREAD

**Issue by jlind23** [elastic/observability-docs#1543]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*
We need to have a doc section explaining what are the minimum configurations needed when running an Elastic Agent.

## Collaboration
- The product team will provide the initial content and the docs team will edit / review

**Contact Person:**

@michel-laterman @nimarezainia 

## Suggested Target Release
8.1

*(Let us know if this feature is needed for a specific release.)*

## Stakeholders

@jlind23 @nimarezainia @ph

**Comment by jlind23** [comment]
@michel-laterman may i assign you this one?

**Comment by michel-laterman** [comment]
How is this ticket different from https://github.com/elastic/observability-docs/issues/726?

**Comment by jlind23** [comment]
@michel-laterman it is not, closing.
