### ISSUE TITLE
[Request] Document how to customize index templates from packages

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#1578]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*
We want to give users better guidance on how to customize assets provided by integration packages. That includes how to apply custom index template settings, mappings, ILM policies and ingest pipelines. We'll document how to customize these at a dataset level of granularity. We can leave namespace-specific customization to a later phase. As a stretch goal, we could offer a temporary workaround that is compatibility with our future vision https://github.com/elastic/kibana/issues/121118.

Note: we previously reverted docs on this topic here https://github.com/elastic/kibana/issues/119013. With https://github.com/elastic/kibana/issues/121184 we will support mappings customization, which means we can proceed up publish these docs, with updates if needed.

Example user questions:
- https://discuss.elastic.co/t/elastic-cloud-fills-up-to-infinity/290999/2
- https://discuss.elastic.co/t/custom-logs-ingest-pipeline/294409
- https://discuss.elastic.co/t/fleet-apply-pipelines/291288

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The product team will provide the initial content and the docs team will edit / review

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:** @hop-dev 

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*
8.2

## Stakeholders

*(Please list any stakeholders for this issue.)*
@joshdover @mostlyjason

**Comment by hop-dev** [comment]
Closing as https://github.com/elastic/observability-docs/pull/1724 now merged
