### ISSUE TITLE
[Request] Create Troubleshooting section for Synthetics

### ISSUE THREAD

**Issue by ollyhowell** [elastic/observability-docs#1615]
## Description

From very useful tech support guidelines for Uptime, is there content that could be used to build a useful Troubleshooting section in docs?

https://github.com/elastic/support-tech-lead/issues/1100#issuecomment-1028873108

## Collaboration

- The docs team will lead producing the content

**Contact Person: @lucasfcosta** (based on initial SDH help)

**Comment by colleenmcginnis** [comment]
Closing in favor of https://github.com/elastic/observability-docs/issues/2695.
