### ISSUE TITLE
[Request] Update docs with new integrations 

### ISSUE THREAD

**Issue by jamiehynds** [elastic/observability-docs#1628]
## Description

We've recently shipped some new integrations and our docs site needs to be updated accordingly. 

- [x] AbuseCH: https://github.com/elastic/integrations/tree/main/packages/ti_abusech/docs *
- [x] Alienvault OTX: https://github.com/elastic/integrations/tree/main/packages/ti_otx/docs *
- [x] Anomali: https://github.com/elastic/integrations/tree/main/packages/ti_anomali/docs *
- [x] Auth0: https://github.com/elastic/integrations/tree/main/packages/auth0/docs
- [x] MISP: https://github.com/elastic/integrations/tree/main/packages/ti_abusech/docs *
- [x] Cybersixgill: https://github.com/elastic/integrations/tree/main/packages/ti_cybersixgill/docs *
- [x] Netskope: https://github.com/elastic/integrations/tree/main/packages/netskope
- [ ] RecordedFuture: @adriansr can you provide a link once the package is merged?
- [x] ThreatQuotient: https://github.com/elastic/integrations/tree/main/packages/ti_threatq/docs *
- [x] Zscaler Internet Access: https://github.com/elastic/integrations/tree/main/packages/zscaler_zia/docs
- [x] Zscaler Private Access: https://github.com/elastic/integrations/tree/main/packages/zscaler_zpa/docs
- [x] Zscaler NSS: These docs can be removed as this module is deprecated in favour of the new Zscaler integrations

---

- [x] *These are threat intelligence integrations. Could see include them under a Threat Intelligence category on our docs page? 

FYI @bmorelli25

**Comment by bmorelli25** [comment]
Thanks, Jamie. These should all be addressed in https://github.com/elastic/wordlake/pull/18 which I hope to merge later today. There are two exceptions:

* RecordedFuture — as noted above
* Auth0 – doesn't have curly brackets and braces escaped in the readme which prevents it from building in the docs system

**Comment by jamiehynds** [comment]
Thanks @bmorelli25!

- Auth0 - @r00tu53r would you mind taking a look at the escaping issue so we can proceed with docs?
- Zscaler - no worries if it isn't possible to add a filter. We can add a deprecation notice within the doc itself (I think)

**Comment by bmorelli25** [comment]
@r00tu53r PR for Auth0 is up here: https://github.com/elastic/integrations/pull/2761. It'd be great if you can take care of the release process.

**Comment by bmorelli25** [comment]
Deprecated filter added in https://github.com/elastic/wordlake/pull/18/commits/d938c22b8aef9e207f181e12a565998d94f7ffd0. I'll update the description with checkboxes.

**Comment by bmorelli25** [comment]
> *These are threat intelligence integrations. Could see include them under a Threat Intelligence category on our docs page?

They've been set up like this for a while. Is there something different you'd like to see?

<img width="247" alt="Screen Shot 2022-03-02 at 1 11 05 PM" src="https://user-images.githubusercontent.com/5618806/156450277-d507b4d8-e46b-4836-83a1-10084994911d.png">

**Comment by jamiehynds** [comment]
Sorry @bmorelli25, totally missed the TI integrations on the docs page. We'll have a new integration (Recorded Future) coming there soon. Will let you know when it's available. 

Thanks for sorting out the Zscaler filter - looks great. 

If you need any help with Auth0, just let me know.

**Comment by jamiehynds** [comment]
@bmorelli25 could you apply the same filter to the Symantec docs that you did for Zscaler? There's currently a deprecated integration in there that would be great to remove from the docs: https://docs.elastic.co/en/integrations/symantec

**Comment by bmorelli25** [comment]
> @bmorelli25 could you apply the same filter to the Cyberark and Symantec docs that you did for Zscaler? There's currently a deprecated integration in both, that would be great to remove from the docs:

Removed in https://github.com/elastic/wordlake/pull/19.
