### ISSUE TITLE
When deploying Agent and not on current the download / install page does not provide enough info

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/observability-docs#1630]
I am running Elastic Stack 8.0.0, and 8.0.1 is "current".  I worked through the steps to create an Elastic Agent Policy and then tried to deploy Agent on a Linux server.  In Kibana I was directed to the download page and all I saw on the page are the links to download Agent for various operating systems.  There is no information about what to do with the binary, and the instructions in Kibana skip to the step after the binary is installed.

Here is the page I was sent to:
https://www.elastic.co/downloads/past-releases/elastic-agent-8-0-0

Here is the page that includes the instructions (I needed the link to the Fleet quick start):
https://www.elastic.co/downloads/elastic-agent

**Comment by DanRoscigno** [comment]
@dede, I think this is more broken now than it was.  I just created a fresh deployment and the standard add an integration workflow takes me to a page without the link to the Fleet guide.

**Comment by dedemorton** [comment]
@DanRoscigno Agreed. It's especially odd and counter-intuitive in 8.1.0 that we send users to a URL containing "past-releases". :-/ I am not sure when/how this decision was made, or why the download pages for past releases don't include installation information.

@jlind23 @jen-huang This problem encompasses more than docs (includes UI and download pags). Who can I follow up with about this?

**Comment by jen-huang** [comment]
This was changed as part of https://github.com/elastic/kibana/issues/102491. It would be nice if the [full download page] accepted a parameter (or similar), that way we can link to the right version with instructions. This sounds like request to the Web Team: https://github.com/elastic/website-requests

**Comment by jen-huang** [comment]
FYI we are also doing a redesign of the Add Agent fly out, it will remove the link to the download page in favor of a single cURL command: https://github.com/elastic/kibana/issues/125534

**Comment by DanRoscigno** [comment]
Thanks @jen-huang , I will add a comment in the design issue also, but we need more than just a curl I would say. Also an extract.  It will be so wonderful to keep the reader in Kibana during the download, extract, install, enroll!!

**Comment by dedemorton** [comment]
Closing because the download pages now include instructions, and version 8.2 and later includes the full cURL needed to download, extract, and install Elastic Agent.
