### ISSUE TITLE
[Request] Update Journalbeat and Filebeat 

### ISSUE THREAD

**Issue by jlind23** [elastic/observability-docs#1636]
## Description

Journalbeat and Filebeat documentation should be updated to highlight the following:
Filebeat shouldn't be used to ship its own log file, or Journalbeat shipping its own log file. It is generally not a good idea to have log shippers ship their own log files.

## Collaboration
- The docs team will lead producing the content

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

@jlind23 @nimarezainia 

## Related known issues
https://github.com/elastic/beats/pull/30482 
https://github.com/elastic/beats/issues/11179

## Suggested Target Release
Should be done in 8.3 and backported all along to 7.17.

## Stakeholders

@jlind23 @nimarezainia

**Comment by jlind23** [comment]
@elastic/obs-docs Can we get your eyes on this please?

**Comment by jlind23** [comment]
@ollyhowell any chance you take a look at it?

**Comment by ollyhowell** [comment]
Hey @jlind23, sorry for delay looking at this - back online and this potentially seems like a quick fix. Was there any reason with this one that the engineer didn't suggest a change to the docs directly? Is it clear where such a statement would go and then we can do a quick review before publish?

**Comment by jlind23** [comment]
Hey @ollyhowell sounds good, let me take a stab at it then and i'll link the PR to this issue.
