### ISSUE TITLE
[Fleet] Rename `agent config` references to `agent policy`, and `datasets` to `data streams`

### ISSUE THREAD

**Issue by jen-huang** [elastic/observability-docs#164]
Following the work done in https://github.com/elastic/kibana/issues/74842, we should update the Ingest Manager/Fleet docs to refer to agent policies rather than agent configurations.

We should also update datasets to data streams, but I see that [data streams is already being used](https://www.elastic.co/guide/en/ingest-management/master/ingest-management-overview.html#data-streams), so this might not be necessary.

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/165
