### ISSUE TITLE
[Request] Update K8s integration documentation

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/observability-docs#1651]
## Description

Existing [K8s integration documentation page](https://docs.elastic.co/en/integrations/kubernetes) and specifically the compatibility section needs an update. There were some changes that were introduced to the package documentation recently which are missing in the docs.elastic.co.

## Collaboration

- The product team has already merged the initial content and the docs team will help merge it into the public integration docs.

**Contact Person:** @akshay-saraswat

## Suggested Target Release

N/A

## Stakeholders

Elastic customers, K8s integration Squad, PMM, and Sales Team.

**Comment by bmorelli25** [comment]
Pending EPR update. See Slack thread for details.

**Comment by bmorelli25** [comment]
This is done.
