### ISSUE TITLE
[Request] Add docs for uptime/apm/ux inspector panel

### ISSUE THREAD

**Issue by shahzad31** [elastic/observability-docs#1663]
## Description

We have an inspect panel in uptime/apm/ux apps, this can be used to trouble shoot queries being run on page and is really helpful in troubleshooting problems.

We should document it's use case. So that customer can also find it and use it.

To enable the panel, you have to turn inspect queries flag under observability in kibana advanced settings

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/3505601/157627605-be7b1b98-70a8-4b5f-961c-d33b953985d3.png">

<img width="1567" alt="image" src="https://user-images.githubusercontent.com/3505601/157627649-88085b3c-c7e1-43b2-a7be-26c2dfb7c828.png">

## Collaboration
- The docs team will lead producing the content

**Contact Person:**

@shahzad31 @sqren 

## Suggested Target Release

8.2

**Comment by bmorelli25** [comment]
I can see this living under a new top-level heading. It would be a great addition to a troubleshooting topic—if this book had one already.

**Comment by ollyhowell** [comment]
Some interesting parallels with the Explore Data feature (also on the top right toolbar and applies to various but not all apps) which is also a little odd at the top level - we could perhaps combine them into some kind of 'exploring/inspecting data' type bucket.

I think we need to consider this item within a mini-iteration of the current Observability Guide top-level headings...adding an item to team meeting agenda this week but also open to any offers to pick the general 'outline refresh' task up.
