### ISSUE TITLE
[Bug]: Note to create policy is completely removed.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#1664]
**Description:**
As per https://github.com/elastic/observability-docs/issues/1489 it is expected that Note under: https://www.elastic.co/guide/en/fleet/8.0/fleet-agent-proxy-support.html#cli-proxy-settings should be updated to - Create agent policies. However it is completely removed for 8.1 docs.

**Link:**
- https://www.elastic.co/guide/en/fleet/8.1/fleet-agent-proxy-support.html#cli-proxy-settings

**Screenshots:**
**8.0:**
![10](https://user-images.githubusercontent.com/77374876/157642354-3541e619-6a2e-40fd-aa1c-1c76b209aedc.JPG)

**8.1:**
![11](https://user-images.githubusercontent.com/77374876/157642371-371d9c2e-9f5c-4b64-ae86-fcab6a89f7f9.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jen-huang** [comment]
This is not an issue; that message is expected to be removed as it is no longer accurate (we no longer create default policies when user visits Fleet).
