### ISSUE TITLE
[Request][Fleet] Adjust documentation to include info about bundled packages

### ISSUE THREAD

**Issue by jen-huang** [elastic/observability-docs#1703]
## Description

Related to effort in https://github.com/elastic/kibana/issues/112095

We need docs for:
- Improving info about preconfiguration, make it a top-level docs section (if it isn't already)
- Add information about bundled packages within preconfiguration section
- Add to existing documentation on air-gapped environments about how bundled packages relate to that exprience

## Collaboration

- The docs team will define with product team the structure and location, and the product team will provide the initial content

**Contact Person:** @kpollich 

## Suggested Target Release

8.2

## Stakeholders

@joshdover

**Comment by joshdover** [comment]
I think we were going to cover this as part of https://github.com/elastic/observability-docs/issues/1603, @kpollich was that your thinking too?

**Comment by kpollich** [comment]
@joshdover Generally, yes. @jen-huang mentioned documenting preconfiguration in detail with this issue though, which the other issue doesn't cover. We could probably combine these.
