### ISSUE TITLE
[Request] Revamp documentation for APM on AWS Lambda

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/observability-docs#1707]
## Description
Our current documentation on the experimental / beta support for AWS Lambda in APM is a bit confusing and lacks clear quick start guides.

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The product team will provide the initial content and the docs team will edit / review

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:**
@AlexanderWert 

## Suggested Target Release

8.2
*(Let us know if this feature is needed for a specific release.)*

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by bmorelli25** [comment]
An outline of the plan is in Alex's PR: https://github.com/elastic/apm-aws-lambda/pull/158#issuecomment-1078409137

**Potential cross-doc link issues:**

* [Node.js](https://www.elastic.co/guide/en/apm/agent/nodejs/current/lambda.html) — No current asciidoctor links. Links to aws-lambda repo need to be updated to point to asciidoc content.
* [Java](https://www.elastic.co/guide/en/apm/agent/java/current/aws-lambda.html) — one link to the APM guide that needs to be updated
* [Python](https://www.elastic.co/guide/en/apm/agent/python/current/lambda-support.html) — no links
