### ISSUE TITLE
[Request] Add info on Elastic Synthetics "Inline Script" option to quickstart

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/observability-docs#1727]
Follow up from #1720
May be impacted by #1725 

## Description

>>This doc outlines the fields for the Zip URL Source Type, but doesn't touch on the Inline Script option. Should it?
>
>Similarly, it probably is worth adding something for Inline script too, especially as this is actually the easiest way to get something up and running. Could this also be done as part of a follow up issue/PR?

## Collaboration

The docs team will lead producing the content

**Contact Person:** @paulb-elastic 

## Suggested Target Release

@paulb-elastic in which release was this introduced?

**Comment by paulb-elastic** [comment]
The _Inline script_ option has been there since real browser types were added to the integration, which was 7.15 (https://github.com/elastic/kibana/pull/102928)
