### ISSUE TITLE
[Request] Adjust any kubernetes template links to new `elastic-agent` repo

### ISSUE THREAD

**Issue by narph** [elastic/observability-docs#1743]
## Description

We've recently added new repo `elastic-agent` and we moved 
https://github.com/elastic/beats/tree/main/deploy/kubernetes/elastic-agent-managed
https://github.com/elastic/beats/tree/main/deploy/kubernetes/elastic-agent-standalone

to the new repo:
https://github.com/elastic/elastic-agent/tree/main/deploy/kubernetes

There might be some docs that are linking to these templates in the beats repo, if so that should be redirected to the new elastic agent repo.
https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html
https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-standalone.html

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content
- The product team will provide the initial content and the docs team will edit / review
- The docs team will define with product team the structure and location, and the product team will provide the initial content
- Other (please describe)

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:**

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*

## Stakeholders

*(Please list any stakeholders for this issue.)*

cc @dedemorton as you have handled the transition to the new repo before

**Comment by dedemorton** [comment]
I'll take care of this. I thought we updated all the references, but must have missed these. :-(
