### ISSUE TITLE
Google search for "Elastic OpenTelemetry" returns the outdated 7.15 doc that doesn't help to find the new docs

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/observability-docs#1768]
## Description

Google search for "Elastic OpenTelemetry" returns the outdated 7.15 doc that doesn't help to find the new Elastic OpenTelemetry Docs

![image](https://user-images.githubusercontent.com/459691/161950638-12eb4956-eec3-48c0-81b8-af0755a37e35.png)

![image](https://user-images.githubusercontent.com/459691/161950103-78dccdad-8246-4066-8db7-ab40782e935f.png)

![image](https://user-images.githubusercontent.com/459691/161950944-16a5d210-25cf-48a4-93c4-e4834d23df02.png)

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content
- The product team will provide the initial content and the docs team will edit / review
- The docs team will define with product team the structure and location, and the product team will provide the initial content
- Other (please describe)

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:** @cyrille-leclerc 

## Suggested Target Release

ASAP

## Stakeholders

 * @alex-fedotyev 
 * @danielkhan 
 * @cyrille-leclerc

**Comment by bmorelli25** [comment]
This has been fixed. Thanks!

**Comment by cyrille-leclerc** [comment]
Many thanks, redirection works on my incognito browser!

**Comment by cyrille-leclerc** [comment]
I'm sorry, there is a step back, the Google result for "Elastic OpenTelemetry" is now an old OpenTracing page

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/459691/165267231-db64a46d-91d9-444f-a3f9-83470b968ced.png">

**Comment by cyrille-leclerc** [comment]
please ignore my re opening, it was a wrong test. Everything is good
