### ISSUE TITLE
Provide more direct links from APM documentation to differentiating features in Kibana APM documentation. 

### ISSUE THREAD

**Issue by bradquarry** [elastic/observability-docs#1804]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*

I am a pre-sales solution architect and always looking through the docs around how to differentiate our solutions in the marketplace. I often point customers to our documentation to learn about differentiated features. I think there is an opportunity to provide more links for the differentiating features listed here 

guide/en/kibana/current/apm-how-to.html

Within this page here

https://www.elastic.co/guide/en/apm/guide/8.1/apm-components.html

As well as perhaps a sub-section of the right hand index table that links to the capabilities in guide/en/kibana/current/apm-how-to.html and maybe even service maps.

After reading the APM docs today end to end it just seemed not calling out the linkages between these capabilities more explicitly within the APM documentation was a bit of a missed opportunity as I might not know enough as a new user to look within the Kibana documentation. There are a few high level links, but calling out the specific features as an eye-catcher seems very useful such as...

[Configure APM agents with central config]
[Create an alert]
[Create custom links]
[Find transaction latency and failure correlations]
[Integrate with machine learning] - I see this is called out on a few pages within the APM docs, but only if you notice it a**t the bottom** of /en/apm/guide/8.1/apm-components.html and /en/apm/guide/8.1/apm-quick-start.html
[Query your data]
[Track deployments with annotations]
[Service map]

Please feel free to reach out to me on this I'm happy to collaborate in any way.

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

Brad Quarry 

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by colleenmcginnis** [comment]
I _think_ this was addressed by https://github.com/elastic/observability-docs/pull/3723 and https://github.com/elastic/observability-docs/pull/4230. Feel free to reopen if needed!
