### ISSUE TITLE
[Request] Add tags to the elastic agent/fleet documentation 

### ISSUE THREAD

**Issue by narph** [elastic/observability-docs#1819]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*

We are introducing tagging for the elastic agent: related issue on the elastic agent/fleet server side are:

https://github.com/elastic/elastic-agent/issues/149
https://github.com/elastic/fleet-server/pull/1350
https://github.com/elastic/elastic-agent/pull/336

Changes:

Add tag flag https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html
Adding tag env variable https://www.elastic.co/guide/en/fleet/master/elastic-agent-container.html

## Collaboration

@kpollich can suggest any doc changes on the Fleet UI side

**Comment by kpollich** [comment]
For the Fleet UI side, we may want to regenerate any screenshots of the agent listing table to include the new tags column. 

The changes to Fleet UI in 8.3 around tags are geared towards a minimally viable implementation, so in this release we're only including two basic UI features:

- Displaying tags in the "agents" table
- Allowing users to filter by tags using the agent table's filter dropdowns

Example Screenshot:

![image](https://user-images.githubusercontent.com/6766512/168611943-f9c5e5db-a003-48f1-b874-1569c8e0a164.png)

In 8.4, we'll be looking to expand this functionality in a phase 2 implementation. The exact scope is still TBD, but functionality around adding new tags and editing existing ones in Fleet UI are likely coming - as well as some visual enhancements around how we actually display tags.
