### ISSUE TITLE
[Fleet]: Old screenshot with no Settings tab on Fleet for self-managed section.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#1875]
**Description:**
Screenshot needs to be updated with Settings tab on Fleet for self-managed section.
- Screenshots with Fleet Settings should be updated.

**Link:**
https://www.elastic.co/guide/en/observability/8.2/ingest-logs-metrics-uptime.html#set-up-fleet
https://www.elastic.co/guide/en/observability/8.2/ingest-traces.html#set-up-fleet-traces
(Self-Managed sections)

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/168528112-2321be28-38c7-4b05-a2b2-50de69f807ec.JPG)
![4](https://user-images.githubusercontent.com/77374876/168543060-07eeae41-cd20-4734-88b3-c56bf726839a.JPG)
![3](https://user-images.githubusercontent.com/77374876/168543069-3c361cf6-abc6-4afd-883f-79cd7abf5474.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @dedemorton

**Comment by amolnater-qasource** [comment]
Hi @dedemorton
We have revalidated the reported docs at links:
(Self-Managed)
- https://www.elastic.co/guide/en/observability/8.2/ingest-logs-metrics-uptime.html#set-up-fleet
- https://www.elastic.co/guide/en/observability/8.2/ingest-traces.html#set-up-fleet-traces

We have observed that the issue is **fixed** now.
- Old Screenshots are removed for self-managed section of Fleet Server setup.

**Screenshots**
![5](https://user-images.githubusercontent.com/77374876/172123687-f05e7dc7-2bb1-4013-8c32-b7973b81b35c.JPG)
![6](https://user-images.githubusercontent.com/77374876/172123697-d8d853bc-165f-4cb1-a0c8-c27ccd30a554.JPG)


Hence marking this as **QA:Validated**.
Thanks
