### ISSUE TITLE
[Fleet]: Agents tab screenshot not updated for View Agent status page.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#1876]
**Description:**
Agents tab screenshot needs to be updated for View Agent Status page

**Link:**
https://www.elastic.co/guide/en/fleet/8.2/view-elastic-agent-status.html

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/168562298-deccd49a-8559-4f51-bb37-956ec278b434.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @dedemorton

**Comment by dedemorton** [comment]
Thanks! Good catch.

**Comment by amolnater-qasource** [comment]
Hi @dedemorton 
We have revalidated this doc https://www.elastic.co/guide/en/fleet/8.2/view-elastic-agent-status.html and observed that the screenshot is updated now.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/172121745-592af996-0a94-4fb3-874c-73fe7518d3f1.JPG)

Hence marking this as **QA:Validated**.

Thanks
