### ISSUE TITLE
[Fleet]: Navigation from `Elasticsearch service`/`Self-Managed` is not uniform throughout the page.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#1877]
**Description:**
Navigation from `Elasticsearch service`/`Self-Managed` is not uniform throughout the page.
- If one step is set to self-managed other steps are still stuck at Elasticsearch service and vice versa.

**Link:**
https://www.elastic.co/guide/en/observability/8.2/ingest-logs-metrics-uptime.html#set-up-fleet
https://www.elastic.co/guide/en/observability/8.2/ingest-traces.html#set-up-fleet-traces

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/168568171-87b2084e-7d3a-4374-b13d-fdcdbeb40009.mp4

**Working fine for metricbeat page:**
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-installation-configuration.html
- Navigation from `Elasticsearch service`/`Self-Managed` is uniform throughout the page.

https://user-images.githubusercontent.com/77374876/168568366-1a6cac44-f5fc-44ae-a42d-112cfa72da83.mp4

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @dedemorton

**Comment by amolnater-qasource** [comment]
Hi @dedemorton 
We have revalidated the reported docs at links:

- https://www.elastic.co/guide/en/observability/8.2/ingest-logs-metrics-uptime.html#set-up-fleet
- https://www.elastic.co/guide/en/observability/8.2/ingest-traces.html#set-up-fleet-traces

We have observed that the issue is **fixed** now.
- Navigation from Elasticsearch service/Self-Managed is uniform throughout the page.

**Screen Recordings:**

https://user-images.githubusercontent.com/77374876/172122774-0475a511-0352-4bb3-8024-ec3109d00de6.mp4


https://user-images.githubusercontent.com/77374876/172122859-ea6af763-012e-4bd7-a6a5-2593aad2a4f6.mp4

Hence marking this as **QA:Validated**.
Thanks
