### ISSUE TITLE
Bring Elastic serverless forwarder documentation to Elastic standard for 8.3 GA

### ISSUE THREAD

**Issue by ravikesarwani** [elastic/observability-docs#1884]
This is a request for the doc team to update the Elastic serverless forwarder [documentation](https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md) and make it up to the Elastic doc standard as we are making this functionality GA for 8.3.

**Comment by ravikesarwani** [comment]
cc: @aspacca

**Comment by bmorelli25** [comment]
@ollyhowell we have two issues open for this task and there's slightly more context in the other issue. I'm going to close this one in favor of https://github.com/elastic/observability-docs/issues/1918.
