### ISSUE TITLE
[Synthetics] Document new `push` feature

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#1906]
## Description

A new `push` feature is being [implemented](https://github.com/elastic/synthetics/issues/494) which supersedes the ZIP URL (aka suites, which currently works via the Synthetics Integration, or from the `heartbeat.yml`).

The new `push` solution is for `push`ing monitor configurations (likely from a repository of some kind) to the user’s stack, for running on the Synthetics Service, and/or on the self-managed nodes (when that’s implemented via [uptime#441](https://github.com/elastic/uptime/issues/441)).  They will be referred to as **projects** (not suites).

There are some notes on how to us `push`, here: https://github.com/elastic/synthetics/releases/tag/v1.0.0-beta.26

The documentation should include:
* How to use the new `push` CLI features of the Synthetics Agent
  * Including how API Keys are used (using the existing, temporary UI in Monitor Management)
* Configuration options for the new `monitor` object
  * Some are mandatory, either against the individual monitor configuration (in the script), or globally in the `synthetics.config.ts` file
* ~~How you need to re `push` if you want to disable a monitor (they are read-ony in the UI)~~ no longer the case with https://github.com/elastic/kibana/issues/134575
* How to use the new `init`CLI features of the Synthetics Agent
* Document that there is no history if `push`ing existing ZIP URL folders (for `heartbeat.yml`, or the existing Synthetics Integration)

**Note that there is a _Learn more_ link in Monitor Management that will refer to this documentation.  This link needs updating to the correct location in time for the 8.3 release, so once the URL is know for this page, please update https://github.com/elastic/uptime/issues/472 accordingly** (UPDATE 17/Jun - URL is https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html)

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will define with product team the structure and location, and the product team will provide the initial content (please contact @lucasfcosta or others in the @elastic/uptime team)

## Suggested Target Release

8.3 (see above regarding needing to know the documentation URL link in time for the 8.3 release)

## Stakeholders

* @andrewvc 
* @drewpost 
* @lucasfcosta 
* @paulb-elastic 
* @vigneshshanmugam

**Comment by lucasfcosta** [comment]
I've added @vigneshshanmugam to the issue so that he can track this one given he would like to update the agent to include links to the docs once released.

**Comment by paulb-elastic** [comment]
Changed the main description and referenced https://github.com/elastic/kibana/issues/134575 where we **are** going to make it possible to enable/disable project monitors that have been pushed (/cc @colleenmcginnis)

**Comment by paulb-elastic** [comment]
@colleenmcginnis we are also removing the `--delete` option in https://github.com/elastic/synthetics/issues/533 (for the 8.3 release).  This will become the default/only behaviour (i.e. there will be no option, and a `push` will remove any project monitors you have previously `push`ed from the same project).

**Comment by colleenmcginnis** [comment]
Thanks @paulb-elastic! I'll make sure this is reflected in #1925.

>This will become the default/only behaviour (i.e. there will be no option, and a push will remove any project monitors you have previously pushed from the same project).

So pushing will essentially overwrite existing monitors that originated from that project? Even if the `id` and/or `name` of the monitors have changed?

**Comment by paulb-elastic** [comment]
If the `id` has changed, then it won't _know_ it's the same monitor so the monitor that's no longer there (against it) that was previously pushed, will be deleted (@dominiqueclarke is that right - we're using `id` as the source of truth, not name?)

**Comment by paulb-elastic** [comment]
@colleenmcginnis in addition to the above, we're also removing the delete option from the UI, which will force users to remove monitors via `push`.

This is being done under https://github.com/elastic/kibana/issues/134598 (for 8.3)
