### ISSUE TITLE
[Synthetics] Document the Script Recorder

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#1907]
## Description

Whilst we’ve been building and changing the Script Recorder, it’s only had very basic documentation in the [GitHub repo](https://github.com/elastic/synthetics-recorder#elastic-synthetics-recorder).

With the recent release of the [first beta version](https://github.com/elastic/synthetics-recorder/releases/tag/v0.0.1-beta.1), and the fact that not much will change now before GA (planned for 8.5), it’s worth documenting the Script Recorder _properly_.

## Collaboration

- The docs team will define with product team the structure and location, and the product team will provide the initial content

(contacts @justinkambic, @kyungeunni)

## Suggested Target Release

The Script Recorder does not get released as part of the stack release, so is not urgent for the 8.3 release.  However, it would be good to start working on this once the other 8.3 documentation activities are out of the way.

## Stakeholders

@drewpost 
@kyungeunni
@justinkambic

**Comment by colleenmcginnis** [comment]
Is the product name "Script Recorder" or "Synthetics Recorder"? It looks like the app itself uses "Elastic Synthetics Recorder", but there are uses of both throughout the [/synthetics-recorder README](https://github.com/elastic/synthetics-recorder#elastic-synthetics-recorder). Maybe this is a question for @drewpost?

**Comment by justinkambic** [comment]
We refer to it colloquially as "script recorder" but its proper name is _Elastic Synthetics Recorder_, which is reflected in the code signing and the `package.json`, so I think this is the "official" name.

cc @drewpost @paulb-elastic @andrewvc

**Comment by drewpost** [comment]
Elastic Synthetics Recorder is the official name but, as Justin correctly highlighted, we're all guilty of using "script recorder" as a generic term for it.
