### ISSUE TITLE
[Request] [Fleet] Improve Elastic Agent installation documentation to capture architectural need for "collector" hosts when integrations are run remotely

### ISSUE THREAD

**Issue by kpollich** [elastic/observability-docs#1908]
## Description

For many integrations (see list below), the subject being monitored is not run directly on the host instance running Elastic Agent. The actual service in question may be running on a separate piece of hardware like a firewall, or may expose its logs via `syslog` or an HTTP endpoint. Our integrations handle these cases, but the documentation around Agent can be confusing. For example, our installation docs begin as follows:

> Fleet is a web-based UI in Kibana for [centrally managing Elastic Agents](https://www.elastic.co/guide/en/fleet/master/manage-agents-in-fleet.html). To use Fleet, you install Elastic Agent on each host you want to monitor or protect, then enroll the agent in a policy defined in Kibana. The policy includes integrations that specify how to collect observability data from specific services and protect endpoints. The Elastic Agent connects to a trusted [Fleet Server](https://www.elastic.co/guide/en/fleet/master/fleet-server.html) instance to retrieve the policy and report agent events.

This statement in particular is a source of confusion: 

> To use Fleet, you install Elastic Agent on each host you want to monitor or protect

For customers monitoring security hardware or SaaS platforms, it is not immediately obvious _where_ they're meant to install Elastic Agent. We mention that they should install Agent on the host they want to monitor, but a Cisco firewall cannot run Agent anymore than they can run Agent within their Okta or 1Password SaaS account.

<details>
<summary>Example integrations that fall into this category</summary>

```
1Password
AbuseCH
Akamai
AlienVault OTX
Anomali
Atlassian Bitbucket
Atlassian Confluence
Atlassian Jira
Auth0
Check Point
Cisco ASA
Cisco Duo
Cisco FTD
Cisco IOS
Ciso ISE
Ciso Meraki
Cisco Nexus
Cisco Secure EMail
Cisco Secure Endpoint
Cisco Umbrella
Cloudflare
CrowdStrike
CyberArk
F5
FireEye
Github Audit
Google Workspace
Juniper SRX
M365 Defender
Microsoft Defender for Endpoint
Mimecast
MISP
ModSecurity
Netscope
Office 365
Okta
Palo Alto Cortex XDR
Palo Alto Logs
Recorded Future
Snyk
Sonicwall
Vmware Carbon Black Cloud
ZeroFox
Zoom
Zscaler
```
</details>

So, I'd like to propose an evaluation of our documentation that seeks to cover integrations like these which - for the time being - require an "intermediary" or "collector" host to ingest data. We don't supply an "agent as a service" concept in Fleet, so we mandate that customers host agent themselves in order to ingest logs for integrations like these, so it stands to reason that we should provide some details on this architectural need. 

A few things we'd like to capture here:
- Addition of architecture diagram(s) for how these "collector" instances interface with Elasticsearch, Fleet, and the customer's infrastructure
- An audit of our existing docs to avoid phrases like "monitor the host on which Elastic Agent is installed" to reduce confusion about integrations that monitor SaaS or otherwise remote services
- Establish first-class terminology for these "intermediary/collector" instances in our docs, so we can be consistent in referencing them elsewhere

## Collaboration

- The docs team will define with product team the structure and location, and the product team will provide the initial content

**Contact Person:** @kpollich and @jamiehynds 

## Suggested Target Release

8.3 or 8.4

## Stakeholders

@elastic/fleet + @jamiehynds

**Comment by kpollich** [comment]
Thanks, DeDe - I'm glad to hear this is something that's sort of been on our radar. 

> "Elastic Agent is a single, unified way to add monitoring for logs, metrics, and other types of data to a host. It can also protect hosts from security threats, query data from operating systems, and more. A single agent makes it easier and faster to deploy monitoring across your infrastructure. Each agent has a single policy you can update to add integrations for new data sources, security protections, and more."

I think this description is a really great step up from what's in the docs now, so kudos to the team for the work here. There might just be some minor additions like you said that we can make to cover some of the confusion raised in this issue. For example

> It can also protect hosts from security threats, query data from operating systems, and more.

Maybe something like this would cover more cases?

> It can also protect hosts from security threats, query data from operating systems, **[forward data from remote services or hardware]**, and more.

It's a bit of a challenge to come up with some verbiage around
1. The concept of "collecting" or "forwarding" monitoring data that does not exist directly on the host
2. A succinct name for "data that does not exist directly on the host" 🙃 

I think the primary sticking point raised in this issue is the lack of references or accommodations for non-host monitoring both in the Fleet UI and in our docs.  If we can make it clear that it's expected and required that a customer who wants to ingest data from some remote service or a piece of hardware will still need to run and host agent _somewhere_ on their own, I think we'll meet this need. 

I put together a (very) rough diagram that attempts (key word 😅) to summarize what we're trying to capture here:

![image](https://user-images.githubusercontent.com/6766512/171477328-27e4b2b1-1124-4385-b0c2-8252b2653d1e.png)

It's important that we clarify that agent can act in a context where it both monitors the host it's deployed to as well as collecting and forwarding data from remote services, hardware, etc.

> Current docs are woefully lacking in conceptual info and architecture diagrams. @ollyhowell is working on an overview and can comment on whether he plans to address this problem.

This is great to hear! Thanks you for mentioning it - I'd love to see more diagrams in the Fleet/Agent docs and I'm confident they'll be very high value. Exciting news 🙂

**Comment by dedemorton** [comment]
Nice diagram! I think we should add it to https://www.elastic.co/guide/en/fleet/current/fleet-overview.html. TBH, I kind of like the handwritten look. I'll probably want to make it consistent with the other docs though.

**Comment by kpollich** [comment]
I use https://excalidraw.com/ for those little hand-drawn style diagrams. Pretty nice little tool!

**Comment by dedemorton** [comment]
@ollyhowell Cool. I'll use the diagram when I work on this issue. It's been a long time since I've watched a developer explain something on a whiteboard, and I kind of miss it. :-) So it fits the mood.

**Comment by mukeshelastic** [comment]
@jamiehynds are you able to review the content/diagrams for this documentation page?

**Comment by osmanis** [comment]
Hi! Is there an ETA on this docs improvement? The 8.3 Agent/Integrations UX improvement is out now and users will see the simplified UI, but they don't see the docs update when they click into the docs from Kibana.

**Comment by dedemorton** [comment]
@osmanis ETA is sometime next week. I'll do what I can this week, but I am recovering from an illness.

**Comment by dedemorton** [comment]
Looks like I need to update the following topics:

https://www.elastic.co/guide/en/fleet/current/fleet-overview.html
https://www.elastic.co/guide/en/fleet/current/migrate-beats-to-agent.html (maybe) 
https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html 
https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html 
https://www.elastic.co/guide/en/fleet/current/install-standalone-elastic-agent.html 
https://www.elastic.co/guide/en/fleet/current/manage-agents.html 

I'll also try to remove some of the duplication if I can do that without violating the concept of "every page is page one."
