### ISSUE TITLE
[Request] Include Elastic Serverless Forwarder documentation in Elastic Docs

### ISSUE THREAD

**Issue by andresrc** [elastic/observability-docs#1918]
## Description

- https://github.com/elastic/obs-dc-team/issues/790

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The product team will provide the initial content and the docs team will edit / review.

The current documentation is in [GitHub](https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md). The goal would be:

- Find a good location in the Observability Guide
- Move the content there, reviewing / editing it as part of the process.

Once the content is in the documentation we might want to remove it from the original location and just link to the docs.

**Contact Person:** @aspacca 

## Suggested Target Release

ESF releases are decoupled from stack releases. Ideally we would like to make it GA around the same as 8.3 is released. In any case, documentation is not available by then, we would need to backport it to 8.3

## Stakeholders

@ravikesarwani @aspacca

**Comment by bmorelli25** [comment]
Adding this as a stretch goal for 8.3.

**Comment by andresrc** [comment]
If possible we would like this two be approach in two phases:
- Editorial revision of the [content](https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md) currently in GitHub (in place)
- Migration to Docs.

**Comment by ollyhowell** [comment]
> If possible we would like this two be approach in two phases:
> 
> * Editorial revision of the [content](https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md) currently in GitHub (in place)
> * Migration to Docs.

1st editorial revision merged in above.

Still to do: work out where in Obs Guide it should go and get another revision in during migration to Asciidoctor...

**Comment by ravikesarwani** [comment]
@ollyhowell , We are working on deprecating Functionbeat in lieu of Elastic Serverless Forwarder.
The topic of Elastic Serverless Forwarder to be on the official documentation pages on Elastic docs has come up.  Can we up the priority of this please?

**Comment by ollyhowell** [comment]
Hey Ravi, yes! I have it on my list for this week...will update soon

**Comment by ollyhowell** [comment]
Adding link to draft PR for review by @aspacca and @ravikesarwani : https://github.com/elastic/observability-docs/pull/2214
