### ISSUE TITLE
[Request] Update docs for changes in agent installation workflow

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1920]
## Description

To increase ingestion rates for Cloud trial users, the design team is changing the workflow for installing agents and integrations. We need to update the guides to reflect these changes. Users will: Install the agent, add an integration, and confirm incoming data.

## Collaboration

- The docs team will lead producing the content

**Contact Person:**
@jen-huang 

## Suggested Target Release

8.3 (stretch)

**Comment by dedemorton** [comment]
@kilfoyle You're probably already on top of this, but just in case, you should look at the ingest-dev issue related to the add agent workflow. It will impact the onboarding docs.

**Comment by dedemorton** [comment]
@ollyhowell @nrichers For 8.3, we need to make sure that someone is "on the hook" to update the onboarding getting started docs to reflect the new step-based workflow for first-time Elastic Agent users on Cloud. The steps in the onboarding docs won't be accurate for cloud users installing their first Elastic Agent.

For 8.3, I think we need to:

- Update the onboarding guide to match the step-based workflow.
- For the existing guides, add some text that sends first-time Elastic Agent users on cloud to the onboarding docs.

After 8.3, we'll need to consider reordering the steps in our guides to match the step-based workflow. We obviously don't have time to do that right now.

Here's what the new page looks like. Again, I believe it only appears if there are no Elastic Agents installed.

![image](https://user-images.githubusercontent.com/14206422/172937869-5130004c-1627-4f7a-9d6b-5b9776489b95.png)

**Comment by kilfoyle** [comment]
I forgot to mention it earlier, but I added this issue to the agenda for the next Onboarding Team sync.

**Comment by kilfoyle** [comment]
@dedemorton Here's a [PR](https://github.com/elastic/tech-content/pull/166) for the .asciidoc version of the Observability GS guide. Once we get that sorted out I'll port the changes into the .mdx version as well.

@jmikell821 I'm not sure, but we may need similar changes for the two security guides.

**Comment by dedemorton** [comment]
Noting here that the observability and Fleet/Agent docs also require updates for this change. Let's keep this issue open until all the docs are updated.

**Comment by dedemorton** [comment]
We need to put more thought into how to implement the doc changes related to the new step-based workflow. Because the step-based workflow only appears under specific conditions (on cloud when Elastic Agent is not installed), we can't know for sure whether the user will encounter this workflow. That makes it hard to provide clear, accurate documentation for all users.

First I need to understand the preferred workflow that we want to recommend to users.

Do we want to tell users to install Elastic Agent _before_ adding integrations? If so, folks who read the docs will never see the step-based workflow. IMO this is OK if the goal of the step-based workflow is to help users who haven't read the docs. 

Should the onboarding guides intentionally show the step-based workflow?
Right now  the [getting started guide for observability](https://www.elastic.co/guide/en/welcome-to-elastic/current/getting-started-observability.html) shows the step-based flow, but the other getting starting guides do not. Users are likely to be confused if they try to follow the other onboarding guides and see the undocumented workflow. Also we are showing users a workflow that's only true if no agents are installed. Will users expect to be able to access that workflow the same way the next time they add an integration?

If we change the onboarding guides, what should we do with the [quick starts](https://www.elastic.co/guide/en/fleet/current/fleet-elastic-agent-quick-start.html)? We can't remove those guides in favor of the onboarding guides because we still need to support self-managed environments (plus the guides provide content that's missing from the onboarding guides). The options are:

1. Change the workflow so that the steps about adding Elastic Agent appear before the steps about adding integrations. Users will not see the step-based workflow.
2. Add notes where users might encounter the step-based workflow and explain the caveats.
I prefer option 1 because trying to explain caveats usually generates confusion.

We will still have some places where the user may encounter the step-based workflow unexpectedly. For example, in the topic about [generating an agent policy for standalone agents](https://www.elastic.co/guide/en/fleet/current/create-standalone-agent-policy.html), users who are not already running Elastic Agent will see the step-based workflow. We can add a note there to explain the UI might be different. IMO every time we have to add a note like that, we are exposing a design flaw.

**Comment by dedemorton** [comment]
@jen-huang Who is the best contact person to help me understand future plans for the step-based onboarding workflow? Please read through [my previous comments](https://github.com/elastic/observability-docs/issues/1920#issuecomment-1184923624) to see where I'm coming from. We want to avoid writing a lot of "it depends" in the docs.

**Comment by ollyhowell** [comment]
Hmm...tricky one. Think it would be good to discuss the points/questions raised by @dedemorton i.e. find out what preferred workdflow is right now and what it will become too.

We might have to default to a note for some pages (e.g. agent policy for standalone agents) where there is a perhaps small but unexpected impact on user steps, or where we expect but can't guarantee the user would be aware of the change. It's not ideal but a reusable snippet would at least plug the gap.

There is quite a lot in Step 2 of the new Obs Getting Started now...I wonder if we should break it into 2 steps, one of which is optional i.e. only needed if Agent not already installed. Again, not ideal... 

There does seem to be a general problem/question around whether the Getting Started guides should be run concurrently i.e. we can't guarantee users have done 1 or other but we're pushing the Cloud sign-up as an always required first step (and not signposting a 'skip if you've already done this', which would make sense to me).

**Comment by dedemorton** [comment]
At the Agent/Fleet docs planning meeting on 7/19/22, we decided that we will not change the existing quick starts and other installation docs until the step-based workflow is visible in all situations. We might want to put notes in some places where users might run into the step-based workflow unexpectedly.

**Comment by dedemorton** [comment]
PR for updating the Observability and Fleet/Agent guides is up here: https://github.com/elastic/observability-docs/pull/2004.

**Comment by dedemorton** [comment]
@jmikell821  Is your team planning to update the security onboarding guide to show the new step-based UI?

TBH, I'm not sure the best way to proceed here because of the conditional nature of that page. I do think new users might be confused if they start with one of the security-related getting started guides and it doesn't match what they see in Kibana on cloud.

**Comment by dedemorton** [comment]
Closing because we have updated the observability guide. If other teams like security need to make these changes, they will need to track them in a separate issue.
