### ISSUE TITLE
[Request] Remove OTLP limitation

### ISSUE THREAD

**Issue by smith** [elastic/observability-docs#1930]
https://www.elastic.co/guide/en/apm/guide/current/open-telemetry.html#open-telemetry-otlp-limitations says OTLP/HTTP is not supported.

This limitation was removed in 8.3 (https://github.com/elastic/apm-server/pull/8156) so this section can be removed for versions ≥ 8.3.

**Comment by bmorelli25** [comment]
Related to https://github.com/elastic/apm-server/issues/8177.
