### ISSUE TITLE
[Request] Metric Fields Replaced in Metrics and Observability Overview app

### ISSUE THREAD

**Issue by neptunian** [elastic/observability-docs#1935]
## Description

New metric fields (`host.network.ingress.bytes`, `host.network.egress.bytes`) are replacing old ones (`system.network.in.bytes`, `system.network.out.bytes`) described in [this PR](https://github.com/elastic/kibana/pull/134471).  This will result in users using metricbeat <=7.14 and Kibana >= 8.4.0 to have no or incomplete data where these fields are used.  I think https://www.elastic.co/guide/en/observability/current/host-metrics.html and https://www.elastic.co/guide/en/observability/current/view-infrastructure-metrics.html should be updated or anywhere that used the "old" fields and will be affected.  A complete list of the pages affected are [in the PR](https://github.com/elastic/kibana/pull/134471).  

## Collaboration
- The docs team will lead producing the content

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:**
@neptunian 

## Suggested Target Release

8.4

**Comment by ollyhowell** [comment]
Just reviewing stragglers in the 8.4 view but this might be worth checking if done / still needs done; could make a good bite-sized update for main docs @mdbirnstiehl

**Comment by neptunian** [comment]
Hi @ollyhowell .  I think it should still be documented that the fields have been updated and that data might not be totally accurate between versions.
