### ISSUE TITLE
[Request] Custom ingest pipeline in Fleet

### ISSUE THREAD

**Issue by nchaulet** [elastic/observability-docs#1936]
## Description

Related Kibana issue  https://github.com/elastic/kibana/issues/133740
We are allowing user to write custom ingest pipeline for their Fleet managed datastream

It should probably be mentioned and documented here https://www.elastic.co/guide/en/fleet/current/data-streams.html 

We can now add a custom pipeline for an integration datastream by creating a pipeline named `{datastream.type}-{datastream.dataset}@custom`

## Collaboration

Contact Person: @nchaulet 

## Suggested Target Release

8.4

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by joshdover** [comment]
cc @akshay-saraswat to add more information here about what we should document

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated the docs for Custom Ingest Pipeline at links:
- https://www.elastic.co/guide/en/fleet/current/data-streams.html
- https://www.elastic.co/guide/en/fleet/current/data-streams-pipeline-tutorial.html

**Screenshots:**
![6](https://user-images.githubusercontent.com/77374876/187405956-0b8b0cb2-610f-466e-ae1f-cf430536643f.JPG)

![7](https://user-images.githubusercontent.com/77374876/187405941-4e593613-3d56-4271-b5e8-b30cf42331b5.JPG)

Hence we are marking this as **QA:Validated**.
Thanks
