### ISSUE TITLE
Verify if the FAQ question about communication between Elastic-Agent and Kibana is needed/correct

### ISSUE THREAD

**Issue by herrBez** [elastic/observability-docs#1939]
## Description

I noted that the [Elastic-Agent Troubleshooting FAQ](https://github.com/elastic/observability-docs/blob/main/docs/en/ingest-management/troubleshooting/faq.asciidoc#how-are-communications-secured-between-agent-and-kib) has a question about ["How are Elastic-Agent Kibana communications secured?"](https://www.elastic.co/guide/en/fleet/master/fleet-faq.html#how-are-agent-kibana-communications-secured"). However, according to [the fleet-server documentation](https://www.elastic.co/guide/en/fleet/master/fleet-server.html) Elastic-Agents do not communicate directly with Kibana but only with Elasticsearch.

**Comment by dedemorton** [comment]
You're correct. This section is old (from before Fleet Server was added). I will remove the statement.
