### ISSUE TITLE
[Request] Update Fleet troubleshooting docs about new reinstall integration button

### ISSUE THREAD

**Issue by jen-huang** [elastic/observability-docs#1972]
## Description

Currently troubleshooting guide has manual for reinstalling an integration: https://www.elastic.co/guide/en/fleet/current/fleet-faq.html#how-do-i-reinstall-a-missing-dashboard-asset

From 8.4 a reinstall option will be surfaced in the Integrations Settings page: https://github.com/elastic/kibana/pull/135590

Let's show this new UI option in the docs and expand on what reinstalling can help fix:
> There are some cases where reinstalling an integration package can help customers resolve problems, such as:
> 
> 1. They made manual edits to a managed asset and want to reset it back to the original state
> 2. Something temporary went wrong (eg. network issue) during a package install or upgrade
> 3. A package was installed in a prior version that had a bug in the install code

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content

**Contact Person:** @jen-huang 

## Suggested Target Release

8.4

## Stakeholders

N/A

**Comment by simranvaseer-qasource** [comment]
Hi Team
We have revalidated the docs for Reinstall Integration button:
 
- [https://www.elastic.co/guide/en/fleet/current/fleet-faq.html#how-do-i-reinstall-a-missing-dashboard-asset](https://www.elastic.co/guide/en/fleet/current/fleet-faq.html#how-do-i-reinstall-a-missing-dashboard-asset)
- [https://www.elastic.co/guide/en/fleet/current/install-uninstall-integration-assets.html#reinstall-integration-assets](https://www.elastic.co/guide/en/fleet/current/install-uninstall-integration-assets.html#reinstall-integration-assets)

**Screenshots:**
![image](https://user-images.githubusercontent.com/102019374/187131928-a0e96ae2-97e1-4e3b-b4d2-2ac55668d76f.png)
![image](https://user-images.githubusercontent.com/102019374/187131969-e149efc0-43f4-48fe-925c-3eefc3acb95f.png)
 
Hence, marking this as QA:Validated.
Thanks
