### ISSUE TITLE
[Request] Update screenshots for new "Add Fleet Server" button

### ISSUE THREAD

**Issue by kpollich** [elastic/observability-docs#1979]
## Description

In https://github.com/elastic/kibana/pull/135747, we separated the "Add Agent" flow from the "Add Fleet Server" flow to fix various issues around consistency, UX, and maintainability in Fleet UI.

![image](https://user-images.githubusercontent.com/6766512/177573362-25466443-94ae-40c5-8693-a0d92167f7b8.png)

As a result, we have some out of date screenshots in our Fleet/Agent documentation. 

I looked through the docs and I've listed the screenshots I found that should be updated below. I'm not sure that is exhaustive, but hopefully it's helpful to start.

I don't know if this is necessarily worth taking on, or what our "standards" are around updating screenshots when UIs are changed like this. The impact of the "Add Fleet Server" button is fairly limited, and it might not even be worth taking this on if there's not much value in updating these screenshots. I figured I'd open an issue either way, but we could easily decide to just close this out if 1:1 accuracy between the live UI and the docs screenshots isn't a high priority in cases like this.

### Screenshots to update

- https://www.elastic.co/guide/en/fleet/current/images/kibana-fleet-agents-overview.png
- https://www.elastic.co/guide/en/observability/8.3/images/kibana-fleet-agents.png
- https://www.elastic.co/guide/en/fleet/current/images/kibana-fleet-agents.png
- https://www.elastic.co/guide/en/fleet/current/images/add-fleet-server.png
- https://www.elastic.co/guide/en/fleet/current/images/rolling-agent-upgrade.png
- https://www.elastic.co/guide/en/fleet/current/images/schedule-upgrade.png
- https://www.elastic.co/guide/en/fleet/current/images/upgrade-status.png
- https://www.elastic.co/guide/en/fleet/current/images/agent-tags.png
- https://www.elastic.co/guide/en/fleet/current/images/agent-status.png
- https://www.elastic.co/guide/en/fleet/current/images/agent-status-filter.png
- https://www.elastic.co/guide/en/fleet/current/images/apply-agent-policy.png

## Collaboration

- The docs team will lead producing the content

**Contact Person:** @kpollich 

## Suggested Target Release

N/A

## Stakeholders

@elastic/fleet

**Comment by dedemorton** [comment]
@kpollich I'm on the fence about this.

It can be time consuming to redo these screen captures, especially if the UI changes are backported (it means we have to redo the screen captures for two different versions).  For most of the screens, there is some setup required to populate the screen with meaningful data, so this basically means setting everything up in two different  versions and taking all the screen captures.

On the other hand, I think stale screen captures undermine the user's confidence in the docs.

In general, I think we *should* redo screens for every new release (8.4, 8.5, etc) but not for backported UI changes unless they are significant and likely to confuse users. I also think we should consider removing some of the screens to make the documentation easier to maintain over time. Are there any that you would remove?

@elastic/obs-docs What do you think?

**Comment by dedemorton** [comment]
We were not able to contain this work for 8.4 so I am adding as an 8.5 candidate.

**Comment by jen-huang** [comment]
@dedemorton, I'm going to close this button as we have work coming up (https://github.com/elastic/kibana/issues/137785) that will remove this button again, so no sense in putting the work in here 😇

**Comment by dedemorton** [comment]
@jen-huang Sounds good, but please do open a docs issue when you remove the button because we have some task-oriented docs in flight that (I think) talk about that button.
