### ISSUE TITLE
[Request] Explain why the Edit hosts link may be grayed out for Fleet Server hosts

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#1986]
## Description

Related to https://github.com/elastic/kibana/pull/135669.

We should explain in the [Fleet docs](https://www.elastic.co/guide/en/fleet/current/fleet-settings.html) that the Edit hosts link is grayed out if  Fleet Server hosts are specified in the kibana config. The popup is useful, but we should also mention this in the docs for users who are learning about Fleet Server.

## Collaboration

- The docs team will lead producing the content

**Contact Person:**

@nchaulet 

## Suggested Target Release

8.4

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated the doc for Fleet Settings at link:
- https://www.elastic.co/guide/en/fleet/current/fleet-settings.html

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/187193262-b81b818c-8683-4f68-afd3-6f29e9a6dcdd.JPG)


Hence we are marking this as **QA:Validated**.
Thanks
