### ISSUE TITLE
[Request] Update Observability Alerting to remove Technical Preview mentionn

### ISSUE THREAD

**Issue by emma-raffenne** [elastic/observability-docs#1997]
## Description

Alerts and Rules view in Observability will go GA in 8.4.0: elastic/kibana#129636. Documentation needs to be updated to:
- remove any mention of "Technical Preview"
- replace screenshots showing "Technical Preview" sticker with ones without

Documentation pages affected:
- https://www.elastic.co/guide/en/observability/current/create-alerts.html
- https://www.elastic.co/guide/en/observability/current/view-observability-alerts.html

## Collaboration

- The product team will provide the initial content and the docs team will edit / review
- Contact Person: @maryam-saeidi 

## ~~Suggested~~ Target Release

8.4.0

**Comment by maryam-saeidi** [comment]
Hi @elastic/obs-docs,
I am the person of contact for adjusting the documents related to Observability Alerting for the next release (v8.4.0), I was wondering how this process is usually and what do I need to provide for this ticket. Any clarification is appreciated.
