### ISSUE TITLE
[Request] Remove beta admonition for Logstash output

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2001]
## Description

Currently the docs about configuring the Logstash output in Fleet include a beta admonition. This needs to be removed when Logstash output support is GA.

## Collaboration

- The docs team will lead producing the content

## Suggested Target Release

8.4

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated the docs for Logstash output feature at links:
- https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html
- https://www.elastic.co/guide/en/fleet/current/fleet-settings.html

We have observed that beta note is removed and is no longer available on both the pages.

Hence we are marking this as **QA:Validated**.
Thanks
