### ISSUE TITLE
[Request] Alerting - View Rule Detail Enhancements

### ISSUE THREAD

**Issue by emma-raffenne** [elastic/observability-docs#2002]
## Description

Further improvements have been introduced in the [Rule Detail Page](https://www.elastic.co/guide/en/observability/current/create-alerts.html#create-alerts-rules-details). More information to be completed by the contact person.

## Collaboration

- The product team will provide the initial content and the docs team will edit / review

**Contact Person: @fkanout **

## Suggested Target Release

8.4.0

**Comment by colleenmcginnis** [comment]
👋  @fkanout @emma-raffenne do you think the screenshot update in https://github.com/elastic/observability-docs/pull/2082 is sufficient? If not or if you have a better screenshot we can include, I can open a separate PR to add more details.

You can see the preview here: https://observability-docs_2082.docs-preview.app.elstc.co/guide/en/observability/master/create-alerts.html#create-alerts-rules-details

**Comment by emma-raffenne** [comment]
@fkanout @colleenmcginnis 
If possible, we could use a screenshot where more than 1 day of _Recent Alert History_ is shown in the top right box.

**Comment by colleenmcginnis** [comment]
@fkanout could you help with a screenshot with a longer history? I had to create a new alert for these screenshots. 🙂

**Comment by fkanout** [comment]
Hey @colleenmcginnis, sorry about the delayed reply. Here are the screenshots. Please let me know if you need anything else.


![Image](https://user-images.githubusercontent.com/6838659/185070773-8c1179e2-23f5-46ec-9474-fb2fee6ff524.png)



![Image](https://user-images.githubusercontent.com/6838659/185070795-33243c45-2e46-4c2e-81d4-0c73bc1b62b5.png)

**Comment by colleenmcginnis** [comment]
Thanks @fkanout! I updated the images used in https://github.com/elastic/observability-docs/pull/2082.
