### ISSUE TITLE
[Request] UI for configuring agent binary download sources in Fleet

### ISSUE THREAD

**Issue by criamico** [elastic/observability-docs#2006]
## Description

Related Kibana issue: https://github.com/elastic/kibana/issues/133828

Added a new section in Fleet settings to manage binary download sources. This new feature exposes to the UI the `sourceURI ` parameter for the Elastic Agent that is documented here https://www.elastic.co/guide/en/fleet/8.3/elastic-agent-reference-yaml.htm

The documentation should include the features introduced with: 
- https://github.com/elastic/kibana/pull/134889
- https://github.com/elastic/kibana/pull/136263

## Collaboration

- The docs team will lead producing the content

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:** @criamico 

## Suggested Target Release
8.4

## Stakeholders

@nimarezainia

**Comment by joshdover** [comment]
@nimarezainia Here's the docs issue we have for this feature. I think we should also include the directory structure for setting up the HTTP server + example curl commands for downloading a release from our public artifacts.elastic.co domain.

**Comment by joshdover** [comment]
@pierrehilbert Who on your team could contribute the details on the expected directory structure for Agent downloads?

**Comment by pierrehilbert** [comment]
@michalpristas Could you please contribute?

**Comment by michalpristas** [comment]
assuming sourceURI as a root rest of the path needs to follow structure Elastic has in place:
such as example is: `https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.3.3-darwin-x86_64.tar.gz`
we take `https://artifacts.elastic.co/downloads/` as a source URI 
then we append `{beat_type}/{beat_type}-{version}-{arch}-{package_type}`
so for anybody creating an http file server, rule is to group artifacts into directories/subpath by type and it should be good

**Comment by dedemorton** [comment]
@michalpristas Can you also please share the example cURL commands for downloading a release from our public artifacts.elastic.co domain? I want to make sure users get all the packages they need. Thanks!

**Comment by michalpristas** [comment]
for Agent itself:
`curl -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.3.3-linux-x86_64.tar.gz`

### Beats
- filebeat: `curl -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.3.3-linux-x86_64.tar.gz`
- metricbeat: `curl -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.3.3-linux-x86_64.tar.gz`
- auditbeat: `curl -O https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.3.3-linux-x86_64.tar.gz`
- cloudbeat: `curl -O https://artifacts.elastic.co/downloads/cloudbeat/cloudbeat-8.3.3-linux-x86_64.tar.gz`
- heartbeat: `curl -O https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-8.3.3-linux-x86_64.tar.gz`
- packetbeat: `curl -O https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-8.3.3-linux-x86_64.tar.gz`
- osquerybeat: `curl -O https://artifacts.elastic.co/downloads/beats/osquerybeat/osquerybeat-8.3.3-linux-x86_64.tar.gz`

### APM
- apm-server: `curl -O https://artifacts.elastic.co/downloads/apm-server/apm-server-8.3.3-linux-x86_64.tar.gz`

### Endpoint
- endpoint-security: `curl -O https://artifacts.elastic.co/downloads/endpoint-dev/endpoint-security-8.3.3-linux-x86_64.tar.gz`

### Fleet server
- fleet-server: `curl -O https://artifacts.elastic.co/downloads/fleet-server/fleet-server-8.3.3-linux-x86_64.tar.gz`

**Comment by dedemorton** [comment]
@michalpristas I was really hoping there would be a way for users to get ALL the agent-related packages for a specific architecture. :-(  We are opaque in the agent docs wrt which shippers get started and why (this was deemed an "implementation detail" that we didn't want to expose). Anyhow...I'll make sure users at least know the set of packages that are needed if they want to host artifacts on an restricted network. Thanks!

**Comment by dedemorton** [comment]
@michalpristas The PR is up for review here: https://github.com/elastic/observability-docs/pull/2078

I did try to test the procedure, but not sure if I did everything I needed to simulate an air-gapped environment. I viewed the agent policy and confirmed that the source uri was set to the file server I had running locally, but agent logs still reported that the artifacts were downloaded from the public artifact registry. Is it possible the log message is hard coded and therefore inaccurate?

![image](https://user-images.githubusercontent.com/14206422/184286280-90c69ce2-f376-4761-a76a-dca937eeb947.png)

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated the docs for Agent Binary feature at links:
- https://www.elastic.co/guide/en/fleet/current/elastic-agent-reference-yaml.html
- https://www.elastic.co/guide/en/fleet/current/fleet-settings.html
- https://www.elastic.co/guide/en/fleet/current/air-gapped.html#host-artifact-registry


**Screenshots:**
![15](https://user-images.githubusercontent.com/77374876/186889517-81bcaad8-782e-4b90-9a5a-83b1ccbccec3.JPG)
![16](https://user-images.githubusercontent.com/77374876/186889522-e6e10176-64fd-4c69-b149-9469e809b2bc.JPG)
![17](https://user-images.githubusercontent.com/77374876/186890745-efc3b051-c947-4b8b-8d8e-fb7e744f8290.JPG)

Hence we are marking this as **QA:Validated**.
Thanks
