### ISSUE TITLE
Replace APM integration documentation with static page

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2008]
### Summary

Remove documentation from the APM integration so we don't have to update docs in two places.

**Comment by bmorelli25** [comment]
@axw — is this issue still relevant? I read through https://github.com/elastic/kibana/issues/137759, but I'm struggling to determine how the final decision impacts this issue.

**Comment by axw** [comment]
@bmorelli25 it's not necessary as we are still publishing packages. IMO it would still be a good thing to do to avoid fragmentation/skew across the main docs and the integration docs. @simitt WDYT?

**Comment by simitt** [comment]
A static page that links to the APM guide of the according version sounds good to me. Having to maintain multiple document sources for the APM integration is error prone.

**Comment by simranvaseer-qasource** [comment]
Hi @bmorelli25

As per the ticket  [https://github.com/elastic/apm-server/pull/9932/files](https://github.com/elastic/apm-server/pull/9932/files)  we have validated changes and found updated changes are available.

**APM changes links:**

- [https://www.elastic.co/guide/en/apm/guide/current/apm-components.html](https://www.elastic.co/guide/en/apm/guide/current/apm-components.html)

- [https://www.elastic.co/guide/en/observability/current/ingest-traces.html](https://www.elastic.co/guide/en/observability/current/ingest-traces.html)

- [https://www.elastic.co/guide/en/apm/guide/current/apm-data-streams.html](https://www.elastic.co/guide/en/apm/guide/current/apm-data-streams.html)

**Screenshot:**
![image](https://user-images.githubusercontent.com/102019374/212314121-334bca3a-ac25-4365-83bd-214a05cca950.png)

Please let us know if any else validation is required.
Thanks
