### ISSUE TITLE
[Request] Add "APM" breadcrumb before "APM User Guide" and "APM Agents"

### ISSUE THREAD

**Issue by axw** [elastic/observability-docs#2058]
## Description

At https://www.elastic.co/guide/index.html, there is an APM page linked underneath Observability. This APM page has sub-sections for APM User Guide (~APM Server), and APM Agents. If you navigate to either of those, there is no breadcrumb link to the overall APM page.

I would often like to navigate between the docs for agents & server, in which case I need to either edit the URL bar, or navigate all the way up to the top of the docs and back down again. It would be great if we had a breadcrumb link to make it easier to navigate between them.

(This is just, like, my opinion, man. If this is at all contentious, let's have a discussion.)

## Collaboration

The docs team will lead producing the content.

**Contact Person:** @axw 

## Suggested Target Release

No specific release.

## Stakeholders

@axw

**Comment by dedemorton** [comment]
What you're asking is completely reasonable. Unfortunately, though, our current docs system severely limits what we're able to do with breadcrumbs. They are generated by the monolithic doc build. This problem will be solved in Next Docs, but until then, I'm not sure there's much we can do.

@colleenmcginnis @bmorelli25 Any ideas? I think we could use HTML passthru blocks to inject a related link at the top of each page, but it wouldn't show up in the breadcrumbs. It's probably not a good idea from a design perspective to add yet another way of navigating.

**Comment by bmorelli25** [comment]
This issue was posted in the #apm-dev Slack channel as well and I couldn't help but play around with it. I put this idea together: It searches the book title for "APM" and if it exists, appends an extra element in the breadcrumbs when the docs are built. We could also use something like this for the ES Clients and perhaps other books where grouping makes sense.

https://user-images.githubusercontent.com/5618806/182931014-afd8bafd-5c5b-4c27-b2cf-11e7511a593d.mov

**Comment by dedemorton** [comment]
That's awesome, Brandon! 👏 👏 

If we do this for APM, we should definitely do it for the other groupings.

**Comment by bmorelli25** [comment]
Adding @colleenmcginnis as an assignee as well as she's making it look much better than I ever could've.

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/docs/pull/2619.
