### ISSUE TITLE
[Request] Change "Metrics" to "Infrastructure"

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/observability-docs#2097]
## Description

It looks like it was decided in https://github.com/elastic/kibana/issues/123972 that the high-level "Metrics" section of the Observability app would be changed to "Infrastructure", and the changes were made for 8.4 in https://github.com/elastic/kibana/pull/135278. This affects the text, screenshots and navigation elements (titles, table of contents, etc) throughout the Observability docs.

👋  @jasonrhodes @matschaffer (just pulling from https://github.com/elastic/kibana/issues/123972 and https://github.com/elastic/kibana/pull/135278, but feel free to tag others) what can we do to make sure these changes are communicated to the docs team earlier in the process? We happened to find out about this change in an [unrelated PR review](https://github.com/elastic/observability-docs/pull/2089#pullrequestreview-1073957096). 

## Collaboration

The docs team (@colleenmcginnis) will lead producing the content

**Contact Person:** @jasonrhodes @matschaffer can one of you serve as contact person and reviewer for this work? Or can you tag someone else in?

## Suggested Target Release

8.4

## Stakeholders

Anyone else?

**Comment by matschaffer** [comment]
Probably good for @neptunian to have this on her radar as well. In general, I'm in favor. Sorry I didn't think to change it as part of https://github.com/elastic/kibana/issues/123972
