### ISSUE TITLE
[Request] Add links to more detailed synthetics `request` examples

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/observability-docs#2115]
## Description

Add links to more detailed Elastic Synthetics `request` examples in [/synthetics-demo](https://github.com/elastic/synthetics-demo). Existing example code:

* https://github.com/elastic/observability-docs/issues/2049#issuecomment-1201343573 by @awahab07
* https://github.com/elastic/observability-docs/issues/2049#issuecomment-1202923144 by @bhoskins7
* https://github.com/elastic/observability-docs/pull/2071#pullrequestreview-1080263961 by @paulb-elastic 

## Collaboration

- [x] The product team will add example code to [/synthetics-demo](https://github.com/elastic/synthetics-demo)
- [ ] The docs team will add links in [Write a synthetic test > Make API requests](https://observability-docs_2071.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-create-test.html#synthetics-request-param) to the example code

**Contact Person:** TBD

## Suggested Target Release

post-8.4

## Stakeholders

* @paulb-elastic 
* @andrewvc 
* @awahab07
* @bhoskins7
* @vigneshshanmugam

**Comment by paulb-elastic** [comment]
@colleenmcginnis this has been done hasn't it, can this be closed?

**Comment by colleenmcginnis** [comment]
@paulb-elastic it looks like I didn't go back and add the link after the example was created. Fixed in https://github.com/elastic/observability-docs/pull/2243.
