### ISSUE TITLE
[APM] Remove extra priv from API key docs

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2143]
### Summary

An extra privilege exists when creating an API key in Kibana in versions <8.5. This privilege will be removed in https://github.com/elastic/kibana/pull/139383. Our documentation needs to be updated to reflect this change.

### Related

* https://github.com/elastic/apm-server/pull/8111

**Comment by gbamparop** [comment]
Sourcemap references could also be removed from [APM user guide](https://www.elastic.co/guide/en/apm/guide/current/api-key.html)
