### ISSUE TITLE
[Fleet]: `-f` flag in installation command available under SSL/TLS Doc.

### ISSUE THREAD

**Issue by ghost** [elastic/observability-docs#2145]
**Description:**
`-f` flag in installation command available under SSL/TLS Doc.

- Currently, `-f` flag is removed from add agent/ fleet server commands. However, `-f` flag is available for installation commands  under guide.

**Link:**
https://www.elastic.co/guide/en/fleet/current/secure-connections.html

**Screenshots:**
Available under Agents tab:
![image](https://user-images.githubusercontent.com/102019374/186649482-b284a9d2-d009-485c-b105-1a446fb902c7.png)

Available under guide:
![2](https://user-images.githubusercontent.com/102019374/186650241-5689ab7d-0f72-4965-a47c-9b12ef626b96.png)

![1](https://user-images.githubusercontent.com/102019374/186650266-58986d00-2eb0-444b-bb7e-1b3c57798dc3.png)

**Comment by dikshachauhan-qasource** [comment]
Secondary Review is done

**Comment by dikshachauhan-qasource** [comment]
Hi @bmorelli25 

We have validated the ticket and found it working fine under current 8.6 released guide.

**URL referred:**  https://www.elastic.co/guide/en/fleet/current/secure-connections.html

**Observations:** Currently, guide installation commands are working as per commands shared shared on Fleet UI i.e. without using -f force flag.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/224226282-21c85f4c-b173-45f3-99c9-b70b9ed2683a.png)
![image](https://user-images.githubusercontent.com/72375798/224226368-4e17c875-23d3-4bed-955b-da34e9823fa0.png)

Hence, marking this as QA:Validated.

Thanks!!
