### ISSUE TITLE
[Synthetics] Remove all references to zip_url monitors

### ISSUE THREAD

**Issue by andrewvc** [elastic/observability-docs#2149]
Now that we have private locations and project monitors we should remove all references to `zip_url` monitors as they are something we should no longer actively recommend.

**Comment by paulb-elastic** [comment]
Removed from 8.5 board as an issue (tracked in https://github.com/orgs/elastic/projects/928#card-84622502)

**Comment by paulb-elastic** [comment]
As raised by @dominiqueclarke we should consider where we document that users should migrate from ZIP URLs to Project Monitors with Private Locations.  Is this better in the release note or some docs?
