### ISSUE TITLE
[air-gapped] Add missing filebeat to download list

### ISSUE THREAD

**Issue by smnschneider** [elastic/observability-docs#2156]
In the documentation for `Air-gapped environments` ([air-gapped.asciidoc](https://github.com/elastic/observability-docs/blob/main/docs/en/ingest-management/fleet/air-gapped.asciidoc)) the link for Filebeat in Line 178 is missing (`curl -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{version}-linux-x86_64.tar.gz`)

**Comment by dedemorton** [comment]
My mistake! Thank you...will fix it.
