### ISSUE TITLE
[Request] Guided Onboarding 8.6: Observability guide

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-docs#2165]
## Description

We are currently planning for introducing a new guided onboarding design that is aimed at assisting the user through the steps of adding their data and exploring it in the relevant solution. The plan is currently to introduce 3 main guides (Search, Observability, and Security) by 8.6. This request is for helping finalize the copy in the already proposed flow for Observability described in the Figma file below.

The request is only for the peripheral elements that will be shown to move the user through the steps;
- Guide title and description
- Guide panel content copy: the description of the steps involved in the guide
- EuiTour components shown through the guide

## Links

- [Figma file](https://www.figma.com/file/IMmQ4KOYbIJUdeQLUTAJUV/Guided-Onboarding%3A-Observability?node-id=1407%3A195543)
- [Prototype](https://www.figma.com/proto/IMmQ4KOYbIJUdeQLUTAJUV/Guided-Onboarding%3A-Observability?page-id=1407%3A195543&node-id=1407%3A202615&viewport=142%2C752%2C0.06&scaling=min-zoom&starting-point-node-id=1407%3A202615)
- [Observability design issue](https://github.com/elastic/observability-design/issues/239)
- [Engineering epic](https://github.com/elastic/mx-team/issues/97)

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The product team will provide the initial content and the docs team will edit / review

**Contact Person:**

@formgeist or @pmeresanu85 

## Suggested Target Release

8.6

**Comment by bmorelli25** [comment]
Hey, @formgeist. Did you get the help you needed for this issue?

**Comment by formgeist** [comment]
@bmorelli25 Yes! All good, I'll close this ticket
