### ISSUE TITLE
[Request][Fleet] Document agent policy/package policy API

### ISSUE THREAD

**Issue by nchaulet** [elastic/observability-docs#2180]
## Description

We made some progress on Fleet API, to create an agent policy or a package policy, it will be a good improvments to reflect this in the guide, maybe we can have an how to guide on how to create a package policy via the API

https://github.com/elastic/kibana/pull/139658
https://github.com/elastic/kibana/pull/139045
https://github.com/elastic/kibana/pull/139420

We could document how to add an agent policy, a package policy, and retrieve the enrollment token to add agent

#### Authentication 

To make request to Kibana Fleet API user should be authenticated https://www.elastic.co/guide/en/kibana/master/api.html#api-authentication

#### Create an agent policy 

Could be done by calling `POST /api/fleet/agent_policies`

<img width="1262" alt="Screen Shot 2022-10-04 at 1 06 57 PM" src="https://user-images.githubusercontent.com/1336873/193882529-52b8f6e7-0295-45cc-8ac9-465040ea8ad4.png">

curl example 
```
curl --request POST \
  --url 'http://localhost:5601/api/fleet/agent_policies?sys_monitoring=true' \
  --header 'Accept: */*' \
  --header 'Authorization: Basic xxxxx' \
  --header 'Cache-Control: no-cache' \
  --header 'Connection: keep-alive' \
  --header 'Content-Type: application/json' \
  --header 'kbn-xsrf: xxx' \
  --data '{
  "name": "Agent policy  1",
  "description": "",
  "namespace": "default",
  "monitoring_enabled": [
    "logs",
    "metrics"
  ]
}'
```

#### Create a package policy

You need to call `POST /api/fleet/package_policies` 
User may need to go to Fleet UI and look at the API reference tab to know what inputs are available for an integration

<img width="1196" alt="Screen Shot 2022-10-04 at 1 10 57 PM" src="https://user-images.githubusercontent.com/1336873/193883197-3cda1b8b-e8d3-4bb0-a30a-76abd3da014b.png">

<img width="1251" alt="Screen Shot 2022-10-04 at 1 07 46 PM" src="https://user-images.githubusercontent.com/1336873/193882631-b3999006-5958-4239-992a-5d3f7fbe8657.png">

Example curl
```
curl --request POST \
  --url http://localhost:5601/api/fleet/package_policies \
  --header 'Authorization: Basic xxxx' \
  --header 'Content-Type: application/json' \
  --header 'kbn-xsrf: xx' \
  --data '{
  "name": "nginx-demo-123",
  "policy_id": "665303e0-434e-11ed-bc2a-95f65f653f79",
  "package": {
    "name": "nginx",
    "version": "1.5.1"
  },
  "inputs": {
    "nginx-logfile": {
      "streams": {
        "nginx.access": {
          "vars": {
            "tags": [
              "test"
            ]
          }
        },
        "nginx.error": {
          "vars": {
            "tags": [
              "test"
            ]
          }
        }
      }
    }
  }
}'
```

### Retrieve an enrollment token 

<img width="1249" alt="Screen Shot 2022-10-04 at 1 12 05 PM" src="https://user-images.githubusercontent.com/1336873/193883332-010f0463-2e86-4825-887c-bfde4c567c87.png">

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content
- The product team will provide the initial content and the docs team will edit / review
- The docs team will define with product team the structure and location, and the product team will provide the initial content
- Other (please describe)

Contact Person: @nchaulet 

## Suggested Target Release

We planned to release this for 8.5

**Comment by amitkanfer** [comment]
Hi @dedemorton @karenzone , curious to hear if we have any updates on this ticket? I see it's planned for 8.5 (as we will be releasing this feature in 8.5).
Would love your feedback.

Thanks
/cc @mukeshelastic

**Comment by dedemorton** [comment]
@amitkanfer The PR is up and ready for review here: https://github.com/elastic/observability-docs/pull/2269. It can't be merged until someone on the dev team reviews and approves it.

/cc @mukeshelastic

**Comment by amitkanfer** [comment]
Thank you @dedemorton, i should have noticed the linked PR... will make sure it's reviewed ASAP
