### ISSUE TITLE
Move fleet/agent docs to ingest-docs repo

### ISSUE THREAD

**Issue by ollyhowell** [elastic/observability-docs#2202]

**Comment by smith** [comment]
> We lose commit history. The person who moves all the files gets credit for them.

I think you can move a directory to another repo while preserving the commit history with `git-filter-branch`.

Some links with advice on how to do this:

* https://mattsch.com/2015/06/19/move-directory-from-one-repository-to-another-preserving-history/
* https://stackoverflow.com/questions/41811986/git-move-directory-to-another-repository-while-keeping-the-history
* https://tecadmin.net/how-to-move-a-directory-to-new-git-repository/

I remember having done this before and it having worked, so it might be worth a try.

**Comment by bmorelli25** [comment]
Nice! Thanks.

**Comment by bmorelli25** [comment]
I've realized that the downside of moving a single directory is that we need to do it 18 times—once for each branch that the ingest docs live in (7.8-main). I've also learned that the ingest-docs dir has dependencies on some of the shared content in the obs-docs repo. We might need to rethink this task.

**Comment by bmorelli25** [comment]
I'm not going to have time to facilitate this change for 8.7.

**Comment by bmorelli25** [comment]
This is done.
