### ISSUE TITLE
[APM] Document custom field mappings

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2206]
### Summary

Our current [index template docs](https://www.elastic.co/guide/en/apm/guide/current/custom-index-template.html#index-template-view) have room for improvement. We should explain how users can index and search on new fields by adding custom field mappings to the `@custom` index templates.

### Related

* @graphaelli's conversation with a user in our community Slack: https://elasticstack.slack.com/archives/CNKF2LEMP/p1664287860071739
* https://github.com/elastic/observability-docs/pull/2094

**Comment by dedemorton** [comment]
We really need a topic like this for the Fleet/Elastic Agent docs, too, so users know what to do if they define a processor that adds a new field.
