### ISSUE TITLE
Create and publish APM overview pages

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2209]
### Summary

We should follow Kibana's lead and create and publish updates to the [APM index pages](https://www.elastic.co/guide/en/apm/guide/current/index.html). As these pages are viewed often, they could be used to better explain how APM components work together, highlight new features, and link to common use-cases.

Here's what Kibana is building: https://github.com/elastic/kibana/pull/138051

<img width="1365" alt="Screen Shot 2022-09-29 at 3 28 01 PM" src="https://user-images.githubusercontent.com/5618806/193153309-e7c29598-74fb-4b82-86f8-6f8261a9e5a5.png">

**Comment by colleenmcginnis** [comment]
@bmorelli25 do you think this is still necessary after consolidating APM docs in the Observability guide and updating the IA? I'm going to close here for now, but feel free to reopen if there's additional work to be done here.
