### ISSUE TITLE
Update APM components diagram

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2210]
### Summary

@colleenmcginnis has recently created a very cool SVG data ingestion pipeline. By moving to an SVG we can track changes in version control and use asciidoc attributes to include versioned links. As a starting point, we should update the [components and documentation](https://www.elastic.co/guide/en/apm/guide/current/apm-components.html) diagram. Additionally, or in the future, we could add a much more detailed APM ecosystem diagram and publish it to the new APM overview page described in https://github.com/elastic/observability-docs/issues/2209.

Here's Colleen's creation for inspiration: https://github.com/elastic/cloud/pull/106505.

<img width="551" alt="Screen Shot 2022-09-29 at 3 55 35 PM" src="https://user-images.githubusercontent.com/5618806/193156384-be483896-4f83-4ec0-9600-0539a4f5f541.png">

**Comment by simranvaseer-qasource** [comment]
Hi @bmorelli25 
I have gone through this ticket and found that the diagram is available in the doc: [https://www.elastic.co/guide/en/cloud/current/ec-cloud-ingest-data.html](https://www.elastic.co/guide/en/cloud/current/ec-cloud-ingest-data.html)
Please let us know if any else validation is required.
Thanks
