### ISSUE TITLE
[DISCUSS] Should we move tutorials up in the Observability Guide navigation

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2229]
The tutorials about monitoring cloud services and K8s currently appear under a "Tutorials" container in the [Observability Guide](https://www.elastic.co/guide/en/observability/current/index.html). After talking with @ollyhowell, we might want to consider moving these tutorials to a more prominent location.

We could group them by categories at the same level as Log monitoring and Infrastructure monitoring . So we might have:

- Cloud monitoring
  - Monitor Amazon Web Services 
  - Monitor Google Cloud Platform
  - Monitor Microsoft Azure

- Container monitoring
  - Monitor Kubernetes

That would leave the Java monitoring tutorial, which I think we can put under Application performance monitoring (APM)].

Some questions, though:

* Is it weird to have tutorial style content at the same level as the more generic content we provide under categories like log monitoring? 
* Are we falling into the same trap that we set for ourselves when we moved the "quick start" to appear under "Deploy Elastic Agent to send data" as a "quick" fix? 
* Should we just leave things as they are for now because we have enough churn coming with the migration?
* Is having a "container monitoring" section misleading if we only cover K8s?
* What else have I forgotten?

**Comment by colleenmcginnis** [comment]
This sounds like a good thing to bring to the content architecture working group, too. I'm not sure if they are thinking about organizing around content types (like tutorials vs. guides vs. reference content). @bmorelli25 may know!

**Comment by bmorelli25** [comment]
> That would leave the Java monitoring tutorial, which I think we can put under Application performance monitoring (APM)].

The Java tutorial focuses on logs, metrics, and traces. I don't think APM makes sense as it's really a complete Observability tutorial.

> Is it weird to have tutorial style content at the same level as the more generic content we provide under categories like log monitoring?

In our current system, yeah, probably. But I actually really like the idea of a Cloud monitoring bucket. And while it might be slightly misleading to only have Kubernetes tutorial under "Container monitoring," I think that makes this content much easier to find.

> Should we just leave things as they are for now because we have enough churn coming with the migration?

No. We don't have a timeline. Let's keep moving forward where we can.

> This sounds like a good thing to bring to the content architecture working group, too. I'm not sure if they are thinking about organizing around content types (like tutorials vs. guides vs. reference content)

We haven't gotten to this topic yet 😅

**Comment by dedemorton** [comment]
Created a related issue here to make sure we fix the navigation regardless of where the content ends up living. https://github.com/elastic/observability-docs/issues/2251

**Comment by dedemorton** [comment]
Closing this because there is a parallel effort to add useful monitoring docs to the observability guide (in addition to the tutorials). Let's leave the tutorials where they are for now, and we can revisit this question when we evaluate the structure of the observability guide holistically.
