### ISSUE TITLE
[Request] Add info on default port assignments

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/observability-docs#2238]
Related #2178 #2009 

## Description

Figure out where to put information on default port assignments when using Fleet Server on-prem. This was included in the draft provided in #2009, but didn't make it into #2178. 

```asciidoc
== Use default port assignments

When {es} or {fleet-server} are deployed on-premises, communication between certain
components will take place over well defined, pre-allocated ports.
In most cases the operators may need to allow access to these ports.

[options,header]
|====
| Component Communication | Default Port
| Elastic Agent → {fleet-server} | 8220
| Elastic Agent → {es} | 9200
| Elastic Agent → Logstash | 5044
| Elastic Agent → {fleet} | 5601
| {fleet-server} → {fleet} | 5601
| {fleet-server} → {es} | 9200
|====
```

## Collaboration

The docs team will lead producing the content (@colleenmcginnis).

**Contact Person:** @nimarezainia

## Suggested Target Release

This is a general improvement that is not tied to a release.

## Stakeholders

@dedemorton

**Comment by nimarezainia** [comment]
@nrichers moving this to the ingest platform docs planning so it can be addressed as part of our backlog.

**Comment by nimarezainia** [comment]
@dedemorton Could this table be includes in this section: https://www.elastic.co/guide/en/fleet/master/add-a-fleet-server.html#deployed-on-prem  ??

**Comment by mdbirnstiehl** [comment]
@nimarezainia do we see this table as a prerequisite to deploying an on-premise Fleet Server? Will users need to have these ports available before they deploy an on-prem Fleet Server? If this is the case, maybe it would make sense [here](https://www.elastic.co/guide/en/fleet/master/add-fleet-server-on-prem.html#add-fleet-server-on-prem-prereq)?

**Comment by nimarezainia** [comment]
@mdbirnstiehl yes they would be prerequisites. The operator would have to open these ports for both on-prem and cloud deployments. For cloud however they are generally opened for internet access. I don't want to make this just an on-prem specific information.
