### ISSUE TITLE
[Request] Update Azure steps in the Beats tutorial about monitoring Azure

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2252]
## Description

As a follow up to https://github.com/elastic/observability-docs/pull/2174, we need to update the outdated Azure steps documented in the Beats tutorial.  The steps and UI have changed since that document was written.

## Collaboration

- The docs team will lead producing the content

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:**

## Suggested Target Release

n/a

## Stakeholders

n/a

**Comment by dedemorton** [comment]
@alaudazzi Can I close this? I'm not sure if it's still relevant.

**Comment by alaudazzi** [comment]
@dedemorton let's close it 👍
