### ISSUE TITLE
[Request] Please add a method installing fleet without an internet connection

### ISSUE THREAD

**Issue by hisashinz** [elastic/observability-docs#2254]
## Description

*(Describe what needs to be documented. Link to relevant issues.)*

Please add a method for installing fleet without an internet connection to https://www.elastic.co/guide/en/observability/7.17/ingest-logs-metrics-uptime.html ?

The document mentions as follows.
> An internet connection is required for Kibana to download integration packages from the Elastic Package Registry. Make sure the Kibana server can connect to https://epr.elastic.co on port 443.

Please add an explanation to install without an internet connection.

I had a customer who asked to know a way to install it without an internet connection(Air gapped) and actually, it is possible.

https://www.elastic.co/guide/en/fleet/current/air-gapped.html

https://elastic.slack.com/archives/CNMNXV4RG/p1665031624728619

## Collaboration
*(Choose the expected collaboration model and delete the others.)* 

- The docs team will lead producing the content
- The product team will provide the initial content and the docs team will edit / review
- The docs team will define with product team the structure and location, and the product team will provide the initial content
- Other (please describe)

*(Assign a contact person for this issue. We need to have a contact person in the product/development team to provide information about how the item to be documented works. This can be omitted when the product/development team is providing the initial content, as the contact person will be the one making the initial contribution.)*

**Contact Person:**

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*

## Stakeholders

*(Please list any stakeholders for this issue.)*

**Comment by dedemorton** [comment]
@hisashinz Good news. Looks like we do provide a link in the 8.5 docs. Would you like us to update the 7.17 docs, too?

![image](https://user-images.githubusercontent.com/14206422/197078219-97fd4425-d153-45cc-8989-7a870544b600.png)

**Comment by dedemorton** [comment]
Closing because the 8.5 docs already mention the air-gapped instructions. Please reopen the issue if you feel strongly that this info should be in the 7.17 docs. Thanks!
