### ISSUE TITLE
[Synthetics] Add docs for data security for Synthetics

### ISSUE THREAD

**Issue by andrewvc** [elastic/observability-docs#2266]
It'd be helpful to have a page listing the data security properties of the synthetics service, similar to [this](https://docs.datadoghq.com/data_security/synthetics/) possibly.

This will need to be completed by an engineer on the synthetics team.

Also include Private Locations (related: https://github.com/elastic/synthetics-dev/issues/207)

**Comment by paulb-elastic** [comment]
I'd suggest this can be pushed back, to 8.8

**Comment by bmorelli25** [comment]
> This will need to be completed by an engineer on the synthetics team.

Who is the best point of contact?

**Comment by paulb-elastic** [comment]
I would suggest either @andrewvc or @vigneshshanmugam

**Comment by colleenmcginnis** [comment]
@andrewvc @vigneshshanmugam would one of you be interested in collaborating on this for the 8.8 release or should we push this out past 8.8?

**Comment by paulb-elastic** [comment]
Just adding my thoughts - with some other features and docs updates more pressing for the 8.8 release, I'd suggest this can be done after the launch

**Comment by paulb-elastic** [comment]
Updated the title / description to include Private Locations
