### ISSUE TITLE
Fix bug => broken links in the integrations documentation

### ISSUE THREAD

**Issue by laraMorenoIgle** [elastic/observability-docs#2299]
There are several pages in the integration documentation that has a link to [Ingest Node Pipeline UI](https://docs.elastic.co/app/management/ingest/ingest_pipelines/), and, as you can see, the link is broken.
It was working fine at the beginning of this week, if I am not wrong. 

These are all the pages that have such a link:
<img width="681" alt="Screenshot 2022-10-28 at 09 43 20" src="https://user-images.githubusercontent.com/49395637/198532850-9d1faaf7-9f1f-406b-9751-bd39eaf36614.png">

For instance, go to [AWS Custom Logs page](https://docs.elastic.co/integrations/aws_logs), search for `Ingest Node Pipeline UI` , click on the link and you will be redirected to:
<img width="1485" alt="Screenshot 2022-10-28 at 09 51 55" src="https://user-images.githubusercontent.com/49395637/198534038-30279d7f-bcdd-400b-8114-f1bff333d5ac.png">

Please, could you help to amend it?

**Comment by colleenmcginnis** [comment]
Thanks @laraMorenoIgle!

We use the integration docs source files in a few places so the reader will be able to read the same content:

1. In GitHub
2. In Kibana's Integrations UI
3. In the Integration docs on [docs.elastic.co](https://docs.elastic.co/integrations)

It looks like these links are assuming the reader is viewing the integration _in Kibana_ so they are using relative links (`/app/management/ingest/ingest_pipelines/`) to the page in the Kibana UI.

I wonder if there's a way to use different links in different environments (GitHub, Kibana, and docs.elastic.co). Although, in this case we would have to find an _alternative_ page (probably something in `www.elastic.co/guides/*`). Maybe @bmorelli25 has some ideas. 👀

**Comment by bmorelli25** [comment]
> I wonder if there's a way to use different links in different environments (GitHub, Kibana, and docs.elastic.co)

I'm not too worried about links working in GitHub. But for Kibana and docs.elastic, this is the only thing I can think of:

1. keep the current Kibana (`/app/...`) link in the integrations repo readmes
2. Update `integrations-exporter` script to check for `/app/*` and if found, update to a documentation link

The downside of this approach is that we'd have to manually maintain a list of all `/app/` links in the wordlake repo. There are currently six instances of linking to a Kibana app, all of which are to the Ingest Pipelines page.

I'd probably vote to change all of the links to documentation links.

**Comment by bmorelli25** [comment]
All of the broken links are in `custom` packages. We should probably clean up the text while we're in there. Some of them could really use a rewrite:

> The custom UDP Log package intializes a listening UDP socket that collects any UDP traffic received and sends each line as a document to Elasticsearch. Custom ingest pipelines may be added by adding the name to the pipeline configuration option, creating custom ingest pipelines can be done either through the API or the [Ingest Node Pipeline UI(opens in a new tab or window)](https://dev-oblt.elastic.dev/app/management/ingest/ingest_pipelines/).
