### ISSUE TITLE
[REQUEST]: Add Kubernetes screencast to the documentation

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2304]
### Description

@marclop is working on a Kubernetes attacher screencast. @bmorelli25 will upload the video to Vidyard and add it to our documentation.

### Resources

I can't find any existing issues for this.

### Collaboration

Other (please describe below in the Point of contact section).

### Point of contact.

**Main contact:** @marclop 

**Stakeholders:**

**Comment by bmorelli25** [comment]
@marclop I couldn't find any existing issues for this. I assigned you, but feel free to remove the assignment if this goes against how your team works.

**Comment by bmorelli25** [comment]
@marclop is there a status update on this issue? Are you still planning on creating a screencast?

**Comment by marclop** [comment]
@bmorelli25 we've currently de-prioritized this ask in favor of more pressing ones. I don't have a time estimate for when this will get tackled. @simitt Do we know when we're looking to work on this again?

**Comment by bmorelli25** [comment]
No problem. I don't need an updated timeline—I just wanted to make sure I didn't miss the video.

**Comment by simitt** [comment]
@marclop how much time would it require for you to incorporate the feedback from the initical screencast and have it ready to be uploaded? If it is something like 3-4 hours, then feel free to re-record when you find some time.

**Comment by colleenmcginnis** [comment]
@bmorelli25 is this still relevant?

**Comment by bmorelli25** [comment]
Please reopen if still relevant, Sivila/Marc.
