### ISSUE TITLE
[Fleet]: Text is missing between 'the' and 'it' on 'Create a Standalone Elastic Agent policy' Doc

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/observability-docs#2311]
**Description:**

- Text is missing between `the` and `it` on `Create a Standalone Elastic Agent policy` Doc.

**Link:**

- https://www.elastic.co/guide/en/fleet/current/elastic-agent-configuration.html
- https://www.elastic.co/guide/en/fleet/current/create-standalone-agent-policy.html

**Screen Recording:**

https://user-images.githubusercontent.com/97870262/199665007-462e2767-dff1-4be6-9271-d97ae7bf0f4d.mp4

![image](https://user-images.githubusercontent.com/97870262/199665042-ec309f2f-0c0b-4713-b469-a2e87fb07b14.png)

**Comment by amolnater-qasource** [comment]
Reviewed & mention to @dedemorton

**Comment by prachigupta-qasource** [comment]
Hi @dedemorton,

We have revalidated the reported doc at link:

- https://www.elastic.co/guide/en/fleet/current/elastic-agent-configuration.html
- https://www.elastic.co/guide/en/fleet/current/create-standalone-agent-policy.html

We have observed that the issue is fixed now.

- Text is not missing on `Create a Standalone Elastic Agent policy` Doc.

**Screenshot:**

![image](https://user-images.githubusercontent.com/97870262/200227879-478c8b75-9e43-4e72-b736-05d18ed13cae.png)

Hence, marking this as QA: Validated.

Thanks!
