### ISSUE TITLE
[REQUEST]: Document new Opsgenie Connector

### ISSUE THREAD

**Issue by ollyhowell** [elastic/observability-docs#2338]
### Description

Request from @emma-raffenne to document new Opsgenie connector as per https://github.com/elastic/kibana/issues/142776

### Resources

https://github.com/elastic/kibana/issues/142776

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @XavierM 

**Stakeholders:** @emma-raffenne

**Comment by lcawl** [comment]
In case it's helpful to see the docs added to the Kibana Guide, I'm tracking updates in https://github.com/elastic/kibana/issues/145198

**Comment by mdbirnstiehl** [comment]
Docs are already updated to include OpsGenie connector.
