### ISSUE TITLE
[REQUEST]: APM agent direct logs

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2362]
### Description

Document APM agents sending logs directly to APM Server.

### Resources

* https://github.com/elastic/apm-server/issues/8757
* https://github.com/elastic/apm-agent-java/pull/2694

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @SylvainJuge 

**Stakeholders:** @felixbarny

**Comment by felixbarny** [comment]
As there are multiple ways to send logs now (Filebeat, Elastic Agent, APM Agents), we should give an overview of the options, their tradeoffs, and provide guidance on when to use which option.

Also, in it's current form, the APM Agents option has a few caveats that should be documented. For example, custom fields aren't supported and a high rate in logs may result in transactions and metrics to be dropped.

**Comment by bmorelli25** [comment]
Step one complete in https://github.com/elastic/observability-docs/pull/2452. A list of follow-up updates is in the [description](https://github.com/elastic/observability-docs/pull/2452#issue-1495683761).

**Comment by SylvainJuge** [comment]
@bmorelli25 the support for direct logs sending has been merged for Java APM agent (thus about to be released soon). Is there anything I could contribute here to move this forward ?

**Comment by bmorelli25** [comment]
Thanks for the nudge, @SylvainJuge :)

I've opened https://github.com/elastic/observability-docs/pull/2542 and https://github.com/elastic/ecs-logging/pull/72 to address the follow-ups.

The only thing left is to update links to the Java agent docs after they are live. I didn't have time today to open a draft PR for that, but I will tomorrow.

**Comment by felixbarny** [comment]
I think we should also link to the Java agent docs for directly sending logs from the [ecs-logging-java docs](https://www.elastic.co/guide/en/ecs-logging/java/current/setup.html)

**Comment by bmorelli25** [comment]
Everything is done except for links to the Java agent docs from the logs guide and the ECS logging book. Please leave a comment here when direct logs has been released, and I'll publish those last two links.

**Comment by SylvainJuge** [comment]
@bmorelli25 the Java agent 1.36.0 was just released a few minutes ago, thus log sending is now official.

**Comment by bmorelli25** [comment]
All done 🚢
