### ISSUE TITLE
[REQUEST]: Document all lightweight monitor configuration options

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/observability-docs#2372]
### Description

_Note: I'm opening this targeting 8.7, but it could happen sooner._

We should document all lightweight monitor configuration options in [Uptime and synthetic monitoring](https://www.elastic.co/guide/en/observability/current/monitor-uptime-synthetics.html) section.

From @andrewvc in https://github.com/elastic/observability-docs/pull/2353: 

>I think it's probably best to just make a wholesale copy of everything under ["Monitors" from the beats docs](https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html) here.

>I was actually thinking we could eventually copy over the individual pages for [`HTTP`](https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-http-options.html) [`TCP`](https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-tcp-options.html) and [`ICMP`](https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-icmp-options.html).
>
>If you're using a project based lightweight monitor it doesn't make sense to have to go to the heartbeat docs, ideally you don't even know what heartbeat is.

We should also add information on [Common monitor options](https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-options.html).

**To do**

- [ ] Copy over content from Heartbeat
- [ ] Edit to remove Beats-specific reference in favor of Projects
- [ ] Decide what if anything to do with the original Heartbeat docs (do we want duplicate content? how can we best manage this situation?)

### Resources

* **Related PR**: https://github.com/elastic/observability-docs/pull/2353
* **Existing docs**: [Monitors](https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html)

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @colleenmcginnis

**Stakeholders:** @andrewvc @paulb-elastic

**Comment by colleenmcginnis** [comment]
@andrewvc @paulb-elastic is there a good place for me to see a full list of supported config options for lightweight monitors in projects?

**Comment by andrewvc** [comment]
@colleenmcginnis , unfortunately not at the moment. I propose we copy all the configuration options over wholesale then have an engineer, perhaps @dominiqueclarke or @awahab07 review it for accuracy.

**Comment by paulb-elastic** [comment]
@andrewvc do we get params implemented automatically based on how Project Monitors work, except in certain circumstances (as opposed to the other way round, where we get none unless we add them in)?

e.g. we had someone try to use `check.response.body` recently but it does not work (because it's an alias).

I created https://github.com/elastic/synthetics-dev/issues/159 as a meta for some specifics and https://github.com/elastic/synthetics/issues/655 to track everything else needed for Lightweight Project Monitors.

**Comment by colleenmcginnis** [comment]
>I propose we copy all the configuration options over wholesale then have an engineer, perhaps @dominiqueclarke or @awahab07 review it for accuracy.

Can someone take a look at the tables of options below? Which are supported in projects? Are there any options that are missing? Are the types, default values, and required status correct for each option?

Feel free to edit the tables directly!

## Common options

| Supported? | Option | | Type | Default | Required |
|:---:|---|---|---|---|---|
| ✓ | `type` | | `"http"`\|`"icmp"`\|`"tcp"` | | Required |
| ✓ | `id` | | String | | Required |
| ✓ | `name` | | String | | |
|   | `service.name` | | String | | |
|   | `enabled` | | Boolean | `true` | |
|   | `schedule` | | Duration | | Required |
|   | `ipv4` | | Boolean | `true` | |
|   | `ipv6` | | Boolean | `true` | |
|   | `mode` | | `"any"`\|`"all"` | `any` | |
|   | `timeout` | | Duration | `16s` | |
|   | `run_from` | `id` | String | | |
|   | | `geo` | ECS geo fields | | |
|   | `fields` | | ? | | |
|   | `fields_under_root` | | Boolean | | |
|   | `tags` | | List of strings | | |
|   | `processors` | | List of strings | | |
|   | `data_stream` | | String | `heartbeat-VERSION` | |
|   | `pipeline` | | String | | |
|   | `keep_null` | | Boolean | `false` | |


## ICMP only options

| Supported? | Option | Type | Default | Required |
|:---:|---|---|---|---|
| ✓ | `hosts` | List of strings | | Required |
|   | `wait` | Duration | `1s` | |

## HTTP only options

| Supported? | Option | | | | Type | Default | Required |
|:---:|---|---|---|---|---|---|---|
| ✓ | `hosts` | | | | List of strings | | Required |
|   | `max_redirects` | | | | Number | `0` | |
|   | `proxy_url` | | | | String | | |
|   | `proxy_headers` | | | | ? | | |
|   | `username` | | | | String | | |
|   | `password` | | | | String | | |
|   | `ssl` | | | | SSL | | |
|   | `headers` | | | | Boolean | `true` | |
|   | `response` | `include_body` | | | `"on_error"`\|`"never"`\|`"always"` | | |
|   | | `include_body_max_bytes` | | | Number | `1024` | |
|   | `check` | `request` | `method` | | `"HEAD"`\|`"GET"`\|`"POST"`\|`"OPTIONS"` | | |
|   | | | `headers` | | ? | | |
|   | | | `body` | | String | | |
|   | | `response` | `status` | | List of strings | | |
|   | | | `headers` | | List of strings | | |
|   | | | `body` | | Regex \| List of regex | | |
|   | | | | `positive` | List of regex | | |
|   | | | | `negative` | List of regex | | |
|   | | | `json` | | List of ? | | |
|   | | | | `description` | String | | |
|   | | | | `expression` | gval expression | | |
|   | | | | `condition` | jsonpath condition | | |

## TCP only options

| Supported? | Option | | Type | Default | Required |
|:---:|---|---|---|---|---|
| ✓ | `hosts` | | List of strings | | Required |
|   | `ports` | | List of strings | | |
|   | `check` | `send` | String | | |
|   | | `receive` | String | | |
|   | `proxy_url` | | String | | |
|   | `proxy_use_local_resolver` | | Boolean | `false` | |
|   | `ssl` | | SSL | | |

**Comment by paulb-elastic** [comment]
cc @vigneshshanmugam too as these relate to project monitors
