### ISSUE TITLE
[REQUEST]: Adding ServiceNow ITOM doc link to the Configure External Connectors Page

### ISSUE THREAD

**Issue by SubhrataK** [elastic/observability-docs#2381]
### Description

The following page which describes the steps to configure the external connectors for sending the cases to the third party systems:
https://www.elastic.co/guide/en/observability/current/cases-external-connectors.html
is missing the link to ServiceNow ITOM connector here: https://www.elastic.co/guide/en/kibana/current/servicenow-itom-action-type.html

Kindly add the same to the list of connectors here:

<img width="416" alt="Screenshot 2022-11-18 at 10 56 43 AM" src="https://user-images.githubusercontent.com/115459202/202627346-6626f74d-174f-44a6-86aa-5d4bb36a7334.png">

And a link under Create a Connector section -> Step no.4

<img width="824" alt="Screenshot 2022-11-18 at 10 58 21 AM" src="https://user-images.githubusercontent.com/115459202/202627521-712fbdf0-9703-46f7-b529-2dec2e88fbce.png">

### Resources

https://elastic.slack.com/archives/C02FQULS9PX/p1668661154500179

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @SubhrataK 

**Stakeholders:** @amena

**Comment by dedemorton** [comment]
Closing because the docs were updated, but this issue was never closed.
