### ISSUE TITLE
[REQUEST]: Document known issue in Fleet Server 8.5.1

### ISSUE THREAD

**Issue by juliaElastic** [elastic/observability-docs#2383]
### Description

We discovered an issue in Fleet Server 8.5.1 that prevents offline agents to be unenrolled after unenrollment timeout.
This results Offline agents to stay indefinitely in Fleet Agent list, and not moved to Inactive state.
The fix is raised in a pr, can be included in 8.5.3.

### Resources

https://github.com/elastic/fleet-server/issues/2091

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @juliaElastic 

**Stakeholders:** @joshdover @elastic/fleet

**Comment by dedemorton** [comment]
@juliaElastic What is the recommended workaround for this problem? Should/can users force remove the offline agents from the list?

**Comment by juliaElastic** [comment]
@dedemorton Yes, they should force unenroll those agents.

**Comment by joshdover** [comment]
@juliaElastic can you provide the API call for this?

**Comment by dedemorton** [comment]
@juliaElastic Actually...just review the content that I've added [here](https://github.com/elastic/observability-docs/pull/2392), including the API call. Thanks!
