### ISSUE TITLE
[REQUEST]: Add processor reference for Agent

### ISSUE THREAD

**Issue by gizas** [elastic/observability-docs#2384]
### What documentation page is affected

We could not find a single reference for processors under agent. 

https://www.elastic.co/guide/en/fleet/master/dynamic-input-configuration.html
In this page processors are used with no reference or explanation.

### What change would you like to see?

We would like to guide our customers to use processors under Elastic Agent standalone scenarios. 
 a relevant link should exist under Elastic Agent like the one we have for eg. for filebeat https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html

The goal would be to describe and help users understand the difference between providers and processors and help them make use in specific agent configurations. 

Probably the list of Processors from Filebeat needs to be adjusted and updated as some processors might not used at the moment

### Additional info

Goal is users not to go under Filebeat or Metricbeat links to read for processors but remain under Agent category and keep reading relevant information and examples. Is confusing to try to explain terms of Agent by giving examples from beats

**Comment by dedemorton** [comment]
I already have a PR in progress that adds processors to the Elastic Agent documentation:
https://github.com/elastic/observability-docs/pull/500

There's also an issue open here with a todo list that shows my progress:
https://github.com/elastic/observability-docs/issues/1376

@gizas Can you please close your issue as a duplicate and add any requests you have to the existing issue?

Also regarding your statement
>Probably the list of Processors from Filebeat needs to be adjusted and updated as some processors might not used at the moment

I really need more input from the development team about which processors to document. The direction I'm getting from the PM team is to document them all, but I'm not sure whether that's the right move. It would be great if someone on your team could go through the list in this comment and provide input: https://github.com/elastic/observability-docs/pull/500#issue-853619712

**Comment by gizas** [comment]
Closing as duplicate

**Comment by gizas** [comment]
Duplicate issue

**Comment by dedemorton** [comment]
@gizas BTW, the [PR that adds the processors documentation](https://github.com/elastic/observability-docs/pull/500) to Elastic Agent is up for review. I would really appreciate any feedback you have, especially related to processors that affect cloud native monitoring. I am not familiar enough with the use cases to understand whether users will actually need to configure processors like add_kubernetes_metadata.

There was a lot of conditional coding in the beats files that I wasn't sure how to handle, so the docs will definitely need work. But before I put in more time, I want to check with the team.
