### ISSUE TITLE
[Synthetics] Document new Synthetics UI and user flows

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2401]
### Description

The new Synthetics UI has created a completely new set of reports, capabilities and UX for making the most of Synthetic tests (particularly browser based tests).

https://github.com/elastic/observability-docs/issues/2549 is the initial requirement for documenting the basics (and won’t be done until we’ve [enabled the UI by default](https://github.com/elastic/kibana/issues/148969)).  After this is done, we can begin documenting these new flows.

This will likely take time, and doesn’t need to be done or ready for a particular stack release, but maybe worked on and released as the documentation becomes ready for each section as it’s done, once https://github.com/elastic/kibana/issues/148969 has been released.

This will require collaboration with the team, especially D who can help position the use cases and main expected flows through the application.

### Resources

The Synthetics UI has become much more capable in 8.7, but there are a lot of issues/PRs, it would not be useful to list them here.

We should collaborate on which flows, features and reports we want to document.

⚠️  We must be sure to include in the docs that the Synthetics UI does not support cross cluster search (CCS)

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @drewpost  

**Stakeholders:**
@drewpost @paulb-elastic @andrewvc

**Comment by paulb-elastic** [comment]
Updated the description as this was raised a little while ago.

@drewpost we'll need help from you to work with the docs team to plan out what we want documented and maybe a priority order for them to work from.

**Comment by drewpost** [comment]
Oh yes. This is going to be lots of fun. I'll coordinate.
