### ISSUE TITLE
[Fleet] update 'Agent upgrade' (on the edge host) steps 

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#245]
from this doc:
https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/docs/upgrade-elastic-agent.asciidoc#upgrade-standalone-agents

we need to update the steps to cite:
call the Agent from the directory where it was installed in Windows or as the service executable as in:
elastic-agent upgrade {version}

e.g. C:\Program Files\Elastic\Agent\elastic-agent.exe upgrade 7.10.1
e.g. elastic-agent upgrade 8.0.0-SNAPSHOT

of course, we'll want to test this out to be sure it works.

**Comment by EricDavisX** [comment]
@ph @dedemorton fyi

**Comment by dedemorton** [comment]
This was closed in elastic/beats#22701
