### ISSUE TITLE
[REQUEST]: Fix Fleet supported outputs table

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/observability-docs#2458]
### Description

The page https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html#supported-outputs-beats-and-agent contains a "feature" table regarding supported outputs by Beats, Fleet-Agent & Standalone Agent.

We should probably add a `*` on all the outputs except Elasticsearch to highlight the fact APM Integration ONLY supports Elasticsearch output.
In the current state, users might be misled into thinking APM Integration can be used with any supported output type.

Final users will realize they cannot use Logstash output only when creating the policy and trying to add the APM Integration - which will be denied.

### Resources

This is derived from https://github.com/elastic/apm-server/issues/7025#issuecomment-1031785020, the docs https://www.elastic.co/guide/en/apm/guide/current/upgrade-to-apm-integration.html#apm-integration-upgrade-limitations and an internal discussion with the APM team

This should go in couple with https://github.com/elastic/apm-server/issues/9848

### Collaboration

Other (please describe below in the Point of contact section).

### Point of contact.

**Main contact:** @simitt 

**Stakeholders:** @lucabelluccini 

Obviously feel free to add/remove anyone

**Comment by dedemorton** [comment]
Looks like this was closed by https://github.com/elastic/observability-docs/pull/2491
