### ISSUE TITLE
[REQUEST]: Create documentation on SLO functionality 

### ISSUE THREAD

**Issue by CoenWarmer** [elastic/observability-docs#2460]
## Description

Documentation on our newly created SLO functionality.

We are currently in the process of creating our first iteration of SLO (Service Level Objective) / SLI (Service Level Indicator) functionality. The aim is to release this in version 8.7.0 behind a feature flag (no GA yet).

It would be good to provide documentation for our users for this functionality.
Documentation should include details about:
- The supported indicator types
- The different budgeting methods used for defining an SLO
- The different time windows used for defining an SLO
- Examples of SLO definition for each indicator type

## Resources

**Designs:**
* https://www.figma.com/file/91R0OtRZHy5xvaE8dGStBo/SLO%2FSLI-assets?node-id=18%3A5&t=fIwzn49oqNAuD60P-1

**Features planned for 8.7.0 (first iteration)**
* https://elastic.slack.com/archives/C044PV8EJ4X/p1670947077450789?thread_ts=1670940094.030689&cid=C044PV8EJ4X

**Documentation**
* RFC: https://docs.google.com/document/d/1ETUpHonf4nbJIuwufRv2O43qIQfx7LnSLh4_u8ZO84Q/edit?usp=sharing

**Meetings / Presentations**
* https://docs.google.com/document/d/1UpqbmMWn6g54Ma0-i5RBx9Grxq92TPPFFqWKqQqTvPo/edit
* https://docs.google.com/presentation/d/10vGURCPPPwkZVDfpLWAexghYl1pSU5Rt_sQzHPRa2S0/edit?usp=share_link

**Ticket on AO board**
* https://github.com/elastic/kibana/issues/147749

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:**

@kdelemme & @CoenWarmer 

**Stakeholders:**

@vinaychandrasekhar @simianhacker @emma-raffenne @grabowskit

**Comment by bmorelli25** [comment]
@mdbirnstiehl can you look into this and see if it's a duplicate?

**Comment by mdbirnstiehl** [comment]
I believe we have covered this with the 8.8 release. Let me know if we need to reopen this issue.
