### ISSUE TITLE
[REQUEST]: SLO burn rate rule

### ISSUE THREAD

**Issue by kdelemme** [elastic/observability-docs#2461]
### Description

A new rule has been created for SLOs. This is behind a feature flag, and won't be GA in 8.7

We need to document the rule parameters and how they are used to trigger or recover an alert.

![](https://user-images.githubusercontent.com/1376800/208472557-352e6cba-07a3-4c55-833e-dd26b3158d7d.png)

### Resources

Frontend PR: https://github.com/elastic/kibana/pull/147557

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @kdelemme

**Stakeholders:** @vinaychandrasekhar @grabowskit @emma-raffenne @simianhacker @CoenWarmer 

Track by https://github.com/elastic/kibana/issues/147860

**Comment by kdelemme** [comment]
@ollyhowell Any updates on this? Do you need us to start a draft?

**Comment by kdelemme** [comment]
@mdbirnstiehl @ollyhowell Do you happen to know the link? So I can update the UI to include the link of the documentation for this new rule type. Thanks!

**Comment by mdbirnstiehl** [comment]
@kdelemme let's make it https://www.elastic.co/guide/en/observability/current/slo-burn-rate-alert.html
