### ISSUE TITLE
[Fleet] Add a clear statement about the "max" number of policies

### ISSUE THREAD

**Issue by jlind23** [elastic/observability-docs#2488]
Following some experimentations we did while scale testing fleet, we discovered that a high number of policy has a non neglectable impact on fleet performances overall.

Thus we should state in fleet docs that above 500 policies there are known performance limitations.

cc @nimarezainia @joshdover

**Comment by jlind23** [comment]
@nimarezainia are you able to take a stab at this or should we ask someone from the docs team?

**Comment by nimarezainia** [comment]
@jlind23 I would usually if we know where it should go :-(    
@dedemorton any idea where in the docs this could be added?

**Comment by dedemorton** [comment]
@nimarezainia You definitely want to mention it here somewhere: https://www.elastic.co/guide/en/fleet/current/agent-policy.html

And maybe add a troubleshooting section that describes the problem and how to work around the limitation: https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html

**Comment by nimarezainia** [comment]
@dedemorton there a PR coming your way. I wasn't able to test it (didn't give me a preview). It's simple so I just copied the format from the same document.
