### ISSUE TITLE
Endpoint Security old name showing instead of Elastic Defend

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/observability-docs#2493]
**Description**
Endpoint Security old name showing instead of Elastic Defend

**URL link**

- https://www.elastic.co/guide/en/fleet/8.6/fleet-overview.html
- https://www.elastic.co/guide/en/fleet/master/fleet-overview.html#unified-integrations

**Screen-Shot**

- Actual result

![image](https://user-images.githubusercontent.com/59917825/211751869-39458339-504f-43cf-82ac-8e5c1475253f.png)

- Expected result

![image](https://user-images.githubusercontent.com/59917825/211751896-7c624e7b-b67b-4b36-a905-b913e32c7d3e.png)

**Comment by karanbirsingh-qasource** [comment]
@amolnater-qasource please review

**Comment by amolnater-qasource** [comment]
Reviewed and mentioned to @dedemorton
