### ISSUE TITLE
[REQUEST]: The new Inativity Timeout needs to be documented

### ISSUE THREAD

**Issue by nimarezainia** [elastic/observability-docs#2543]
### Description

8.7 brings in a new feature: https://github.com/elastic/kibana/issues/143455

I have created the documentation for this feature:

https://docs.google.com/document/d/1sWXzljzvuIccpreHou-xD7STo6nSpy6vWhDVzdVI6jw/edit?usp=sharing

### Resources

https://docs.google.com/document/d/1sWXzljzvuIccpreHou-xD7STo6nSpy6vWhDVzdVI6jw/edit?usp=sharing

### Collaboration

The product team will provide the initial content.

### Point of contact.

**Main contact:** @nimarezainia 

**Stakeholders:**
@kylepol

**Comment by nimarezainia** [comment]
@dedemorton all the data is in the document attached. I placed this on the radar column but needs to be prioritized for 8.7

**Comment by dedemorton** [comment]
@nimarezainia Might be better to add your details (and link) to the existing issue here: https://github.com/elastic/observability-docs/issues/2352. Otherwise feels like we are double tracking....

**Comment by nimarezainia** [comment]
@dedemorton i can't add the doc which is private to elastic to a public issue. Well technically I can but will point the reader to something they can't access.

**Comment by dedemorton** [comment]
Yah I understand. The duplicate issues become kind of confusing though. I've started adding the link and just explaining that it's internal only. I don't know if there is a company wide standard for how to do this, but double tracking just seems inefficient and error-prone.

**Comment by bmorelli25** [comment]
Closing this as it looks to be done.
