### ISSUE TITLE
[REQUEST]: Add decode_duration processor docs to Fleet/Agent Guide

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2545]
### Description

The `decode_duration` and `move_fields` processors were added to Beats in 8.6 and need to be added to the[ processors section](https://www.elastic.co/guide/en/fleet/current/elastic-agent-processor-configuration.html) of the Fleet and Elastic Agent Guide.  

The docs need to follow the same format and style as the other processor docs (which have been edited and re-formatted).

### Resources

Related PR: https://github.com/elastic/beats/pull/31301

Source file for decode_duration docs: https://github.com/elastic/beats/blob/main/libbeat/processors/decode_duration/docs/decode_duration.asciidoc

Source file for move_fields docs: https://github.com/elastic/beats/blob/main/libbeat/processors/move_fields/docs/move_fields.asciidoc

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** 
TBD

**Comment by bmorelli25** [comment]
@dedemorton please add link to Beats source file for Mike
