### ISSUE TITLE
[Synthetics] Update existing docs to show Synthetics UI instead of Uptime Monitor Management

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2549]
### Description

Depends on https://github.com/elastic/kibana/issues/148969

With the enabling of the Synthetics UI by default (once the [PR](https://github.com/elastic/kibana/pull/149115) is merged), we should update the existing documentation to reflect setting up and managing monitors by using the Synthetics UI instead of Uptime Monitor Management (which was always a temporary UI whilst the Synthetics UI was being built).

Once we have a confirmed docs location, we should revisit https://github.com/elastic/kibana/issues/146046 (⚠️ please let us know when this URL is confirmed, so we can work on it).

In addition, the [migration page](https://www.elastic.co/guide/en/observability/current/synthetics-migrate-from-integration.html) should be updated to refer to the Synthetics UI.

### Resources

The Synthetics UI has been around for several stack releases albeit behind a feature flag (which we haven’t advertised).  It’s not useful linking the issues/PRs here, but to refer to the Synthetics UI `Management` page.

![image](https://user-images.githubusercontent.com/70908889/214657471-52741e78-4b80-4e03-b6e5-e347abcf2850.png)

In addition, when there are no monitors configured, the default empty state for Synthetics UI is much better than Uptime, where we have an very simple form for setting up the first monitor, that we should include in the docs.

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @paulb-elastic 

**Stakeholders:**
@drewpost @paulb-elastic

**Comment by paulb-elastic** [comment]
@colleenmcginnis do you know what the URL will be for the docs for the new empty state for Synthetics UI?  We'd like to include a link back to it in https://github.com/elastic/kibana/issues/146046 into 8.7.

We can always use a placeholder URL for now if not, just wondered if you already know what this will be?

**Comment by paulb-elastic** [comment]
Added a reminder to include the https://www.elastic.co/guide/en/observability/current/synthetics-migrate-from-integration.html page (to refer to the Synthetics UI)

**Comment by colleenmcginnis** [comment]
>just wondered if you already know what this will be?

I don't know yet.
