### ISSUE TITLE
[Synthetics] Document how to control the number of concurrent browser runs a Private Location can run

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2550]
### Description

https://github.com/elastic/beats/issues/34290 will be implementing the ability to control how many browser tests can run in parallel with Elastic Agent running as a Private Location.

The current behaviour (as [documented](https://www.elastic.co/guide/en/observability/master/synthetics-private-location.html#synthetics-private-location-fleet-agent)), is that this is fixed at 2 (and cannot be overridden).  https://github.com/elastic/beats/issues/34290 adds this capability.

We should add some advice as to sensible limits, and setting this too high could end up having CPU and/or memory contention that introduces performance variability, or even stops tests running at all.

### Resources

The new implementation allows this to be configured via environment variables, read when the Elastic Agent is started up (i.e. it cannot be changed on the fly).  More details are shown in the [PR](https://github.com/elastic/beats/pull/34307).

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @andrewvc 

**Stakeholders:**
@andrewvc @paulb-elastic

**Comment by colleenmcginnis** [comment]
@paulb-elastic is this covered by @andrewvc's https://github.com/elastic/observability-docs/pull/2582 or is there other information to be added?

**Comment by andrewvc** [comment]
Apologies for not linking the two, yes this covers that. I've added the right "fixes" comment to the PR, so it will auto-close this when merged.
