### ISSUE TITLE
[REQUEST]: Define structure and template for monitoring docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2555]
### Description

As part of the effort to develop AWS services monitoring documentation (see https://github.com/elastic/observability-docs/issues/2562), we want to develop an asciidoc template that developers can use to get started.

The content in these guides will:

* Introduce and describe of the service
* Show an image of our dashboard
* Describe the set of metrics that are key from monitoring perspective for this service
* Explain why those metrics are key and how the current integration gathers and visualizes that data in the dashboard
* Describe how users can extend the dashboard for more use cases as needed
* Link to integration, Agent, log monitoring etc. relevant documents for more details

```[tasklist]
- [x] Come up with an initial topic structure for the MVP
- [x] Publish the existing 4 documents (EBS, S3, Kinesis, and SQS)
- [ ] Get some initial data from google analytics (page views, time on page, etc)
- [ ] Get feedback from internal users on structure, usability, etc of the new content
- [ ] Improve the content structure based on the data we collect
```

### Initial outline (draft)

Intro
Get started*
Dashboards
Metrics to watch
Related resources

*May include a mini "quick guide" about adding data (see [this](https://github.com/elastic/observability-docs/issues/2555#issuecomment-1426487433) proposal).

### Resources

Related issue: https://github.com/elastic/obs-infraobs-team/issues/824 (link is for internal folks only)

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @dedemorton 

**Stakeholders:** @sacc

**Comment by dedemorton** [comment]
**Question:** Should we Include data ingestion steps in these guides?

**What problem would this solve?** The user experience for data oboarding/ingestion when using our docs is not great.  In the integrations documentation and elsewhere, we send users to tutorial-style guides that don't address the specific type of service they're monitoring. Sometimes users need to make multiple hops to find information that doesn't address their specific use case.

**Proposal:** Include mini "quick guides" as collapsible sections within each monitoring topic to make it possible for users to get started without switching context to view other documents. We would still point to the integrations documentation for reference content. This would also help us meet our goal for integrations docs to "set the reader up for a successful installation and setup by connecting them with any other resources they'll need."

**Potential problems:**
* This content will need to be updated whenever the UI/data onboarding experience changes. 
* We could single source the content and use variables to resolve names, but that makes the source files harder to read/maintain. It also makes it harder 

IN PROGRESS

**Comment by dedemorton** [comment]
@bmorelli25 @colleenmcginnis I'm working on a template for the new AWS monitoring docs. We'll use this template for other cloud monitoring docs in the future. I'd like to get your feedback on whether we should include data ingestion steps in this guide. Take a look at my proposal [here](https://github.com/elastic/observability-docs/issues/2555#issuecomment-1426487433) and let me know what you think.

**Comment by bmorelli25** [comment]
This seems like a really useful addition.

> We could use a shared file and variables to single-source the text (making it easier to maintain the content), but we know from previous experience that "there be dragons."

There be dragons, yes, but I think the benefits of single-sourcing outweigh the 🐉 negatives. The template you suggest is very reusable across most of our integrations.

> Users who already know Elastic might get annoyed by the repeated information.

Maybe? But as you mention, collapsible sections fix this. It'd be really neat to have analytics on how many times the section is opened up. If it's more than x% of page views (50%?), we probably shouldn't even use the collapsable sections.

**Comment by colleenmcginnis** [comment]
I agree with @bmorelli25. In addition to DeDe's points above, two things I would also factor into the decision:

✔️ There's little to no risk associated with the reader following these steps without having the full context around Fleet/Elastic Agent/integrations (which I think is true).

✔️ The lack of context is not overwhelmingly confusing to readers -- in other words, we're referencing vocab or concepts that we're ok assuming most readers should already be familiar with (though maybe this is less of a concern if it's collapsible because then reading the content is kind of "opt in" instead of default).

**Comment by dedemorton** [comment]
Thanks for your feedback. I will make it so!

**Comment by dedemorton** [comment]
This work is stalled pending review feedback on https://github.com/elastic/observability-docs/pull/2564. (Need feedback before finalizing the template.)

**Comment by dedemorton** [comment]
@alaudazzi Should I close this issue? I'm not sure if it's still relevant given work that you've been doing on the cloud monitoring docs.

**Comment by alaudazzi** [comment]
@dedemorton let's close it 👍
