### ISSUE TITLE
[Synthetics] Document how to set up rules to allow Synthetics Service / Private Location when using traffic filters

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2589]
### Description

If a deployment is using [traffic filters](https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-deployment-configuration.html), connections into Elasticsearch are restricted, which prevents Heartbeat from writing the results (or even any error message) back to the user’s cluster.

Traffic filters are not enabled by default but may have been enabled by the customer.

We should have a call out in the Synthetics documentation to configure these filters if traffic filters are in place (true for both public and private locations, as all will be blocked from writing into ES).

We'll want to work out the best location for this (for example, a new/separate page or add to something existing).  I think we should at least call out in the main Synthetics documentation (_if using the global managed testing infrastructure...._), and maybe include something in the upcoming [change](https://github.com/elastic/observability-docs/pull/2583) that also refers to the IP addresses of the testing regions.

I've marked this for 8.7, although it doesn't specifically relate to that release, and it wouldn't matter if it wasn’t immediately ready on release day, but came out shortly after.

### Resources

The IP addresses for the various regions are documented in https://manifest.synthetics.elastic-cloud.com/v1/ip-ranges.json

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @paulb-elastic 

**Stakeholders:**
* @paulb-elastic 
* @andrewvc

**Comment by paulb-elastic** [comment]
Updated to reflect this will needs to be done for Private Locations too, if they are using Traffic Filters.

**Comment by paulb-elastic** [comment]
Some very rough first ideas for a section or page whilst I have just gone through and tried it out.  I think it might be worth including links between this page/section and https://github.com/elastic/observability-docs/pull/2583/files too...

If you have a deployment configured with [traffic filters](https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-deployment-configuration.html), connections into Elasticsearch are restricted.

When running Synthetics monitors (from any of the Elastic global managed testing infrastructure, or from Private Locations), Heartbeat will not be able to write the results into Elasticsearch unless granted.

> Worth including one of your existing images such as this or a version of it showing just the _Location_ and Elasticsearch_ boxes
![](https://www.elastic.co/guide/en/observability/master/images/synthetics-get-started-ui.png)

If you don’t configure the traffic filters, none of your results will be visible in the Synthetics UI (it will appear like the tests are not running, even though they are, but the results cannot be written back to Elasticsearch).

### Obtaining the IP address

The IP address or CIDR block of the host(s) running the tests, need to be configured in your Traffic filters to allow inbound connection into your Elasticsearch instance to store the results (see [here](https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-ip.html) for more information on setting up Traffic filters).

#### Elastic global managed testing infrastructure

The Global managed testing infrastructure is managed by Elastic. The IP CIDR block (which is a single address, or `/32` block for each region) can be found in https://manifest.synthetics.elastic-cloud.com/v1/ip-ranges.json. This contains a JSON list of all the regions and the address that outbound connections will be made from (i.e. these will be the connections into your Elasticsearch cluster).

For example, the `Europe - United Kingdom` region has the following entry:

```
"europe-west2-a": {
   "ip_prefix": ["34.89.88.187/32"],
   "name": "Europe - United Kingdom"
},
```

If you are going to be running tests from the `Europe - United Kingdom` region, you would need to enable access from the `34.89.88.187/32` CIDR block.

Note that as regions are added, [this list](https://manifest.synthetics.elastic-cloud.com/v1/ip-ranges.json) will change. Similarly existing region addresses are subject to change.

> We should think about how we position _subject to change_ to make it clear this won’t be often (or at all), but may happen at some point

#### Private Locations

If you’re running tests from Private Locations, you will have the Elastic Agent installed on host machine(s) that run the tests. You need to obtain the address ranges for these machines. These needs to be the IP address that the host is making the connection from, into the Elasticsearch cluster (so, may not be the IP address bound to the network interface of the host machine, but the proxy or other address based on your network configuration).

### Adding the Traffic Filter

Once you know the CIDR blocks for your testing sources, these need to be added to your Elasticsearch deployment. More details can be found in the [IP traffic filters](https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-ip.html) docs.

For example, if you had a Private Location running with a public CIDR block of `1.2.3.4/32` and were running tests from the `Europe - United Kingdom` region, you would first create a _Traffic filter_ with the following:

![image](https://user-images.githubusercontent.com/70908889/217528388-b4d4d33b-d97a-4715-a206-dc5b0a755210.png)

Once the _Traffic filter_ has been created, it needs to be assigned to the deployment you are managing monitors from (i.e. the deployment containing the Elasticsearch cluster where your result need to go):

![image](https://user-images.githubusercontent.com/70908889/217528427-a9bb42a6-120d-44e0-bc3a-2af37c5f3815.png)

**Comment by igor-kupczynski** [comment]
FWIIW the description above looks good to me (as a control plane ingress representative) :shipit:
