### ISSUE TITLE
[Synthetics] Document that not all Playwright capabilities are available in Synthetics

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2603]
### Description

We’ve had some confusion (internally and externally) when folk take a Playwright script example and it fails to run in Synthetics.  This has been because we do not support the Playwright Test features (as we have our own runner in Synthetics).

For example, https://playwright.dev/docs/api/class-locatorassertions documents things like [`toHaveText`](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text) assertions.  However these will not work in Synthetics as they are provided by Playwright Test.

I've marked this for 8.7, although it doesn't specifically relate to that release, and it wouldn't matter if it wasn’t immediately ready on release day, but came out shortly after.

### Resources

I think the Project Team (namely @vigneshshanmugam) will need to provide the content, with help from the Docs team on the best place to put it.

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @vigneshshanmugam 

**Stakeholders:**
* @vigneshshanmugam 
* @andrewvc 
* @paulb-elastic

**Comment by colleenmcginnis** [comment]
>This has been because we do not support the Playwright Test features (as we have our own runner in Synthetics).

>I think the Project Team (namely @vigneshshanmugam) will need to provide the content, with help from the Docs team on the best place to put it.

@vigneshshanmugam can you help point me in the right direction here?

Based on browsing through the /synthetics repo, it looks like maybe we support _most_ of the Playwright [GenericAssertions](https://playwright.dev/docs/api/class-genericassertions) in [`expect.ts`](https://github.com/elastic/synthetics/blob/main/src/core/expect.ts), but we might not support any of the [LocatorAssertions](https://playwright.dev/docs/api/class-locatorassertions), [PageAssertions](https://playwright.dev/docs/api/class-pageassertions), or [SnapshotAssertions](https://playwright.dev/docs/api/class-snapshotassertions). Is that true? Is there somewhere else I should be looking?

**Comment by vigneshshanmugam** [comment]
> Based on browsing through the /synthetics repo, it looks like maybe we support most of the Playwright [GenericAssertions](https://playwright.dev/docs/api/class-genericassertions) in [expect.ts](https://github.com/elastic/synthetics/blob/main/src/core/expect.ts)

💯 We support most of the generic ones and as you mentioned, its located on the `expect.ts` in the synthetics agent code. We don't support any other assertions which are basically utilities built on top of the generic ones. Even though we don't support them, we can point users to use an alternative version by utilizing the generic assertions. One such example is shown below
```ts
 await expect(page.locator('.status')).toHaveText('Submitted');

// translates to
expect(await page.locator('.status').text()).toContain("Submitted");
```

Some of the assertions does not have any alternatives as of now. We may have to call this out explicitly on the docs
- toHaveScreenshot
- toMatchSnapshot

**Comment by vigneshshanmugam** [comment]
Thanks for the detailed writeup @colleenmcginnis, super helpful. 

> I worry that having a full list of Synthetics vs Playwright capabilities might be difficult to maintain

Agreed. The list might get more nuanced if we start doing in to performance monitoring criteria in the future. Having a simple list would make it more manageable. 

> do you think that's something we'd be able to identify and document?
Yes we can identify most of them and probably only document the ones that would be most used. Like as a first step, we can easily pick from the the table @colleenmcginnis has put together
- Expect library
- Video being unsupported
- Request parameter for the API tests. 

We should also bear in mind that we dont support 1:1 with what Playwright Test and we do support all of the exposed API's from Playwright itself. 


> I see that we have some code comments in https://github.com/elastic/synthetics (for example [expect.ts](https://github.com/elastic/synthetics/blob/main/src/core/expect.ts#L63-L65)). Do you think it would be a good use of time to build out those comments and use a tool like [JSDoc](https://jsdoc.app/about-getting-started.html) to generate a complete reference for Synthetics

Good idea @colleenmcginnis , We can create a separate issue and track it. We dont need to document everyrthing on the elasitc.co website, We can also directly link to the generated document on the Synthetics repo as it would be make it easier for the writers than manually copy pasting same work across multiple places.
