### ISSUE TITLE
[REQUEST]: Infrastructure Hosts Feature (Technical Preview only)

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#2609]
### Description

_Disclaimer : This is only in Technical Preview so we're unsure whether we need documentation on this whilst its in this state? Perhaps we can discuss best practice for how we progress (@roshan-elastic - PM)..._

We are releasing the [Hosts](https://wiki.elastic.co/display/PM/Hosts) feature under technical preview.

You can access the feature as follows:

- [Latest build - Edge cluster](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts)
- [8.7 build credentials](https://dev-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts) - [8.7 build link](https://ela.st/dev-oblt-credentials)

> **Note** : This is behind a feature flag but you can see this in the [left-hand nav](https://user-images.githubusercontent.com/117740680/218136553-963b6819-5fa6-4d8e-ae7a-2eba7c85d387.png), we also promote it within [inventory](https://user-images.githubusercontent.com/117740680/218136553-963b6819-5fa6-4d8e-ae7a-2eba7c85d387.png) but when you actually land on it, it's clearly denoted as within technical preview via the [splash screen](https://user-images.githubusercontent.com/117740680/218136885-a4708417-46f8-4e31-a5d8-dfd94e6ffd25.png) (you can enable it easily by just clicking on 'enable')

### Resources

[Feature Wiki](https://wiki.elastic.co/display/PM/Hosts)
[Edge URL](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts)

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:**
@crespocarlos @kkurstak @formgeist @smith @neptunian

**Comment by roshan-elastic** [comment]
@smith FYI

**Comment by bmorelli25** [comment]
> Disclaimer : This is only in Technical Preview so we're unsure whether we need documentation on this whilst its in this state? Perhaps we can discuss best practice for how we progress

So, it depends 😄. For a technical preview feature behind a feature flag, a blog post might make sense. Or, something we've discussed with the APM team is having a developer put together a quick screen share w/audio of the feature—how to enable it, clicking through it with some sample data, etc., and then having us add that to the docs until the feature matures and we replace the video with real documentation. Regardless, if the feature is this prevalent we should at least have something available for users who want to learn more.

**Comment by roshan-elastic** [comment]
Great - thanks @bmorelli25. I've put in 30 mins for next week.

**Comment by dedemorton** [comment]
@roshan-elastic I've started working on this content in #2756 but it's just a start. We should meet after the EAH to discuss how much detail to cover in this topic, what sorts of questions users are likely to have, etc. I don't want to go too far down the road of documenting stuff that users can figure out pretty easily by clicking around in the UI. Sometimes that's helpful because it gets users to the right place in the UI, but it's not everything.

**Comment by roshan-elastic** [comment]
@dedemorton - sounds good to me. I'm planning to support you for the week after EAH so I'll have time!
