### ISSUE TITLE
[REQUEST]: Adding support for mobile APM agents

### ISSUE THREAD

**Issue by gbamparop** [elastic/observability-docs#2633]
### Description

Since 8.6 we have started adding support for mobile APM agents to the service overview pages which is in technical preview. The purpose of these improvements is to provide more actionable insights to SREs and dev users at a glance, as well as to make it easier to slice and dice the APM data based on popular filtering options.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/5831975/218486716-4d6929c0-1752-4c9a-a965-fbfa0fc9c9af.png">

-----------

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/5831975/218486907-6dd0789e-a4eb-4a90-8dce-710433a29aeb.png">

### Resources

- https://github.com/elastic/kibana/issues/146615 (Meta issue)
- https://github.com/elastic/apm-dev/issues/884 (pitch)
- https://github.com/elastic/kibana/issues/146854
- https://github.com/elastic/kibana/issues/146854
- https://github.com/elastic/kibana/issues/146868
- https://github.com/elastic/kibana/issues/146870
- https://github.com/elastic/kibana/issues/146873
- https://github.com/elastic/kibana/issues/146876

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @akhileshpok 

**Stakeholders:**
- @kpatticha 
- @MiriamAparicio 
- @boriskirov  
- @gbamparop

**Comment by bmorelli25** [comment]
👋 How did you get data for these screenshots? I'm not seeing any mobile agent data in the dev and edge clusters.

**Comment by kpatticha** [comment]
@bmorelli25 have you tried edge-lite? 
Otherwise, try to extend the time ranges (>3 months).

**Comment by bmorelli25** [comment]
> Otherwise, try to extend the time ranges (>3 months).

You're right—I was able to find iOS data in `edge` from 23/12/22-07/01/23. Thank you, @kpatticha!
