### ISSUE TITLE
[Synthetics] Stop promoting browser options in `heartbeat.yml`

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2680]
### Description

The future supported way of running browser monitors, will only be as GUI managed monitors (inline), or Project Monitors.  The way of defining browser based monitors in the `heartbeat.yml` will never go GA.

### Resources

These are currently defined on the following pages:
* https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html#monitor-types describes a `browser` option
* This links through to a full page describing the configuration https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-browser-options.html
  * This currently describes the feature as beta, and does call out to use Project monitors instead

Looking for input from the docs team here, but it might be useful to remove this from the docs completely, with a link to previous versions of the docs (like we have done before) if users still want to find it (rather than leaving it there and say to stop using it).

As a starting example:
> Defining `browser` monitors in the `heartbeat.yml` is not supported, use [Project Monitors](https://www.elastic.co/guide/en/observability/current/synthetics-get-started-project.html) instead. If you need to refer to how these were set up (in beta) in previous versions, refer to [previous versions](https://www.elastic.co/guide/en/beats/heartbeat/8.6/monitor-browser-options.html).

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @paulb-elastic 

**Stakeholders:**
* @paulb-elastic 
* @andrewvc

**Comment by colleenmcginnis** [comment]
@paulb-elastic what do you think about replacing the [Browser options](https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-browser-options.html) page to use language similar to https://github.com/elastic/observability-docs/pull/2732#pullrequestreview-1353165120 (if it is also true here). 

>**Heartbeat browser checks are in beta and will not be made generally available.**
>
>If you want to set up browser checks, we highly recommend using Synthetics via [Projects](https://www.elastic.co/guide/en/observability/current/synthetics-get-started-project.html) or the [Synthetics app in Kibana](https://www.elastic.co/guide/en/observability/current/synthetics-get-started-ui.html) to create and manage browser monitors.
>
>If you need to refer to how beta Heartbeat browser checks were set up previously, refer to the [8.7 documentation](https://www.elastic.co/guide/en/beats/heartbeat/8.7/monitor-browser-options.html).

```asciidoc
*{heartbeat} browser checks are in beta and will not be made generally available.*

If you want to set up browser checks, we highly recommend using Synthetics via {observability-guide}/synthetics-get-started-project.html[Projects] or the {observability-guide}/synthetics-get-started-ui.html[Synthetics app in {kib}] to create and manage browser monitors.

If you need to refer to how beta {heartbeat} browser checks were set up previously, refer to the {beats-ref-root}/heartbeat/8.7/monitor-browser-options.html[8.7 documentation].
```

**Comment by paulb-elastic** [comment]
@colleenmcginnis do you mean by keeping the page as it is now, but add that banner to the top?

We could certainly do that for 8.7 and previous versions of the docs.  My only worry leaving it there for 8.8+ is that people may find this and try and use it, and we're really trying to stop this from being used, or a source of support issues.

A middle ground could be to remove the content from 8.8 with the banner info with a link to the 8.7 version (with that banner), so people have to specifically go into it rather than it be shown in the 8.8 docs.

**Comment by colleenmcginnis** [comment]
What do you think about this plan?

* **On 8.8 and main:**

  * Add a note to the bottom of [Configure Heartbeat monitors](https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html) page:
    <img width="889" alt="Screenshot 2023-05-09 at 9 44 29 AM" src="https://github.com/elastic/observability-docs/assets/10479155/c9ce3735-3856-429b-ba82-b45f79151120">

  * Replace content on [Browser options](https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-browser-options.html) page, remove from the table of contents (but is still available if directly linked or from Google search results):
    <img width="1512" alt="image" src="https://github.com/elastic/observability-docs/assets/10479155/83263fae-044c-466a-8027-4e109f386bb5">

  * Remove all other mentions of browser monitors:
    * Example at the bottom of [Configure the task scheduler](https://www.elastic.co/guide/en/beats/heartbeat/current/monitors-scheduler.html)
    * [`data_stream` option](https://www.elastic.co/guide/en/beats/heartbeat/current/monitor-options.html#monitor-data-stream) on the Common monitor options page.

* **On 8.7 (and some number of previous versions?):** 
  * Add a banner to [Configure Heartbeat monitors](https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html) page warning users about future of browser monitors in Heartbeat.
