### ISSUE TITLE
[Synthetics] Enhance troubleshooting page

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2695]
### Description

We should look to see if there is additional content that will be useful to document around troubleshooting or known issues.

### Resources

We currently have [this page](https://www.elastic.co/guide/en/observability/current/troubleshoot-uptime-mapping-issues.html).  We could potentially change this to a generic troubleshooting page (with individual items), or have a top level troubleshooting section under which the various pages go.

Initial content ideas:
* Missing / incorrect API key (should get notification, but how to regenerate if not getting results)
* No Agent running with the Private Location Agent Policy (so no results)
* Review forums / SDHs, anything else keep coming up?

### Collaboration

Other (please describe below in the Point of contact section).

### Point of contact.

**Main contact:** @paulb-elastic 

**Stakeholders:**
* @drewpost 
* @elastic/uptime 

It would be good to get a recommendation from the docs team on the page layout (e.g. new section, single page), and the content will be generated by the project team

**Comment by colleenmcginnis** [comment]
>It would be good to get a recommendation from the docs team on the page layout (e.g. new section, single page), and the content will be generated by the project team

My suggestion is to start with a troubleshooting page, and we can break it up into individual pages in a troubleshooting _section_ if/when we have too much content for a single page (this is subjective, but once the page starts to get difficult navigate/scan quickly it should probably be broken into separate pages).
