### ISSUE TITLE
Add Fleet and Elastic Agent terminology to the glossary

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#270]
Add fleet terminology to glossary: https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html

**Related PRs:**
https://github.com/elastic/observability-dev/issues/659
https://github.com/elastic/endpoint-app-team/issues/423

**Terms to define:**

**_Agent policy_** TBD
We need to sort out the inconsistencies across Security and Fleet/Elastic Agent docs. An agent policy contains integration policies.

**_integration policy_** an instance of an integration that is configured and added to an agent policy

**_data stream_** TBD

**_dataset_** TBD

**_Elastic Agent_** a single, unified agent that you can deploy to hosts or containers to collect data and protect endpoints.

**_Fleet_** TBD

**_integration_** a bundle of assets needed to ingest and visualize data or protect endpoints.

**_namespace_** a user-defined string used to group data.

**_standalone_** 

**_data stream naming scheme_** https://www.elastic.co/blog/an-introduction-to-the-elastic-data-stream-naming-scheme

**_Fleet_**

**_input_** 

**_Elastic package registry_** a service that stores Elastic package definitions in a central location that is hosted by Elastic. 

**Other terms we might need to define:**

**Comment by dedemorton** [comment]
This issue is going to change the terminology around policies: https://github.com/elastic/integrations-dev/issues/379

**Comment by mostlyjason** [comment]
I added a few more terms to your list. Not sure we need package manager since that is an internal name.
