### ISSUE TITLE
[Synthetics] Document required permissions

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#2707]
### Description

Document the permissions needed to use Synthetics (there have been some queries and issues where customers have had difficulties setting up limited permission users because we don’t make this clear in the docs).

I've marked this for 8.7, although it doesn't specifically relate to that release, and it wouldn't matter if it was worked on post the public release date for 8.7.

### Resources

We currently document the permissions for:
* Enable Monitor Management ([here](https://www.elastic.co/guide/en/observability/current/synthetics-get-started-project.html#_prerequisites_2))
* Generating an API key to `push` Project Monitors ([here](https://www.elastic.co/guide/en/observability/current/synthetics-command-reference.html#elastic-synthetics-push-command))

But we don’t document how to _use_ Synthetics (as recently documented by Dominique to help with a support case).

We should document these so users know exactly what permissions are needed.

Maybe it should go in the [Getting started](https://www.elastic.co/guide/en/observability/current/synthetics-get-started.html) section, or a page underneath it?

The permissions needed for the various use cases are:
* Privileges need to use monitor management with public locations
  `Index privileges: synthetics-*: read`
  `Kibana privileges: Synthetics and Uptime: All`
* Privileges need to use monitor management with private locations (and to edit or delete any monitors configured with private locations)
  `Index privileges: synthetics-*: read`
  `Kibana privileges: Synthetics and Uptime: All, Fleet: All, Integrations: All`
* Privileges needed to use monitor management with project monitors configured with only public locations
  `Cluster priviledges: At least one of `manage_own_api_key`, `manage_security`, or `manage_api_key` // to generate the api key`
  `Index privileges: synthetics-*: read`
  `Kibana privileges: Synthetics and Uptime: All`
* Privileges needed to use monitor management with project monitors configured with private locations
  `Cluster priviledges: At least one of `manage_own_api_key`, `manage_security`, or `manage_api_key` // to generate the api key`
  `Index privileges: synthetics-*: read`
  `Kibana privileges: Synthetics and Uptime: All, Fleet: All, Integrations: All`

NOTE that the `Fleet: All` permissions apply to all spaces, so Private Locations and monitors configured to run on them, can be created and managed from any space.

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @dominiqueclarke 

**Stakeholders:**
* @paulb-elastic 
* @andrewvc

**Comment by colleenmcginnis** [comment]
I'm really struggling with making sense of all the information here and in #2645. This is my current understanding... the overall privileges any user will need depends on two factors: (1) where are the monitors hosted, and (2) what you want to achieve. Is this accurate at all? 

| Factors | Options | Kibana privs | Index privs | Cluster privs |
|---|---|---|---|---|
| **Where the monitors are hosted** | Elastic's global managed infrastructure | <ul><li>`Uptime/Synthetics: All`</li></ul> | | |
|  | Private Locations | <ul><li>`Uptime/Synthetics: All`</li><li>`Fleet: All`</li><li>`Integrations: All`</li></ul>  | | | 
| **What you want to achieve** | Enable Monitor Management | <ul><li>`Uptime/Synthetics: All`</li></ul> | <ul><li>`synthetics-*: read`</li><li>`synthetics-*: view_index_metadata`</li><li>`synthetics-*: create_doc`</li><li>`synthetics-*: auto_configure`</li></ul> | <ul><li>`monitor`</li><li>`read_ilm`</li><li>`read_pipeline`</li></ul> |
|  | Create an API key |  | | At least one of:<ul><li>`manage_own_api_key`</li><li>`manage_security`</li><li>`manage_api_key`</li></ul> |
|  | Create/modify/delete monitors | | <ul><li>`synthetics-*: read`</li><li>`.alerts-observability.uptime.alerts-*: read`</li></ul> | |
|  | View monitor data results | | <ul><li>`synthetics-*: read`</li></ul> | |

**Comment by colleenmcginnis** [comment]
I talked with the Obs Docs team about this issue, and they recommended taking a similar approach to how we discuss permissions in the [APM docs](https://www.elastic.co/guide/en/apm/guide/current/feature-roles.html) and [Beats docs](https://www.elastic.co/guide/en/beats/heartbeat/current/feature-roles.html). In these docs, we have a specific page/section outlining typical types of users, recommend that the reader create "roles" with the necessary permissions, and sprinkle notes with links to this section throughout the rest of the docs (for example, for Synthetics we would add notes to the set up guides, the docs on `push`, etc). I think this might be what @dominiqueclarke was getting at in https://github.com/elastic/observability-docs/pull/2645#pullrequestreview-1310276937:

>I want to distinguish between admins and Synthetics users. I'm not sure what is the best, clearest way to do so. @colleenmcginnis

If this sounds like a good plan, I can start a PR and ping @dominiqueclarke, @shahzad31, and @paulb-elastic when there's a preview up to review. Let me know what you think.

**Comment by paulb-elastic** [comment]
Thanks @colleenmcginnis, I agree, this seems like a good approach for us here too.

**Comment by dominiqueclarke** [comment]
Hi there. I just wanted to add some additional context to this after investigating further. I believe we can simplify things considerably. Here I've listed the built-in role users can use depending on what they want to accomplish, and the extra privileges they'll need depending on the high-level actions they are trying to accomplish.

| Factors | Options | Role | Extra Kibana privs | Extra Index privs | Extra Cluster privs |
|---|---|---|---|---|---|
| **Where the monitors are hosted** | Elastic's global managed infrastructure | editor | | | |
|  | Private Locations | editor | | | | 
| **What you want to achieve** | Enable Monitor Management | editor | | <ul><li>`synthetics-*: view_index_metadata`</li><li>`synthetics-*: create_doc`</li><li>`synthetics-*: auto_configure`</li></ul> | <ul><li>`monitor`</li><li>`read_ilm`</li><li>`read_pipeline`</li></ul> |
|  | Create an API key | editor | |  |At least one of:<ul><li>`manage_own_api_key`</li><li>`manage_security`</li><li>`manage_api_key`</li></ul> |
|  | Create/modify/delete monitors | editor| |  | |
|  | View monitor data results | viewer | | | |
