### ISSUE TITLE
[REQUEST]: Document missing Fleet scalability options

### ISSUE THREAD

**Issue by juliaElastic** [elastic/observability-docs#2758]
### Description

Not all scalability settings are documented in [Fleet Server scalability doc](https://www.elastic.co/guide/en/fleet/current/fleet-server-scalability.html).
E.g. `server.limits.checkin_limit.max_body_byte_size` is missing.

### Resources

All options are here: https://github.com/elastic/fleet-server/blob/main/internal/pkg/config/limits.go

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @kpollich 

**Stakeholders:** @elastic/fleet

**Comment by jlind23** [comment]
@karenzone just added this to your radar.
