### ISSUE TITLE
Document new monitor details view for synthetic checks

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#278]
Related issue: https://github.com/elastic/kibana/issues/80144

**Comment by paulb-elastic** [comment]
Key changes in 7.11 that will need documentation changes...

## Screenshots

The Uptime UI has changed quite a bit, so likely that a number of screenshots will need to be updated to reflect the new UI.  For example, the Overview page top menu, monitor list table layout.  This includes the expanded view in the monitor list.

Similarly, the UI has been updated when drilling into a monitor (e.g. the inclusion of the tags in the summary at the top, and the history list at the bottom).

## Waterfall Chart

There is a new waterfall chart in Uptime for Synthetic monitors (of type `browser`).  This is accessible by clicking on the **step name** when expanding the test result from the **History** view.

We should document how to get to the waterfall chart, and what it represents.

![image](https://user-images.githubusercontent.com/70908889/102611915-c172fa80-4127-11eb-8e59-c6134c3f9e50.png)
