### ISSUE TITLE
[REQUEST]: Add documentation in the observability guide for sending logs to Elasticsearch with AWS Kinesis Firehose

### ISSUE THREAD

**Issue by tommyers-elastic** [elastic/observability-docs#2797]
### Description

This is a new product feature within Infrastructure Observability for shipping logs to ESS via AWS Kinesis Firehose delivery streams. 

This solution is designed to be used alongside existing AWS integrations in Kibana (e.g. https://docs.elastic.co/en/integrations/aws/vpcflow), but can also be used for shipping any AWS logs. 

We will produce a setup guide, troubleshooting guide, and something more dry with reference configuration etc. 

### Resources

There are some draft documents but they are currently in internal Google docs/private GH issues, so not linking them in this public issue. Please reach out to me and I can provide the links. We will be creating a draft PR with the content shortly anyway. 

### Collaboration

The product team will provide the initial content.

### Point of contact.

**Main contact:** @tommyers-elastic @vinaychandrasekhar 

**Stakeholders:**

**Comment by dedemorton** [comment]
@tommyers-elastic Adding my name as assignee so you know I'm available to help you finalize these docs. Next step is for you to go through Bradon's comments on https://github.com/elastic/observability-docs/pull/2802. Now that I'm back, I can do a final review and assist with any build-related questions.

**Comment by dedemorton** [comment]
@tommyers-elastic Nevermind...I will go through and apply Brandon's comments.
