### ISSUE TITLE
Link to Android Agent from Central Config

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2812]
https://github.com/elastic/apm-agent-android/pull/137 adds central config to the Android agent. We need to link to this feature from https://www.elastic.co/guide/en/kibana/8.6/agent-configuration.html. This is only possible after version 0.4.0 is released.

cc @LikeTheSalad

**Comment by LikeTheSalad** [comment]
Version `0.4.0` is now released 😁
