### ISSUE TITLE
Improve Custom logs integration documentation

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2813]
### Summary

We need better documentation for the [custom logs integration](https://github.com/elastic/integrations/tree/main/packages/log).

* This issue has some ideas: https://github.com/elastic/ingest-dev/issues/1372.
* This is forward-looking but has a lot of context around how the integration works and its main features: https://github.com/elastic/ingest-dev/issues/1371

### Who

This integration is owned by the https://github.com/orgs/elastic/teams/elastic-agent-data-plane team. @pierrehilbert, I believe that's your team. Do you have a developer you can recommend for Mike to work with?

**Comment by pierrehilbert** [comment]
@rdner worked on Custom Logs and is probably the best developer to work with for that.

**Comment by mdbirnstiehl** [comment]
Hi @rdner, I discussed with @bmorelli25 , and we wanted to address these points:

-  The user flow in Kibana addresses some of the steps in the readme. If a user is adding the integration from Kibana, this could be confusing.
- The readme doesn't address why the user might want to use this integration. Is this really the integration that they should user or should they try other more specific logs integrations first?
- Users will need to jump all over the documentation to complete the readme. Maybe we can provide a better user experience here.
- And just some general grammar fixes.

I could set up some time to discuss some of these points and what needs to be there from your side if that works for you?

**Comment by rdner** [comment]
@mdbirnstiehl well, it seems like you know what to do and it's purely a documentation change. I think I'm not required for this task but if you have questions about the integration, I'm happy to answer.

When I made this change https://github.com/elastic/integrations/pull/5153 I just copy-pasted the doc provided to me by @jlind23, perhaps he has more context.

**Comment by mdbirnstiehl** [comment]
Focusing on logs+ over this specific issue.
