### ISSUE TITLE
Need to discuss package.json in synthetics docs

### ISSUE THREAD

**Issue by andrewvc** [elastic/observability-docs#284]
We set a [`package.json`](https://github.com/elastic/synthetics/blob/master/examples/todos/package.json) file for our synthetics example, but don't really explain how it works. Let's document that for users unfamiliar with node.

**Comment by vigneshshanmugam** [comment]
Closing this in favor of https://discuss.elastic.co/t/synthetics-1-0-0-beta-0-breaking-changes/271118
