### ISSUE TITLE
[Synthetics]:  Different timeout configuration in synthetic tests

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/observability-docs#2868]
### Description

There are different types of timeouts when it comes to running Synthetic tests. Basically it can be split in to Navigation and Action timeouts. Navigation refers to the timeouts that basically happens when there is a page navigation by means of `page.goto, page.click, etc`. Action timeouts are tied to actions that Playwright takes for finding selectors or locators etc. 

### Resources

We have recently made changes in the Synthetics agent to keep the default timeout of `50 seconds` for both Navigation and Action timeouts. 

Also added the option to configure these timeouts via `playwrightOptions` which can be configured in both the UI and for project based browser monitors. Users can override these default by different which are already documented in the Playwright API's. 

Default action timeout - https://playwright.dev/docs/api/class-browsercontext#browser-context-set-default-timeout
Default navigation timeout - https://playwright.dev/docs/api/class-browsercontext#browser-context-set-default-navigation-timeout

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @vigneshshanmugam 

**Stakeholders:**
@paulb-elastic 
@vigneshshanmugam

**Comment by paulb-elastic** [comment]
Linking to https://github.com/elastic/synthetics/pull/742 which may be helpful
