### ISSUE TITLE
[REQUEST]: AWS Lambda metrics view

### ISSUE THREAD

**Issue by gbamparop** [elastic/observability-docs#2890]
### Description

In 8.5 we have added support for AWS Lambda metrics and implemented further UX improvements in 8.6. The [documentation](https://www.elastic.co/guide/en/kibana/master//apm-lambda.html) for Lambda functions could be enriched with additional details and screenshots from the metrics tab.

### Metrics view for a service
<img width="612" alt="image" src="https://user-images.githubusercontent.com/5831975/234824705-8cd6b0e3-0e61-4488-9d43-d32625ab17e7.png">

### Metrics view for an single function
<img width="697" alt="image" src="https://user-images.githubusercontent.com/5831975/234824893-0208908b-e8e7-493c-b175-6437e3056faf.png">

### Resources

- https://github.com/elastic/apm-dev/issues/735 (pitch)
- https://github.com/elastic/kibana/issues/138420 (original implementation issue)
- https://github.com/elastic/kibana/issues/142328 (UX improvements)
- https://github.com/elastic/kibana/pull/143113 (PR)

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @akhileshpok 

**Stakeholders:**
- @akhileshpok 
- @AlexanderWert 
- @gbamparop

**Comment by bmorelli25** [comment]
Hey all. I'm not sure what to document with this one. I made a few updates to our existing docs, but most charts have tooltips explaining what a user is looking at. See https://github.com/elastic/kibana/pull/160568 for the minor updates that I made.

@akhileshpok and @AlexanderWert is there a workflow you have in mind that you want me to document?

**Comment by bmorelli25** [comment]
Cool beans. Thanks!
