### ISSUE TITLE
[REQUEST]: Rename ingest-traces.asciidoc and change the ID

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2894]
### What documentation page is affected

https://www.elastic.co/guide/en/observability/current/ingest-traces.html

### What change would you like to see?

As part of our magnificent [spacetime project](https://github.com/elastic/observability-docs/pull/2880), I've renamed all getting started source files to match the contents of the files. I've also changed the IDs.

To avoid breaking the APM docs, I didn't change the name or ID of ingest-traces.asciidoc. We should do that as "tech debt" after we merge https://github.com/elastic/observability-docs/pull/2880.

We'll need a corresponding update and backport here:
https://github.com/elastic/apm-server/blob/087e516ac23277aa2f76bf9749ff367347073cbf/docs/apm-quick-start.asciidoc?plain=1#L9

**Comment by colleenmcginnis** [comment]
Related PRs to be merged _in this order_:

- [ ] https://github.com/elastic/observability-docs/pull/3309
  - [ ] After merged, open an issue requesting a permanent redirect.
- [ ] https://github.com/elastic/apm-server/pull/11942
- [ ] https://github.com/colleenmcginnis/observability-docs/pull/3
