### ISSUE TITLE
Logs onboarding current status

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#2907]
### Summary

1. Go through the current logs onboarding flow
2. Identify what went well and what didn't
3. Share results in the [Google Doc](https://docs.google.com/document/d/1jS8TS6RjYo4IBXHweKRScyEg-QfRRs6P5vcomz4WWZc/edit?pli=1#heading=h.uawzdj9mdfe0) (sorry, internal only)

**Comment by bmorelli25** [comment]
@mdbirnstiehl to chat with Ruflin + Tom before planning next steps.

**Comment by mdbirnstiehl** [comment]
I'm going to close this issue, and the user journey issue. I spoke with Tom, and we will cover the output of these two tickets in [this issue](https://github.com/elastic/observability-dev/issues/2677). We are meeting next week to start outlining and planning.
