### ISSUE TITLE
[REQUEST]: Rename Azure integration  to 'Azure Native ISV Service' in obs guide

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2918]
### Description

The Azure integration is being renamed. We need to update the tutorial in the obs guide:  https://www.elastic.co/guide/en/observability/current/monitor-azure-native.html

Wait until https://github.com/elastic/cloud/pull/114457 is merged to see final decision about acceptable short name.

This change needs to be backported to all "active" releases shown in the release dropdown (i.e., 8.8, 8.7, 8.6, & 7.17).

### Resources

Related cloud issue: https://github.com/elastic/cloud/issues/114248.

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** 

**Stakeholders:** @kilfoyle

**Comment by kilfoyle** [comment]
@dedemorton  The Cloud docs PR for this change is now merged: https://github.com/elastic/cloud/pull/114457

Please note that:
 - We should use the full product name `Elastic Cloud (Elasticsearch) – An Azure Native ISV Service` on the first instance, if possible. For the Cloud docs I added [a tip](https://github.com/elastic/cloud/pull/114457#issuecomment-1539025249) indicating the full product name, and I used either `Azure Native ISV Service` or `Elastic Cloud Azure Native ISV Service` in all other instances, depending on the context.
 - For the Observability change, I'd suggest merging it into all active releases listed in the docs version dropdown.
