### ISSUE TITLE
[Synthetics] Document parameters encryption / security

### ISSUE THREAD

**Issue by andrewvc** [elastic/observability-docs#2950]
It's not uncommon to get questions around the security of parameters, both global and otherwise in synthetics.

We partially documented this for on-prem [here](https://www.elastic.co/guide/en/fleet/current/_elastic_agent_configuration_encryption.html), but should make a dedicated synthetics page discussing this. This would cover:

1. Encryption of secrets within the user's elastic stack via Kibana saved objects
2. Encryption in fleet (already covered [here](https://www.elastic.co/guide/en/fleet/current/_elastic_agent_configuration_encryption.html), but should be linked to)
3. Encryption in the synthetics service

**Comment by paulb-elastic** [comment]
@andrewvc is there cross over here with https://github.com/elastic/observability-docs/issues/1975 and https://github.com/elastic/observability-docs/issues/2266?

**Comment by andrewvc** [comment]
With #2266 yes, not #1975 . I've opened https://github.com/elastic/observability-docs/pull/2953 which will close both of those
