### ISSUE TITLE
[REQUEST]: Enhance AWS monitoring docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#2980]
### Description

I brought up a couple requests to enhance the AWS monitoring content during the review of https://github.com/elastic/observability-docs/pull/2564, but the team thought we should merge the existing content and make these enhancements later, specifically:

 - [ ] Provide more detail about why users should watch specific metrics (similar to what we do in the EC2 topic).
 - [ ] Where we list the metrics to watch, we should tell users how to view them in the UI.

### Resources

n/a

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @kaiyan-sheng

**Comment by bmorelli25** [comment]
Closing and adding to https://github.com/elastic/observability-docs/issues/1672.
