### ISSUE TITLE
[Synthetics] Document how to set locale and timezone via PlaywrightOptions

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#3004]
### Description

At the moment, neither the timezone or locale is set in the Synthetics Service, which will work for many sites, but some sites will not work properly without one or both of these being set.

The Service is going to be [changed](https://github.com/elastic/synthetics-service/issues/1312) to set the timezone for each individual location, but the locale will not be set as this will be dependent on the use case the user is trying to achieve (sometimes the same locate will be desired from different locations, sometimes it will intentionally want to be different).

These can already be set on a per monitor or global basis using for example:
```
playwrightOptions: {
  locale: 'en-AU',
  timezoneId: 'Australia/Brisbane',
}
```
We need to make this clearer in the documentation but also clarify that the `timezoneId` will reflect the timezone the location is running in.  Likewise we should clarify that `playwrightOptions` set in the script/configuration will take priority over the default `timezoneId` set in the service.

This should wait until https://github.com/elastic/synthetics-service/issues/1312 has been implemented and rolled out.

### Resources

Need to work out the best location, maybe somewhere in https://www.elastic.co/guide/en/observability/current/synthetics-create-test.html (looking for guidance here from the Docs team)

### Collaboration

The product team will provide the initial content.

### Point of contact.

**Main contact:** @paulb-elastic

**Stakeholders:**
- @vigneshshanmugam 
- @paulb-elastic

**Comment by colleenmcginnis** [comment]
>This should wait until https://github.com/elastic/synthetics-service/issues/1312 has been implemented and rolled out.

@paulb-elastic it looks like https://github.com/elastic/synthetics-service/issues/1312 has been bumped to 8.10. Should I hold on this issue as well?

**Comment by paulb-elastic** [comment]
@colleenmcginnis I think this is useful info (I've referred others to it recently), but the specific messaging in this issue talks about saying "we set timezone in the service", but we don't yet until that issue is done.  However, I wonder if it would still be useful to document how to do it (set the timezone and locale), and then when we do set the timezone in the service, we can update the docs to make that clear (but users can still override if they wanted to).

**Comment by paulb-elastic** [comment]
Note that the service/agent change will now be done under https://github.com/elastic/beats/issues/36117
