### ISSUE TITLE
[REQUEST]: Conditional actions in Observability rules

### ISSUE THREAD

**Issue by lcawl** [elastic/observability-docs#3006]
### Description

In 8.8, security rules gained the ability to have conditional actions (e.g. only send notifications if alert occurs between these hours, or only if it matches this filter). We updated the Kibana docs and Security docs for that feature.  Now it seems like some Observability rules will be able to have this functionality in 8.9.

Expected impact:

- [ ] Review new text that appears in the affected rule creation wizards
- [ ] Update screenshots and details in the action-related sections of the affected rule pages (under https://www.elastic.co/guide/en/observability/current/create-alerts.html)
- [ ] Add to release highlights

### Resources

- https://github.com/elastic/kibana/issues/158014
- https://github.com/elastic/kibana/issues/158017
- https://github.com/elastic/security-docs/issues/3142
- #ro-feature-conditional-action

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** 

I'm not sure who's working on the implementation from the observability dev team, only who's enabling the functionality on the Kibana side per https://github.com/elastic/kibana/issues/158017

**Stakeholders:**

@lcawl - Let me know if I can help since I wrestled with this understanding this concept in 8.8.

**Comment by lcawl** [comment]
It looks like this is on hold now per https://github.com/elastic/kibana/issues/158017

**Comment by mdbirnstiehl** [comment]
I've moved it to Sprint 9 (8.10) sprint accordingly.

**Comment by mdbirnstiehl** [comment]
After talking with the devs, this will be in 8.9. So I've brought it back to the current sprint.
