### ISSUE TITLE
[REQUEST]: Update RUM source map API docs 

### ISSUE THREAD

**Issue by gbamparop** [elastic/observability-docs#3021]
### Description

The default max payload size in Kibana is 1MB, however, user can change it through the `server.maxPayload` [configuration in Kibana](https://www.elastic.co/guide/en/kibana/current/settings.html).

Source maps can vary in size and if a user tries to upload one that exceeds the max payload size, they will get a `413` error. We could update the RUM source map API [docs](https://www.elastic.co/guide/en/kibana/current/rum-sourcemap-api.html#rum-sourcemap-post) to suggest that the payload size can be configured to accommodate such cases.

### Resources

- https://github.com/elastic/sdh-apm/issues/972
- https://www.elastic.co/guide/en/kibana/current/rum-sourcemap-api.html

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @gbamparop 

**Stakeholders:** @sqren

**Comment by sqren** [comment]
@gbamparop We should reach out to the platform team and ask if the limit can be increased per API. A limit of 1mb by default is too low. Most likely a majority of users will run into this (also a hugh problem for Mobile 

cc @likethesalad
