### ISSUE TITLE
Document "project" settings in `synthetics.config.ts`

### ISSUE THREAD

**Issue by andrewvc** [elastic/observability-docs#3030]
Currently there's no documentation of how to update the `project` section of `synthetics.config.ts`. You can get a good config by using `npx @elastic/synthetics init` but for future changes this can be confusing to users.

Spotted by @bshetti

**Comment by shahzad31** [comment]
we also need to clarify the env specified in the template file are local env , not the actual running env https://github.com/elastic/synthetics/blob/main/templates/synthetics.config.ts#L3
