### ISSUE TITLE
Broken GH workflow? 

### ISSUE THREAD

**Issue by SeanHeelan** [elastic/observability-docs#3035]
When I created another issue just now in this repository I got an email from Github telling me that a workflow run had failed. See [here](https://github.com/elastic/observability-docs/actions/runs/5378727523). 

Might not be a problem, but I figured I'd let y'all know in case it is.

**Comment by bmorelli25** [comment]
Ah, yes, it is broken. Thanks! I'll look into this.

**Comment by bmorelli25** [comment]
Fixed in https://github.com/elastic/observability-docs/commit/aadcbec6aa2544afd900e50fc27cfcbe2961e23d.

Thanks again.
