### ISSUE TITLE
[REQUEST]: Update OpenTelemetry Collector exporter links

### ISSUE THREAD

**Issue by gbamparop** [elastic/observability-docs#3075]
### Description

In the "[OpenTelemetry Collector exporter for Elastic](https://www.elastic.co/guide/en/apm/guide/current/open-telemetry-known-limitations.html#open-telemetry-collector-exporter)" section there are links to `elasticexporter` which result in a 404 page as the exporter has been [removed](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13173).

### Resources

- https://www.elastic.co/guide/en/apm/guide/current/open-telemetry-known-limitations.html#open-telemetry-collector-exporter

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:**
@gbamparop 

**Stakeholders:**
@AlexanderWert 
@estolfo

**Comment by AlexanderWert** [comment]
Maybe we can link the PR that removed the `elasticexporter`?

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13173

**Comment by colleenmcginnis** [comment]
This was fixed in https://github.com/elastic/apm-server/pull/11882. The change will be live on the current branch as soon as https://github.com/elastic/apm-server/pull/11986 is merged.
