### ISSUE TITLE
[REQUEST]: Infrastructure Observability : Explaining 'dotted lines' in metrics charts

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3127]
### Background

The Hosts List by default uses a 15 minute duration which can cause charts to be unusable for end users:

_Example - spikes_
<img width="1108" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/e2d43ad5-21ce-47c2-aa43-5b50a1069c9c">

We are [implementing a change](https://github.com/elastic/obs-infraobs-team/issues/1134) to eradicate this in 8.10 but we need to explain to the end user how it works. To do this, we are implementing a popover directly in the UI with a link through to documentation explaining this behaviour:

_Popover in UI - 'why am I seeing dotted lines?'_
<img width="825" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/3259fe51-e1ee-4173-a71e-cd2b7170f22d">

### What do we need?

We need this documentation to exist so we can point users at it so they can learn how the new behaviour works.

> **How are you pointing a a document which doesn't exist yet?** : We are pointing to a short-link which we can change at any time. The UI currently links to https://ela.st/docs-infra-why-dotted - we can change this to direct to the new docs once it is ready

### When do we need it?

We need this for the 8.10 release.

# Detail of Issue

## What causes this behaviour?

- The 'spikey' chart is caused by the 'interval' in the lens chart being more frequent than that of the data being collected
- This causes lens to try and plot not existing values in the intervals where there is not data - resulting in an oscillation between the real values and what Lens perceives to be '0'

_Example spikey chart_
<img width="1108" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/e2d43ad5-21ce-47c2-aa43-5b50a1069c9c">

## When does it happen?

The 'interval' is automatically set by lens by default based on the duration chosen. If the user extends the duration then it will get rid of the spikey behaviour (alternatively, they can open the chart in lens and adjust the 'interval' temporarily but this isn't saved to the actual hosts view).

## How did we resolve it?

We are using the (relatively undocumented) 'missing data' feature in Lens. It joins in the lines between the missing data to make it smooth.

Additionally, we use the **use dotted line** setting to ensure that when data is filled, it is differentiated to data which has not been filled.

_Lens setting applied to all charts from 8.10 in Host List and fly-out_
<img width="416" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/01e2c501-9493-4d00-93ce-64d8ef84f8ff">

> **Note** : It is very important that missing data is not obscured. It needs to be clear that it is missing so users don't miss an outage because it is 'filled in'

## Show me how it works

> **Note** : We will be applying this setting to **all** charts in the Hosts feature (both the [Host List](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts?waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1691675351358,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:url,timelineOpen:!f,view:map)&_a=(dateRange:(from:now-15m,to:now),filters:!(),limit:100,panelFilters:!(),query:(language:kuery,query:%27%27))&controlPanels=(cloud.provider:(explicitInput:(fieldName:cloud.provider,id:cloud.provider,title:%27Cloud%20Provider%27),grow:!f,order:1,type:optionsListControl,width:medium),host.os.name:(explicitInput:(fieldName:host.os.name,id:host.os.name,title:%27Operating%20System%27),grow:!f,order:0,type:optionsListControl,width:medium))) and the new [Overview tab within the Host fly-outs](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts?waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1691675351358,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:url,timelineOpen:!f,view:map)&_a=(dateRange:(from:now-15m,to:now),filters:!(),limit:100,panelFilters:!(),query:(language:kuery,query:%27%27))&controlPanels=(cloud.provider:(explicitInput:(fieldName:cloud.provider,id:cloud.provider,title:%27Cloud%20Provider%27),grow:!f,order:1,type:optionsListControl,width:medium),host.os.name:(explicitInput:(fieldName:host.os.name,id:host.os.name,title:%27Operating%20System%27),grow:!f,order:0,type:optionsListControl,width:medium))&flyout=(itemId:gke-edge-oblt-edge-oblt-pool-ea052177-1hd4-Ubuntu,tabId:overview)) we are adding in 8.10. Eventually, all charts we have will leverage this functionality so the education on this is generic (and technically applicable to any lens-powered charts using this setting).

### For charts where the interval is too granular for the data emission frequency

Here is what a chart looks in 8.9 and before:

_Example spikey chart_
<img width="1108" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/e2d43ad5-21ce-47c2-aa43-5b50a1069c9c">

It will look like this from 8.10 onwards:

<img width="1561" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/432e29f5-d542-4c65-ac4c-6cff887eacf2">

> **Note** : The line is entirely dotted because it is filling in gaps on every interval where data was not sent due to the frequency of data emission being lower than that of the interval for the lens chart

### For charts where the interval is OK

It would show as a normal line - the user won't see anything:

<img width="1559" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/1f3b0884-11e2-4e15-9cde-79216cd14c37">

### How will users see/spot genuinely missing data?

> **Note:** This is a very important concern for our users so it needs to be clear on how to spot missing data

If the interval is OK, it will be very clear with this '---' line (the dotted line indicates missing data - the user may want to investigate this in case there is an outage/issue):

_Example for just a single host with missing data_
![image](https://github.com/elastic/observability-docs/assets/117740680/e70db459-025b-42bc-a763-53c8a772a602)

If the interval is too fine (i.e. the duration is so short that there are intervals with no data due to the emission frequency being relatively too long) then it is harder to spot:

_This example has an missing data points (represented in pink) _
<img width="1608" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/704da224-7011-4b1c-aa16-77d1d63ad6b6">

## Where can I check this out?

By the time you read this, you should see the new behaviour showing in [Hosts on the Edge environment](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts?waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1691675351358,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:url,timelineOpen:!f,view:map)&_a=(dateRange:(from:now-15m,to:now),filters:!(),limit:100,panelFilters:!(),query:(language:kuery,query:%27%27))&controlPanels=(cloud.provider:(explicitInput:(fieldName:cloud.provider,id:cloud.provider,title:%27Cloud%20Provider%27),grow:!f,order:1,type:optionsListControl,width:medium),host.os.name:(explicitInput:(fieldName:host.os.name,id:host.os.name,title:%27Operating%20System%27),grow:!f,order:0,type:optionsListControl,width:medium))&flyout=(itemId:%27%27,tabId:overview)).

### Resources

See issue to resolve problem:

- [x] https://github.com/elastic/obs-infraobs-team/issues/1134

To see the new behaviour, you should see it on [Hosts on Edge ](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts?waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1691675351358,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:url,timelineOpen:!f,view:map)&_a=(dateRange:(from:now-15m,to:now),filters:!(),limit:100,panelFilters:!(),query:(language:kuery,query:%27%27))&controlPanels=(cloud.provider:(explicitInput:(fieldName:cloud.provider,id:cloud.provider,title:%27Cloud%20Provider%27),grow:!f,order:1,type:optionsListControl,width:medium),host.os.name:(explicitInput:(fieldName:host.os.name,id:host.os.name,title:%27Operating%20System%27),grow:!f,order:0,type:optionsListControl,width:medium))&flyout=(itemId:%27%27,tabId:overview)) (if you look soon enough, you'll see the old behaviour)

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:** @smith @neptunian

**Comment by jrodewig** [comment]
Hey @roshan-elastic — Thanks for reaching out. This actually falls under the domain of the Observability docs team. I think this request is already on [their board](https://github.com/orgs/elastic/projects/649/views/4). You should be set! If you have any questions, @bmorelli25 should be able to help out.

**Comment by roshan-elastic** [comment]
Ah sorry @jrodewig - I completely missed that your email was Platform. Thanks!

**Comment by markov00** [comment]
nitpicking here: these are dashed lines, not dotted lines

**Comment by roshan-elastic** [comment]
@dedemorton - FYI we're going to point our UI links to the doc URL once these are created. I created an issue on our side to do this once this issue is completed:

- [ ] https://github.com/elastic/kibana/issues/165815

**Comment by roshan-elastic** [comment]
@bmorelli25 - just wondering whether I should be pinging you on this one? (someone mentioned Dede might be more focused on serverless right now)

(see description for context but we're relying on these docs being available for 8.10 as our UI will be pointing at them - hoping this is a minimal piece of work...)

**Comment by bmorelli25** [comment]
Thanks for the ping, @roshan-elastic! Yes, @dedemorton is focussing on Serverless documentation this sprint. I picked this issue up and just opened https://github.com/elastic/observability-docs/pull/3213. Thanks for the _very_ detailed issue!

Enjoy your time off.

**Comment by roshan-elastic** [comment]
Thanks @bmorelli25!
