### ISSUE TITLE
[REQUEST]: Adding documentation for different equations that the new custom threshold rule supports

### ISSUE THREAD

**Issue by maryam-saeidi** [elastic/observability-docs#3134]
### Description

We have a new custom threshold rule in observability that supports a custom equation, we would like to have a page for the possible equations that can be supported here with some examples to link to the new rule as shown below:

<img src="https://github.com/elastic/observability-docs/assets/12370520/e11764cb-1a93-461a-acad-17b8267d4cd5" width=500>

This rule will not be released in v8.10, but I didn't see a template for the next version so I used `8.10 Documentation request` template.

### Resources

@simianhacker Any suggestion about what content/examples to include on this page? Is there another similar documentation page that we can get inspiration from?

This rule can be accessed via Observability > Alerts > Rules > Create a new rule: Threshold (Technical Preview)
Make sure `xpack.observability.unsafe.thresholdRule.enabled: true` is added to the Kibana yaml config file.

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @maryam-saeidi 

**Stakeholders:**
@elastic/actionable-observability

**Comment by katrin-freihofner** [comment]
I have an additional request for documenting the aggregation types (avg, ratio,...) we provide in our alerting rules. I could not find any existing docs about this.
I'm not sure if we want to handle it separately or together with this request here.

**Comment by mdbirnstiehl** [comment]
@maryam-saeidi @katrin-freihofner I think it makes sense to include both of these things in the documentation for the custom threshold rule, for which I've opened a [draft PR](https://github.com/elastic/observability-docs/pull/3314). I could still use some examples of equations and use cases for custom equations.

**Comment by maryam-saeidi** [comment]
@mdbirnstiehl For the equation, it would be nice to have 2 types of equation:

1. Mathematical equation
For a math equation, I think we can use CPU calculation like: ([link](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts?waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1698657686898,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:default,timelineOpen:!f,view:map)&_a=(dateRange:(from:now-15m,to:now),filters:!(),limit:100,panelFilters:!(),query:(language:kuery,query:%27%27))&controlPanels=(cloud.provider:(explicitInput:(fieldName:cloud.provider,id:cloud.provider,title:%27Cloud%20Provider%27),grow:!f,order:1,type:optionsListControl,width:medium),host.os.name:(explicitInput:(fieldName:host.os.name,id:host.os.name,title:%27Operating%20System%27),grow:!f,order:0,type:optionsListControl,width:medium))))

    <img src="https://github.com/elastic/observability-docs/assets/12370520/a617a6b0-c333-443a-99f1-87a1f969ad25" width=300 />


2. Boolean logic
For boolean logic, this is an interesting use case: https://elastic.slack.com/archives/CHSSGF015/p1690270378699259?thread_ts=1690187902.145269&cid=CHSSGF015

cc: @simianhacker (maybe you have better examples for custom equations.)
