### ISSUE TITLE
Docs for Endpoint protecting Agent in 7.11

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#319]
HI - this is a quick note to drop in the docs placeholder for this feature.  I don't know if @jmikell821 has been in touch with @bjmcnic from Endpoint team on their docs, but since we extended protection to the Agent I thought we'd want to have something on Fleet / Agent side too.

The 'testing' ticket is here with some notes https://github.com/elastic/obs-dc-team/issues/426
The good questions are if we want to document which versions this is supported on or not, and the note that it is only for macOS and Windows, and only for x64 architectures.

@dedemorton I am available for questions but Ben knows more likely, so we can all keep in touch on what we want to say and where.  Thanks in adv

**Comment by jmikell821** [comment]
@EricDavisX thanks for the heads up. We'll sync with the Endpoint team to see what needs to be done, but please keep us in the loop. Adding @DonNateR since he typically documents the Agent docs.

**Comment by EricDavisX** [comment]
Thanks Dan.  @dedemorton I think we can just link to that content being created by Endpoint team and it should be enough perhaps?

**Comment by dedemorton** [comment]
@EricDavisX Agreed. It's probably worth mentioning in the agent docs that you'll be unable to stop the service if endpoint protection is running.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

As per testing covered in [#426](https://github.com/elastic/obs-dc-team/issues/426), we have prepared a summarized matrix on testing covered related to Endpoint protecting Agent in 7.11 as follows :


OS supported | Unable to Kill Agent | Stop Agent | Restart Agent
-- | -- | -- | --
macOS 10.15 x64 | Working Fine | Working Fine | Working Fine
macOS 10.15.6 x64 | Working Fine | Working Fine | Working Fine
macOS 11.0.1 x64 | Working Fine | Working Fine | Working Fine
Windows 8.1 x64 | Working Fine | Working Fine | Working Fine
Windows 10 x64 | Working Fine | Working Fine | Working Fine
Windows server 2012 R2 x64 | Working Fine | Working Fine | Working Fine
Windows Server 2016x64 | Working Fine | Working Fine | Working Fine
Windows Server 2019x64 | Working Fine | Working Fine | Working Fine

Further, we have below 01 query as follows: 
QUERY: Could you please provide us docs link related to this feature if any further validations are required from our side.

Thanks
QAS

**Comment by dedemorton** [comment]
All the details are pretty much covered in the Endpoint docs, so I've just added a short section to the overview and included a pointer to the security docs: https://github.com/elastic/observability-docs/pull/372.

**Comment by EricDavisX** [comment]
closing this out as we did the docs, nice.
