### ISSUE TITLE
[REQUEST]: Host Metrics : Rename metric name

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3210]
### Description

Hi there,

Can we rename the following metric in the docs?

https://www.elastic.co/guide/en/observability/current/host-metrics.html#key-metrics-network

### Current

<img width="885" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/83ee8749-b145-4f70-8107-969172882ccf">

### Changes

1. 
**Current** : `Disk Space Availability (%)`
**New** : `Disk Usage - Available (%)`

2. 
**Current** : `Disk Space Usage (%)`
**New** : `Disk Usage - Used (%)`

3. 
**Current** : `Disk Space Available`
**New** : `DELETE THIS METRIC` (we don't use it right now so will add it in when we do)

### Resources

Feel free to check edge for where these are used:

[Host List](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts?waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1693989886732,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:url,timelineOpen:!f,view:map)&_a=(dateRange:(from:now-15m,to:now),filters:!(),limit:100,panelFilters:!(),query:(language:kuery,query:%27%27))&controlPanels=(cloud.provider:(explicitInput:(fieldName:cloud.provider,id:cloud.provider,title:%27Cloud%20Provider%27),grow:!f,order:1,type:optionsListControl,width:medium),host.os.name:(explicitInput:(fieldName:host.os.name,id:host.os.name,title:%27Operating%20System%27),grow:!f,order:0,type:optionsListControl,width:medium))&tableProperties=(detailsItemId:gke-edge-oblt-edge-oblt-pool-3109d673-dbmq-Ubuntu,pagination:(pageIndex:0,pageSize:10),sorting:(direction:desc,field:diskSpaceUsage)))

[Fly Out](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/hosts?waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1693989886732,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:default,timelineOpen:!f,view:map)&_a=(dateRange:(from:now-15m,to:now),filters:!(),limit:100,panelFilters:!(),query:(language:kuery,query:%27%27))&controlPanels=(cloud.provider:(explicitInput:(fieldName:cloud.provider,id:cloud.provider,title:%27Cloud%20Provider%27),grow:!f,order:1,type:optionsListControl,width:medium),host.os.name:(explicitInput:(fieldName:host.os.name,id:host.os.name,title:%27Operating%20System%27),grow:!f,order:0,type:optionsListControl,width:medium))&tableProperties=(detailsItemId:gke-edge-oblt-edge-oblt-pool-3109d673-t9hj-Ubuntu,pagination:(pageIndex:0,pageSize:10),sorting:(direction:desc,field:cpu)))

[Detail View](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/detail/host/gke-edge-oblt-edge-oblt-pool-3109d673-dbmq?_a=(autoReload:!f,refreshInterval:5000,time:(from:%272023-09-06T09:21:41.496Z%27,interval:%3E%3D1m,to:%272023-09-06T09:36:41.496Z%27))&assetName=gke-edge-oblt-edge-oblt-pool-3109d673-dbmq&waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1693993036640,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:default,timelineOpen:!f,view:map))

**Note** : Depending on when you check this, the charts may or may not have been renamed (see this [issue](https://github.com/elastic/kibana/issues/165812))

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @roshan-elastic 
(I'm away from 7th-26th Sept so @smith might be your best contact)

**Stakeholders:**
@smith @neptunian

**Comment by dedemorton** [comment]
Just to confirm...the target here is 8.11, correct?

**Comment by smith** [comment]
> Just to confirm...the target here is 8.11, correct?

Correct.

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/3328
