### ISSUE TITLE
[REQUEST]: Add a data store section to the AI Assistent documentation

### ISSUE THREAD

**Issue by 111andre111** [elastic/observability-docs#3211]
### Description

For Security AI Assistant we already have a data disclaimer like this:
https://www.elastic.co/guide/en/security/current/security-assistant.html#data-information

It would be good if there could be something similar on the Observability AI Assistant section:
https://www.elastic.co/guide/en/observability/current/obs-ai-assistant.html

### Resources

https://www.elastic.co/guide/en/security/current/security-assistant.html#data-information
https://www.elastic.co/guide/en/observability/current/obs-ai-assistant.html

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @grabowskit 

**Stakeholders:**

**Comment by mdbirnstiehl** [comment]
Hi @111andre111, this info was added to the docs with the 8.10 release. You can see it [here](https://www.elastic.co/guide/en/observability/current/obs-ai-assistant.html#data-information).

**Comment by 111andre111** [comment]
Thanks a lot for driving this. 👍
