### ISSUE TITLE
[REQUEST]: Update APM Server processing and performance numbers

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#3215]
### Description

The data on this page is out of date: https://www.elastic.co/guide/en/apm/guide/current/processing-and-performance.html

### Resources

* @dmathieu has been working on updated numbers in [this google doc](https://docs.google.com/document/d/1Vb-KzXZBJ9I01LOQAONru69SDSH_LDQjOenxyJ3FcXk/edit) (sorry, internal link).
* Related issue: https://github.com/elastic/apm-server/issues/7842.

### Collaboration

Other (please describe below in the Point of contact section).

### Point of contact.

**Main contact:** @dmathieu 

**Stakeholders:** APM Server team

**Comment by dmathieu** [comment]
cc @elastic/apm-server FYI

**Comment by bmorelli25** [comment]
Duplicate of https://github.com/orgs/elastic/projects/649/views/42?pane=issue&itemId=42400435.
