### ISSUE TITLE
Add tutorials and quick start videos to the observability guide

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#323]
The observability docs team will partner with the education team to publish tutorials in the observability guide. This issue is to track cross-team tasks and communication.

Note: This repository is public, so please do not include links to internal documents.

**Participants and stake holders:**

Writing team: @bmorelli25, @dedemorton, @EamonnTP 
Education team: @melvynator 

**Goals**

Deliver tutorial and guides to help customers solve real-world use cases.

**Tasks**

- [x] Embed videos in the current version of the observability guide. Issue: https://github.com/elastic/observability-docs/pull/324 [@bmorelli25] 
- [x] Provide education team with asciidoc tutorial template and work to refine it. PR: https://github.com/elastic/observability-docs/pull/54

**Open issues and questions**

* Does the education team need help ramping up on how to contribute to the docs?

**Comment by bmorelli25** [comment]
Closing this as all tasks are completed. Additional information on the cloud monitoring tutorials created by the education team can be found in https://github.com/elastic/observability-docs/issues/299.
