### ISSUE TITLE
[REQUEST]: Add versions to android docs

### ISSUE THREAD

**Issue by LikeTheSalad** [elastic/observability-docs#3240]
### Description

I'd like to show different versions of the [Android docs](https://www.elastic.co/guide/en/apm/agent/android/current/index.html), similarly to how it's currently done for [iOS's](https://www.elastic.co/guide/en/apm/agent/swift/current/index.html).

At the moment there would only be one version to choose from: `0.x`.

### Resources

Android's current doc: https://www.elastic.co/guide/en/apm/agent/android/current/index.html
iOS's current doc: https://www.elastic.co/guide/en/apm/agent/swift/current/index.html 

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @LikeTheSalad 

**Stakeholders:**

**Comment by colleenmcginnis** [comment]
👋  @LikeTheSalad This should be relatively easy to implement. Here's what I propose: 

- [ ] @LikeTheSalad create a `0.x` branch in /apm-agent-android
- [ ] @colleenmcginnis open a PR in /docs to add the new branch to the config
- [ ] [long term] @LikeTheSalad decide how your team will keep `main` and version branches (`0.x`, in the future `1.x`, etc) in sync
    - I'm not sure how they do this in /apm-agent-ios. In larger repos like /observability-docs we use mergify, but it doesn't look like that's the case in /apm-agent-ios.

**Comment by bmorelli25** [comment]
> I'm not sure how they do this in /apm-agent-ios. In larger repos like /observability-docs we use mergify, but it doesn't look like that's the case in /apm-agent-ios.

The APM agent repositories work a little differently. In general, APM agent documentation is only updated in `main`. Only when a new release is cut, is the documentation updated in release branches. So, at release time and as a part of the release process, all changes in `main`, including docs, are force pushed to (in this example) `0.x`.

**Comment by LikeTheSalad** [comment]
Hi @colleenmcginnis 

Thanks, I've just created the `0.x` branch, please let me know if there's something else I can help with 👍 

Regarding keeping branches in sync from `main`, as mentioned by @bmorelli25, I think that sounds about right, although I'm guessing that by the time we bump our major version number and create a `1.x` branch, the latest changes from `main` would only go to the branch `1.x` and not to `0.x`, unless we backport some changes into the `0.x` versions in the future. That'd be my guess but I'm not fully sure, since we still haven't gone GA with this project, we haven't gotten to that scenario yet.

**Comment by colleenmcginnis** [comment]
This is live! https://www.elastic.co/guide/en/apm/agent/android/current/intro.html
