### ISSUE TITLE
[REQUEST]: Infrastructure UI : Inventory : Updated Fly-out

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3250]
### Description

We will be deprecating the existing Host fly-out within Inventory and replacing it with a new consistent version (as used in Hosts):

_Current behaviour_
![inventory - existing fly-out](https://github.com/elastic/observability-docs/assets/117740680/2c04fbc2-a8f2-41a2-b41d-4535c2a6ced2)

_New behaviour_

TBC - will provide but it'll use this new fly-out instead as used within 'Hosts'

<img width="744" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/23d46aba-81be-402b-993d-bcb8b5ef4896">

### Docs which would need changing

It will be this page:

https://www.elastic.co/guide/en/observability/current/view-infrastructure-metrics.html

_Specifically, this section:_
<img width="899" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/8a9d2b65-6c17-4a5e-bb4b-4354254202b6">

### Resources

**New behaviour**
[See latest edge build](https://edge-oblt.kb.us-west2.gcp.elastic-cloud.com/app/metrics/inventory?inventoryViewId=%270%27&waffleTime=(currentTime:1695896903735,isAutoReloading:!f)&waffleFilter=(expression:%27%27,kind:kuery)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),timelineOpen:!f,view:map)) (at the time of writing, this is not showing the new version yet)

**Old behaviour**
[See demo environment](https://demo.elastic.co/app/metrics/inventory?inventoryViewId=%270%27&waffleFilter=(expression:%27%27,kind:kuery)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),timelineOpen:!f,view:map))

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:** @neptunian @smith

**Comment by roshan-elastic** [comment]
This will be available in 8.11

**Comment by dedemorton** [comment]
I should "own" this issue since I will be working on https://github.com/elastic/obs-docs-projects/issues/138 too.

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/3328
