### ISSUE TITLE
Integrations: Setup or Installation steps missing for MSSQL and IIS integrations

### ISSUE THREAD

**Issue by SubhrataK** [elastic/observability-docs#3270]
The docs for MSSQL integration and IIS integration do not have the "Set up" section as is available in other integrations. Please find the screenshot from Apache Tomcat integration.
<img width="760" alt="Screenshot 2023-10-12 at 12 49 46 PM" src="https://github.com/elastic/observability-docs/assets/115459202/f472bd0f-f10e-4bca-8e06-ccdd19774148">

However, the issue is low priority since the UI is designed in a way that the user will be able to navigate easily and follow the steps, without referring to the documentation

**Comment by colleenmcginnis** [comment]
Done in https://github.com/elastic/integrations/pull/8240 + https://github.com/elastic/integrations/pull/8241. 🎉

**Comment by shmsr** [comment]
@colleenmcginnis Could you please check https://github.com/elastic/integrations/pull/8240 again? There are a few more review comments. It seems that there are a few issues that need to be addressed. Thanks!
