### ISSUE TITLE
[incorrect] Feedback from `/serverless/observability/aiops-generate-anomaly-alert`

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#3273]
## What do you see?

I have been unable to successfully validate that the steps documented in this topic actually result in alerts. The rule that gets defined doesn't show up on the Alerts tab (it's only under the anomaly job), and I have been unable to see any alerts resulting from test jobs.

Sooooo....

If we don't get review input from SMEs by EOD tomorrow, we should pull this topic from the release.

## What were you expecting to see?

Validated docs. :-)

**Comment by bmorelli25** [comment]
> I have been unable to successfully validate that the steps documented in this topic actually result in alerts.

Due to lack of time or lack of input from SMEs? In other words, is this something that we can do ourselves?
