### ISSUE TITLE
[incorrect] Feedback from `/serverless/observability/create-slo-burn-rate-alert-rule`

### ISSUE THREAD

**Issue by mgiota** [elastic/observability-docs#3275]
## What do you see?

In Step 3 of how to create an slo burn rate rule you say `Select the SLO burn rate rule type from the SLO use case.` There is no grouping of rules anymore in the Create Rule Flyout of the Observability UI. Rules are still grouped in Stack Management though. See screeshots below

### Create rule through Observability (no SLO use case anymore, all rule types are listed together)
<img width="300" alt="Screenshot 2023-10-13 at 10 24 30" src="https://github.com/elastic/observability-docs/assets/2852703/56c13870-2d5e-46ca-8ea0-567085ef365e">

### Create rule through Stack Management
<img width="300" alt="Screenshot 2023-10-13 at 10 25 13" src="https://github.com/elastic/observability-docs/assets/2852703/018cb68d-d7c9-4870-a8cb-4cb74abf43d9">

## What were you expecting to see?
Step 3 should just say `Select the SLO burn rate rule type`

**Comment by dedemorton** [comment]
This didn't autoclose when https://github.com/elastic/staging-serverless-observability-docs/pull/127 was merged, so closing now.
