### ISSUE TITLE
[missing] Feedback from `/serverless/observability/create-slo-burn-rate-alert-rule`

### ISSUE THREAD

**Issue by mgiota** [elastic/observability-docs#3276]
## What do you see?
Everything looks good. I was just wondering if we could rephrase this sentence `Get alerts when your SLO burn rate is too high over a defined period of time.` to what I suggest below, as a quick reminder of what SLO burn rate means.

## What were you expecting to see?

`Get alerts when the rate at which SLOs are failing is too high over a defined period of time.`

You can ignore this feedback, if it doesn't make sense. It is already good as it is!

**Comment by dedemorton** [comment]
Closed in https://github.com/elastic/staging-serverless-observability-docs/pull/127.
