### ISSUE TITLE
[missing] Feedback from `/serverless/observability/apm-reduce-your-data-usage`

### ISSUE THREAD

**Issue by chrisdistasio** [elastic/observability-docs#3278]
## What were you expecting to see?
should we mention something about storage explorer here?  its a good resource for understanding storage behavior.

**Comment by bmorelli25** [comment]
Does storage explorer exist in Serverless? We took out all of the docs for it because we couldn't find it in the UI.

**Comment by chrisdistasio** [comment]
important point you raise :)

please disregard.  we will open a ticket to re-introduce the storage explorer as the apis become available

**Comment by bmorelli25** [comment]
Phew! Sounds good. Regardless, thanks for the feedback!
