### ISSUE TITLE
[confusing] Feedback from `/serverless/observability/apm-agent-ecs-reformatting`

### ISSUE THREAD

**Issue by chrisdistasio** [elastic/observability-docs#3282]
## What were you expecting to see?

same comment as previous issue regarding filebeat setup.  have we tested that this works?  when i follow link through to filebeat setup it states that auth is user based.  managed service will require API auth.

**Comment by bmorelli25** [comment]
I'm going to close this issue as a duplicate of https://github.com/elastic/observability-docs/issues/3280. We'll fix the entire topic as a part of that issue.
