### ISSUE TITLE
Updates to Mobile Docs for GA

### ISSUE THREAD

**Issue by bryce-b** [elastic/observability-docs#3377]
Several portions of the apm quick-start guide needs to be updated:
https://www.elastic.co/guide/en/apm/guide/current/apm-quick-start.html
- Android needs to be added to the quick start guide.
  - Installation document here : https://www.elastic.co/guide/en/apm/agent/android/current/setup.html
- Android needs to be added to https://www.elastic.co/guide/en/apm/guide/current/_step_3_install_apm_agents.html
- Remove `technical preview` warning from iOS tab.
<img width="739" alt="Screenshot 2023-11-21 at 07 25 32" src="https://github.com/elastic/observability-docs/assets/75274611/32cc48c8-c040-4c6f-9ae0-08bb6d382bd0">

**Comment by bryce-b** [comment]
Additionally, can we verify there are no more references to tech preview else where in the docs?

**Comment by akhileshpok** [comment]
@colleenmcginnis - I hope that all the work related to the mobile APM solution doc updates is in-hand and on track for completion in 8.12, as we are planning to go GA! Thanks

**Comment by colleenmcginnis** [comment]
👍   I plan to start this work in our next sprint, which starts next week. I'll reach out if I need anything else from you all.
