### ISSUE TITLE
[Discuss]: Update Observability landing page to match the new docs landing page design

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#3399]
### Description

With a few tweaks, I think we can carry the look/feel of the new landing page over to the Observability docs. Here's a rough idea of what I'm talking about. I don't like the graphic elements I'm showing in this mockup because they take up too much space...I'm just including them to show how we can extend the look easily to our landing page without any substantial changes to the layout or content.

I think we'd want to use a bigger title font, too, and work on alignment for sure.

By including the navigation bar with "Browse all docs" and "API docs" users could navigate easily to the main doc page.

<img width="1731" alt="image" src="https://github.com/elastic/observability-docs/assets/14206422/d1ae2124-4ac1-48c6-8808-8c5e5f7bb88f">

### Resources

Work in progress landing page is here: https://docs_2847.docs-preview.app.elstc.co/guide/index.html

### Which documentation set does this change impact?

Stateful only

### Feature differences

n/a

### What release is this request related to?

N/A

### Collaboration model

Unknown

### Point of contact.

**Main contact:** TBD

**Stakeholders:** Obs writers and users

**Comment by colleenmcginnis** [comment]
>The font is huge?

Do you think this is just about the intro text? It is slightly larger than the body text to mimic a "hero" component, but we could make it the same size as the body text if that's preferred. 

>The What do you want to Observe - I would imagine that we want the first/default selection to be Logs, given our "land with logs" strategy.

That's a quick fix! Any other tabs we want to move around while we're doing it?

>Maybe an intro video on the landing page that shows the power of collecting logs, and how much more we can do as you add more signals?

Does a current video like this exist yet? If it does we should be able to add it pretty easily.

**Comment by mdbirnstiehl** [comment]
I think the logs cards should be updated as well to include the stream any log, parse logs, and filter logs pages as well. Let me know if/what help you need there.

**Comment by dedemorton** [comment]
After listening to the recording of the landing page discussion this week, I'm not sure we should try to align with the look/feel of the main landing page until _after_ the landing page workgroup has had more time to discuss the design of sub-landing pages. It sounds like our design won't work for all teams (especially teams that have multiple books to wrangle).

I think acting on Steve's feedback now is a good idea, though!

**Comment by bmorelli25** [comment]
Closing this issue. DeDe will open a new issue with a tighter scope.
