### ISSUE TITLE
[Request]: Remove beta labels from SLO docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#3402]
### Description

The beta label is being removed from the "classic" docs in https://github.com/elastic/observability-docs/pull/3400. At some point, we will need to apply this change to the serverless docs, too. 

Timing TBD

### Resources

n/a

### Which documentation set does this change impact?

Serverless only

### Feature differences

n/a

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @paulb-elastic 

**Stakeholders:** n/a

**Comment by paulb-elastic** [comment]
@dedemorton the 2x PRs we wanted to get in have now been merged, so this is now ready to work on (remove beta from SLO docs for serverless).  Thanks.

**Comment by dedemorton** [comment]
@paulb-elastic Thanks! I'll be OOTO for a few weeks over the holidays, so I threw up a quick PR: https://github.com/elastic/staging-serverless-observability-docs/pull/208

**Comment by paulb-elastic** [comment]
Thank you so much @dedemorton

**Comment by bmorelli25** [comment]
Thanks, Paul and DeDe. I'll merge DeDe's PR.
