### ISSUE TITLE
[Request]:Recipe to autoscale Elastic synthetic agents to monitor from private locations? 

### ISSUE THREAD

**Issue by dbalijapalli0264** [elastic/observability-docs#3405]
### Description

Hello Elastic Team,
Could you please provide a document or a recipe for synthetic agent running on ECK Operator to autoscale? Or is autoscaling synthetic agents even a possible thing?

Following this doc: https://github.com/elastic/observability-docs/edit/main/docs/en/observability/synthetics-private-location.asciidoc
This one does not show how to have multiple private locations that can autoscale based on a specific resource. 
For instance I could set SYNTHETICS_LIMIT_BROWSER = 10 (to fall within the recommended slots) But I would like to autoscale if I have more than 10 tests at a given time.

If you already have a recipe, please point me to it. 

### Resources

https://github.com/elastic/observability-docs/edit/main/docs/en/observability/synthetics-private-location.asciidoc
OR
https://www.elastic.co/guide/en/observability/master/synthetics-private-location.html#synthetics-private-location-scaling

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

Currently we are implementing Elastic-syntheitcs V8.10.1 and on ECK Operator version 2.10.

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @
@Paul
**Stakeholders:**

**Comment by bmorelli25** [comment]
Hi @dbalijapalli0264 👋 . Thanks for reaching out. For product support, please create a new topic in our [discuss forum](https://discuss.elastic.co/c/observability/82).
