### ISSUE TITLE
[Request]: Will 2 synthetic agents with the same agent policy let us create 4 browser monitors?

### ISSUE THREAD

**Issue by dbalijapalli0264** [elastic/observability-docs#3407]
### Description

Hello Elastic team, 
Looks like we could use your help in understand the behavior of the synthetic agents run on ECK Operator.

### Resources

Issue:
We created 2 replicas of synthetic-agent in the deployment, and they both register under the same agent-policy as 2 agents. But I can have only one private-locations as I get an error saying the agent policy is already in use. when trying to create the 2nd private-location for the second agent I have deployed. 

Question: 
1. My question is that, in free Elastic version 8.10.1  Could we create more than one private-location if we deploy more than one agent?

.Here is my spec
- spec:
-   policyID: eck-agent
-   version: 8.10.1
-   image: elastic-agent-complete:8.10.1
-   kibanaRef:
-     name: kb-apm
-   fleetServerRef:
-     name: apm-fleet-server
-   mode: fleet
-   deployment:
-     replicas: 2

2. If I add this env variable, as stated in the document here, https://github.com/elastic/observability-docs/edit/main/docs/en/observability/synthetics-private-location.asciidoc,  will it let me create 20 browser monitors, as I have 2 agents running with that agent-policy with the below setting that is overriding the default 2 browser checks per agent? 
          - name: SYNTHETICS_LIMIT_BROWSER
            value: "10"

 

### Which documentation set does this change impact?

Unknown

### Feature differences

I'm using Elastic Synthetics version 8.10.1

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @
@Paul
**Stakeholders:**

**Comment by bmorelli25** [comment]
Hi @dbalijapalli0264 👋 . Thanks for reaching out. For product support, please create a new topic in our [discuss forum](https://discuss.elastic.co/c/observability/82).
