### ISSUE TITLE
[Request]: Documentation for Log threshold alert details page

### ISSUE THREAD

**Issue by benakansara** [elastic/observability-docs#3410]
### Log threshold alert details page
- To access this page, go to Observability → Alerts.
- Open Log threshold alert flyout (by clicking on Reason message).
- Click on "Alert details"

There are 3 sections in the alert details page:

## 1. Threshold breached chart
<img width="1264" alt="Screenshot 2023-12-06 at 00 44 57" src="https://github.com/elastic/observability-docs/assets/69037875/1a075b44-4c0d-43dd-b6e1-11b10197f141">

## 2. Log rate analysis
<img width="1236" alt="Screenshot 2023-12-06 at 00 46 35" src="https://github.com/elastic/observability-docs/assets/69037875/e1e58682-c619-4c05-bb60-43f273943a71">

## 3. Log threshold alerts history
<img width="1240" alt="Screenshot 2023-12-06 at 00 47 05" src="https://github.com/elastic/observability-docs/assets/69037875/ebac72fe-3067-4967-8636-0c1e53821723">

### Resources

https://github.com/elastic/kibana/issues/150854

### Which documentation set does this change impact?

Stateful only

### Feature differences

This feature is not available in Serverless.

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @benakansara 

**Stakeholders:** @vinaychandrasekhar @paulb-elastic @maryam-saeidi

**Comment by mdbirnstiehl** [comment]
Hi @benakansara, I believe this [Threshold breaches](https://www.elastic.co/guide/en/observability/current/triage-threshold-breaches.html) page covers this information, but I just wanted to check and make sure nothing else needs to be added here.

**Comment by jasonrhodes** [comment]
@benakansara is this still needed? if so, can we create an issue in elastic/observability-docs and reach out to @dedemorton about it, otherwise we can just close this if it's no longer needed. Thanks!

**Comment by benakansara** [comment]
@mdbirnstiehl sorry I missed your comment. The [Threshold breaches](https://www.elastic.co/guide/en/observability/current/triage-threshold-breaches.html) covers the features of Log threshold alert details page.

@jasonrhodes I believe this ticket was intended for elastic/observability-docs, I somehow didn't notice @mdbirnstiehl's comment earlier. Since above documentation covers same features as Log threshold alert details page and we might deprecate Log threshold rule in future, I think we don't need to create a separate documentation for it.
