### ISSUE TITLE
Onboard NGINX using integrations (part one)

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#3411]
Document the user flow for onboarding nginx logs and metrics using the integration, exploring those logs and metrics, and finding and resolving issues.

**Iteration 1:**

- Overview of nginx
   - [x]    What you’ll learn
   - [x]    Prerequisites
- Add and configure nginx integration
- Configure and install agent
   - [x]    Standalone (start here)
   - [x]    Fleet
- [x] Explore logs and metrics

Iteration 2: https://github.com/elastic/observability-docs/issues/3717

**Comment by bmorelli25** [comment]
@mdbirnstiehl to outline end-to-end flow, identify parts, and break into smaller chunks
