### ISSUE TITLE
Audit and update Kibana Serverless/Stateful links

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#3431]
### Summary

We now have the ability to conditionally change in-product links to point to a different location for our Serverless and Stateful offerings. @lcawl has opened the first PR here: https://github.com/elastic/kibana/pull/173343.

Using the 🤖's Test Serverless Observability project, we should go through the Serverless UI and update all of our documentation links to point to Serverless documentation instead of stateful documentation.

**Comment by dedemorton** [comment]
Should I close this issue? https://github.com/elastic/obs-docs-projects/issues/136

**Comment by dedemorton** [comment]
Let's keep both issues open for now and use this one to track updating the doclink service.

https://github.com/elastic/obs-docs-projects/issues/136 is sort of a meta issue that tracks related tasks.

**Comment by dedemorton** [comment]
I've updated the docslink service to include serverless links for observability (see https://github.com/elastic/kibana/pull/174725). However there are still quite a few links in the Obs UI that are not defined in the doclinks service.

The conditional logic required to provide a serverless-specific link is only available for links that are defined in the doclinks service.

I'll try to do an inventory of all the remaining links that need to be updated, but it would be helpful to have a complete list of all the links that are defined in the code _and_ appear in the observability UIs. I'm not sure how to do this easily for serverless.
