### ISSUE TITLE
[Logs] Log Details Flyout Design

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#3479]
We want to redesign the log details flyout to make sure users know how the information is useful. We want to avoid simply given the user the same information in a different way without providing guidance on how to use it.

Potential organization to consider:

- Log origin? service.name
- Service origin? host.name, orchestrator.cluster.name
- Location? cloud.provider, cloud.region, cloud.instance.id
- Shipper? agent.name, agent.type

[Figma](https://www.figma.com/file/j1ycRFoVsbmXHIhqWsj6cj/Log-detail-flyout?type=whiteboard&node-id=0-1&t=2jHnGj6EQDYuJMD7-0)

Design issue: https://github.com/elastic/observability-dev/issues/3028

**Comment by bmorelli25** [comment]
Blocked until card sorting is complete.
