### ISSUE TITLE
[Request]: Universal Profiling within Hosts

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3481]
### What?
We will be integrating Universal Profiling into the Hosts views

### When?
8.12 (TBC whether this will be turned on/off by default - it can be controlled by a feature flag)

### Why?
Users who are investigating high CPU usage on a host want to know what is consuming this CPU. Profiling helps users identify the exact usage...right down to the single line of application code.

This will help users:

(a) Resolve utilisation issues with their hosts quicker by identifying the root cause of the resource usage
(b) Help users optimise their application code to be more performant and reduce their overall infrastructure costs

> **Note** : Wondering where we should talk about this in the docs? E.g. do we need to update the [host docs](https://www.elastic.co/guide/en/observability/current/analyze-hosts.html)?

### Resources

_Screenshot_
![image](https://github.com/elastic/observability-docs/assets/117740680/3d6710b3-443f-4599-a8e9-e11345ce43df)

[General profiling documentation](https://www.elastic.co/guide/en/observability/current/universal-profiling.html)

### Which documentation set does this change impact?

Stateful only

### Feature differences

At the time of writing, profiling is only available in stateful and for cloud customers (not self-managed)

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @roshan-elastic (PM)

**Stakeholders:** @iogbole (PM) @smith

**Comment by roshan-elastic** [comment]
@iogbole FYI I'm seeing whether the docs team needs to update the Host documentation to explain this within the context of hosts

**Comment by bmorelli25** [comment]
> 8.12 (TBC whether this will be turned on/off by default - it can be controlled by a feature flag)

@roshan-elastic is this going live in 8.12 without a feature flag?

**Comment by roshan-elastic** [comment]
Hey @bmorelli25 - there will be a feature flag so users can turn it off but it will be on by default.

@mykolaharmash - Would you mind confirming your current understanding? Just want to check I'm right about this (if I'm wrong, we can pick up separately).

**Comment by mykolaharmash** [comment]
You're correct @roshan-elastic 💯

**Comment by roshan-elastic** [comment]
@bmorelli25 cool gif here demo'ing it:

![Discoverable profiling](https://github.com/elastic/observability-docs/assets/117740680/b907284b-aaaa-4964-802b-951c434c47fd)

**Comment by mykolaharmash** [comment]
Closing this one as [the docs PR](https://github.com/elastic/observability-docs/pull/3527) was merged 🎉
