### ISSUE TITLE
[Custom Threshold Rule] Update the documentation to reflect GA status

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#3549]
### Description

In 8.13 the Custom Threshold Rule will be updated from Beta to GA, so the documentation labelling needs to be updated to reflect this status.

### Resources

The main issue for the UI changes are in https://github.com/elastic/kibana/issues/172942
The project, that includes links to other tasks, is https://github.com/elastic/actionable-observability/issues/114

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

Same in stateful and serverless

### What release is this request related to?

8.13

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @fkanout 

**Stakeholders:**
- @vinaychandrasekhar

**Comment by bmorelli25** [comment]
Same question here. Will the change happen in Serverless at the same time as the 8.13 release?

**Comment by paulb-elastic** [comment]
@bmorelli25 serverless won't have the same date as stateful, as it will be aligned with the PR being merged, then once it's been released to production

**Comment by fkanout** [comment]
@bmorelli25 @dedemorto, FYI, the linked PR that GA the Custom Threshold rule will be merged today.

**Comment by dedemorton** [comment]
I'm going to move this issue to the current sprint so I can have the PRs up and ready to merge.

**Comment by bmorelli25** [comment]
Thanks, @fkanout!

> I'm going to move this issue to the current sprint so I can have the PRs up and ready to merge.

Sounds good, @dedemorton
