### ISSUE TITLE
[apm] Make apm guide URLs apm specific and unified

### ISSUE THREAD

**Issue by simitt** [elastic/observability-docs#3573]
The apm guide recently moved to https://www.elastic.co/guide/en/observability/current/apm.html. The URLs of the guide should now be following a common naming schema indicating to be part of the `apm` guide. 
For example, the synthetics guide prefixes everything with `synthetics-` (https://www.elastic.co/guide/en/observability/8.12/synthetics-support-matrix.html). 

At the moment this leads to several URL that look like generic observability URLs, but only contain apm specific content, such as https://www.elastic.co/guide/en/observability/8.12/release-notes-8.12.html. 

cc @colleenmcginnis 

---

Once the link to the release notes change, a bit of follow up work must happen so that releases point to the right documentation:
- if change for already released versions, links in github releases need to change (https://github.com/elastic/apm-server/releases/tag/v8.12.0)
- a comment needs to be added to https://github.com/elastic/infra/pull/40558/files, indicating what the new release note URL for apm is

**Comment by simitt** [comment]
@bmorelli25 I see that this considered for next sprint in January, has there been any update on this? 
For now, we move forward with the release note URLs as they are.

**Comment by bmorelli25** [comment]
Hi @simitt. I have a PR open to address this problem: https://github.com/elastic/observability-docs/pull/3674.

**Comment by bmorelli25** [comment]
Draft infra PR is up and linked above this comment.
