### ISSUE TITLE
[Docs] Add required privileges to view logs explorer

### ISSUE THREAD

**Issue by mdbirnstiehl** [elastic/observability-docs#3629]
Add the privileges required to view Logs Explorer to the Explore logs docs. 

Probably also need to update the [Kibana privileges](https://www.elastic.co/guide/en/kibana/current/kibana-privileges.html) docs.

Relates to [Issue 177067](https://github.com/elastic/kibana/issues/177067)

**Comment by mdbirnstiehl** [comment]
@elastic/obs-ux-logs-team Do we know which privileges are required to view Logs Explorer? I assume at least `read` for discover. Are `integrations` privileges required?

**Comment by gbamparop** [comment]
> Are `integrations` privileges required?

I think it is for the dataset selector, @tonyghiani can you confirm?

**Comment by tonyghiani** [comment]
> I think it is for the dataset selector

That's correct, without the `integrations` privileges, we wouldn't retrieve the integrations shown in the data source selector, it is required to keep that working.
