### ISSUE TITLE
[Synthetics Serverless] Add the pricing page URL in when it's available

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#3635]
### Description

The Synthetics in Serverless docs needs to have a link to the pricing page, but it's not currently available.

As described in [here](https://github.com/elastic/staging-serverless-observability-docs/pull/216#discussion_r1497735865) this has currently been commented out, but should be added in, with the correct URL, when @drewpost has it available

### Resources

Docs originally created for Synthetics in Serverless in https://github.com/elastic/staging-serverless-observability-docs/pull/216

### Which documentation set does this change impact?

Serverless only

### Feature differences

This link is specific to the pricing for synthetics in serverless

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @drewpost will provide the URL

**Stakeholders:**
- @paulb-elastic

**Comment by paulb-elastic** [comment]
Drew has said the pricing page should be available in the next week or so, so we will be able to link through to it then.

**Comment by dedemorton** [comment]
There's a pricing URL that went live this week: https://cloud.elastic.co/cloud-pricing-table?productType=serverless&project=observability

Is this the correc t link? Is it ready for us to link to for synthetics?

**Comment by paulb-elastic** [comment]
Thanks @dedemorton!!

@drewpost are you ok for this to be linked to now?

**Comment by drewpost** [comment]
Hi @dedemorton - I'm OK with this link however...  Are Security and ES3 linking to the table you linked to above OR the page here https://www.elastic.co/pricing/serverless-observability 

That page I linked to have a LOT more context about the billing dimensions and how it all works.
