### ISSUE TITLE
[Request]: Update AI assistant documentation for 8.13

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#3652]
### Description

Request submitted by @grabowskit 
~We need to get the `query` (previously called `esql`) and `context` functions into the 8.13 documentation for the AI Assistant.~ It sounds like we do not really want to externalize these functions after all based on Dario's feedback on the draft PR.
AWS Bedrock support is coming too.

### Resources

https://www.elastic.co/blog/whats-new-elastic-observability-8-13-0

@grabowskit Can you point me to related issues/PRs that describe the new functions? Thanks!

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

TBD

@dgieselaar Can you identify any differences for stateful vs serverless?

### What release is this request related to?

8.13

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @dgieselaar 

**Stakeholders:** @tomgab

**Comment by dedemorton** [comment]
This is going to take more than 4 hours because I need to set up the AI assistant to view the UI.

**Comment by dedemorton** [comment]
@dgieselaar I've set up the AI Assistant in the QA cloud environment, but I only see a subset of the available functions when I click **Select a function**.  

![image](https://github.com/elastic/observability-docs/assets/14206422/2d62678b-b197-4ae3-b30b-b2c341da3a60)

Interestingly when I ask the Assistant which functions are available, it gives me a long list that includes the `query` and `context` functions. Are some of the functions being hidden in the UI intentionally right now? Or maybe I'm doing something wrong?

**Comment by dgieselaar** [comment]
@dedemorton yes, some of them are hidden from the UI, ie they are available to call for the assistant only.
