### ISSUE TITLE
a broken link for beat (auditbeat) download is on the 8.0.0 / master page

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#369]
https://www.elastic.co/guide/en/beats/auditbeat/master/auditbeat-installation-configuration.html
 has curl call pointing to
https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.0.0-amd64.deb

 which is a bad link.

There is an auditbeat file is in the snapshot artifactory repo at this path:
https://artifacts-api.elastic.co/v1/search/8.0-SNAPSHOT
... tho I'm forgetting how to dynamically construct the curl link to an individual file, like this example:
https://snapshots.elastic.co/8.0.0-28551f9c/downloads/beats/auditbeat/auditbeat-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz

Thanks to @cnasikas on the Security team for pointing it out

**Comment by dedemorton** [comment]
Usually we conditionally code those commands so they don't show up in docs for unreleased software versions. We probably just have an override that was turned on for review purposes. I'll remove it. Thanks!!

**Comment by dedemorton** [comment]
Fixed in https://github.com/elastic/beats/pull/23866.
