### ISSUE TITLE
[Request]: Services for Hosts

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3746]
### Description

In 8.13, we introduced the ability to see the services running on a host directly in a host view (if the service is instrumented with APM):

<img width="1164" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/153067df-e5c0-4d8c-8706-467d32ed3e80">

We need to reflect the docs (probably [here](https://www.elastic.co/guide/en/observability/current/analyze-hosts.html)) to explain this.

You can test this [here](https://demo.elastic.co/app/metrics/hosts?waffleTime=(currentTime:1712768602441,isAutoReloading:!f)&_a=(dateRange:(from:now-15m,to:now),filters:!(),limit:100,panelFilters:!((meta:(index:infra_metrics_7c7390f7-1c37-55c4-84ee-a81aba8ecdd8,key:service.name),query:(exists:(field:service.name)))),query:(language:kuery,query:%27%27))&controlPanels=(cloud.provider:(explicitInput:(fieldName:cloud.provider,id:cloud.provider,title:%27Cloud%20Provider%27),grow:!f,order:1,type:optionsListControl,width:medium),host.os.name:(explicitInput:(fieldName:host.os.name,id:host.os.name,title:%27Operating%20System%27),grow:!f,order:0,type:optionsListControl,width:medium),service.name:(explicitInput:(existsSelected:!t,fieldName:service.name,id:service.name,selectedOptions:!(),title:%27Service%20Name%27),grow:!f,order:2,type:optionsListControl,width:medium))&tableProperties=(detailsItemId:gke-demo-elastic-co-pool-5-29a9d3db-t79s-Ubuntu,pagination:(pageIndex:0,pageSize:10),sorting:(direction:asc,field:name))&assetDetails=(dateRange:(from:%272024-04-10T16:54:52.992Z%27,to:%272024-04-10T17:09:52.992Z%27),name:gke-demo-elastic-co-pool-5-29a9d3db-t79s)) 

> **Note** : Just go to the demo cluster, filter to find hosts where a 'Service' exists then you open any of those hosts to see this 

### Resources

[Demo URL](https://demo.elastic.co/app/metrics/hosts?waffleTime=(currentTime:1712768602441,isAutoReloading:!f)&_a=(dateRange:(from:now-15m,to:now),filters:!(),limit:100,panelFilters:!((meta:(index:infra_metrics_7c7390f7-1c37-55c4-84ee-a81aba8ecdd8,key:service.name),query:(exists:(field:service.name)))),query:(language:kuery,query:%27%27))&controlPanels=(cloud.provider:(explicitInput:(fieldName:cloud.provider,id:cloud.provider,title:%27Cloud%20Provider%27),grow:!f,order:1,type:optionsListControl,width:medium),host.os.name:(explicitInput:(fieldName:host.os.name,id:host.os.name,title:%27Operating%20System%27),grow:!f,order:0,type:optionsListControl,width:medium),service.name:(explicitInput:(existsSelected:!t,fieldName:service.name,id:service.name,selectedOptions:!(),title:%27Service%20Name%27),grow:!f,order:2,type:optionsListControl,width:medium))&tableProperties=(detailsItemId:gke-demo-elastic-co-pool-5-29a9d3db-t79s-Ubuntu,pagination:(pageIndex:0,pageSize:10),sorting:(direction:asc,field:name))&assetDetails=(dateRange:(from:%272024-04-10T16:54:52.992Z%27,to:%272024-04-10T17:09:52.992Z%27),name:gke-demo-elastic-co-pool-5-29a9d3db-t79s))

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

None

### What release is this request related to?

8.13

### Collaboration model

I'm happy to help!

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:**

**Comment by roshan-elastic** [comment]
@colleenmcginnis FYI

**Comment by bmorelli25** [comment]
Duplicate. Closing and using https://github.com/elastic/observability-docs/issues/3626 to track instead.
