### ISSUE TITLE
[Request]: Host Metrics Tab

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3788]
### Description

> **Note** : This **will** be going out in 8.14

To reduce the clutter in our 'overview' tab per host ([example](https://demo.elastic.co/app/metrics/detail/host/gke-demo-elastic-co-pool-5-29a9d3db-m49n?assetDetails=(dateRange:(from:%272024-04-15T16:32:39.752Z%27,to:%272024-04-15T16:47:39.752Z%27),name:gke-demo-elastic-co-pool-5-29a9d3db-m49n)&waffleFilter=(expression:%27%27,kind:kuery)&waffleTime=(currentTime:1713199662834,isAutoReloading:!f)&waffleOptions=(accountId:%27%27,autoBounds:!t,boundsOverride:(max:1,min:0),customMetrics:!(),customOptions:!(),groupBy:!(),legend:(palette:cool,reverseColors:!f,steps:10),metric:(type:cpu),nodeType:host,region:%27%27,sort:(by:name,direction:desc),source:default,timelineOpen:!f,view:map))) we will be:

1. Reducing the metrics shown
2. Organising them into logical types (e.g. disk, network, CPU)
3. Linking them to the relevant section in a new 'metrics' tab (this has further metrics that would clutter an 'overview')

FYI this host view is the template for all future 'resource' views (e.g. containers, kubernetes pods etc). We're gradually migrating things over to use this template

### Resources

[PR](https://github.com/elastic/kibana/pull/180447#pullrequestreview-2000721325)

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

Identical in serverless/stateful

### What release is this request related to?

8.14

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:** @jennypavlova @crespocarlos

**Comment by bmorelli25** [comment]
Hi Roshan. Is this feature behind a feature flag? Is that why we're currently unsure of the release date? It looks like it made it into 8.14 before FF.

**Comment by smith** [comment]
@bmorelli25 It's not behind a feature flag. Self-managed release date is 8.14 and I believe it's on serverless already.

**Comment by dedemorton** [comment]
@roshan-elastic I'm working on a PR to resolve this issue and during testing noticed that the Inspect option no longer appears when you click the ellipses icon. Was this removed at some point?

![image](https://github.com/elastic/observability-docs/assets/14206422/a457a4bd-2491-42a6-b63b-f9cf92451ab1)

**Comment by crespocarlos** [comment]
hey @dedemorton , the Inspect button was never meant to be there. It was probably added by mistake.

**Comment by dedemorton** [comment]
@crespocarlos Do you happen to know when the Inspect button was removed because it's been documented for awhile. Might be good to update earlier docs, too, so users aren't confused.

**Comment by smith** [comment]
@roshan-elastic do you remember any decision about whether or not to show Inspect? I don't feel strongly about it but it's definitely used by support engineers. 

Might I suggest showing it only if `observability:enableInspectEsQueries` is enabled? 

It's a true/false option that's passed to the Lens chart, so it's our decision on whether or not to show it. 

@dedemorton we can discuss this outside of the docs request. You can leave the docs that mention inspect as-is and we'll let you know if anything needs to be changed in a separate request.

**Comment by crespocarlos** [comment]
@smith @roshan-elastic @dedemorton  here is the ticket that originated the charts implementation: https://github.com/elastic/obs-infraobs-team/issues/921#issue-1555322314 (internal). It says that the only action available would be something "To redirect the user to Lens".

**Comment by roshan-elastic** [comment]
Hey all - thanks for looking at this.

I'll be honest - I've never used Inspect and didn't realise it was an option!

> Might I suggest showing it only if observability:enableInspectEsQueries is enabled?

Is that something a support engineer can set (and we could update Lens to automatically respect that)? If so, sounds like a good idea!

Happy to do that if it's a minor thing. Maybe we could add it as a snack we can pick up next time we touch the lens chart code?

**Comment by dedemorton** [comment]
>You can leave the docs that mention inspect as-is and we'll let you know if anything needs to be changed in a separate request.

@smith  I don't think it's a good idea to document an option that doesn't currently exist in the UI. If we add the option later, we can add the docs, too. I'll comment out the section instead of removing it entirely so that it'll be easy to add it back in later.

As an aside,  I would not recommend hiding this feature behind a feature flag. IMO every caveat we need to document degrades the scannability and ultimately the quality of the docs.
