### ISSUE TITLE
[Request]: Updated Disk Metrics in Host List

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3793]
### Description

We are updating the disk metrics to show 'max' instead of 'avg' because the average metric is *useless for most users. We should update the [host disk documentation](https://www.elastic.co/guide/en/observability/current/host-metrics.html#key-metrics-network) to reflect this...I'm not sure on the best approach.

_*Users care if a partition on a disk is going to run out - we've been reporting an 'average' across all partitions - this disguises when a particular partition is running out. 'Max' should be a good indication of whether 'any' partition is going to run out of space_

_Current implementation_
<img width="1212" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/adb45f5a-dfed-4d32-acf2-252b6c4394b9">

_Changing to..._
See [issue](https://github.com/elastic/kibana/issues/179044#issuecomment-2013202087)

> **Note** : In the future, we'd like to offer the user the ability to simply toggle between `max`, `avg`, `p95` etc across certain metrics. This might impact the way we document metrics? i.e. there could be single metrics with 'variants' that users can swap between. Just FYI

### Resources

See [issue](https://github.com/elastic/kibana/issues/179044#issuecomment-2013202087) (not released yet)

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

Same on stateful and serverless

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:** @jennypavlova

**Comment by dedemorton** [comment]
@roshan-elastic Looking at the UI, I'm wondering if some of the other metrics described on this page have changed. Are we documenting metrics that no longer appear in the UI? Are we using the correct labels in the docs?

It's been awhile since I've looked at the Hosts UI (I'm working in a different area now), but I suspect there are some UI changes that never made it into the docs.

**Comment by roshan-elastic** [comment]
Hey @dedemorton, good question. Aside from this request, everything **should** be up-to-date, I don't think we've changed anything in the UI since we centralised the [host metric definitions ](https://www.elastic.co/guide/en/observability/current/host-metrics.html).

Worth checking over though.
