### ISSUE TITLE
[Request]: Update Container Documentation

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#3862]
### Description

> **Placeholder** : Please don't start yet - we need to confirm that we can rename 'Docker Containers' as 'Containers' in our UI before we make this change

This issue is to update our documentation to reflect that our UI is showing 'Containers' and there are two different types of containers...Docker and K8s.

[Docker Container Metrics](https://www.elastic.co/guide/en/observability/current/docker-container-metrics.html)
[Inventory](https://www.elastic.co/guide/en/observability/current/view-infrastructure-metrics.html)
[Inventory Alert Rules](https://www.elastic.co/guide/en/observability/current/infrastructure-threshold-alert.html) (doesn't specifically refer to types of Inventory so changes may not be needed here)

### Context

We are migrating our container views from an older template ([example](https://demo.elastic.co/app/metrics/detail/container/c42bb6b731b249e50e999e58b5d5b64b74ba987b19d5df268bbe6b6dee7c5301)) to the same one Hosts uses ([example](https://demo.elastic.co/app/metrics/detail/host/gke-demo-elastic-co-pool-5-29a9d3db-m49n)).

However, we have found that references to 'Docker Container' in our UI are actually showing Kubernetes containers too (we show both and then conditionally show the right metric depending on which type of container it is). For example:

_'Docker Containers' in Inventory_
<img width="394" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/6c3576c0-e7f5-4fc6-9e46-6abdc845f3ce">

_'Docker Container' Inventory Rules_
<img width="632" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/d55607f0-80f7-42b4-95a0-49daae8c45f6">

Therefore, we may rename 'Docker Containers' in our UI to 'Containers' and want to update the documentation for 'Docker Containers' to reflect metrics for 'Docker Containers' and 'Kubernetes Containers' in the same docs:

https://www.elastic.co/guide/en/observability/current/docker-container-metrics.html

**Additionally...** as part of migrating these views to the new template we will also need to explain to users what the 'dotted lines' mean in these views:

![image](https://github.com/elastic/observability-docs/assets/117740680/9c98ede0-e6d5-4404-850e-07017239806c)

In hosts, we link to https://ela.st/docs-infra-why-dotted to explain this. However, this is housed within Host-specific documentation. We probably need to refer to this in a more generic way (we don't want to repeat this guidance for every type of resource as we start to migrate other things, e.g. K8s pods, to the new template, which will all need dotted lines explaining).

### Resources

This is the epic for the work:

- [x] https://github.com/elastic/observability-dev/issues/3313

**Related:**

- [ ] https://github.com/elastic/observability-dev/issues/3470 (future work to unify containers into one type)

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

The feature is identical in serverless and stateful

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @roshan-elastic @MiriamAparicio @jennypavlova 

**Stakeholders:**

**Comment by bmorelli25** [comment]
Putting in the backlog for now based on https://github.com/elastic/observability-dev/issues/3313#issuecomment-2117224012.

**Comment by roshan-elastic** [comment]
Hey @alaudazzi - after reviewing this, the issue is dependent on this being completed:

- [ ] https://github.com/elastic/observability-dev/issues/3470

I'm happy to close this issue as I think we may change direction here so it's not a priority anymore.

**Comment by alaudazzi** [comment]
Closing.
