### ISSUE TITLE
Update Inventory threshold rule preview section

### ISSUE THREAD

**Issue by maryam-saeidi** [elastic/observability-docs#3880]
### Description

As mentioned in this [comment](https://github.com/elastic/sdh-kibana/issues/4666#issuecomment-2101190200), the preview section description and screenshot of the following page are outdated:

https://www.elastic.co/guide/en/observability/8.13/infrastructure-threshold-alert.html

|Old|New|
|---|---|
|![image](https://github.com/elastic/observability-docs/assets/12370520/77ecb31d-7a02-4518-be07-9edb1575d5af)|![image](https://github.com/elastic/observability-docs/assets/12370520/2a1e8543-88d9-44c9-b541-dd8af41adf02)|

### Resources

I think this might be the related PR for this change: https://github.com/elastic/kibana/pull/91658

### Which documentation set does this change impact?

Stateful only

### Feature differences

I assume this issue is only related to stateful but please help me to verify this assumption in Serverless docs.

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @maryam-saeidi 

**Stakeholders:** @vinaychandrasekhar @jasonrhodes

**Comment by dedemorton** [comment]
Looks like this affects 7.10 and later. We don't typically backport changes that far, but let me know if you think it's warranted here.

**Comment by maryam-saeidi** [comment]
@dedemorton Based on the [PR](https://github.com/elastic/kibana/pull/91658) that I shared, this change was introduced in the `v7.13.0` and `v8.0.0` versions ([comment](https://github.com/elastic/sdh-kibana/issues/4666#issuecomment-2109494477) to verify it), so I don't think it will affect `7.10` documents.
