### ISSUE TITLE
[Request]: Add field calculations to serverless docs about host metrics

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#3897]
### Description

The [stateful docs](https://www.elastic.co/guide/en/observability/current/host-metrics.html) include field calculations, but the [serverless docs](https://docs.elastic.co/serverless/observability/host-metrics) do not.

I'm not sure if this was intentional or just a timing SNAFU. We need to investigate and, if it makes sense, add the missing field calculations to the docs.

### Resources

n/a

### Which documentation set does this change impact?

Serverless only

### Feature differences

n/a

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @roshan

**Stakeholders:**

**Comment by dedemorton** [comment]
@roshan-elastic Before I proceed with this work, can you confirm that we do indeed want to add the field calculations to the serverless docs about host metrics? I'm not if they were left out intentionally. Thanks!

**Comment by roshan-elastic** [comment]
Hey @dedemorton - I think it was probably just missed? We intend to keep feature parity as much as we can between stateful/serverless so feel free to have identical docs with the host metrics.

**Comment by alaudazzi** [comment]
@dedemorton  
the [stateful docs](https://www.elastic.co/guide/en/observability/current/host-metrics.html) don't seem to be  generated pages, so I guess the field calculations should be _manually_ copied to the serverless docs. Can you confirm?

**Comment by dedemorton** [comment]
>I guess the field calculations should be manually copied to the serverless docs. Can you confirm?

That's correct.
