### ISSUE TITLE
[serverless] Update slugs/ids of alerting rule topics

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/observability-docs#3933]
### Description

@lcawl suggested that we remove "alert" from the slugs and IDs for the alerting rule topics:

- [ ] `create-anomaly-alert-rule.mdx`
    - [ ] slug
    - [ ] id
    - [ ] filename
- [ ] `create-custom-threshold-alert-rule.mdx`
    - [ ] slug
    - [ ] id
    - [ ] filename
- [ ] `create-elasticsearch-query-alert-rule.mdx`
    - [ ] filename
- [ ] `create-error-count-threshold-alert-rule.mdx`
    - [ ] slug
    - [ ] id
    - [ ] filename
- [ ] `create-failed-transaction-rate-threshold-alert-rule.mdx`
    - [ ] slug
    - [ ] id
    - [ ] filename
- [ ] `create-inventory-threshold-alert-rule.mdx`
    - [ ] slug
    - [ ] id
    - [ ] filename
- [ ] `create-latency-threshold-alert-rule.mdx`
    - [ ] slug
    - [ ] id
    - [ ] filename
- [ ] `create-slo-burn-rate-alert-rule.mdx`
    - [ ] slug
    - [ ] id
    - [ ] filename

When we do this, we'll need to:

* Update any topics that point to the old slug IDs.
* Check the doclink service and update it was required.
* Implement redirects.

cc @dedemorton 

### Resources

N/A

### Which documentation set does this change impact?

Serverless only

### Feature differences

N/A

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @dedemorton @colleenmcginnis 

**Stakeholders:** @lcawl @elastic/docs-engineering

**Comment by dedemorton** [comment]
All the docs are in asciidoc now, so if we make this update, IMO we should make it across stateful and serverless.

**Comment by colleenmcginnis** [comment]
@bmorelli25 I don't think this is worth the effort with the IA changes coming up. What do you think?
