### ISSUE TITLE
[Fleet] Docs support indicating to users they must create new Integration policies to make use of upgraded Integration packages (it is not automatic)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#395]
The support for it to be automatic (or more so) is being considered for 8.0, but we have many releases to support before this gets in, so PH / Jen and I chatted and decided to put this ticket in.

Background: see this Fleet feature issue about showing version info for the Integration and calling out what versions are 'outdated' for a user to know how to manage their Agent & Integration policies:
https://github.com/elastic/kibana/issues/90308

And see this issue which is kinda a precursor to giving the user a finer level of detail on the subject, as we wish to do here:
https://github.com/elastic/observability-docs/issues/394
 - this ticket calls out that we don't really have a section that talks about how to remove (or add) Integrations explicitly or how to 'create a new policy' tho it is a fairly intuitive operation from the Fleet UI, we may want to discourse about when and why someone would do this.   
 
 - For example, it may benefit users to set up an Integration policy per OS type (Windows, macOS, and Linux hosts) or by functional groupings of how the hosts are used (IT Email servers, Linux servers, user work-stations), or by user categories (Engineering department, Marketing Department, etc).  Though the last option here is the least valuable probably, it is still an ok example.

**Comment by EricDavisX** [comment]
This issue depends on the content from https://github.com/elastic/observability-docs/issues/394
 - and I will reference it as if it exists already here in my proposed notes for what we can add:

New Integration updates are released by Elastic periodically, every month or two, generally - or as otherwise syncs up to a minor release version.  When the Integration 'packages' are released (the packages are how the Integrations are delivered to the stack, via the on-line Elastic Package Registry and the Kibana side Elastic Package Manager component).  When a new Integration is released by Elastic it will show up in the Integrations listing in Kibana after a restart (like during a stack upgrade) or *_TBD_.  In order to take advantage of a newer Integration, there are a few steps a user must take as outlined below.  It is also recommended in larger deployments to try a new Integration with one sample Agent instead of all that may apply.  

Based on this recommendation, to achieve this a user can follow these steps:  A user can confirm the new Integration version desired is shown in the Integrations list in Kibana [1].  If a newer Integration exists, the user can move forward with the following steps.  Step [2], a user can create a new Agent policy with the desired Integration (this will use the newer available version) and apply it to the Agent, as described in the Policy management documentation.  Step [3] if the data streams from the new Integration version are as desired after a trial is applied to a given smaller set of test Agent hosts, the user can apply a few more steps to get all of the desired Agent Policies with the noted Integration updated to the latest version available.

1) To check if a new Integration exists, follow the Policy management documentation steps to view a policy with the Integration whose version is to be compared against the available Integrations listing, and note the Integration version.  Then browse to 'Integrations' in Kibana and (scroll or browse) navigate to the noted Integration and click on it.  The latest version of the integration shipped to the stack by the Elastic Package Registry is the only version that can be integrated into Agent policies at this point (though older Integration versions in use on hosts by older Agent policies will continue to work).  The version is displayed on the right top side of the view, along with information about the Integration details.  Any Agent policies that use the Integration are listed in the Policies tab.  Likewise the 'Settings' tab gives information and further access to manage the Integration's assets as they exist in the stack.  Compare the version noted from the Agent policy with what is listed in the Integration's view.  If the Integration has a newer version available, continue on to steps 2 and 3.

2) Follow the Policy management documentation to create a new policy with the newer version of the Integration and apply it to the smaller desired set of hosts you wish to use as a test bed.  If all looks acceptable with the data ingested into Elasticsearch after applying the Agent policy, move on to step 3.

3) Use either the Integrations view 'Policies' tab listing or the Agent Policy details listing to identify all Agent policies that use the given Integration.  Then one by one, browse to the Agent policy as noted in the Policy Management documentation and perform the following actions:  3A) Delete the Integration from the Agent policy and save it.  This will apply the policy to all Agents, as a temporary state.  Then, while still browsed to the Integration details, add the Integration back to the policy (again).  This will use the new version and will apply it to all Agents.  As noted, repeat this for each Policy that uses the Integration.  Alternatively a user can copy the Agent policies, or create a new one, as noted in the Policy management documentation, and then set up all new Integrations as desired as apply the policy to the desired set of Agents.  This has the benefit of picking up new Integration versions for all Integrations selected, and it applies all changes at one time, which is more efficient for network usage and Fleet.  Though the downside is losing the granularity of assessing the individual Integration version changes to confirm they are working as desired before rolling the change out to all Agents / policies.  The safer route is recommended unless the scale of Agents at hand or the number of different Policies prevents this from being feasible.

**Comment by EricDavisX** [comment]
@mostlyjason @ph we don't have this in the Docs Meta issue - https://github.com/elastic/obs-dc-team/issues/147
 - fyi

**Comment by mostlyjason** [comment]
Great thanks @EricDavisX I'm also going to look at how we can improve this from a product perspective as well

**Comment by EricDavisX** [comment]
hopefully we'll be able to resolve this from this pr:
https://github.com/elastic/observability-docs/pull/469

**Comment by jen-huang** [comment]
We've add this documentation since: https://www.elastic.co/guide/en/fleet/current/agent-policy.html#roll-out-an-integration

![image](https://user-images.githubusercontent.com/1965714/116621162-9da29b00-a8f7-11eb-871e-d4a9a1e03dd2.png)
