### ISSUE TITLE
Port Osquery host details to serverless docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#3954]
### Description

Stateful docs have content that is not available in serverless docs:

https://www.elastic.co/guide/en/observability/current/analyze-hosts.html#view-host-details

![image](https://github.com/elastic/observability-docs/assets/14206422/df02c4c6-de40-44fa-bb3b-5cb9c5f1ae9e)

https://docs.elastic.co/serverless/observability/analyze-hosts#view-host-details

![image](https://github.com/elastic/observability-docs/assets/14206422/98a0f10a-edae-48b2-91f5-7758d4313ab9)

### Resources

n/a

### Which documentation set does this change impact?

Serverless only

### Feature differences

n/a

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:** n/a

**Comment by bmorelli25** [comment]
This is a sub-issue of https://github.com/elastic/observability-docs/issues/4127

**Comment by bmorelli25** [comment]
The PR that needs to be moved over is https://github.com/elastic/observability-docs/pull/3328.

Note that Universal Profiling should be excluded as it is not supported in Serverless.
