### ISSUE TITLE
[Request]: Link to ECS fields reference from integration page and adjust developer guide

### ISSUE THREAD

**Issue by flash1293** [elastic/observability-docs#3968]
### Description

The `ecs@mappings` component template is now applied automatically for all data streams, correctly configuring ECS fields in the mapping by default. This means that ECS fields don't need to be specified as part of an integration. This is causing two changes:

- [x] On this page https://www.elastic.co/guide/en/integrations-developer/current/add-a-mapping.html#_agent_yml , it's not necessary anymore to specify ecs fields, as they are defined by default via the standard index template

- [ ] On integration pages (like https://docs.elastic.co/integrations/nginx ), this will cause the ecs fields to not be listed anymore - instead we should introduce a prominent link to the central ECS field specifications

### Resources

This doc is describing the change: https://docs.google.com/document/d/1I5GKUB8AWUdEhqNjhHE2CXDeUMHk3_kcMaI3xKbQ16g/edit

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

No difference

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @flash1293 

**Stakeholders:** @ishleenk17 @zmoog

**Comment by alaudazzi** [comment]
@flash1293 

> On this page https://www.elastic.co/guide/en/integrations-developer/current/add-a-mapping.html#_agent_yml , it's not necessary anymore to specify ecs fields, as they are defined by default via the standard index template

I will open a PR to fix this page


> On integration pages (like https://docs.elastic.co/integrations/nginx ), this will cause the ecs fields to not be listed anymore - instead we should introduce a prominent link to the central ECS field specifications

The **Exported fields** table is generated.
@zmoog @ishleenk17 do you know which source file should be updated to address the change Joe is requesting?

**Comment by flash1293** [comment]
@alaudazzi the generated table is coming from the integration itself - the idea was to still render that one, but also provide a link to the central ECS reference.

Right now, the exported fields list contains some ECS fields by default, once we have the central link, we can remove the ECS fields from the table on that page.

**Comment by alaudazzi** [comment]
@flash1293 

@ishleenk17 and I have just met and agreed on the following steps. Please review and comment:

1. The integrations team will remove the ecs fields from the Exported fields generated table on each integration page
2. On all the integrations doc pages, we could reference the ECS fields definitions by adding a link to this page https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html
3. Arianna will update the https://www.elastic.co/guide/en/integrations-developer/current/add-a-mapping.html#_agent_yml page by removing the ecs.yml section.

**Comment by flash1293** [comment]
@alaudazzi That matches my understanding

**Comment by ishleenk17** [comment]
> 2\. On all the integrations doc pages, we could reference the ECS fields definitions by adding a link to this page https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html

@flash1293 : This is the link that I found for ECS references. I am hoping this is always the latest one. So each Integration will provide a link to this for ECS definitions. 



> 3\. Arianna will update the https://www.elastic.co/guide/en/integrations-developer/current/add-a-mapping.html#_agent_yml page by removing the ecs.yml section.

@alaudazzi @flash1293 : I think changes might be needed to the agent.yml and base-fields.yml section as well. As we discussed to remove the ecs fields from these files as well.

**Comment by alaudazzi** [comment]
@ishleenk17 @flash1293 
I pushed a [PR](https://github.com/elastic/observability-docs/pull/3989) to remove the ecs.yml section. Please confirm if the agent.yml and base-fields.yml sections need to be removed as well.

**Comment by alaudazzi** [comment]
@flash1293 
This ticket contains [tasks](https://github.com/elastic/observability-docs/issues/3968#issuecomment-2157568764) that could be split into separate issues. I can create them and close this one if it's OK with you.

**Comment by flash1293** [comment]
@alaudazzi sounds good to me 👍

**Comment by alaudazzi** [comment]
Closing this ticket and breaking down into the following issues:
1. The integrations team will remove the ecs fields from the Exported fields generated table on each integration page
https://github.com/elastic/integration-docs/issues/450
3. On all the integrations doc pages, we could reference the ECS fields definitions by adding a link to this page https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html
https://github.com/elastic/observability-docs/issues/4029
4. Arianna will update the https://www.elastic.co/guide/en/integrations-developer/current/add-a-mapping.html#_agent_yml page by removing the ecs.yml section.
https://github.com/elastic/observability-docs/pull/3989
