### ISSUE TITLE
Update Elastic Agent windows installation steps

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#402]
The installation docs for Windows currently tell users to download Elastic Agent, extract it, and rename the directory (similar to what we recommend for Beats). Now that we have the install command, this step is no longer needed. Users can install anywhere, and the files are copied by the install command to the correct location for Windows. 

See https://discuss.elastic.co/t/few-questions-about-elastic-agent-7-10-2 for details

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/observability-docs/pull/455.
