### ISSUE TITLE
[Request]: Entity-Centric Services

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#4027]
# Description

> **Note** : This is a placeholder for awareness for a 9th Jul deliverable we will be releasing to customers. Detail TBC but wanted to put this in on the radar

We are delivering our first step in a new Observability Experience which will focus on showing users entities (e.g. Hosts, Containers, Services, K8s deployments etc)...even if they only have logs for them.

Our first step will be an updated Services Inventory which will show not only services instrumented with APM but also services we found in logs (reliant on `service.name` being declared in the data).

### What do we need?
We potentially need docs to go live after 9th July (serverless first) which explain the following concepts to users:

```[tasklist]
### Requirements
- [x] Tech preview documentation explaining the new 'Experience' to users
- [x] ==> within these docs : Explain What it is and how it works?
- [x] ==> within these docs : Explain how users can add services to their Inventory - covered via https://github.com/elastic/observability-docs/issues/4037
- [x] Tech preview docs explaining Explain what the Elastic-Entity Model (EEM) is - covered via https://github.com/elastic/observability-docs/issues/4028
```

### Background

**What are we releasing?**

We will be releasing a new experience to our users that will allow us to be far more 'entity-centric' with Observability . Eventually, we be able to have faster loading experiences, be able to show relationships between entities better and generally have a more opinionated Observability experience talking less and less about ECS field names and signals and focused on the entities first (entities first...signals second).

**What are entities?**

Entities include things like Hosts, Containers, Services, S3 buckets, Kubernetes Clusters - the 'things' that customers want to observe.

**What is the benefit to the customer in this release?**

One huge benefit to customers is that we will start to show these entities regardless of what signal we have available (e.g. detecting services from log files, i.e. you wouldn't need to add APM into your services to populate the [services inventory](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/apm/services?comparisonEnabled=true&environment=ENVIRONMENT_ALL&rangeFrom=now-15m&rangeTo=now&offset=1d))

**What are we releasing first?**

Our first step in this direction will be to promote the new experience to users by offering the ability to view services not just by [instrumenting with APM](https://www.elastic.co/guide/en/observability/current/apm.html) or OTel but by declaring `service.name` in a `logs-*` index. This would populate an updated Service Inventory which will show services from APM, from custom logs or both:

> **Note** : See link to [designs](https://www.figma.com/design/aD0vVWPOqxFmPIzi3iIsiV/ECO-Observability?node-id=252-27656&t=ph5fsXxYzbKXv0kg-4) for how users interact with this experience

_Promoting the new experience_
<img width="706" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/5c76dc38-f1da-4c94-bd85-06c900905ebb">

_Entity-Centric Services Inventory_
<img width="1335" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/30a8c0fb-f25d-4f2f-bdd3-0a9fe5d9d376">

> **Note** : We will progressively adding different parts of the UI to this experience. We're starting with Services but we'll move onto Hosts, then Containers and then a new Inventory.

**How will users turn this on and off?**
The UI will let any user toggle the experience on or off in **their** browser (it won't be a feature flag so anyone can try it out without affecting other users):

_Turning it on_
<img width="416" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/7094eed7-3f78-47bb-a681-5bc4f6362acc">

_Turning it off_
<img width="907" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/12d691db-3738-4046-8adc-8627794d91e6">

Under the hood though, it will require EEM (below) to be turned on. We'll likely enable this immediately upon 'trying out' the feature in the UI.

If they are admins, we'll just turn on EEM for the cluster and let them know:

_Toast showing on the new experience when we enable EEM for them upon first 'try'_
<img width="638" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/2dd2ea96-3d11-405c-8129-a94d1924651e">

If they don't have the right permissions, we'll tell them they need to speak to someone with the right permissions to turn it on:

_Experience if you try the new UI but you don't have permissions for us to turn on EEM for your cluster_
<img width="983" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/0ecd78e0-dcb8-4aa8-b193-b983d0cda462">

> **Note** : EEM will be able to be controlled via a feature flag in case someone wants to turn it off. However, as soon as we can, we want to turn this on by **default**.

**What will users see when they open the experience within the services inventory?**
If they have APM services, we'll show them as per usual. If they have declared `service.name` in any of their `logs-*` indices - we'll also show those services too. Where there are services which have both APM and custom logs, they'll show as the same service:

_Services from multiple signal types in a single inventory_
<img width="1335" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/30a8c0fb-f25d-4f2f-bdd3-0a9fe5d9d376">

If they click on a logs-only service, they'll have a service view they'll see a minimal service view based on logs:

_Service views (logs only)_
<img width="1157" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/59acf7c7-98af-4a44-a6ca-22550d92d58e">

The service inventory will need to explain to users how to add more services to their service inventory via an empty state or call to action for a populated service inventory:

_Example empty state_
<img width="1045" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/9c79500a-8db3-44df-b772-02a478403a89">

**How will users add new services to this inventory?**
The three options for declaring services will be:

1. Add APM (e.g. Elastic APM Agent, Otel or Synthetics) ([existing journey](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/observabilityOnboarding/?category=apm))
2. Declaring new logs with `service.name` populated ([existing journey](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/observabilityOnboarding/customLogs/?category=logs))
3. Updating their existing logs to have `service.name` (e.g. maybe via ingest pipelines or logstash) - we will need a documentation to explain how users can do this:

_Mock - just illustrative_
![image](https://github.com/elastic/observability-docs/assets/117740680/8b1bfdcf-6d6b-4025-b9fa-0a489e6b3357)

**What is EEM?**
We are using a new platform we call the Elastic-Entity Model (EEM). This effectively processes data using [transforms](https://www.elastic.co/guide/en/elasticsearch/reference/current/transforms.html) into pre-aggregated indices which store entities and their metadata, relationships and metrics (see [sample entity](https://github.com/elastic/observed-asset-model/blob/main/docs/architecture/asset-data-schema.md) - it was called OAM, renamed to EEM)

The Observability solution will then effectively query these indices instead of constructing these entities on-the-fly by parsing thousands or maybe millions of documents.

### What do we need?
We need a set of documentation we can point users to from the UI which will explain:

1. What is our new Observability Experience?
2. How can users populate the new service inventory with services?
3. What is the Elastic-Entity Model (EEM)?

 **1. What is our new Observability Experience?**
We need documentation which will explain what this new experience is. We'll refer to this in various parts of the UI:

<img width="416" alt="image" src="https://github.com/elastic/observability-docs/assets/117740680/17ec0744-061a-434f-afff-e1f8fdb29921">

**2. How can users populate the new service inventory with services?**
The above docs will need a section which we can point users to in order to explain how services get populated. Effectively, this is either:

a. APM instrumented services
b. Services we found in documents matching a `logs-*` index pattern which contain a value for `service.name`

For (a), users can do this via the [application onboarding journey](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/observabilityOnboarding/?category=apm)

For (b), users can do this by either:

- Collecting new logs via our [custom logs onboarding journey](https://edge-lite-oblt.kb.us-west2.gcp.elastic-cloud.com/app/observabilityOnboarding/customLogs/?category=logs)

- Declaring `service.name` in their logs using things like Logstash, processors in beats/agent, mappings or ingest pipelines.

> **Important!** We'll need documentation we can link to how users can declare `service.name` in their existing logs! We assume you will need some expertise to help on this.

**3. What is the Elastic-Entity Model (EEM)?**
This is handled in a separate request:

- [x] https://github.com/elastic/observability-docs/issues/4028

# Resources

See epic (and parent issue):

- [ ] https://github.com/elastic/observability-dev/issues/3350

[Designs](https://www.figma.com/design/aD0vVWPOqxFmPIzi3iIsiV/ECO-Observability?node-id=44-123965&t=tysueFRC1Ejr3jv1-0) - in progress

# Which documentation set does this change impact?

Stateful and Serverless

# Feature differences

Same across both (released in serverless first though)

# What release is this request related to?

Stateful : 8.16
Serverless : As soon as `main` is deployed after **9th July**

# Collaboration model

The documentation team

# Point of contact.

**Main contact:** @roshan-elastic @chrisdistasio 

**Stakeholders:** @kkurstak @tommyers-elastic @kpatticha @akhileshpok

**Comment by roshan-elastic** [comment]
Just FYI @bmorelli25 - FYI for now
(cc @chrisdistasio @kpatticha and @kkurstak)

**Comment by chrisdistasio** [comment]
Can replace 

> What is the Elastic-Entity Model (EEM)? (might not want to do this)

with https://github.com/elastic/observability-docs/issues/4028

**Comment by roshan-elastic** [comment]
> Declaring service.name in their logs using things like Logstash, processors in beats/agent, mappings or ingest pipelines.

Hey @dedemorton, I just wanted to call out that I assume we'll need some pretty heavy expertise from our side in how users can add `service.name` to existing logs using things like:

- [Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html)
- [Logstash](https://www.elastic.co/guide/en/logstash/current/pipeline.html#_outputs)
- Processors : [filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html) | [elastic agent](https://www.elastic.co/guide/en/fleet/current/elastic-agent-processor-configuration.html)

I think we can probably point to these kind of docs but it might be helpful to give a simple example just to help someone get started?

Our expectation is that only really technical users will probably be able to do this...we doubt a brand new user will be able to follow this and do it really easily.

> **Note** : We really want to figure out a way services can be discovered/declared with a specific feature in Observability but at the moment, we don't have anything like this

**I'm on PTO until Thu 4th Jul but I'll dedicate my time after this support any efforts on this!**

**Comment by bmorelli25** [comment]
Thanks, @roshan-elastic. I'm going to break the `service.name` request into its own issue (#4307) and have @mdbirnstiehl (our award-winning log writer) work on that part.

**Comment by roshan-elastic** [comment]
Sounds like a great idea @bmorelli25 - I was hoping you would!

**Comment by roshan-elastic** [comment]
As per my other comment @bmorelli25, we'll most likely point towards this document via a short-link from the UI:

https://ela.st/new-experience-services

However, we'd make sure this doesn't get in front of customers until the docs are ready (e.g. by putting it behind a feature flag which is off by default).

**Comment by dedemorton** [comment]
Met with @bmorelli25  and @mdbirnstiehl  to discuss the location of this new content in the docs. Decisions:

- Topic about our new Observability experience will appear in the Observability Guide at the same level as the Obs overview for now. We'll revisit this decision later when we work on the AI for the serverless GA (or if reviewers have a strong preference for some other location).
- Topic about how to populate the new service inventory with services will appear under Logging for now since it currently only pertains to logs.
- Topic about EEM will appear nested below the topic about our new Observability experience.

We'll make sure that there are links between the topics so users can find this information quickly. We'll also make sure the current topic about the [Service inventory](https://www.elastic.co/guide/en/kibana/current/services.html) (in the Kibana Guide) points to the topic about the new experience.

**Comment by dedemorton** [comment]
@roshan-elastic I went through all the resources today and have a few questions plus some ideas about what we should cover in the docs. I'm going to drop my questions and rough ideas here in case we aren't able to touch base tomorrow (scheduling is difficult with the timezone difference). 

QUESTIONS:

- What are we calling this thing? Entity-centric Observability?
- Where can I see this feature in action? (Is there an oblt environment that has these changes?) I have the Figma link, but in my experience, it's better to work with the product.
- Should the topic focus on what we are delivering for the technical preview? Or should we tell users about our future vision? 
- Which privileges are required to turn on the new experience? Which privileges are required to enable the EEM?

ROUGH OUTLINE:

- [Not sure if we want to cover this] Describe why we are introducing a new experience (limitations of signal-based observability)
- Describe the new experience and what it provides over the traditional, signals-based approach.
- Explain what features the technical preview provides: updated Services inventory that shows services instrumented with APM plus services found in logs
- Describe how to turn the new experience on (and off)
- Describe how to add services to the inventory (include a link to details about adding the service name to logs)

WDYT? Am I on the right track here?

**Comment by chrisdistasio** [comment]
> Eventually, all of this entity-centric stuff will go to GA and will replace the existing functionality (e.g. services, hosts etc) so we'd prob just merge all this new stuff into the normal docs (i.e. nothing would need to be nested under 'Entity-Centric Observability'.

I agree with this, and it gives me pause to introduce it as "Entity-centric Observability."  

As this is currently an extension of the Services (Inventory), I would propose it be linked to from the existing Services Inventory page and not even giving it a new place in the IA (until there is a real notion of a new comprehensive inventory experience)

**Comment by chrisdistasio** [comment]
> Is this probably too early do you think? Maybe we need to complete HCS first so people can really see the end-to-end value?

Agreed, a bit premature for now.

On #1-3 agreed; also need to consider placement for Serverless.  Calling out because it's similar but slightly different.

**Comment by roshan-elastic** [comment]
@dedemorton - hopefully this [last comment](https://github.com/elastic/observability-docs/issues/4027#issuecomment-2220520291) helps give a better steer?

**Comment by dedemorton** [comment]
Ok so based on your comments:

* I've created a new topic that focuses on the new experience for services. You can see the draft in https://github.com/elastic/observability-docs/pull/4062 and provide feedback on that section now.
* Mike is working on the docs about declaring the service name in logs. Draft is up in https://github.com/elastic/observability-docs/pull/4054.
* I've created a placeholder file for EEM topic. Right now, I've added the topic under the Observability overview. Unfortunately there is no good place where we can define this content right now, but if there's a desire to de-emphasize it, I can move it to the bottom of the nav. Just let me know by adding a comment to the PR.

**Comment by roshan-elastic** [comment]
Nice one @dedemorton.

A question...every time I review docs I kind of get lost and end up looking at the raw files in github. 

Is this the best way for me to be reviewing docs or should I be able to see a preview of the doc (i.e. what a user should see)? 

I'm sure I just need a bit of education!

**Comment by dedemorton** [comment]
>A question...every time I review docs I kind of get lost and end up looking at the raw files in github.

@roshan-elastic Typically I'll include a link to the preview docs, but I haven't done that in this PR (yet!) because I need to figure out why the preview link is 404ing. I'll drop the link in the PR when I get that figured out. 

(Right now the doc previews are kind of confusing because we have two different doc builds taking place...one for asciidoc and one for markdown (mdx files). The markdown build needs to be triggered manually. A preview link gets added to the PR for asciidoc changes, but not mdx, which means I need to remember to run the build and update the link every time I push a commit.)

**Comment by roshan-elastic** [comment]
Got it @dedemorton - thanks!

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/4062 and https://github.com/elastic/observability-docs/issues/4037
