### ISSUE TITLE
[Request]: Add warning in release notes for AI Assistant error

### ISSUE THREAD

**Issue by grabowskit** [elastic/observability-docs#4090]
### Description

We have found that by fixing a [different bug](https://github.com/elastic/kibana/pull/184933), we have created an issue with function calling in the AI Assistant that causes [an error](https://github.com/elastic/kibana/pull/185691) message when using OpenAI. There is a fix that will be available in 8.15 and a workaround in 8.14.3 to use simulated function calling in AI Assistant Settings. Only 8.14.3 is affected by this issue

### Resources

[Support doc](https://docs.google.com/document/d/1FCbYgSJaYeDQSvlFjwrHESVssjxl1X4z2oQCz29JuQo/edit)

### Which documentation set does this change impact?

Stateful only

### Feature differences

Not an issue in Serverless because it has already been updated

### What release is this request related to?

8.14

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @grabowskit 

**Stakeholders:** @dgieselaar @emma-raffenne @sorenlouv @neptunian @dede

**Comment by dedemorton** [comment]
@grabowskit This sounds fairly urgent. What is the priority of this work?

**Comment by grabowskit** [comment]
++ Yes, this is an existing issue, it would be good to have a doc to point users to
