### ISSUE TITLE
[Request]: Get Observability serverless docs ready for GA

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#4127]
### Description

We need to do some work leading up to serverless GA to get the docs ready:

- [ ] Add missing content about:
  - [ ] AWS monitoring
  - [ ] Azure monitoring
  - [ ] Anything else???
- [ ] Verify that stateful and serverless docs have parity. In some cases, the content has diverged significantly and we may not have time (or want) to "consistify" the content. We should at least make sure that any feature-related doc changes have been ported to serverless.
- [ ] Review technical preview tags/limitations/restrictions and remove them if they will no longer be true at GA.
- [ ] Follow up with @KOTungseth and other solution teams to see if there are any general doc requirements that we need to address.
- [ ] Follow up with @chrisdistasio to see if the PMs have any serverless doc requirements for GA that are not already captured in an issue.
- [ ] Follow up with @KOTungseth to see what--if anything--we can/should do about all doc links that continue to point to the "classic" docs. 

### Resources

n/a

### Which documentation set does this change impact?

Serverless only

### Feature differences

n/a

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @chrisdistasio 

**Stakeholders:** @kot

**Comment by bmorelli25** [comment]
I wonder if for things like AWS monitoring and Azure monitoring, we can just link to stateful instead of duplicating. Would that be too confusing?

**Comment by dedemorton** [comment]
@bmorelli25 You make a good point. I'm not sure we *should* duplicate all of that content since the game plan is to remove duplication with the new IA. I don't think we can get around the fact that pointing to the classic docs will be potentially confusing to users. (We haven't solved that problem for other areas of the documentation either.) Maybe we just need to be explicit in the serverless docs so users understand they're being sent outside of the serverless docs, and we need to probably clean up a few instances in the cloud monitoring docs where we refer to Kibana. WDYT? I don't like this half solution, but I am also reluctant to introduce more duplication, especially since most of the content under cloud monitoring is fairly generic. Any cleanup work that we don on the existing files won't be wasted because we'll need to do that when we implement the new IA anyhow.

**Comment by bmorelli25** [comment]
All tasks accounted for. Closing this issue. We'll continue to track the smaller sub issues—all of which are assigned to @dedemorton  😄
