### ISSUE TITLE
[Request]: Port new quickstarts to stateful

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#4148]
### Description

The changes added in https://github.com/elastic/observability-docs/pull/4073 need to be ported to the stateful docs and backported.

### Resources

n/a

### Which documentation set does this change impact?

Stateful only

### Feature differences

n/a

### What release is this request related to?

8.16

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** n/a

**Stakeholders:**

**Comment by alaudazzi** [comment]
Closing in favor of https://github.com/elastic/observability-docs/pull/4168.
