### ISSUE TITLE
Improve AI assistant docs

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#4206]
### Summary

Improve the wording in https://www.elastic.co/guide/en/observability/current/obs-ai-assistant.html#obs-ai-functions to be more explicit:
asking questions on your own data requires `function calling`.

More info: https://github.com/elastic/sdh-kibana/issues/4895#issuecomment-2314659446

**Comment by dedemorton** [comment]
@bmorelli25 Is the ask here to make the statement shown under the Requirements section more prominent? Under requirements, we already say that "an account with a third-party generative AI provider that supports function calling" is required.

I think it makes sense to add a statement right before the section about suggesting functions (where we talk about asking the assistant questions).

**Comment by alaudazzi** [comment]
@dedemorton thank you for your suggestion. 

This morning I had an interesting Slack chat with @lucabelluccini. While we realized that the overall page is addressing an audience of experts and some of the info might be cryptic, for the scope of this ticket, we can add a more explicit description of what `function calling` is and what it does by adding the following text at the end of the section [Chat with the assistant](https://www.elastic.co/guide/en/observability/current/obs-ai-assistant.html#obs-ai-chat) and just before [Suggest functions](https://www.elastic.co/guide/en/observability/current/obs-ai-assistant.html#obs-ai-functions):

**Asking questions about your data requires `function calling`, which enables LLMs to reliably interact with third-party generative AI providers to perform searches or run advanced functions using customer data.**

**Comment by alaudazzi** [comment]
Something like this:



![Image](https://github.com/user-attachments/assets/c3da1653-8331-41ae-82bd-03262928e619)

**Comment by lucabelluccini** [comment]
Can we rename `Suggest functions` into `Suggest functions (Function calling)`?

**Comment by lucabelluccini** [comment]
Another improvement we might add:
- When executing function calling queries, the LLM will be allowed to execute the queries with the same permissions of the user.

**Comment by alaudazzi** [comment]
@lucabelluccini thank you for your feedback!
I'll integrate your comments into this PR https://github.com/elastic/observability-docs/pull/4211 and ask for final review.
