### ISSUE TITLE
Audit missing Serverless content

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#4235]
Audit content to determine what's missing from Serverless. For https://github.com/elastic/observability-docs/issues/4127.

**Comment by colleenmcginnis** [comment]
Here's a spreadsheet we can use to identify commits that should have been ported to serverless but weren't: [audit serverless/stateful content](https://docs.google.com/spreadsheets/d/1YPQ-kmiKjY5wCk_IGyzVs_RZK-3QlNdxG2PyJV6iA54/edit?pli=1&gid=262286814#gid=262286814) (internal only). Each @elastic/obs-docs writer should review the commits they authored and confirm if the commit should be ported, if it was it ported, and link to the port PR.

Check off your name when you've reviewed all your commits in the spreadsheet:

- [ ] @alaudazzi 
- [ ] @bmorelli25 
- [ ] @colleenmcginnis 
- [ ] @dedemorton 
- [ ] @eedugon (I know you don't have any yet, but I didn't want to leave you out!)
- [ ] @mdbirnstiehl 

Bonus points:
* If a PR should _not_ be ported describe why in the "Notes" column. 
* Review some commits authored by non-@elastic/obs-docs contributors.

**Comment by alaudazzi** [comment]
@bmorelli25 can we close this ticket?
