### ISSUE TITLE
[Request]: Update EEM docs to reflect new inventory

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#4253]
### Description

We need to update the [EEM docs](https://www.elastic.co/docs/current/serverless/observability/elastic-entity-model) to reflect that they will now:

a) include more entities than just services (e.g. hosts and containers)
b) the new service inventory is going to be merged into the [new inventory](https://github.com/elastic/observability-dev/issues/3882) - we can just remove references to the 'new service inventory' and instead mention the 'new inventory'

**Notes**
- This go live in serverless on 7th Oct

### Resources

- [ ] https://github.com/elastic/observability-dev/issues/3882)
- [ ] https://github.com/elastic/observability-docs/issues/4254

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

Identical in stateful/serverless

### What release is this request related to?

8.16

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @chrisdistasio 

**Stakeholders:** @smith

**Comment by roshan-elastic** [comment]
@chrisdistasio - I put you as the owner on this as I figured it made sense. That OK?

**Comment by smith** [comment]
Added this as a dependency on https://github.com/elastic/observability-dev/issues/3882.

**Comment by chrisdistasio** [comment]
@roshan-elastic is this still planned to go live on 7 October?

**Comment by chrisdistasio** [comment]
[proposed updates](https://docs.google.com/document/d/17IZQs_568qyuiEVopLgntztx6FYLj1gq5w82Y6oytnM/edit)

**Comment by alaudazzi** [comment]
Doc updates ready for review in https://github.com/elastic/observability-docs/pull/4340
