### ISSUE TITLE
[Request]: Create new inventory docs and remove docs for new service inventory

### ISSUE THREAD

**Issue by roshan-elastic** [elastic/observability-docs#4254]
### Description

We will be building a new inventory that will eventually supersede the [existing inventory](https://demo.elastic.co/app/metrics/inventory) that will show **all** entities in one place (see [PRD](https://docs.google.com/document/d/1UneuZHaqJGztZWpVDNpiGmQlW8CV-1xTVqat2rvtUC8/edit)).

The [first iteration](https://github.com/elastic/observability-dev/issues/3882) will only show Hosts, Containers and Services but it will quickly start showing other entity types ([next up is Kubernetes](https://github.com/elastic/observability-dev/issues/3921)) - eventually all entities (e.g. S3, RDS, Kafka, user-provided entities).

Additionally, we will be removing the 'new service inventory' that we started and promoting the new inventory within the existing services inventory - the new inventory will also include services so this effectively envelopes the new services inventory.

This issue is to:

(a) Create documentation explaining what this feature is
(b) Remove the [new services inventory documentation](https://www.elastic.co/docs/current/serverless/observability/new-experience-services)

> **Note** : The changes in the product will be made in serverless on **7th Oct**

### Resources

- [New Services Inventory docs](https://www.elastic.co/docs/current/serverless/observability/new-experience-services)
- [Epic for new Inventory](https://github.com/elastic/observability-dev/issues/3882)
- [New Inventory Designs](https://www.figma.com/design/UBOcxRvYiwBSKt8zVCdk2O/New-Inventory?t=QcWtHgy4udX9uOWo-0)
- [PRD for new Inventory](https://docs.google.com/document/d/1UneuZHaqJGztZWpVDNpiGmQlW8CV-1xTVqat2rvtUC8/edit)

The main pitch for the new inventory is that you can "See everything you have in one place". It will help users do two things during an incident:

1. Find their stuff : Find whatever it is they're investigating in **one place**
2. See what needs attention : See what isn't working as expected so they can begin root cause analysis

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

Identical in stateful and serverless (although the new service inventory wasn't live in stateful yet)

### What release is this request related to?

8.16

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @roshan-elastic 

**Stakeholders:** @kpatticha @kkurstak

**Comment by roshan-elastic** [comment]
@alaudazzi  - updated!

**Comment by alaudazzi** [comment]
Thank you @roshan-elastic 
Additional notes from our chat this morning:

- @alaudazzi  will share a gdoc with an initial draft based on the structure discussed with @roshan-elastic  (see above)
- Deadline remains Oct 7, unless otherwise stated
- @kpatticha might help with access to the latest UI
- the new doc page on Inventory will be located after `Log monitoring`
![Image](https://github.com/user-attachments/assets/cf5674d3-7c7c-4bc7-9bfa-674b6d07aa4b)

**Comment by alaudazzi** [comment]
@roshan-elastic 
Here is an [initial draft](https://docs.google.com/document/d/1bNGQeNdWbM9MJ1c0MM5RQ9t_CtrnuFXjxdSaQZnlW3Y/edit) of the new Inventory doc page.
It's very much WIP, but it gives us a baseline to work on. 
I've added a few questions/comments where your feedback is appreciated.

CC @kpatticha

**Comment by alaudazzi** [comment]
@roshan-elastic 

PRs are ready for your review:
- Create new Inventory documentation => https://github.com/elastic/observability-docs/pull/4341
- Remove the [new services inventory documentation](https://www.elastic.co/docs/current/serverless/observability/new-experience-services) => https://github.com/elastic/observability-docs/pull/4342
