### ISSUE TITLE
[Request]: Remove "Tech Preview" tags as they relate to general serverless functionality

### ISSUE THREAD

**Issue by chrisdistasio** [elastic/observability-docs#4350]
### Description

As we move toward GA, we will need to align the removal of the generalized Tech Preview tags for Serverless.  There may be feature related instances where tech preview badges still make sense.

In addition, the [technical preview limitations ](https://www.elastic.co/docs/current/serverless/observability/observability-technical-preview-limitations)left nav item needs to be reconsidered.  The limitation will still exist, even in GA.  Perhaps we can rework the menu item to "Disclaimers"

### Resources

n/a

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

Serverless

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @chrisdistasio 

**Stakeholders:**

**Comment by bmorelli25** [comment]
From DeDe: Beware of duplicate TP admonitions in the docs
