### ISSUE TITLE
[Request] Update references to apps and pages re: solution views and classic nav updates in Kibana

### ISSUE THREAD

**Issue by florent-leborgne** [elastic/observability-docs#4358]
Follow-up to https://github.com/elastic/platform-docs-team/issues/486

With the stateful navigation updates, we need to check that the way we refer to apps and pages in our UI-related guides remains true independently of which navigation users got by default (classic or solution view).

The wording that was discussed and agreed is [documented in our style guide](https://docs.elastic.dev/tech-writing-guidelines/ui-writing#referring-to-apps-and-pages).

This specific issue is for **Observability** guides.

The new navigation will arrive with 8.16, so ideally updates should be done by then.

Note: There's a related issue to update the general information about search and navigation principles in Kibana https://github.com/elastic/platform-docs-team/issues/530

**Comment by dedemorton** [comment]
These sections need to be checked and updated, as required:

- [ ] [Get started](https://www.elastic.co/guide/en/observability/master/observability-get-started.html) [DeDe]
- [ ] [Applications and services](https://www.elastic.co/guide/en/observability/master/application-and-service-monitoring.html)
- [ ] [CI/CD](https://www.elastic.co/guide/en/observability/master/ci-cd-observability.html)  [DeDe]
- [ ] [Cloud](https://www.elastic.co/guide/en/observability/master/cloud-monitoring.html)
- [ ] [Infrastructure and hosts](https://www.elastic.co/guide/en/observability/master/infrastructure-and-host-monitoring-intro.html) [DeDe]
- [ ] [Logs](https://www.elastic.co/guide/en/observability/master/logs-checklist.html)
- [ ] [Troubleshooting](https://www.elastic.co/guide/en/observability/master/troubleshooting.html) [DeDe]
- [ ] [Incident management](https://www.elastic.co/guide/en/observability/master/incident-management.html) [DeDe]
- [ ] [Data set quality](https://www.elastic.co/guide/en/observability/master/monitor-datasets.html) 
- [ ] [Observability AI Assistant](https://www.elastic.co/guide/en/observability/master/obs-ai-assistant.html) [DeDe]
- [ ] [Reference](https://www.elastic.co/guide/en/observability/master/reference.html) [DeDe]
