### ISSUE TITLE
[Request]:  Rename old "Inventory" page to "Infrastructure Inventory"

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#4395]
### Description

When the new Inventory page was added to the UI, it looks like the old Inventory page was renamed to "Infrastructure Inventory." 

![Image](https://github.com/user-attachments/assets/72e0db60-7a17-4756-a1fe-8715a3c00e21)

We need to update the docs to reflect the name change, making sure any remaining mentions of "Inventory" are actually referring to the new page, not the old one.

The "old" Inventory page is documented here (and mentioned in other topics): https://www.elastic.co/docs/current/serverless/observability/view-infrastructure-metrics 

The "new" inventory page is documented here: https://www.elastic.co/docs/current/serverless/observability/inventory

### Resources

n/a

### Which documentation set does this change impact?

Stateful and Serverless

### Feature differences

n/a

### What release is this request related to?

8.16

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @dedemorton 

**Stakeholders:**

**Comment by alaudazzi** [comment]
![Image](https://github.com/user-attachments/assets/8a995523-453c-4152-95e1-0ab03f23fd03)

**Comment by alaudazzi** [comment]
Closing as completed.
