### ISSUE TITLE
Update alerting docs to reflect new terminology

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#443]
## What?

Renamed `Alerts` -> `Rules` and `Actions` -> `Connectors` in UI

## Why?

* Terminology issue: https://github.com/elastic/kibana/issues/90375
* Implementation PR: https://github.com/elastic/kibana/pull/93597

## Where?

- [x] [APM app docs](https://www.elastic.co/guide/en/kibana/current/apm-alerts.html)
- [x] [Observability docs](https://www.elastic.co/guide/en/observability/master/create-alerts.html)

**Comment by EamonnTP** [comment]
@brandon Maybe this work is still-in-progress? On the `edge-oblt` cluster I'm seeing a mismatch in terminology within the Obs apps. 

When you select **Alerts** (which I think should be **Rules**?), you can see **Create rule**.

![image](https://user-images.githubusercontent.com/31283375/112291655-36eee980-8c88-11eb-9301-67c6a8e101ee.png)

And **Actions** hasn't been updated to **Connectors**.

![image](https://user-images.githubusercontent.com/31283375/112292344-e926b100-8c88-11eb-8365-abc23abcc4ff.png)

**Comment by bmorelli25** [comment]
Sorry, my copy/pasta description is confusing. Based on the definitions in https://github.com/elastic/kibana/issues/90375#issue-801756493, I think this is correct. Rules and actions are subtypes of alerts if I'm reading this correctly.

**Comment by EamonnTP** [comment]
Perfect. Do you mind if I pick this one up?

**Comment by bmorelli25** [comment]
Sounds good. I would hold off until after FF before getting started though.

**Comment by EamonnTP** [comment]
Closed by https://github.com/elastic/observability-docs/pull/679 and https://github.com/elastic/kibana/pull/104232
