### ISSUE TITLE
[Serverless]: When installing an agent it doesn't bring you to Discover page but gives you a link to dashboards

### ISSUE THREAD

**Issue by ZoiaAubryParis** [elastic/observability-docs#4453]
### Serverless Docs

Elastic Observability

### Description

I follow this guide: https://www.elastic.co/docs/current/serverless/observability/quickstarts/monitor-hosts-with-elastic-agent

When agent is installed, I'm not taken to discover page to check logs ( new data in) , but it gives me a link to discover assets![Image](https://github.com/user-attachments/assets/bd6c4d34-2e8e-4d5d-980d-804a7e3e7e08)

### Resources and additional context

don't have more content

**Comment by mdbirnstiehl** [comment]
Not sure what we're looking for here. The docs say:

> Depending on what type of observability data was collected,
> the page may link to the following integration assets:
>
> **Custom .log files**
> Logs Explorer for analyzing custom logs.

In my testing, the custom log links do take the user to Logs Explorer in Discover. @ZoiaAubryParis, could you provide any additional feedback as to what you were expecting/what was incorrect in the docs?
