### ISSUE TITLE
Add new topic about Fleet server

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#449]
Add a topic called "Fleet server" that describes:

* [x] What is fleet-server. 
* [x] Where it lives and how it interacts with other parts of the stack? Describe architecture on a high level
* [x] How is fleet-server run / setup
  * [x] Prerequisites, eg. 7.13+, ECE 2.10+ 
  * ~What params exist~ duplicate of https://github.com/elastic/observability-docs/issues/527.
  * ~What environment variables exist~ - tracked in https://github.com/elastic/observability-docs/issues/623
  * [x] What needs to be done in Fleet?
  * ~How to enroll an Elastic Agent into fleet-server~ - duplicate of https://github.com/elastic/observability-docs/issues/522
  * ~How to set up multiple Fleet servers and why you would do that~ - tracked in https://github.com/elastic/observability-docs/issues/608
  * [x] Document Elastic Cloud and self-hosted use cases
  * ~ECE needs additional wildcard domains and certificates (which normally only cover `*.cname`, not `*.*.cname`)~ - tracked in https://github.com/elastic/observability-docs/issues/640
  * ~Document use case of missing APM server in the template for ECE~ https://github.com/elastic/observability-docs/issues/640
* ~Existing config options~ - tracked in https://github.com/elastic/observability-docs/issues/642
* Compatibility: Elasticsearch >= Fleet Server >= Elastic Agent. Bugfix releases might differ. Kibana is assumed to be on the same minor as Elasticsearch. - tracked in https://github.com/elastic/observability-docs/issues/643
* [x] Setup in Kubernetes
* [x] Troubleshooting: how to check logs and status endpoint /api/status

Related:
- Onboarding flow https://github.com/elastic/kibana/issues/89396
- Handling TLS https://github.com/elastic/fleet-server/issues/90
- Renaming parameter, adding service token https://github.com/elastic/beats/pull/25083
- Onboarding google doc
- Fleet server URLs https://github.com/elastic/kibana/issues/89442

**Comment by mostlyjason** [comment]
@dedemorton Where should we document how to migrate older Elastic Agents to Fleet Server? There are a set of instructions and commands that users will need to follow. We hope to link to this from the product. https://github.com/elastic/kibana/issues/95445

**Comment by mostlyjason** [comment]
Sorry I see you already answered my question here https://github.com/elastic/observability-dev/issues/1402#issuecomment-804298338. Do we need a separate tracking issue for that?

**Comment by dedemorton** [comment]
@mostlyjason To make it easier to track this work and possibly assign subsets to different writers, let's break this issue up into smaller issues. 

I have an outline in google that we can use to keep track of the full list of topics. 

Right now, I'm working on the first 3 items listed in this issue, which more or less map to what I intended originally when I opened this issue.

**Comment by mostlyjason** [comment]
@dedemorton sure feel free to break it up, whatever is more convenient for tracking

**Comment by dedemorton** [comment]
I'm not sure who added these items to this issue, but they need to be handled by the cloud team:

 ECE needs additional wildcard domains and certificates (which normally only cover *.cname, not *.*.cname)
 Document use case of missing APM server in the template for ECE

If you can give me more detail (link to a PR or document), I can follow up with the cloud writers.

**Comment by dedemorton** [comment]
I'm marking the following item as complete because we mention the API in a couple places in the [troubleshooting docs] (https://www.elastic.co/guide/en/fleet/master/fleet-troubleshooting.html#agent-enrollment-timeout) now:

- [x] Troubleshooting: how to check logs and status endpoint /api/status

@mostlyjason Feel free to open an issue with details if you think the troubleshooting docs require additional info about the api.

**Comment by dedemorton** [comment]
I've either completed the work listed above or created issues to track it, so I am closing this issue now.
