### ISSUE TITLE
Update bad navigation references in Serverless

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#4530]
### Summary

Fix procedures where the navigation path has been updated.

**Comment by dedemorton** [comment]
One big change is the renaming of AIOPs to Machine learning. I'm going to take care of the file and topic naming in the PR that applies the new IA to serverless (https://github.com/elastic/observability-docs/pull/4532).

However the procedures that refer to AIOPs will need to be updated to show Machine learning instead.
