### ISSUE TITLE
[Request]: Include on-premises Elasticsearch cluster as an option in all quickstart guides

### ISSUE THREAD

**Issue by eedugon** [elastic/observability-docs#4534]
### Description

When applicable we should also include on-prem clusters in the `prerequisites` section of the quickstarts.

This only applies to Stateful docs.

### Resources

N/A

### Which documentation set does this change impact?

Stateful only

### Feature differences

N/A

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @eedugon 

**Stakeholders:** @bmorelli25

**Comment by akhileshpok** [comment]
All of the quickstart workflows, except for Firehose are supported in on-prem deployments starting 8.16.

**Comment by eedugon** [comment]
@dedemorton , this issue is indirectly related with the issues you have taken:

https://github.com/elastic/observability-docs/issues/4562
https://github.com/elastic/observability-docs/issues/4563

The change requested in this issue is included for the quickstart guides affected by the related issues when they say:
> This functionality is available in all Elastic deployment models.

As soon as you update those two guides we will just need to update the remaining one ([Unified Kubernetes Observability with Elastic Distributions of OpenTelemetry (EDOT)](https://www.elastic.co/guide/en/observability/current/monitor-k8s-otel-edot.html)) on the scope of this issue and check that the `prerequisites` sections are kind of aligned.
