### ISSUE TITLE
[Request]: Crop or redo images that show old navigation

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#4539]
### Description

The Observability Guide still has some images that show left-side navigation. Because the navigation varies according to environment (and gets stale over time), we should avoid showing the nav in screen captures.

Even if we don't have time to redo the offending screens, we should at least crop out the nav so we don't show old/misleading nav.

To find these images, it's probably easiest just to:

1. Preview all the images in the `images` directories, looking for images that show the nav.
2. Search to docs to see if the image is used anywhere.
3. If the image is not used, delete it.
4. If it is used, open it in an editor like SnagIT and crop out the nav.

### Resources

Related to https://github.com/elastic/observability-docs/pull/4437

### Which documentation set does this change impact?

Stateful only

### Feature differences

n/a

### What release is this request related to?

8.16

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @dedemorton 

**Stakeholders:**

**Comment by alaudazzi** [comment]
List of images in serverless that might need to be cropped

- cases.png
- entity-detailed-view.png
- inventory-catalog.png
- observability-cases-settings.png
- quickstart-k8s-otel-dashboard.png
- quickstart-k8s-overview.png

**Comment by alaudazzi** [comment]
Closing as completed.
