### ISSUE TITLE
[Onboarding] Update the Quickstart doc for monitoring of Kubernetes.

### ISSUE THREAD

**Issue by akhileshpok** [elastic/observability-docs#4562]
The 'Quickstart: Monitor your Kubernetes cluster with Elastic Agent' doc should be updated.

- This functionality is available as GA in 8.16.
- This functionality is available in all Elastic deployment models. 

Please reach out to @akhileshpok for clarifications on any of the above items.

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/4582
