### ISSUE TITLE
Content needing a technical writer review

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#503]
The following content was merged without a technical writer review:

**Agent/Fleet**

- [ ] [Elastic agent provider](https://www.elastic.co/guide/en/fleet/master/dynamic-input-configuration.html#providers)
  - https://github.com/elastic/observability-docs/blob/master/docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
- [ ] Running on Kubernetes standalone
  - https://github.com/elastic/observability-docs/blob/master/docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc

**APM**

- [ ] Almost every APM agent's config reference is solely maintained by developers. There is a lot of room for improvement in these docs. https://www.elastic.co/guide/en/apm/agent/index.html

**Beats**

* https://github.com/elastic/beats/issues/17163

**Comment by dedemorton** [comment]
@bmorelli25 For the agent provider docs, it might make sense to do a full edit. I think I just moved the docs over to the observability-docs repo. I can't remember if I did any editing, but it would have been light editing.

**Comment by leahleahy** [comment]
Hi!

**Comment by bmorelli25** [comment]
Closing as this issue is old and no longer relevant.
