### ISSUE TITLE
[Bug] Agent status shows as "Online", "Offline" instead of "Healthy" & "Unhealthy"

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/observability-docs#507]
**Description**: Agent status shows as "Online", "Offline" instead of "Healthy" & "Unhealthy"

**URL link or topic name**: 
- https://www.elastic.co/guide/en/fleet/current/fleet-overview.html
- https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html

**Screenshots**:
![8_1 AgentStatusOnlineOfflineInsteadOfHealthyUnhealthy](https://user-images.githubusercontent.com/60252716/114384107-ed6d2c80-9bab-11eb-9bab-524093c00387.PNG)

**Comment by muskangulati-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigend to @jmikell821

**Comment by dedemorton** [comment]
Hi. This discrepancy has been resolved in the 7.14 (GA-level) docs, so I'm closing this issue.
