### ISSUE TITLE
Public documentation for Integrations 

### ISSUE THREAD

**Issue by sorantis** [elastic/observability-docs#509]
Today the only place where users can check the docs for integrations available via the Elastic Agent is Kibana. We don't seem to have public facing docs for integrations, which impacts integration discoverability through web search engines and also gives the impression that the main/preferred way to monitor 3pp systems is with Beats modules. 

We need to provide public documentation for all integrations we support in Elastic Agent and consider the following requirements: 
- the integrations docs on the Elastic website as well as Kibana should be generated from the same source.
- the integrations docs should be web searchable
- the integrations docs should represent the primary way of monitoring 3pp systems once Elastic Agent becomes the default way of ingesting data.
- the beats docs for a given module should point to a corresponding integration page in the integration docs.
- The [marketing page](https://www.elastic.co/integrations) where we describe Elastic integrations needs to point to (or be replaced by) the integrations documentation.

**Comment by mtojek** [comment]
I would add another bullet point to evaluate existing README resources for packages as I remember they were consider at early stage as better approach. Everything is in Github, around integration source code. Do we want to get rid of it/replace it?

**Comment by exekias** [comment]
We need to figure out what would be the right place for these docs, also taking into account the release cycle of integrations is different from the rest of the stack.

@mtojek I don't think we want to move existing docs somewhere else, they should be part of the package and ideally live next to it. +1 to keep improving them over the time and hopefully reach a common structure.

**Comment by dedemorton** [comment]
I agree with @sorantis. Let's add this to the list:

* The [marketing page](https://www.elastic.co/integrations) where we describe Elastic integrations needs to point to (or be replaced by) the integrations documentation.

Responding to a couple of comments:

> the integrations docs on the Elastic website as well as Kibana should be generated from the same source.

Agreed. However our current doc build system does not support markdown. Our new doc system will, but won't be ready before Fleet GA. Adding @glitteringkatie and @gtback to the discussion for doc tooling perspective. 

>+1 to keep improving them over the time and hopefully reach a common structure.

Agreed.  I expect many users to start their monitoring journey by browsing integrations, so the content needs to be written to support new users. The doc team had some feedback about the structure captured [here](https://github.com/elastic/obs-dc-team/issues/119#issuecomment-653254760) (might be outdated), but we've been spread too thin to move this forward. :-( 

We're also waiting to see how much package granularity is changing.

**Comment by gtback** [comment]
I would lean towards a variation on the new docs system, or a separate standalone doc build process, rather than trying to fit something into the current docs system.

**Comment by goodroot** [comment]
Hi everyone. 👋 🙂 

Looking at feasibility of using new docs, thus I have assigned myself.

There will be many questions! 

But for now:

> We need to figure out what would be the right place for these docs, also taking into account the release cycle of integrations is different from the rest of the stack.

Does the release cycle vary per integration? 

Or, as per Package Specification, are they "batched"? 

I am not 100% clear on the EPR pattern and how an integration relates to Package Specification, so that might be incorrect.

**Comment by exekias** [comment]
> Does the release cycle vary per integration?
>
> Or, as per Package Specification, are they "batched"?
> 
> I am not 100% clear on the EPR pattern and how an integration relates to Package Specification, so that might be incorrect.

Each integration has its own lifecycle but ultimately they all make it to the https://github.com/elastic/package-storage repo. Which is what we use to publish them.

For instance, you can see all integrations packaged in production here: https://github.com/elastic/package-storage/tree/production. Each released version has a README.md for the docs, for example: https://github.com/elastic/package-storage/blob/production/packages/aws/0.5.0/docs/README.md

**Comment by goodroot** [comment]
Thanks for the response!

Started a thread in [#integrations](https://elastic.slack.com/archives/CJZ9U5G9X/p1619464804246300). 

Shaunak gave me a brief tour (thanks).

I propose the following, happy to put up PRs to complete this work:

1. Add frontmatter to all [the templates](https://github.com/elastic/integrations/tree/master/packages) to make them compatible with new docs
2. Change template extension to `.mdx`. Are any changes needed apart from a direct change of the `.md` templates to `.mdx`?
3. Document how to build frontmatter and use the new system in the appropriate location.

On our end, we still need to figure out:

1. Versioning
2. What `tags` + `related` would be, in accordance with frontmatter

**Comment by sorantis** [comment]
Any update on this issue? We keep getting requests to provide single source of truth for all Elastic integrations.

**Comment by melissaburpo** [comment]
I'm also interested in this issue for the Asset Management team's [Osquery Manager integration](https://github.com/elastic/integrations/tree/master/packages/osquery_manager), which will have some growing doc needs over the coming releases. It would be great if there was a way to publish this content in a standard location outside of the integration's Overview page in Kibana.

**Comment by goodroot** [comment]
Update provided in the upstream issue: https://github.com/elastic/package-spec/issues/166#issuecomment-876653575.
