### ISSUE TITLE
Elastic Package Registry

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#524]
We should document Elastic Package Registry including

- [ ] What is EPR? https://github.com/elastic/package-registry
- [ ] Why its a requirement for Integrations
- [ ] Why it requires an internet connection
- [ ] The url at epr.elastic.co
- [ ] How to configure a proxy to access it https://github.com/elastic/kibana/pull/78648

**Comment by dedemorton** [comment]
Needs contribution for the integrations team.

**Comment by EamonnTP** [comment]
Hi @dedemorton Is this issue for a docs contribution or a docs request?

**Comment by dedemorton** [comment]
Yes, I've added the label. This topic will include some general conceptual info about the package registry. The docs team should write that. However, the details about configuring the proxy should probably be contributed by the development team.
