### ISSUE TITLE
Troubleshooting no data streams in Fleet

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#526]
We have several support issues for users who add Elastic Agent but don't see any data streams being created in Fleet. This is one of the first places users look to see if its working. This can occur for several reasons, and it would be nice to give them a list of things to check.

Please see:
- https://discuss.elastic.co/t/elastic-agent-not-providing-data-stream/259433 
- https://discuss.elastic.co/t/how-to-use-elastic-agent-docker-image/269183 
- https://discuss.elastic.co/t/elastic-agent-attempting-to-push-data-to-the-wrong-url/264184 
- https://discuss.elastic.co/t/agent-cant-sent-data-to-host/264393 
- https://discuss.elastic.co/t/agents-are-running-properly-but-no-data-in-data-stream/260111/17 
- https://discuss.elastic.co/t/fleet-data-stream-empty-but-only-in-default-space/257902

**Comment by dedemorton** [comment]
@EamonnTP 

@EricDavisX has graciously offered to contribute content to the troubleshooting docs for Fleet. Can you work with him on changes to those docs? Thanks!

**Comment by EamonnTP** [comment]
No problem. Thanks @EricDavisX

**Comment by EricDavisX** [comment]
It looks like we have a who set of info there in those links, and each seems (at a glance) to be a different problem we could document how to diagnose and correct.  One of them was never solved, which is a bummer, but that is separate.

I'm almost done working up a set of triage info for Fleet Server, but this is fairly separate from the other known problems we will still have on the Agent side.  There is some acknowledged overlap.  Let me start a PR with some info that you can massage.  And then the task is to go through the list of issues and see if the debug steps used and/or specific problem per ticket are explicitly covered somewhere in our content.  I may or may not have more time to help on that.  I propose that we reconnect after getting a starter update for Fleet Server in place.

**Comment by EricDavisX** [comment]
I put a PR up there, and will let you review Eamonn, and carry it forward.  I can try to come back to this docs section after other tasks.  If you've gotten the listed SDH troubleshooting tasks integrated by then that's great, otherwise I can help later on (timeline tbd at this point)

**Comment by EamonnTP** [comment]
First iteration has been [merged](https://github.com/elastic/observability-docs/pull/616).

**Comment by dedemorton** [comment]
@EamonnTP Not sure if you are ready to close this out, but if you are still working on the Troubleshooting docs, I noticed that the current docs still show a setting that was removed in 7.13: `xpack.fleet.agents.tlsCheckDisabled: true`. Also since `xpack.fleet.enabled: true` is the default, users no longer have to explicitly set it to true. Maybe for the purpose of troubleshooting, they'll want to make sure it's not false?

Let me know if you want me to fix this. Thanks!

**Comment by EamonnTP** [comment]
Thanks @DeDe I'll make the update.

**Comment by EamonnTP** [comment]
Hi @EricDavisX I'm going to make the update that DeDe mentioned above. Are there any other updates required for this issue, before we close it as part of the 7.13 release? Thanks!

**Comment by EricDavisX** [comment]
sounds good - close it out @EamonnTP.  cheers
