### ISSUE TITLE
Document Logstash output in Agent

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#535]
Document how users can set the Logstash output in the standalone agent policy https://github.com/elastic/beats/issues/24020

**Comment by dedemorton** [comment]
Starting this work now. I'm going to add the Logstash settings to the PR that's started here: https://github.com/elastic/observability-docs/pull/460

**Comment by dedemorton** [comment]
@mostlyjason Can you paste in an example logstash config into this issue? I usually start by looking at the reference yaml, but I don't see anything there for logstash: https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/elastic-agent.reference.yml

**Comment by mostlyjason** [comment]
@nimarezainia this is agent standalone so I think you own this one? Maybe PH left an example somewhere here or in the linked issues https://github.com/elastic/beats/issues/24020?

**Comment by dedemorton** [comment]
BTW, Andres has asked @faec to help me with this.

**Comment by nimarezainia** [comment]
> @nimarezainia this is agent standalone so I think you own this one? Maybe PH left an example somewhere here or in the linked issues [elastic/beats#24020](https://github.com/elastic/beats/issues/24020)?

@mostlyjason no don;t have this but I can try and get it. Will revert back.

**Comment by dedemorton** [comment]
Closed by https://github.com/elastic/observability-docs/pull/904.

We also have a more detailed PR in progress to add all the settings: https://github.com/elastic/observability-docs/pull/460
