### ISSUE TITLE
Test setup topics in the observability and related guides

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#582]
Please run through the steps in the following documents and confirm the steps work as expected.  For the first pass, use the Elasticsearch Service.   

https://www.elastic.co/guide/en/observability/7.12/add-observability-data.html
https://www.elastic.co/guide/en/observability/7.12/ingest-logs.html
https://www.elastic.co/guide/en/observability/7.12/ingest-metrics.html
https://www.elastic.co/guide/en/observability/7.12/ingest-uptime.html

1. If possible, fix any broken steps or errors that you find and submit a PR (use the Edit link). Fix typos, but please do not edit the text; just focus on fixing errors so that we get a clean diff of problems.

2.  Make notes of problems you can't fix, and open a GitHub issue that describes the problems.

3. If you have time, make a second pass through the topics and follow the Self-managed path. This will require you to set up the stack as described in https://www.elastic.co/guide/en/elastic-stack-get-started/7.12/get-started-elastic-stack.html. If you find errors in the Getting Started document, either fix them and open a PR, if possible, or [open a GitHub issue in the stack-docs repo](https://github.com/elastic/stack-docs/issues/new).

**Comment by bmorelli25** [comment]
Start a free trial of the Elasticsearch Service here: https://cloud.elastic.co/registration?fromURI=%2Fhome

**Comment by dedemorton** [comment]
Closing because this was a short-term work list for a contractor.
