### ISSUE TITLE
Ingest Logs Article

### ISSUE THREAD

**Issue by leahleahy** [elastic/observability-docs#604]
Article: https://www.elastic.co/guide/en/observability/7.12/ingest-logs.html
I found this extremely difficult to follow. I have some recommendations for this.

- I'm not sure what DEB and RPM are, but I would suggest setting the default tabs to MacOS or windows, as they are more common.
- When I tried to set this up using my MacOS terminal, it didn't work. Is there a specific update of OS that you must be on? If so, I would clarify that somewhere in these docs, but otherwise people would just be frustrated like I was.
- I would be more specific about customers needing to use the command line. I know that sounds silly, but tell them to open it and to copy and paste those into their command line.
- I got this to work using Brew, but I couldn't authenticate myself.  I tried using the password I was given when I set up my free trial, but after multiple attempts, it didn't work.
- Where is the user supposed to type in the command line the cloud ID and auth? In the terminal or the config file? This wasn't clear, leaving me not to get past the second step.
- Why do the instructions say to set the connection information in filebeat.yml? How do you set the connection? It looks like just an instructions file.
- What configuration file should be located? More step by step instructions are needed here to set up the connection/authentication.

**Comment by dedemorton** [comment]
Closing because I've not seen these problems encountered by actual users.
