### ISSUE TITLE
Document Fleet Server prereqs for ECE

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#640]
For Fleet Server to work, ECE needs several prerequisites:

- ECE 2.10 or higher and Elastic Stack 7.13 or higher to get APM & Fleet Slider
- Requires additional wildcard domains and certificates (which normally only cover *.cname, not *.*.cname). This enables us to provide the URL for Fleet Server of https://<deployment name>.fleet.<cname>:<port>
- The template must contain a slider for APM & Fleet. Link to docs describing how to add it if its missing.

**Comment by mostlyjason** [comment]
@dedemorton updated the list of prerequisites

**Comment by dedemorton** [comment]
I've added this info to the docs in #731 but I've temporarily commented it out until ECE 2.10 is live.

**Comment by dedemorton** [comment]
Noting here that we also need to provide a link to the documentation about wildcard domains and certificates when that info is available.

**Comment by dedemorton** [comment]
Still waiting for 2.10 to go live (can't do anything here until it does).

**Comment by mostlyjason** [comment]
@dedemorton can we add a note about the Fleet Server requirements to ECE 2.9 as well? Some users are running into a problem that Fleet Server isn't working on ECE 2.9. ECE 2.10 is a known requirement, but its not documented anywhere visible to 2.9 users.

**Comment by dedemorton** [comment]
Yah, that's a good point. I think we're close enough to 2.10 that I should just make the content live (without a link) in the Fleet Server docs.

**Comment by dedemorton** [comment]
OK, so I've made the info about 2.10 live in the Fleet Server docs: https://github.com/elastic/observability-docs/pull/778

Regarding the question about updating the 2.9 ECE docs, I'll defer to the cloud team. Typically we don't update older versions to discuss future functionality. @kellyemurphy WDYT? Would this be feasible? Make sense? Should I create an issue against the cloud docs?

**Comment by dedemorton** [comment]
@mostlyjason Can you help me close out this issue?

The final task is to add a link to the cloud docs about the Fleet Server requirement to add wildcard domains and certs (which normally only cover `*.cname`, not `*.*.cname`).

Is that still a requirement? When I went through the discussion and related PRs, it was hard to figure out the final resolution, and I was unable to find any docs that mention cname and Fleet.

Nothing here that I also need to fix our docs because GitHub gobbled the asterisks in `*.*.cname`. They say: 

`Requires additional wildcard domains and certificates (which normally only cover *.cname, not ..cname). This enables us to provide the URL for Fleet Server of https://.fleet.`

**Comment by mostlyjason** [comment]
Yes this is still required I'll forward an email to you with some more details

**Comment by dedemorton** [comment]
Since the remaining work here is more involved than simply adding a link, I've created a new issue to track this: https://github.com/elastic/observability-docs/issues/825

I will close this issue after putting a PR up to fix the error in the prereqs.

**Comment by dedemorton** [comment]
Opened a PR to add the missing asterisks: https://github.com/elastic/observability-docs/pull/829. Closing out this issue now.
