### ISSUE TITLE
[Synthetics] Document offline synthetics use case

### ISSUE THREAD

**Issue by andrewvc** [elastic/observability-docs#663]
Many of our users would like to run synthetics and airgapped environments. While we do support this it is not currently documented. We do have an example showing how to do this with a docker file and are synthetics repo [here](https://github.com/elastic/synthetics/blob/master/examples/todos/Dockerfile). We should write a proper docs page explaining how to use this docker file when we get a chance.

As suggested [here](https://github.com/elastic/beats/pull/27052#issuecomment-887595056) this most likely needs to go on [this](https://www.elastic.co/guide/en/fleet/master/elastic-agent-container.html) docs page.

**Comment by paulb-elastic** [comment]
Shifting this to 7.15, as this won't be going in, in 7.14 now

**Comment by paulb-elastic** [comment]
As suggested [here](https://github.com/elastic/beats/pull/27052#issuecomment-887595056) this most likely needs to go on [this](https://www.elastic.co/guide/en/fleet/master/elastic-agent-container.html) docs page.

Work for the offline image is being done in https://github.com/elastic/beats/pull/27052.

**Comment by paulb-elastic** [comment]
To clarify, this use case is specifically to document how to run Synthetics (with suites, as inline aren’t affected) in such a way that it doesn’t do an `npm install` which requires external access.

This is different to the `complete` Docker Agent image that’s being put together to support browser monitors via the Synthetics integration (which is being documented via https://github.com/elastic/observability-docs/issues/668).

**Comment by EamonnTP** [comment]
Thanks @paulb-elastic Just to confirm, this content should be placed in the [Agent docs](https://www.elastic.co/guide/en/fleet/master/elastic-agent-container.html) rather than an additional topic in the [Synthetics docs](https://www.elastic.co/guide/en/observability/current/synthetics-quickstart.html)?

**Comment by paulb-elastic** [comment]
@EamonnTP to be honest, I suspect this would go in the [Synthetics docs](https://www.elastic.co/guide/en/observability/current/synthetics-quickstart.html), but defer to @andrewvc to confirm.

**Comment by paulb-elastic** [comment]
Discussed in docs planning today, and this should ideally wait for https://github.com/elastic/beats/issues/28749 as it will be a better user experience

**Comment by paulb-elastic** [comment]
Closing in favour of https://github.com/elastic/beats/issues/28749
