### ISSUE TITLE
Move synthetics quick start content into Send data to ES

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#672]
Originally, we left the [synthetics quick start](https://www.elastic.co/guide/en/observability/current/synthetics-quickstart.html) out of the "[Send data to ES](https://www.elastic.co/guide/en/observability/current/add-observability-data.html)" bucket because it wasn't ready for production use. We should move this content over now.

**Comment by dedemorton** [comment]
@EamonnTP I like the idea of having these tasks organized under actual user goals, but I wonder how well this will work when we plug in the Elastic Agent (instead of Beats). Eventually, when Elastic Agent is functionally complete, the setup  for monitoring log, metrics, and other types of data will be quite different. Users will be more focused on the specific services they want to monitor rather than the type of data they need to collect.

I'm not opposed to moving the content right now since the effort seems minimal, but we need to have a plan for how we're going to plug in the Elastic Agent tasks when the agent is functionally complete, and the workflow is different. We will not want to repeat the Elastic Agent steps in each section. Also we'd need to figure out what to do with the introductory page.

**Comment by EamonnTP** [comment]
@dedemorton Fair point. I agree we should focus on how and where we plug in the Elastic Agent tasks, especially how it all fits into the Unified Observability approach.

**Comment by andrewvc** [comment]
I'm worried that for synthetics moving the quickstart guide would really negatively impact the structure of the content there. Can we just do links instead of moving the docs? Synthetics is a complex topic, so it makes more sense to keep it all together, a short quickstart may seem marooned from the required context, and for people landing on the synthetics guide it will seem like content is missing.

**Comment by ollyhowell** [comment]
Thanks for the comment @andrewvc and apologies, I meant to respond in issue sooner but we have had a couple of discussions about this and it's actually a trickier issue than it appears...

I don't think I'm yet convinced moving the synthetics quick start topics (plural, which is notable!) into the Send Data to ES topic makes sense right now. It's an interesting example which touches on the broader topic of how we see that Send Data... topic/section and I still have some questions/concerns:

Does it get a rebrand as a Get/Getting Started or Spin up the stack topic? 
Do we keep the high level topic (and inline links to individual quick start topics) but move the individual topics into their respective sections within the TOC (including Metrics, Uptime etc.)? Or can we use multiple TOC links to one topic i.e. Synthetics Quickstart link would appear in two places within TOC, one in Send Data.../Getting Started and one in Synthetics itself (not ideal but possible tactical fix)
In terms of getting started and quick starts, what is the expected or desired user journey? Would it make more sense for a Getting Started section to evolve in relation to use cases and providing high level overviews of steps for these and leaving the individual detailed quick starts or tutorials in their respective section?

I think in general we have to decide how that section evolves, becoming a more complete Getting Started or becoming stripped down to one topic with links, and the content in the respective section, or something more radical. There's arguments for and against and I don't think we have the complete, validated picture of what the Observability Guide will become (i.e. come back and review the Outline for Obs... doc) which I think is needed to decide the general case, which this specific issue is triggering (lots of discussions).

So, to cut a long comment short, I reckon it would make sense to expand https://www.elastic.co/guide/en/observability/current/add-observability-data.html to add a Step 5 related to Synthetics (which quick start and how do we signpost the options for the user?) but not move the content until we have an overall outline for Obs Guide that we're happy with. But we should do this reaosnably quickly as right now the section/flow could be clearer and definitely more consistent.

**Comment by EamonnTP** [comment]
I like the idea of changing the [Send data to ES](https://www.elastic.co/guide/en/observability/current/add-observability-data.html) bucket into a one topic landing page that contains all the links to the various quick starts (that would reside in their respective sections within the TOC). And I agree we shouldn't move the Synthetics quick starts.

I think before we start moving the Fleet quick starts, we should consider the options that are available to us:

1. Move the Fleet quick starts into the current [Send data to ES](https://www.elastic.co/guide/en/observability/current/add-observability-data.html) bucket.
1. Move the Fleet quick starts into their respective app bucket, and link to each one from a renamed [Send data to ES](https://www.elastic.co/guide/en/observability/current/add-observability-data.html) topic? Possibly a Get/Getting Started or Spin up the stack topic. 

I like option 2. As @andrewvc points out, it makes sense to have a quick start beside the required context.

**Comment by dedemorton** [comment]
@EamonnTP But the problem with putting the quick starts under each bucket is that the [quick start for Fleet and Elastic Agent](https://www.elastic.co/guide/en/fleet/current/fleet-quick-start.html) covers logs, metrics, and uptime. The real power of observability is being able to see all your data in one place, so I don't think we want to break things down further.

@ollyhowell I think it's time for us to be more strategic about our getting started/quick start docs. We need to think through audience, goals, etc as a group.  I have some ideas and can start a document (unless you would prefer to do that). Let me know!

**Comment by colleenmcginnis** [comment]
I think this was completed in the past, but was intentionally undone today in https://github.com/elastic/observability-docs/pull/2331.
