### ISSUE TITLE
Elastic Agent Logging documentation missing

### ISSUE THREAD

**Issue by richardim** [elastic/observability-docs#699]
Symptom: users host system had system failure due to filling their primary root drives. The offending process was the elastic agents logging.

After the fact, they searched for configuring elastic agent logging and could not find documentation for this. I pointed them to the elastic-agent.reference.yml which has the settings available.

However, a documentation improvement would be to have a dedicated page, like filebeat does https://www.elastic.co/guide/en/beats/filebeat/current/configuration-logging.html

This page in the elastic-agent should go one step further and either 

1. link to how one should configure managed beats logging
2. directly document how to configure the managed beats logging running under agent.

**Comment by dedemorton** [comment]
The docs are beta-level and incomplete right now, but we do plan to document the logging options for GA. Thanks for opening this issue!
