### ISSUE TITLE
7.13 Fleet user guide Link navigates to 7.12 Fleet user guide page [tagged as current]

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/observability-docs#719]
**Kibana version:**
7.13 Prod Kibana Cloud environment 

**Host OS and Browser version:**
APM & Fleet, All

**Preconditions**
1.  7.13 Prod Kibana Cloud environment  should be available.
```
Kibana version: 7.13 Prod Kibana Cloud environment 
BUILD 40865
COMMIT 9863e88bd63ad546b9d36e6b0c0c55cb65dd9081
```
2. Managed host should be avilable under Agents tab.

**Steps to reproduce:**
1. Login to Kiabana
2. NAvigate to Agents tab and click on 'Add Agent' button.
3. Click on 'troubleshooting guide' Link provided at Add agent flyout. 
4. Observe fleet-troubleshooting guide opens up in new tab.
5. Observe, on top 'Fleet User Guide [7.13]' link is provided.
6. Click on it.

**Actual Result:**
- User is navigated to 7.12 Fleet user guide tagged as current.
- Same is observed at links widget provided on right side after landing to fleet-troubleshooting guide page.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/119616554-5c31dc80-be1e-11eb-8b96-e3c4f5156b3a.png)

**Comment by amolnater-qasource** [comment]
Reviewed and Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
this is just pending a deploy of new docs, or a different / real bug, @dedemorton ?  Note, I had asked Amol and Diksha to run through some docs review.  There are a few bugs I'll review and ask for help reviewing with you.

**Comment by dedemorton** [comment]
I think it's a caching problem on the browser side. Try doing a hard reload in your browser.

**Comment by dikshachauhan-qasource** [comment]
Hi @dedemorton 

Yes, it resolved out on using congnito window.

We are closing this out. Thanks for the feedback and taking it our side that we missed it.
