### ISSUE TITLE
Updated screenshots not provided on 7.13 fleet guide.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/observability-docs#720]
**Link1** : https://www.elastic.co/guide/en/fleet/7.13/fleet-overview.html

Screenshot provided is not updated as per latest 7.13 UI changes.
![image](https://user-images.githubusercontent.com/72375798/119628133-71146d00-be2a-11eb-90e2-71a9ab8e3ea1.png)

**Link2**: https://www.elastic.co/guide/en/fleet/7.13/fleet-quick-start.html
**Link3**: https://www.elastic.co/guide/en/fleet/7.13/fleet-quick-start-traces.html

Screenshot: 
![image](https://user-images.githubusercontent.com/72375798/119628455-c05a9d80-be2a-11eb-9ffb-d51a2b1ab23f.png)

**Link4**: https://www.elastic.co/guide/en/fleet/7.13/upgrade-elastic-agent.html

Screenshot1:
![image](https://user-images.githubusercontent.com/72375798/119629459-a8374e00-be2b-11eb-80dc-ecf6ed96fa7f.png)

Screenshot2:
![image](https://user-images.githubusercontent.com/72375798/119629665-db79dd00-be2b-11eb-9bb2-7e385fc7034f.png)

**Link 5**: https://www.elastic.co/guide/en/fleet/7.13/agent-policy.html
![image](https://user-images.githubusercontent.com/72375798/119630691-cfdae600-be2c-11eb-8227-7f7a2b0bf485.png)

**Comment by amolnater-qasource** [comment]
Reviewed and Assigned to @EricDavisX

**Comment by dedemorton** [comment]
Thanks for opening this issue. Updating the screen shots was deemed a lower priority than other work items for 7.13, so those screenshots have not been updated. We feel it's OK for the screenshots to be out-of-date for beta-level software.

All of the screenshots have been updated for 7.14, so I'm closing this issue.
