### ISSUE TITLE
No screenshot provided for user reference to managed policy "Elastic Agent cloud policy" on Fleet user guide.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/observability-docs#721]
Link : https://www.elastic.co/guide/en/fleet/7.13/agent-policy.html

There is no screenshot for existing managed policy that is created during deployment for users to refer. It could be helpful if screenshot related to  "Elastic Agent cloud policy" are provided on Fleet user guide.

Along with information regrading default integration packages [ i.e Fleet server package] it has in it.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/119637237-14698000-be33-11eb-91ea-58aed6687c9c.png)

**Comment by amolnater-qasource** [comment]
Reviewed and Assigned to @EricDavisX

**Comment by dedemorton** [comment]
Typically we avoid providing screenshots outside of getting started content unless the screenshots are integral to understanding the topic. Screenshots are costly to maintain and get out of date quickly. They get even more expensive when you add translation (which we aren't doing yet, but will someday).

@bmorelli25 WDYT? Is it worth the maintenance cost to add a screenshot here?

**Comment by bmorelli25** [comment]
Hmmm. I'd prefer not to add a screenshot here. I think there's enough context to differentiate, and I don't think a screenshot adds much. The UI has an icon (explained in the docs) that users can hover over to determine if a policy is hosted or regular:

<img width="1219" alt="Screen Shot 2021-05-26 at 1 57 36 PM" src="https://user-images.githubusercontent.com/5618806/119730275-64901480-be2a-11eb-974f-7b4c9d898db3.png">

**Comment by bmorelli25** [comment]
@dikshachauhan-qasource I'm going to close this, but feel free to continue the conversation if you feel strongly about this. Appreciate your help making the docs better!

**Comment by dikshachauhan-qasource** [comment]
Hi @bmorelli25 

Thanks for all the feedback. 

Our only point to raise the ticket was to highlight that reference screenshots provides more clarity and confidence on things we are working upon. So raised above if somebody is still confused on content then screenshots might help.

Further, as per feedback provided above, we have no issue in being this closed out.
