### ISSUE TITLE
Installation layout path for windows is incorrect.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#722]
**Description:** 
Unnecessary "/" between Program Files under Installation layout path for Windows.

**Link:** https://www.elastic.co/guide/en/fleet/7.13/elastic-agent-installation.html#installation-layout

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/119649916-d4a99500-be40-11eb-947d-beb4f2233ba5.JPG)

**Error:**
![5](https://user-images.githubusercontent.com/77374876/119650711-c14af980-be41-11eb-92a1-d0136bcf2317.JPG)

**Comment by dikshachauhan-qasource** [comment]
Reviewed and assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I can take this one

**Comment by EricDavisX** [comment]
track the pr and backports to know when / where this can be tested. closing out now.
