### ISSUE TITLE
Information provided under Set Up fleet section is ambiguous

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#723]
**Link:**
https://www.elastic.co/guide/en/fleet/7.13/fleet-quick-start.html#set-up-fleet

**Description:**
>3. Under Policies, confirm that Fleet Server is running and healthy.

Point 3 under Set up Fleet section is not providing correct information to the user.

**Expected:**
As per our understanding, it should be:
3. Under **Hosts**, confirm Fleet Server agent is enrolled Healthy against Elastic Cloud agent policy.

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/119661832-5227d200-be4e-11eb-8d9f-756432dfda43.JPG)

**Comment by EricDavisX** [comment]
i can take this

**Comment by EricDavisX** [comment]
track the pr and backports to know when / where this can be tested. closing out now.
