### ISSUE TITLE
Agent uninstall command is wrong on macOS and Linux

### ISSUE THREAD

**Issue by ferullo** [elastic/observability-docs#724]
This page https://www.elastic.co/guide/en/fleet/current/uninstall-elastic-agent.html says to uninstall Agent with the command `sudo elastic-agent uninstall`. That won't work for users because the directory Agent is installed into isn't in (most) people's `PATH`. The command should be a full path command, e.g. `sudo /Library/Elastic/Agent/elastic-agent uninstall` (macOS) or `sudo /opt/Elastic/Agent/elastic-agent uninstall` (Linux).

cc @ph @gogochan

**Comment by dedemorton** [comment]
The intro text says: "To uninstall Elastic Agent, run the uninstall command from the directory where Elastic Agent is running. Not sure where the agent is running? See Installation layout."

But I can see how users might skip over this info, so let's go ahead and update as you suggest. Thanks for the input!
