### ISSUE TITLE
[Agent] Document some minimum hardware requirements and available tuning strategy for Agent / Beats 

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#726]
This ticket is to ensure we put in some requirements for the system, based on testing, with some minimum expectation of success shipping logs + metrics + Endpoint events from Agent.

It needs discussion on how we'd cite this.  It may need to be some simple citation of available CPU and Memory based on a tested configuration on (say) Linux and windows systems, e.g: 

Recommended minimum is to run Agent on a system with an average of 10% CPU bandwidth available for Agent processes to collect and send x amount MB of data every X minutes with minimum 2 CPU processors and process speed of 512 MHz.

I'm just throwing numbers out there.  And I've made the statement more complex than just system requirements of CPU / Memory available because having the Agent running doesn't imply that it performs as desired if the other load on the system is high.

**Comment by nephel** [comment]
I was wondering, are the documented defaults on ECK anything to go by?
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html#k8s-compute-resources-beats-agent
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html#k8s-default-behavior
