### ISSUE TITLE
Communicate beats management removal

### ISSUE THREAD

**Issue by afgomez** [elastic/observability-docs#732]
On https://github.com/elastic/kibana/pull/99789 we have removed the old Beats Management plugin. 

I think it can be good to redirect users to the Fleet documentation when they try to find the docs for Beats Management, but maybe y'all have a better approach (or don't think it's necessary).

I open this issue to discuss it, and to execute the necessary work.

**Comment by dedemorton** [comment]
I apologize, but this issue got lost in our backlog. Given the maturity of Fleet, I'm not sure whether a redirect still makes sense. WDYT? Can we close this?

**Comment by dedemorton** [comment]
I'm going to close for now. Please re-open if you think the request still makes sense.
