### ISSUE TITLE
Incorrect name for Elastic Agent cloud policy under Set up Fleet.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#733]
**Link:**
https://www.elastic.co/guide/en/fleet/7.13/fleet-quick-start.html#set-up-fleet

**Description:**
> Fleet Server is the agent enrolled in the Elastic Agent on Cloud policy.

Incorrect name for Elastic Agent cloud policy under Set up Fleet. It is not updated as per latest changes.

**Expected:**
Elastic Agent on Cloud policy should be renamed to Elastic Cloud agent policy.

**Screenshots:**
**New name:**
![11](https://user-images.githubusercontent.com/77374876/119803176-d5076600-befc-11eb-9d13-ee3dd656a65d.JPG)

**Documented name:**
![10](https://user-images.githubusercontent.com/77374876/119803199-dc2e7400-befc-11eb-8a94-c62009297cba.JPG)

**Comment by dikshachauhan-qasource** [comment]
Reviewed and assigned to @EricDavisX

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We observed similar incorrect name of cloud policy issue under link: https://www.elastic.co/guide/en/fleet/master/fleet-troubleshooting.html#_check_the_elastic_agent_status

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/119954779-f9c31280-bfbc-11eb-8858-02b382ef31d3.JPG)

Thanks
QAS

**Comment by EricDavisX** [comment]
Indeed it looks like the name has changed and we can update the docs
