### ISSUE TITLE
[Synthetics] Document timing and performance caveats

### ISSUE THREAD

**Issue by andrewvc** [elastic/observability-docs#735]
Once https://github.com/elastic/synthetics/pull/194 is merged in, and the stats are available in the UI, we should document in the synthetics guide how to use these numbers and explain that they are mostly useful in reference to themselves over time and may not correlate exactly with external tools like lighthouse due to platform differences etc.

CC @drewpost @paulb-elastic

**Comment by paulb-elastic** [comment]
Reference to a post about differences between lab and real user performance metrics: https://groups.google.com/a/chromium.org/g/chrome-ux-report/c/PRGtZJvmGkw/m/rzQV99-kCAAJ

**Comment by bmorelli25** [comment]
Is this relevant?
