### ISSUE TITLE
Steps for Secondary agent connectivity to healthy Fleet Server Agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/observability-docs#743]
**Link:** https://www.elastic.co/guide/en/fleet/master/fleet-troubleshooting.html#secondary-agent-not-connecting

**Description:**
This link is about the troubleshooting of secondary agent not connecting to the healthy Fleet Server agent issue.

**Suggestion:**
>Fleet Server host to communicate. You can review and correct this using common tools in alignment with any networking and security concerns you may have.

As we have the steps to open the ports for windows, **we can add the following**: 

**For windows:** Navigate to Windows Defender Firewall with Advanced Security>Inbound rules> New Rule >Port >Add 8220 in Specific local ports field >Allow the connection> Choose appropriate name for the rule> Finish

Re-attempt to install the secondary agent.

**Expected Result:**
We can add the above information under this link.

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/119957374-a605f880-bfbf-11eb-9914-11748c17524e.JPG)

**Comment by amolnater-qasource** [comment]
@deepikakeshav-qasource Please review.

**Comment by deepikakeshav-qasource** [comment]
Reviewed and assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I spoke with @dedemorton and we want to track this in:
https://github.com/elastic/observability-docs/issues/587
 - and we likely won't choose to cite line-by-line steps for specific setup.  closing as a dupe
