### ISSUE TITLE
Document the threat model for Elastic Agent while running under fleet

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#746]
@mostlyjason Can you add more details and link to resources about this item?

Created from item listed in https://github.com/elastic/obs-dc-team/issues/147

**Comment by mostlyjason** [comment]
I think @ph added this one to the list, so I'll ping him for input

**Comment by dedemorton** [comment]
Closed as duplicate of https://github.com/elastic/observability-docs/issues/605
