### ISSUE TITLE
Update FAQ for bundled endpoint 

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#747]
Update FAQ for bundled endpoint https://www.elastic.co/guide/en/fleet/current/fleet-faq.html#does-agent-download-anything-from-internet

Copied from https://github.com/elastic/obs-dc-team/issues/147

@mostlyjason Do you know where this came from? Can you link to some details or tell me who to follow up with?

**Comment by mostlyjason** [comment]
Not sure who added this one, but I can see the FAQ only talks about Endpoint Security. We still need to download artifacts for agent binary upgrades from the internet.
