### ISSUE TITLE
Document how to create user or API key for standalone Elastic Agent

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#749]
How to create a user or API key with necessary permissions for agent in standalone mode in ES, and then configure that in the agent policy.

copied from https://github.com/elastic/obs-dc-team/issues/147

**Comment by dedemorton** [comment]
I've tried generating an API key and using it in a standalone config, but I cannot get it to work (user and password does work, so I know the config is OK). 

I need someone on the development team to tell me exactly what to put under **Restrict privileges** when defining the API key. (It would be good to cover all the privileges that are required to ingest different types of data.)

![image](https://user-images.githubusercontent.com/14206422/143159403-2c52a3f1-3de7-40bc-bca8-3b521f9b4d51.png)

@ruflin Based on what you said in https://github.com/elastic/kibana/issues/106389, I think you might be able to help me with the details here.

**Comment by ruflin** [comment]
You can copy the permissions from here but skip the endpoint part as endpoint will not run in standalone: https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/server/services/package_policies_to_agent_permissions.ts#L14

Ideally we would have a UI in the future to create such API keys.

**Comment by dedemorton** [comment]
Adding a reminder here to also update the privileges shown in https://www.elastic.co/guide/en/fleet/7.16/install-standalone-elastic-agent.html.

**Comment by dedemorton** [comment]
@ruflin I couldn't get the API key that I created to work. :-/

When I try to use the API key instead of a username/password, I get this error:

```
{"log.level":"error","@timestamp":"2021-12-07T20:48:32.856-0800","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/output.go","file.line":154},"message":"Failed to connect to backoff(elasticsearch(https://da4e7a6298c24a6683e6064ebfbe9abe.us-central1.gcp.cloud.es.io:443)): 401 Unauthorized: {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"unable to authenticate with provided credentials and anonymous access is not allowed for this request\",\"additio$
```

I _was_ able to create a role with the following privileges, assign it to a user, and specify username/password in agent.yml (data started flowing into ES):

```
{
  "cluster": ["monitor"],
  "indices": [
    {
      "names": ["logs-*", "metrics-*", "traces-*", "synthetics-*"],
      "privileges": ["auto_configure", "create_doc"]
    }
  ]
}
```

Either something isn't working, or (more likely) I'm doing something wrong in my standalone elastic-agent.yml file or when I create the API key. I've tried many many variations, and frankly I'm frustrated.

Can you paste in an elastic-agent.yml configuration example plus API call (or screen capture of the create API key UI) to show me a working example?

**Comment by dedemorton** [comment]
@ruflin Nevermind. I was using the wrong encoding. Ugggg. I'll work with Gail to make sure the intro text in the UI explains this clearly.
