### ISSUE TITLE
Add Logs monitoring content to Observability Guide

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#75]
In the proposed [outline](https://docs.google.com/document/d/1jOTSdgFH_qStDC5p0Plolc8Rv1WU4ZXuEJgzouLXuOk/edit?ts=5e66599a#) for the Observability Guide, we have the **Visualize data in Kibana** section. This issue is to add the Logs monitoring content to this new section. This content will eventually remove the need for a separate Logs monitoring Guide. 

Documentation updates:
- [ ] Monitor logs - brief overview of Logs monitoring.
    - [ ] Stream logs (Stream UI)
    - [ ] Inspect anomalies (Anomalies UI)
    - [ ] Categorize log entries (Categories) [Related blog](https://www.elastic.co/blog/elastic-logs-7-6-0-released) 
    - [ ] Configure data sources (Settings UI)
    - [ ] Create alerts
    - [ ] Tail log files

**Comment by EamonnTP** [comment]
@bmorelli25 @dedemorton  Will you give this issue a quick review? I want to ensure that I have captured what needs to be documented and if it's the correct structure we want to follow. Thanks!

**Comment by EamonnTP** [comment]
@bmorelli25 @dedemorton We have a Fields reference topic in both the [Logs](https://www.elastic.co/guide/en/logs/guide/current/logs-fields-reference.html) and [Metrics](https://www.elastic.co/guide/en/metrics/guide/current/metrics-fields-reference.html) monitoring guides. Should we consider having one fields reference topic in the Observability guide that covers both logs and metrics?

**Comment by dedemorton** [comment]
@EamonnTP I'm not sure why we didn't include that in our outline. :-( I do see "data fields" but it's under "Change app settings," and I don't think that's quite right. Let's think about when and why users will be looking at these docs. I think they'll look at the field reference when they need to understand the fields they're seeing. At that point, I think they'll be looking at a specific app (logs or metrics).

So in the obs guide, it might be worth having a separate topic that describes each group of fields. That would make it easier for the UI to link to the reference topic (not sure if we currently do that, but we probably should). (Eventually, I'd like to see all these field descriptions easily accessible--maybe in a popup--from the UI.) 

I would group the reference topics under a container topic called "Field reference."

My main concern about having one reference topic is that it will be quite long and hard to navigate, which isn't ideal if we
