### ISSUE TITLE
Add Metrics monitoring content to Observability Guide

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#76]
In the proposed [outline](outline) for the Observability Guide, we have the **Visualize data in Kibana** section. This issue is to add the Metrics monitoring content to this new section. This content will eventually remove the need for a separate Metrics monitoring Guide.

Documentation updates:
- [ ] Analyze metrics - brief overview of Metrics monitoring.
    - [ ] View metrics by topology (Inventory UI)
        - [ ] Monitor servers
        - [ ] Monitor Kubernetes pods [Related blog](https://www.elastic.co/blog/kubernetes-observability-tutorial-k8s-metrics-collection-and-analysis)
        - [ ] Monitor Docker containers
        - [ ] Monitor AWS services [Related blog](https://www.elastic.co/blog/elastic-metrics-7-6-0-released)
    - [ ] Group and explore metrics (Metrics Explorer UI) [Related blog](https://www.elastic.co/blog/elastic-infrastructure-7-3-0-released)
    - [ ] Configure data sources (Settings UI)
    - [ ] Create alerts

**Comment by EamonnTP** [comment]
@bmorelli25 @dedemorton  Will you give this issue a quick review? I want to ensure that I have captured what needs to be documented and if it's the correct structure we want to follow. Thanks!

**Comment by dedemorton** [comment]
So just to clarify (since you point to the blogs here), these topics won't cover data collection and agent/shipper configuration, right? The assumption is that your data is already streaming into Elasticsearch and now you want to know how to navigate the UI and figure out what you can do to visualize your data. For end-to-end steps, we'll rely on tutorials. Is that what you're thinking?

**Comment by EamonnTP** [comment]
Yeah that’s what I’m thinking. There is some useful info in the blogs that can help with navigating the UI.

**Comment by dedemorton** [comment]
Also, are you planning to cover settings and alerts in each section? That might involve a lot of duplication/maintenance.

**Comment by EamonnTP** [comment]
Good point. Maybe settings and alerts should have dedicated sections elsewhere in the Observability guide?

**Comment by dedemorton** [comment]
> Maybe settings and alerts should have dedicated sections elsewhere in the Observability guide?

Yes, that was our thought with the section called "Get alerted." TBH, I'm not crazy about that title, and would prefer "Create alerts" (assuming we're consistent with the language we use in the UI).
