### ISSUE TITLE
Document secret storage assumptions

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#760]
We discussed that a security limitation of Fleet is that users with read access to certain indices in Fleet will have access to secrets. We should document this in our Fleet documentation:
> Credentials that you provide for a policy can be read by any user having read permissions to the .fleet-* and .kibana* indices in Elasticsearch. By default these are superuser, fleet-server service account tokens and the kibana_system user. 

See discussion on google groups

**Comment by dedemorton** [comment]
Contact Jason about google group thread.

**Comment by andresrc** [comment]
@mostlyjason could you prepare a draft for this (in a google doc or similar) and then we can integrate it? Thanks

**Comment by mostlyjason** [comment]
@dedemorton what page would this go on and what can we assume has already been explained? I assume they know what policies are? This is more of a warning/disclaimer so I dont think it needs a long document.

**Comment by dedemorton** [comment]
I recommend adding a "known issues" section to the release notes. It might also be useful to say something in the FAQ.

If this is still a problem when we create the info requested in https://github.com/elastic/observability-docs/issues/605, then the page should mention this as an issue.

**Comment by mostlyjason** [comment]
@dedemorton thanks what about both the release notes and the FAQ?  

Here is something we can put in the FAQ:

> How do you secure secrets entered into integration policies or agent policies in Kibana?
> Credentials that you provide for an agent or integration policy are stored in Elasticsearch. They can be read by any user having read permissions to the .fleet-* and .kibana* indices in Elasticsearch. By default these are superuser, fleet-server service account tokens and the kibana_system user. These secrets are also included in agent polices and shared with agents via Fleet though TLS. When you use our installer for Elastic Agent and enroll those agents into Fleet, the policies are stored on the host filesystem and can only be read by root by default.

For the release notes we can probably put the same text minus the question.

@nchaulet can you confirm the above is correct? Anything you'd add?

**Comment by nchaulet** [comment]
> @nchaulet can you confirm the above is correct? Anything you'd add?

Yes that is correct, I think you covered everything here.

**Comment by dedemorton** [comment]
@mostlyjason I need to create the relnotes source files. I'll just dump this content into the docs when I create the file. I'll do that today.

**Comment by mostlyjason** [comment]
Great assigning back to you @dedemorton to work on publishing this content
