### ISSUE TITLE
Add Uptime monitoring content to Observability Guide

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#77]
In the proposed [outline](https://github.com/elastic/observability-docs/issues/outline) for the Observability Guide, we have the **Visualize data in Kibana** section. This issue is to add the Uptime monitoring content to this new section. The content will eventually remove the need for a separate Uptime monitoring Guide.

Related [blog](https://www.elastic.co/blog/service-monitoring-and-availability-made-simple-with-elastic-uptime-and-heartbeat)

Documentation updates:

- [ ] Monitor uptime - brief overview of Uptime monitoring.
    - [ ] View monitors by status (Overview UI) - includes content about certificates.
    - [ ] Analyze network endpoints (Monitor UI)
    - [ ] Configure Heartbeat indices (Settings UI)
    - [ ] Create alerts

**Comment by EamonnTP** [comment]
@bmorelli25 @dedemorton  Will you give this issue a quick review? I want to ensure that I have captured what needs to be documented and if it's the correct structure we want to follow. Thanks!

**Comment by dedemorton** [comment]
I think there have been some changes to the uptime UI since the outline was written, so the details probably need to be fleshed out. Looks like the current uptime docs have some info that's not in the outline.

Pinging @andrewvc for awareness and input.
