### ISSUE TITLE
Discuss Elastic Agent monitoring

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#770]
The Elastic Agent integration is now installed by default. We need to mention this in the quick start and in other places where we discuss integrations that are installed by default (System integration).

We probably also need a topic about monitoring Elastic Agents so users understand that it's on by default and know where to look for metrics and agent logs.

**Comment by mostlyjason** [comment]
@dedemorton the linked issue #899 talked about agent logging. What about the metrics shown in the ELastic Agent dashboard? Should we open a separate issue for that?

**Comment by dedemorton** [comment]
@mostlyjason Can you open a separate issue? I think we've addressed the basic request I was making here...to make sure we mention that monitoring is on by default.

But I agree that the logging topic is insufficient. I would rather have all the monitoring info (about logs and metrics) in the same topic under monitoring.
