### ISSUE TITLE
Document Elastic Agent statuses

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#774]
Current docs do not describe the agent statuses that appear in the Kibana UI. 

![image](https://user-images.githubusercontent.com/14206422/120701004-3b453900-c467-11eb-8804-f6f2839d10cb.png)

Ideally it would be great to provide descriptions as UI text. If that's not possible, we need to document what these statuses mean.

Note that we need to describe statuses for standalone users, too. See the related issue here: https://github.com/elastic/observability-docs/issues/581

**Comment by andresrc** [comment]
@mostlyjason can you provide the description of the different values?

**Comment by mostlyjason** [comment]
Sure the statuses are defined here https://github.com/elastic/kibana/issues/75236#issue-680564343
