### ISSUE TITLE
Improvements to the Observability Guide

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#78]
Creating this issue for future reference. All issues were raised during the review of the Observability Guide.

- [ ] Should we document types of logs users might want to add? Currently only Filebeat is documented.
- [ ] Should we document Logstash? 
- [ ]  Should we add a tip to the `set-connection-widget` that tells users how where to find the cloud ID? (The link sends users away from the main flow.) 
- [ ] Should the content for installing the APM server be included in the Observability guide? 
- [ ] Get feedback from Marketing on the introductory content.

**Comment by bmorelli25** [comment]
> Should we document types of logs users might want to add? Currently only Filebeat is documented.

Application logs would be nice to add to this section at some point. We recently added them to the [Filebeat quickstart](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html#collect-application-logs).

> Should we document Logstash?

I don't think so.

> Should we add a tip to the set-connection-widget that tells users how where to find the cloud ID? (The link sends users away from the main flow.)

Good point. A tip explaining that it's found in the Elasticsearch Service web console might be helpful.

> Should the content for installing the APM server be included in the Observability guide?

I don't think so. I think what we have [here](https://www.elastic.co/guide/en/observability/current/add-observability-data.html) covers enough.

**Comment by dedemorton** [comment]
Closing because this is quite old and the guide content has changed. We can open new issues if there's still something missing.
