### ISSUE TITLE
iOS Agent Documentation update

### ISSUE THREAD

**Issue by bryce-b** [elastic/observability-docs#792]
## Summary

iOS agent documentation links and/or content needs to be added to the following locations:
This list is based off the PHP ticket; I'm working through it verifying what is applicable. 

### Observability Guide
- [x] [Instrument apps](https://www.elastic.co/guide/en/observability/7.x/instrument-apps.html) https://github.com/elastic/apm-server/pull/5634

### APM Overview
- [x] [Components](https://www.elastic.co/guide/en/apm/get-started/7.13/components.html) https://github.com/elastic/apm-server/pull/5634
- [x] [Quick start](https://www.elastic.co/guide/en/apm/get-started/7.13/install-and-run.html) https://github.com/elastic/apm-server/pull/5634
- [x] [Dropped spans](https://www.elastic.co/guide/en/apm/get-started/7.13/transaction-spans.html#dropped-spans) 
- [x] ~~- [ ] [SetLabel/SetContext/SetUser](https://www.elastic.co/guide/en/apm/get-started/7.13/metadata.html#metadata) Marked as _coming soon_.~~ n/a
- [x] [Distributed tracing:](https://www.elastic.co/guide/en/apm/get-started/7.13/distributed-tracing.html)  `traceparent` compatibility and manual tranceparent propagation https://github.com/elastic/apm-server/pull/5634
~~- [ ] [Transaction sample rate config](https://www.elastic.co/guide/en/apm/get-started/7.13/trace-sampling.html)~~
- [x] [Agent/Server compatibility](https://www.elastic.co/guide/en/apm/get-started/7.13/agent-server-compatibility.html) https://github.com/elastic/apm-server/pull/5634
- [x] [Troubleshooting](https://www.elastic.co/guide/en/apm/get-started/7.13/troubleshooting.html) https://github.com/elastic/apm-server/pull/5634
~- [ ] [Metrics](https://www.elastic.co/guide/en/apm/get-started/7.13/metrics.html)~
- [x] [OpenTracing Bridge](https://www.elastic.co/guide/en/apm/get-started/7.13/opentracing.html) https://github.com/elastic/apm-server/pull/5634

### APM Server Reference
- [x] [Set up](https://www.elastic.co/guide/en/apm/server/current/next-steps.html) https://github.com/elastic/apm-server/pull/5634
~- [ ] [Server cert/pinning](https://www.elastic.co/guide/en/apm/server/current/ssl-setup.html)~
  ~- not sure if this is relevant to mobile...~
~- [ ] [API keys](https://www.elastic.co/guide/en/apm/server/current/api-key.html)~
    ~- not sure if this is relevant to mobile...~
- [x] [Secret token and serverURLs](https://www.elastic.co/guide/en/apm/server/current/secret-token.html)
   - this is dependent on - dependent on https://github.com/elastic/apm-agent-ios/issues/39 https://github.com/elastic/apm-server/pull/5634
- [x] [Troubleshooting](https://www.elastic.co/guide/en/apm/server/current/troubleshooting.html) https://github.com/elastic/apm-server/pull/5634

### Kibana Reference
- [x] [Service maps supported version](https://www.elastic.co/guide/en/kibana/current/service-maps.html) https://github.com/elastic/kibana/pull/104232
- [x] [Central config support](https://www.elastic.co/guide/en/kibana/current/agent-configuration.html) https://github.com/elastic/kibana/pull/104232
- [x] [Service environment filter](https://www.elastic.co/guide/en/kibana/current/filters.html#environment-selector) https://github.com/elastic/kibana/pull/104232
- [x] [Troubleshooting](https://www.elastic.co/guide/en/kibana/7.11/troubleshooting.html) https://github.com/elastic/kibana/pull/104232

### In product
- [ ] APM agent setup instructions (example: https://github.com/elastic/kibana/pull/91381)

## Implementation PRs

- [x] docs: Add iOS agent information to shared docs elastic/apm-server
- [x] docs: add boilerplate troubleshooting topic elastic/apm-agent-ios
- [x] docs: Add iOS agent information to docs

**Comment by bmorelli25** [comment]
Closing as all documentation steps have been completed. Following up in Slack to determine if a new issue should be opened for:

> APM agent setup instructions (example: [APM] Add setup instructions for PHP agent kibana#91381)
