### ISSUE TITLE
Include --insecure flag in the Agent docs

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#802]
We've had several users run into certificate problems and get stuck. 
When a user follows the in-product instructions to add a Fleet Server in 7.13/14 in a self-managed cluster, they must use the `--insecure` flag when enrolling agents or they will get an error message https://github.com/elastic/beats/issues/26365. 

The current documentation does not describe adding this flag https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html#install-fleet-managed-agent.

Can we document how to add this flag and what implications it has for their security?

Can we also include that error message in our troubleshooting guide along with guidance on how to resolve it?

**Comment by EricDavisX** [comment]
@dedemorton hi - wanted to call this out to the Docs team, if there was anything we can do here easy to help users.  I know it is just one issue on the list of stuff for Agent, etc.

**Comment by dedemorton** [comment]
Yup, it's on our pile. We do mention the --insecure flag in multiple places in the docs, but we should mention it in the install/enroll topics too. We can bump the priority if it's a big problem for users.
