### ISSUE TITLE
Document certs and DNS requirements for using ECE with Fleet Server

### ISSUE THREAD

**Issue by dedemorton** [elastic/observability-docs#825]
In 2.10, ECE users will have to manually update their TLS certificates before they can use Fleet Server. The same will be true for APM in ECE 3.0. A wildcard certificate is required to create multiple deployments on demand in the format $id.$host_root. However, adding fleet as an extra wildcard like *.*.$host_root is not possible. So users have to manually and statically add the $domain part like *.fleet.$host_root. 

They might also need to add DNS infrastructure similarly to what they need to do for aliases now.

**Comment by andresrc** [comment]
@dedemorton anything missing from here?

**Comment by dedemorton** [comment]
Let's keep this open. I'm waiting for the related cloud docs to be published so that I can link to them. It looks like the work is next on their list, but the writer was on PTO when I checked in recently.

**Comment by dedemorton** [comment]
We need to make sure that we add a link to https://www.elastic.co/guide/en/cloud-enterprise/current/ece-manage-apm-and-fleet.html

Something like, “If hosting Fleet on ECE, see...."
