### ISSUE TITLE
Document new APM app API for uploading RUM source maps

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#852]
### Summary

> As part of the move to Fleet we will need to move away from fetching source maps directly from (and indexing source maps into) Elasticsearch, as the privileges APM Server is given do not cover this.

> I propose that we introduce an API endpoint to Kibana that is roughly equivalent: users will upload source maps to Kibana (e.g. /api/apm/sourcemaps)

  Issue: https://github.com/elastic/kibana/issues/95393.

### Implentation PRs:
* https://github.com/elastic/kibana/pull/101623
* https://github.com/elastic/kibana/pull/103152

### Documentation PRs:
- [x] Kibana API docs: https://github.com/elastic/kibana/pull/105332
- [ ] ~[Source map guide in APM Server](https://www.elastic.co/guide/en/apm/server/7.13/sourcemaps.html) -- Update to use tabbed widgets and provide a walkthrough for both standalone APM Server users and APM integration users.~ This doesn't make sense unless we're doing it for all of the how to guides. A larger conversation around what APM integration documentation is going to look like needs to happen first.
- [x] Add note to [APM Server API ref](https://www.elastic.co/guide/en/apm/server/7.13/sourcemap-api.html) that mentions other use case. https://github.com/elastic/apm-server/pull/5935 For example:
   ```
   IMPORTANT: If you're using the {apm-server-ref}/apm-integration.html[APM integration for Elastic Agent],
   you must use Kibana's {apm-server-ref}/sourcemap-api.html[source map upload API] instead.
   ```

**Comment by axw** [comment]
In case it's not clear, this new API will only work for the Fleet integration. For standalone APM Server, the existing API must be used.
