### ISSUE TITLE
Update limitations for GA release

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#856]
We should retire our limitations page for the GA release https://www.elastic.co/guide/en/fleet/current/fleet-limitations.html. This was originally created for beta, and we don't want to use negative language in the GA release. 

We'll replace it a new page called "Beats vs Elastic Agent comparison". This will allow us to clearly define what is supported with more detail so we don't unintentionally create breaking changes down the road. It will help net new users select which shipper to use, and help users migrating from Beats to Agent. We'll redirect from the limitations page to this one.

- Overview
  - Compare features between Beats/Agent standalone/Agents enrolled in Fleet
  - Clarify its comparing Beats as a standalone shipper, only include Beats that Agent supports
- Inputs
  - Do we plan to deprecate any?
  - What about ones that are not used in any integration?
- Outputs
  - not redis, file, console
- Top level configuration settings
  - Allowlist of ones we definitely support
  - Processors
  - Autodiscover
  - General settings <- deprecated?
  - Don’t define individual input / output settings right now
- Stack feature compatibility (CCS, spaces)
- Other commonly expected features

Next Steps: 
- [x] Write content in a spreadsheet @nimarezainia & @mostlyjason 
- [x] Convert to a doc page @dedemorton 
- [x] Identify a new home for limitations on existing pages, if they don't fit on the comparison page
  - [x] Requires internet access for Kibana to download integration packages from the Elastic Package Registry 
  - [x] Elastic Agent requires internet access to perform binary upgrades from Fleet 
  - [ ] ~On Elastic Cloud, there’s a limit to the number of enrolled Elastic Agents that a single Kibana instance can handle~ removing from this list because scaling guidelines should be covered by https://github.com/elastic/observability-docs/issues/523

**Comment by mostlyjason** [comment]
@nimarezainia can you help collect a list of inputs, outputs and config settings that are supported in beats but not supported in agent? I believe you are already tracking that internally?

**Comment by nimarezainia** [comment]
Document out for review.

**Comment by dedemorton** [comment]
Adding this as a reminder. 

Assuming we want to the page to have this URL:
https://www.elastic.co/guide/en/fleet/7.14/fleet-agent-comparison.html

The page ID needs to be `[[fleet-agent-comparison]]`
