### ISSUE TITLE
Document APM switch to data streams on cloud

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#864]
> copied from https://github.com/elastic/kibana/issues/104427#issue-937849362

Ensure that the APM migration to data streams clearly calls out that:

- this step cannot be reverted
- the migration impacts how to configure apm-server and the resulting indices (data streams)
- on ECE additional steps are required (at least configuring TLS certs for succesful connection between APM Server and ES).
- no stack monitoring is available
- APM integration is in beta and does not have feature parity with APM standalone
- production deployments should not yet be migrated, this is only intended for test deployments

Related to https://github.com/elastic/kibana/issues/105651.

**Comment by bmorelli25** [comment]
@kilfoyle I'd like to hear your thoughts on adding these limitations the ECE or ESS documentation as well. Do you think it makes sense to call these out on, for example, the [APM settings page](https://www.elastic.co/guide/en/cloud/current/ec-manage-apm-settings.html)? See https://github.com/elastic/kibana/issues/104427 for a bit more information.

**Comment by kilfoyle** [comment]
@bmorelli25 thanks for thinking of the Cloud docs! I think it would be good to mention something on that APM settings page. That lives in both the ESS and ECE documentation. 

In the ECE docs, we also have:
* [Manage your APM & Fleet Server](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-manage-apm-and-fleet.html)
* [Manage your APM Server (versions before 7.13)](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-manage-apm.html)

I'm happy to help with the updates.

**Comment by bmorelli25** [comment]
@kilfoyle and I met to discuss adding these warnings to the cloud docs. We ultimately decided:

* the links from the cloud docs to the APM documentation are sufficient
* it doesn't make sense to add these integration warnings to the cloud docs since the APM integration is currently not mentioned
