### ISSUE TITLE
[Request] Beats "view commits" links are broken

### ISSUE THREAD

**Issue by bmorelli25** [elastic/observability-docs#876]
## Description

Starting in the version 7.11.0 release notes, the links to "view commits" in the Beats release notes are broken. These links previously worked, but have since omitted the crucial `\` before the `...`.

Examples:

Good link (7.10.2): https://github.com/elastic/beats/blame/c03d2abe7b4c037a2a4958054e7b001c87957fa2/CHANGELOG.asciidoc#L660

Bad link (7.13.0):
https://github.com/elastic/beats/blame/c03d2abe7b4c037a2a4958054e7b001c87957fa2/CHANGELOG.asciidoc#L8

## Collaboration

* [x] The docs team will lead producing the content

## Suggested Target Release

Easy fix. Shouldn't be too long.

## Stakeholders

🍔

**Comment by dedemorton** [comment]
@bmorelli25 Do you still want to "own" this, or should I?

**Comment by bmorelli25** [comment]
> Easy fix. Shouldn't be too long.

Famous last words.

Feel free to take this on 😄
