### ISSUE TITLE
Create Fleet docs page

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#877]
Reorganize the content in the Fleet User Guide to include a documentation page for Fleet at the top level. Describe what it is at a high level. Move Fleet settings, Fleet server, Fleet enrollment tokens under it. Document requirements, such as that agent binary upgrades requires internet access to the artifacts repo.

**Comment by dedemorton** [comment]
This issue sounds mostly organizational and would be part of the effort described here: #784

**Comment by dedemorton** [comment]
@mostlyjason I think this page satisfies most of the changes you've requested: https://www.elastic.co/guide/en/fleet/7.16/manage-agents-in-fleet.html

I think the point about upgrades probably belongs in the documentation about upgrading though. WDYT?

**Comment by mostlyjason** [comment]
Looks great I think we can close this then. The upgrade docs already list internet access as a requirement.
