### ISSUE TITLE
Create Integrations docs page

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#878]
Create a top-level documentation page for Fleet Integrations. Move integration policy content and data streams under it. Document that access to EPR is a requirement.

Related:
- https://github.com/elastic/observability-docs/issues/513

**Comment by dedemorton** [comment]
This issue sounds mostly organizational and would be part of the effort described here: https://github.com/elastic/observability-docs/issues/784

**Comment by dedemorton** [comment]
This would also be a good place to our hosted integrations documentation.

**Comment by bmorelli25** [comment]
Closed in #1029.
