### ISSUE TITLE
Ingest Manager feedback for pull/80

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#90]
Hi here are some feedback items, in a general order of urgency, from review over:
https://github.com/elastic/observability-docs/pull/80

1)  from the Trouble shooting page, about the Endpoint - we could enhance this to be more accurate now (since its live and we want folks to use it!
What is the Endpoint integration shown in Ingest Manager?
Let's change the scripting to something like...
The Elastic Endpoint Security integration facilitates running the Elastic Endpoint on your Agent controlled host. It provides protection capabilities and is a security-data event shipper that integrates seamless with the Elastic Security Kibana app.  Endpoint is managed by Elastic Agent in the same way that other Integrations are, try it out!  For more information, please see the relating Elastic Endpoint and Elastic Security solution documentation.

2) from this page:
https://observability-docs_80.docs-preview.app.elstc.co/guide/en/ingest-management/master/elastic-agent-cmd-options.html

recommend we remove this internal-only intended enrollment option:
--staging
Configures agent to download artifacts from a staging build.

3) I'm uncertain if all of the current 'Limitations' are correct... we should have this content further reviewed.  
 - for instance, I don't know if we support a stand-alone package registry in 7.9 or not.  IF so, we can modify or remove that limitation and add a topic about how to set it up if user has the appropriate license level to do so (I thin its upper level like Gold / Platinum)

4) From the troubleshooting page:
Where does Elastic Agent store logs after startup?
When started successfully, Metricbeat logs are stored in data/logs/metricbeat under the folder where Elastic Agent was started. If that log path does not exist, Elastic Agent was unable to start Metricbeat, which is a higher level problem to triage.

I think we should start it with citing the logs for the Agent process itself and then mention Metricbeat.  Agent logs are in data/logs location. You can mention Filebeat will have logs in the same location as Mericbeat.

And now that we know more we could cite here that for .deb / .rpm installs, the logs are at:
/var/lib/elastic-agent/logs/elastic-agent-json.log
/var/lib/elastic-agent/logs/default/metricbeat-json.log
/var/lib/elastic-agent/logs/default/filebeat_monitor-json.log

5) from the IM overview: this highlighted blue text could be removed from the bottom, its basically stated above and seems repetitive
"using SSH, Ansible playbooks, or other configuration methods"
<img width="809" alt="Screen Shot 2020-08-07 at 9 47 29 AM" src="https://user-images.githubusercontent.com/12970373/89652219-29205b80-d893-11ea-972c-cd4785281d11.png">

6) from this page:
https://observability-docs_80.docs-preview.app.elstc.co/guide/en/ingest-management/master/elastic-agent-configuration.html
we could put a note in that all of these same settings can be modified for the Fleet usage in the Integration and Configuration UIs.
 - I'm not sure of this was intended to be 'stand-alone' only content but all has a UI counterpart that we could cite now or in the future if we wanted.  Not mandatory

7) do you think we should add a topic for how to delete the Agent and relating files from the host?  the dpkg or rpm usage should be easy and clear to most admins.  and for Windows there is a .ps1 script to uninstall the service, at which point you can simply stop the agent and delete the folder.  Maybe its overkill for now?  but we could split it to an enhancement for future doc'ing.

**Comment by dedemorton** [comment]
I'm going to add my remaining to-do items here to have all this info in one place:

- [ ] Update config reference and CLI docs (will be done in a different PR). Remove --staging flag.
- [ ] Follow up with Endpoint team about steps they're writing that describe how to configure the service manually. See if it makes sense to use them here.
- [ ] Remove `release-state` overrides in these docs and the agent docs in the beats repo.

**Comment by EricDavisX** [comment]
Hi - from number 4 above, I have collected more detailed and well rounded citation of where the Agent logs and Endpoint logs live on the given 5 different install types, as cited below.  I do think we should call out the Endpoint log locations, please, if I need to convince you - because Agent is the first place to start triaging any Endpoint problems (which is why you'd need the logs).  I will contact Janeen and Nate and make sure they have the data they need to document it on their side as well, and maybe we can reduce the overlap sometime, if we must - but for now (during a Beta particularly) it will be helpful I bet!  Plus, I'm not sure if they have content you can link to yet!!

I think you could add this info to the Trouble shooting page as a topic, or maybe the main docs in https://www.elastic.co/guide/en/ingest-management/7.9/ingest-management-getting-started.html under step 5 (its not too big yet), with content for each package type?  Up to you.   

Note, content was added to and pulled from my faq doc:
https://docs.google.com/document/d/1_HhrkWlJVYNZo3L49iuvki7wWCQS72VUiogKQxLsuck/edit#

Question:  where are the Agent and Endpoint logs ?

A1: For Windows and .tar.gz deploy (relates to macOS and Linux):
Agent relating logs are in a subdirectory of the folder where the Agent was started, as: 
<agent directory>/data/logs/elastic-agent-json.log
Agent logs are versioned off, for example, with older logs named as elastic-agent-json.log.1 
Metricbeat and Filebeat logs, if deployed are also in this directory under the ‘default’ folder, as:
<agent direction>/data/logs/default/metricbeat-json.log
<agent direction>/data/logs/default/metricbeat_monitor-json.log
<agent direction>/data/logs/default/filebeat-json.log
<agent direction>/data/logs/default/filebeat_monitor-json.log

Note: Beats logs are typically more heavily populated and so are versioned off with the dated appended as well as a number within that date. For example: filebeat-json.log-2020-08-13-11-1

About Elastic-Endpoint logs:
On Windows the Endpoint files will be in: Program Files\Elastic\Endpoint
On macOS the Endpoint files will be in: /Library/Elastic/Endpoint
On Linux .tar.gz the Endpoint files will be in: /opt/Elastic/Endpoint
And, from the <Endpoint> folder location on your host, the Endpoint logs will be in the state/log location as: endpoint-000000.log
The endpoint logs are rotated by size, incrementing the number to indicate later log files.
Note, you will need Administrator privilege to see the folders or access the Endpoint logs

A2: For Linux .deb and .rpm installs (relates to Linux .deb and .rpm installs, not .tar.gz usage):
Agent relating logs are in a the subdirectory where the package installer places Agent files, as: 
/var/lib/elastic-agent/logs/elastic-agent-json.log
Agent logs are versioned off, for example, with older logs named as elastic-agent-json.log.1 

Metricbeat and Filebeat logs, if deployed are also in this directory under the ‘default’ folder:
/var/lib/elastic-agent/logs/default/metricbeat-json.log
/var/lib/elastic-agent/logs/default/metricbeat_monitor-json.log
/var/lib/elastic-agent/logs/default/filebeat-json.log
/var/lib/elastic-agent/logs/default/filebeat_monitor-json.log
Beats logs are typically more heavily populated and so are versioned off with the dated appended as well as a number within that date. For example: filebeat-json.log-2020-08-13-11-1

About Elastic-Endpoint logs, on Linux .rpm & .deb install the Endpoint files will be in: 
/opt/Elastic/Endpoint/state/log
And, from that location on the host, the Endpoint logs will be cited as: 
endpoint-000000.log
The endpoint logs are rotated by size, incrementing the number to indicate later log files
Note, you will need Administrator privilege to see the folders or access the Endpoint logs

**Comment by dedemorton** [comment]
@EricDavisX Sorry I haven't updated the docs yet to indicate the log locations. I wonder if it might be a good idea to provide a topic similar to what we provide for Beats that describes the directory layout based on the typo of distribution: https://www.elastic.co/guide/en/beats/filebeat/current/directory-layout.html. 

We might still want to provide a topic in the FAQ: Where are my logs? 

I'm on the fence about whether to provide all the log file names. My main concern is that names change over time and references to them in the docs might get overlooked. Describing the paths is probably more future-proof. Curious what you think.

**Comment by EricDavisX** [comment]
no worries on getting it done, thanks for the attention.

To your questions - I like the Beats style directory layout, if you want to go for that.

I totally see the point about future maintenance needs when doc'ing this low level of info.  If you want to lay it out without filenames we can see how it looks and presumably go with that.  If I genuinely feel strongly after seeing it (different than now) we can reconsider, but my vote only counts for so much.  :)  Thanks for keeping things tight for us.  

@ph do you feel strongly about the logs files citations for all of Agent, Filebeat, Metricbeat, and Endpoint?  It does start to feel like a lot to keep up with.

**Comment by EricDavisX** [comment]
And we could link the FAQ topic to the new section, I like that idea - easily can be added after the fact, anytime.

**Comment by ph** [comment]
@EricDavisX  

> @ph do you feel strongly about the logs files citations for all of Agent, Filebeat, Metricbeat, and Endpoint? It does start to feel like a lot to keep up with.

No, I think it will change we can revisit that for GA?

**Comment by dedemorton** [comment]
I want to close out this issue because I've done most of the work. I created a separate issue to track the new topic that describes the location of logs and other data: https://github.com/elastic/observability-docs/issues/119
