### ISSUE TITLE
[Request] Document how users can upgrade integrations and integration policies

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#900]
## Description
We'd like to document how integrations are upgraded, both automatically and manually by users on the integrations settings page. (Note: this requirement may be related to https://github.com/elastic/observability-docs/issues/878)

Also, we'd like to document the options to upgrade integration policies. Describe how this works in the case where the integration is automatically upgraded and manually. Also, explain how it works when the upgrade can be completed automatically, or when the user needs to manually resolve conflicts. See more information here: https://github.com/elastic/kibana/issues/106048

## Collaboration

* [x] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

## Suggested Target Release

7.15 since we'll be releasing a new integration policy upgrade feature 

## Stakeholders
@jen-huang @mostlyjason @kpollich

**Comment by mostlyjason** [comment]
@dedemorton @jen-huang I didn't check a collaboration box because I wasn't sure what criteria to use to decide. Let's discuss this in our next meeting.

**Comment by andresrc** [comment]
@jen-huang we will need a contact point in the Fleet team for this.

**Comment by jen-huang** [comment]
@kpollich Should be the point of contact on Fleet side for this.

**Comment by kpollich** [comment]
I'll take a quick pass at outlining the functionality for upgrading package policies that we'll be shipping in `7.15` below. This implementation is very barebones for the time being, but there are significant follow-up features that we'll be shipping in `7.16` as well. See https://github.com/elastic/kibana/issues/106048 for more info. 

---

## Upgrading Package Policies

Fleet now provides a streamlined way to push updated policies out to your Elastic Agents when you update your Elastic Agent integrations. To begin, ensure you have the latest version of a given integration installed by clicking the 'Update to latest version" button on its settings page.

![Screen Shot 2021-08-16 at 3 55 23 PM](https://user-images.githubusercontent.com/6766512/129622572-3f442a4f-a2f0-4e22-8197-f78cf5dfd869.png)

![Screen Shot 2021-08-16 at 3 55 51 PM](https://user-images.githubusercontent.com/6766512/129622574-32e91fab-3b41-4eec-87e7-b3646958398f.png)

Once you have the latest version of the integration installed, navigate to either the Policies tab of the integration's settings page or the Agent Policies page in Fleet. Click the "Upgrade" button to enter the upgrade process.

![Screen Shot 2021-08-16 at 3 56 09 PM](https://user-images.githubusercontent.com/6766512/129622576-b003dbe7-06d3-44e6-9f6f-92deaa33de41.png)

![Screen Shot 2021-08-16 at 3 56 23 PM](https://user-images.githubusercontent.com/6766512/129622577-0f106a75-1d2d-4b1d-9e1b-f1317a908683.png)

Upon clicking "Upgrade", you'll be able to make any configuration changes to your policy before saving. This includes updating any new fields that may have been added in the latest version of the integration. Be sure to review your policy configuration before saving to complete the upgrade process.

![Screen Shot 2021-08-16 at 3 56 54 PM](https://user-images.githubusercontent.com/6766512/129622578-77e6cbf6-0699-421f-ab23-ecde0f295593.png)

---

@dedemorton - I hope this is helpful. Does it make sense for me to just take a pass at putting this into asciidoc over at https://github.com/elastic/observability-docs, or should this be more of a hand-off to you and your team? I'm happy to help any way I can, I'm just new to Elastic and would appreciate some guidance if possible. Thank you!

**Comment by dedemorton** [comment]
@kpollich Thanks! Sorry about the delay (I was on PTO last week). This is a good start. The steps look fairly straightforward, so I'll take care of getting this into asciidoc for 7.15. When the PR is ready, I'll include you as a reviewer.
