### ISSUE TITLE
Update images to reflect the Amsterdam EUI theme in Kibana for 7.14

### ISSUE THREAD

**Issue by EamonnTP** [elastic/observability-docs#911]
## Description

Update images to reflect the new Amsterdam EUI theme, which is default in Kibana for 7.14.

## Collaboration

* [x] The docs team will lead producing the content
content

## Still to do

The following topics are still outstanding and require updated images:

- [Categorize log entries](https://www.elastic.co/guide/en/observability/7.14/categorize-logs.html)
- [Inspect log anomalies](https://www.elastic.co/guide/en/observability/7.14/inspect-log-anomalies.html)
- [Synthetic monitoring](https://www.elastic.co/guide/en/observability/7.14/synthetic-monitoring.html)
- [Visualize synthetic monitoring](https://www.elastic.co/guide/en/observability/7.14/synthetics-visualize.html)

**Comment by dedemorton** [comment]
Closing because this issue is quite old.
