### ISSUE TITLE
[Request] Document delayed enrollment for gold images and VDIs

### ISSUE THREAD

**Issue by blakerouse** [elastic/observability-docs#918]
## Description

The new support for `--delay-enroll`. Which will cause installation of the Elastic Agent to not enroll, but to enroll on first start of the machine.

https://github.com/elastic/beats/pull/27118

## Collaboration

* [ ] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

## Suggested Target Release

7.15

**Comment by andresrc** [comment]
@nimarezainia we need to describe how to approach this

**Comment by nimarezainia** [comment]
[cross pasting from the original issue on how this is to be tested. ]

At this point I am not sure we want the VDI use-case documented as there's more involved in how this flag helps with the VDI use case. That needs to be tested before we can claim the VDI usecase. the flag and its use case should definitely be documented.


Perform the following steps:

- Run the install command just like it is provided in Kibana but add the --delay-enroll flag. See that the Elastic Agent is installed, but it is NOT running and it is NOT showing in Kibana.
-     Restart the machine.
-     Upon restart of the machine you should see a new Elastic Agent (for that machine) appear in Fleet and it should be reporting as healthy.

**Comment by EricDavisX** [comment]
cross connecting the 'delay-enroll' option with the 'unenrollment timeout' feature from https://github.com/elastic/observability-docs/issues/901
 - we could ideally hit those both together with short blurbs in 7.16.

**Comment by EricDavisX** [comment]
and cross-posting the public ticket for testing if it helps - https://github.com/elastic/beats/issues/26312

**Comment by ollyhowell** [comment]
As per email chat, removing needs-input
