### ISSUE TITLE
[Request] Document Experimental AWS Lambda support in Node.js and Python APM Agent

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/observability-docs#920]
## Description
Document instrumentation support for AWS Lambda for the Node.js and Python agent

## Collaboration

* [ ] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [x] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

## Suggested Target Release
7.15 (stretch)

## Stakeholders
- @astorm  @trentm 
- @basepi

**Comment by bmorelli25** [comment]
Some Node.js content was recently added in https://github.com/elastic/apm-server/pull/5780

**Comment by bmorelli25** [comment]
👋 Following up here. I found the following issues and implementation PRs in the Python and Node.js agent repos. It looks like milestones in each PR have been moved to 7.16. I'm going to remove this from our 7.15 iteration – please let me know if that's not right.

**Python**

* Issue: https://github.com/elastic/apm-agent-python/issues/428
* Implementation: https://github.com/elastic/apm-agent-python/pull/1193

**Node.js**

* Issue: https://github.com/elastic/apm-agent-nodejs/issues/2156
* Implementation (partial?): https://github.com/elastic/apm-agent-nodejs/pull/2194

**Comment by bmorelli25** [comment]
This is done.
