### ISSUE TITLE
[Request] Document jRuby JVM metrics

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/observability-docs#921]
## Description
Document capturing of JVM metrics for jRuby in https://www.elastic.co/guide/en/apm/agent/ruby/current/metrics.html.

## Collaboration

* [ ] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ x ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

## Suggested Target Release
7.15

## Stakeholders
@mikker

**Comment by mikker** [comment]
@bmorelli25 These are the fields we collect. They are the same as the Java agent collects, so there's probably some copy/paste potential. https://github.com/elastic/apm-agent-ruby/blob/6aa9f74ee2d8ccd5fbdbe74b0701648bfa4c3aba/lib/elastic_apm/metrics/jvm_set.rb#L47-L62

Let me know if I can help 😊

**Comment by mikker** [comment]
You're right! I don't think we need more than that necessarily.

**Comment by bmorelli25** [comment]
👍 I'll close this then. Alex, feel free to reopen if you see a need for additional documentation.
