### ISSUE TITLE
Documentation update for Agent and Fleet based data collection for stack monitoring

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#942]
## Description

Documentation changes are needed to describe the new mechanism for collecting data in Stack Monitoring, via Fleet and Elastic Agent (as described in https://github.com/elastic/kibana/issues/104746)

## Collaboration

* [X] The docs team will lead producing the content

## Suggested Target Release

Collecting Stack Monitoring data via Fleet/Agent is targeted for 7.15.

## Stakeholders

@ravikesarwani @jasonrhodes @sayden

**Comment by andresrc** [comment]
Who would be the contact point in the team to guide the docs team on how the feature works?

**Comment by paulb-elastic** [comment]
> 
> 
> Who would be the contact point in the team to guide the docs team on how the feature works?

@ravikesarwani would that be you?

**Comment by ravikesarwani** [comment]
As far as my understanding goes someone from engineering usually would be the best person to guide the doc team on how the feature works. I am happy to help out in the doc review and provide suggestions etc.

**Comment by dedemorton** [comment]
Closing this old issue in favor of https://github.com/elastic/observability-docs/issues/2602, which is newer.
