### ISSUE TITLE
[Request] we need to review older O11y docs wrt to if we want to cite Beats install order vs Agent usage

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#952]
I posted to slack, but it was late at night - tracking here so I don't forget:

who can comment on if we plan to update this page, which cites the order to install Beats (as opposed to mentioning Agent)? 
https://github.com/elastic/observability-docs/blob/master/docs/en/observability/add-observability-data.asciidoc

**Comment by bmorelli25** [comment]
This is done.
