### ISSUE TITLE
[Request] update the docs for the format of the non-primary (rotation) logs

### ISSUE THREAD

**Issue by EricDavisX** [elastic/observability-docs#954]
In docs/en/ingest-management/tab-widgets/install-layout.asciidoc
 - we list the path for rotated Agent logs.  the format of the log name is changed now.
 
I would like to cite the nuance of what the rotation # is, besides the date.  
the log files for filebeat/metricbeat seem to show like:
2021-07-29-18-1

but the main agent log has a different format, and maybe a different scheme, I'm just not sure.  at It's end, it looks like:
20210729181154

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource can you re-verify this in the Agent documentation please?  And if so, it would be helpful to post further data, my description here is terrible. :0  if you need help understanding do let me know.  cheers.

@dedemorton I'm unassigning myself either way, it may be a small fix if still relevant.

**Comment by dedemorton** [comment]
I'll get this added to our project board. I thought we had some automation set up to do that, but it appears that it's not working.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this with installed agent logs and observed:
the log files for filebeat/metricbeat/fleet-server show like:
2021-07-29-18-1
**Screenshot:**
![8](https://user-images.githubusercontent.com/77374876/149759353-043bc294-278f-46f7-a3d9-ddacfb9db019.JPG)

The agents log has a different format and it looks like:
20210729181154
**Screenshot:**
![9](https://user-images.githubusercontent.com/77374876/149759656-a48a6fbd-ff37-4bf4-b30c-f62feaaeb05b.JPG)

We are unable to get to `docs/en/ingest-management/tab-widgets/install-layout.asciidoc`.
Could you please share the specific guide reference for the same?

Further we have initiated doc testing on 8.0, we will be sharing if we get any more updates in docs.

Thanks

**Comment by dedemorton** [comment]
FYI, docs/en/ingest-management/tab-widgets/install-layout.asciidoc appears on this page: https://www.elastic.co/guide/en/fleet/8.0/installation-layout.html

The documentation work is in our queue, but not yet assigned to a writer. We will update this issue when the docs are available.

**Comment by kvch** [comment]
My PR fixes the naming problem from version 8.0. But below that version (7.17 and below), the names still need an update.

**Comment by dedemorton** [comment]
Closed in #1849
