### ISSUE TITLE
[Request] Clarification of correlation between transactions and errors

### ISSUE THREAD

**Issue by psanz-estc** [elastic/observability-docs#959]
## Description

The error rate shown in Transaction tab is not directly correlated with actual error captures on Errors tab, and the documentation doesn't mention anything about it.

ie: Error 4XX are reported in Transaction tab

![image](https://user-images.githubusercontent.com/44199691/128161814-a69ba016-7cb2-42e8-a9fe-67f0678726e3.png)

But there is nothing on Errors tab:

![image](https://user-images.githubusercontent.com/44199691/128161858-75f0170d-c280-4cc1-a7d9-60c34d8cb8cb.png)

We should mention something like:

A transaction with a http status code of 4xx will have `event.outcome=success`  (so won’t be marked as an error).
A transaction with 5xx will be have `event.outcome=failure`  (marked as an error)

## Collaboration

* [ ] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Comment by bmorelli25** [comment]
Related to the content added in https://github.com/elastic/kibana/pull/95598. This tip only currently exists on the transaction overview page. We should add something similar to the error overview page.

Relevant Slack discussion is [here](https://elastic.slack.com/archives/C877NKGBY/p1628069267038000) (sorry, internal link).

**Comment by graphaelli** [comment]
Also related: https://github.com/elastic/kibana/issues/106146
