### ISSUE TITLE
Discuss agent monitoring metrics

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#971]
We added content to our documentation about agent monitoring logs here https://github.com/elastic/observability-docs/issues/770. However, we did not yet add content about agent monitoring metrics. It'd be good to discuss metrics in the same places for consistency and visibility to this feature. It may also be helpful to discuss how this information is used for hosted agent and Fleet Server scaling, and agent and fleet server dashboards.

**Comment by ravikesarwani** [comment]
Thanks for assigning me the issue @dedemorton. Let me know how I can help.
The changes in the Elastic Agent dashboard is described in https://github.com/elastic/integrations/pull/1529.
The image from there can potentially be used in the doc as well.

The default metrics on the dashboard focuses on:
- CPU and memory information including CGroup usage (useful when Agent its running in container environment with limits set)
- Open handles
- Event information
- Errors
The dashboard can be used by the users to understand the Elastic Agent resource usage and throughput in terms of event processing. It uses standard kibana visualizations and can be extended to meet specific customer needs.

@mostlyjason Not to sure about the hosted agent and Fleet Server scaling but one way we can potentially refer is via linking. The Agent monitoring sections describes the Logs and metrics collection and default visualizations and is linked from places where we talk about the hosted agent and Fleet Server .

@dedemorton Let me know if there's more information you need to move this forward. 
Happy to have a conversations and/or review and provide feedback offline on the documentation about this.

**Comment by mostlyjason** [comment]
Sure good idea to link to the Fleet Server guide that Nima is drafting up since it talks about how to scale the hosted agent/fleet server
