### ISSUE TITLE
[Request] Add documentation that 2 Elastic Agent's cannot run on the same host

### ISSUE THREAD

**Issue by blakerouse** [elastic/observability-docs#982]
## Description

It is possible that a user will try to run 2 Elastic Agents on the same host. This should not be done and can result in behavior that is not expected by the user. See https://github.com/elastic/beats/issues/27321

## Collaboration

* [ ] The docs team will lead producing the content
* [ ] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

## Suggested Target Release

*(Let us know if this feature is needed for a specific release.)*

**Comment by dedemorton** [comment]
Really sorry this got lost in our backlog.
