### ISSUE TITLE
7.15.0 Documentation Release

### ISSUE THREAD

**Issue by andresrc** [elastic/observability-docs#983]
### General release tasks

- Observability
  - [x] What's new in 7.15 https://github.com/elastic/observability-docs/pull/1082 
- Agent
  ~- [ ] [Upgrade guide](https://www.elastic.co/guide/en/fleet/master/upgrade-elastic-agent.html)~
- Fleet and Agent
  - [ ] Release notes https://github.com/elastic/observability-docs/pull/1080
- APM Server
  - [x] Release notes https://github.com/elastic/apm-server/pull/6178
  - [x] Breaking changes https://github.com/elastic/apm-server/pull/6214
  - [x] Upgrade guide https://github.com/elastic/apm-server/pull/6214
- Beats
  - [x] Release notes https://github.com/elastic/beats/pull/28033
  - [x] Breaking changes https://github.com/elastic/beats/pull/28070
~- [x] Upgrade guide~
- Stack docs
  - [x] Copy of Observability What's new https://github.com/elastic/observability-docs/pull/1082
  - [x] Copy of APM Server breaking changes https://github.com/elastic/stack-docs/pull/1825
  - [x] Copy of Beats breaking changes https://github.com/elastic/stack-docs/pull/1833

**Comment by bmorelli25** [comment]
Missing links have all been added. Closing. 🚢
