### ISSUE TITLE
Documentation for the experimental version of self-managed Package Registry

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/observability-docs#984]
## Description

epr.elastic.co is essential for integrations to be identified by Kibana and work properly. In air-gapped environments, Kibana is not able to reach this endpoint and that makes adoption of the fleet for such customers challenging. We have an experimental version of the self-managed EPR that customers could host in their network and easily use agent integrations. We wish to open that for customers. We have been using it internally for development and the only thing that is required for this capability at the moment is documentation. Once we have the documentation, it will be easier for users to discover this capability and use it which will, in turn, help us in gathering feedback and planning for future iterations.

[We already have the content and looking for a place to host it](https://github.com/elastic/package-storage#air-gapped-environments). _Integrations developer_ guide would seem to fit the requirement. Hence, adding a separate section for _Package Registry_ or a sub-section under _Package Specification_ in the _Integrations developer_ guide would be great.

## Collaboration

* [x] The prodiuct team will provide the initial content
* [ ] The docs team will edit / review and publish

## Suggested Target Release

*7.15*

## Stakeholders
@mukeshelastic , @sorantis, @mtojek, @masci

**Comment by bmorelli25** [comment]
Added in https://github.com/elastic/observability-docs/pull/769/commits/6ec97f1e3b2ea658209a029ed36c917b6ba50a95.
