### ISSUE TITLE
Exploratory View support for multi series and new UX/UI

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/observability-docs#987]
## Description

Exploratory View is being updated to support multi series in https://github.com/elastic/uptime/issues/321.

This isn’t *just* adding multi series, it’s changing the UX and UI quite significantly, even for those using a single series.

The documentation in https://www.elastic.co/guide/en/observability/master/exploratory-data-visualizations.html and the sub pages will need to be updated

## Collaboration

* [X] The docs team will lead producing the content

## Suggested Target Release

7.16

## Stakeholders

@liciavale 
@drewpost 
@andrewvc 
@paulb-elastic

**Comment by andresrc** [comment]
Who would be the contact person to guide the docs team on how the feature work?

**Comment by paulb-elastic** [comment]
I would suggest starting with @drewpost and/or @liciavale 

For reference, all of @dominiqueclarke, @justinkambic and @shahzad31 have worked on it (although it will continue with a number of chages throughout 7.16).

**Comment by andresrc** [comment]
Thanks @drewpost , the person from the team who takes over this task will ping you (/cc @ollyhowell )

**Comment by ollyhowell** [comment]
Thanks folks, will send you an invite @drewpost

**Comment by paulb-elastic** [comment]
Just to call out, that as well as the Exploratory View page itself having changed significantly in 7.16, the links to it from Uptime and User Experience have also been changed (in https://github.com/elastic/kibana/issues/116279), so there may be some copy/screenshot changes needed.

**Comment by paulb-elastic** [comment]
@EamonnTP just catching up on this, has there been any updates on this for Exploratory View?  Thanks.

**Comment by EamonnTP** [comment]
Hi @paulb-elastic I'm playing catchup at the moment, having been off for a while. I plan to get to this asap.

**Comment by paulb-elastic** [comment]
Thanks @EamonnTP, no problem.

**Comment by EamonnTP** [comment]
[A proposal](https://docs.google.com/document/d/1ykjfr30JA5jqDjDbQer0m08-92fAAFeld3n7Ho0VNEM/edit?usp=sharing) to restructure the content and provide a specific use-case that showcases a multi-series visualization.

**Comment by ollyhowell** [comment]
Looking at Eamonn's proposal doc and digging into the feature itself, I'll shortly link a draft PR I'm working on but highlights below:

1. update existing exploratory-data-visualizations.html page with some of the proposed content from Eamonn's doc and some additions/edits based on the content and functionality we have now
2. either remove the 2 sub pages (synthetic-monitoring-visualizations.html and user-experience-visualizations.html) entirely just now or make minimal changes (remove tech preview labels and correct Explore Data link etc.) - this would be in line with proposal to consolidate 3 pages into 1
3. make changes for 7.16 and 7.17 but deal with 8.0 changes separately (with infra metrics and hopefully better use case content and topic structure/placement) and with context of ongoing dev changes (some questions/discussion needed)

@shahzad31 has helped with tech questions and @bryce-b has supplied screenshot for Device distribution but looking for some feedback on above from @paulb-elastic and @drewpost in particular

**Comment by paulb-elastic** [comment]
I think it would be useful to at least update what we have to bring it inline with what it looks like (changes from 7.16 onwards).  Maybe getting those done initially whilst a bigger overhaul is planned?  There will be ongoing updates to Exploratory View, most of which will be done by the **Unified Observability** team going forward, so they will also have thoughts here too (/cc @danielkhan, @smith, @jasonrhodes).

@drewpost, WDYT?

**Comment by ollyhowell** [comment]
Yeah, totally agree - here is a link to the intermediate update: https://observability-docs_1532.docs-preview.app.elstc.co/guide/en/observability/7.16/exploratory-data-visualizations.html
It's a draft PR but could get this reviewed and complete this week...

**Comment by danielkhan** [comment]
@paulb-elastic, we are currently talking to different groups within o11y and security to find out more about the use-cases but I don't yet have anything to share.
