### ISSUE TITLE
Links not working for PHP agent installation widget

### ISSUE THREAD

**Issue by ba0708** [elastic/observability-docs#990]
[On this page](https://www.elastic.co/guide/en/fleet/current/fleet-quick-start-traces.html#add-apm-integration-agents), the links are not being generated correctly for the PHP agent in Step 4 (within the PHP tab).

![Screen Shot 2021-08-19 at 11 31 15](https://user-images.githubusercontent.com/3290228/130045614-31a5a0f8-6c49-46c8-9ee3-2b5b92f21165.png)

Within this repository, the page is this one:
https://github.com/elastic/observability-docs/blob/master/docs/en/ingest-management/getting-started-traces.asciidoc

It uses the following widget from the apm-server repository:
https://github.com/elastic/apm-server/blob/master/docs/tab-widgets/install-agents.asciidoc

Not sure which repository the issue is best suited for, but I am sure someone knows. ;-)

**Comment by bmorelli25** [comment]
Thanks for opening this issue, @ba0708! I'll look into this.
