### ISSUE TITLE
Automatically upgrade integration policies

### ISSUE THREAD

**Issue by mostlyjason** [elastic/observability-docs#996]
## Description

We are planning to add the ability for users to automatically upgrade integration policies when they upgrade an integration. We'd like to document this new capability, and what users should do if the upgrade fails. 

Implementation issue: https://github.com/elastic/kibana/issues/106048

## Collaboration

* [ ] The docs team will lead producing the content
* [x] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Contact Person:**

*(We need to have a contact person in the product/development team to provide information about how the item to be documented works.)*
@kpollich 

## Suggested Target Release

7.16

## Stakeholders

@jen-huang @mostlyjason

**Comment by andresrc** [comment]
@mostlyjason can you describe the required collaboration. Please use the issue template.

**Comment by mostlyjason** [comment]
@andresrc updated

**Comment by dedemorton** [comment]
Adding my name to this issue because it's next up in my work queue.

**Comment by amolnater-qasource** [comment]
Hi @kpollich
We have tested automatic integration upgrade on 7.16.0 BC-5 Kibana cloud environment
- We disabled the automatic package upgrade for System integration.
- Degraded the System integration version to `v0.12.7`.
- Added the integration to Policy.
- Still System integration upgraded to latest version however policies didn't upgrade.

**Question:**
Is this feature only restricted for integration in policies whether to upgrade automatically or not?
Is this expected that on disabling automatic upgrade, actual system integration would get back to latest version automatically?

cc: @mostlyjason and @EricDavisX
Thanks

**Comment by kpollich** [comment]
> Hi @kpollich We have tested automatic integration upgrade on 7.16.0 BC-5 Kibana cloud environment
> 
> * We disabled the automatic package upgrade for System integration.
> * Degraded the System integration version to `v0.12.7`.
> * Added the integration to Policy.
> * Still System integration upgraded to latest version however policies didn't upgrade.
> 
> **Question:** Is this feature only restricted for integration in policies whether to upgrade automatically or not? Is this expected that on disabling automatic upgrade, actual system integration would get back to latest version automatically?
> 
> cc: @mostlyjason and @EricDavisX Thanks

Thanks for the questions, @amolnater-qasource . The "Keep policies up to date" checkbox only controls policies, not the actual package update. Since `system` is a "managed" Fleet package, the latest version is always installed automatically. This is true of `fleet_server` and `elastic_agent` integrations as well, and some others. Packages marked with this note fall into this category:

![image](https://user-images.githubusercontent.com/6766512/143256496-81eb0950-1b0b-42db-ada8-ba7116d3503f.png)

To verify, I did the following in my local environment

1. Remove all `system` integration policies via the Fleet UI, and manually remove the `system` integration via the API

```
DELETE http://localhost:5601/kyle/api/fleet/epm/packages/system-1.6.3
Authorization: Basic elastic:changeme
kbn-xsrf: xyz
Content-Type: application/json

{
  "force": true
}
```

2. Force install an earlier version of `system`

```
POST http://localhost:5601/kyle/api/fleet/epm/packages/system-1.1.2
Authorization: Basic elastic:changeme
kbn-xsrf: xyz
Content-Type: application/json

{
  "force": true
}
```

3. Observe the outdated notification on the integration settings page

![image](https://user-images.githubusercontent.com/6766512/143258011-d5abcea0-b2aa-494e-b990-dd3c6d29fa5e.png)

4. Navigate to the "Fleet" app in the Kibana sidebar, or otherwise take some action that re-initiates Fleet's `setup` such as restarting Kibana

5. Observe that `system` has been automatically updated in the UI, and check Kibana logs to confirm

![image](https://user-images.githubusercontent.com/6766512/143258297-103e1229-b741-47b7-8bc8-3338c8f497c7.png)

![image](https://user-images.githubusercontent.com/6766512/143258200-eeac47bd-4b57-43aa-96a7-2ed959c4be17.png)

Let me know if this clears things up!

**Comment by EricDavisX** [comment]
@kpollich  Thanks so much for info. I'll let Amol reply.

I have a separate follow up, where do we need to update to get the language improved for 'Note: The system integration is a system integration and cannot be removed' ?  It is confusing language.  Is it in the package or is that Kibana side?   Do you have ability to help follow up on this further for us?

For suggested language I might suggest we avoid the 'why' or explaining too much and simply cite something like:
"Note: The System Integration cannot be removed.'

We can discourse more in the docs elsewhere about it and why.

**Comment by kpollich** [comment]
> I have a separate follow up, where do we need to update to get the language improved for 'Note: The system integration is a system integration and cannot be removed' ? It is confusing language. Is it in the package or is that Kibana side? Do you have ability to help follow up on this further for us?
> 
> For suggested language I might suggest we avoid the 'why' or explaining too much and simply cite something like: "Note: The System Integration cannot be removed.'
> 
> We can discourse more in the docs elsewhere about it and why.

This messaging does come from Kibana, so we can start a discussion w/ just the Fleet UI team to improve the language here - we won't need to involve the ecosystem team or package spec to improve this.

**Comment by amolnater-qasource** [comment]
Hi @kpollich 
Thanks for sharing detailed feedback.
We are now clear with the working of this feature and we have created 02 testcases for this feature under our ingest manager test suite at links:
- [Validate when Automatic Package upgrade is disabled for System integration, it doesn't upgrade lower version system integration to latest under any policy automatically.](https://elastic.testrail.io/index.php?/cases/view/164163)
- [Validate when Automatic Package upgrade is enabled for System integration, it upgrades lower version system integration to latest under all policies automatically.](https://elastic.testrail.io/index.php?/cases/view/164164)

> 'Note: The system integration is a system integration and cannot be removed' ? It is confusing language.
Further @EricDavisX as per feedback we have logged an issue for this at https://github.com/elastic/kibana/issues/119928

Please let us know if we are missing anything.
Thanks

**Comment by dedemorton** [comment]
Regarding the note about the System integration....  In the [upgrade docs](https://www.elastic.co/guide/en/fleet/7.16/upgrade-integration.html), I say, "Some integration packages, like System, are installed by default during Fleet setup."

So I think you could change the note to say something like:

Note: The system integration is installed by default and cannot be removed.
